In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on 2024-06-18

@author: Juan Enrique López Marcos

@description: Jupyter Notebook creado para obtener las relaciones entre items de MITRE principalmente con las Técnicas (Tácticas, Data Sources, Software, Grupos). Adicionalmente se incluye una funcionalidad que permite retornar el listado de reglas de detección por técnica disponibles en CP. 

"""

'\nCreated on 2024-06-18\n\n@author: Juan Enrique López Marcos\n\n@description: Jupyter Notebook creado para obtener las relaciones entre items de MITRE principalmente con las Técnicas (Tácticas, Data Sources, Software, Grupos). Adicionalmente se incluye una funcionalidad que permite retornar el listado de reglas de detección por técnica disponibles en CP. \n\n'

**Índice de contenidos**

[1. TÉCNICAS - TÁCTICAS]()

- [1.1 Tablas intermedias (N:N)]()

- [1.2 Técnicas - Tácticas (1:N)]()

- [1.3 Tácticas - Técnicas (1:N)]()

[2. DATA SOURCES - TÉCNICAS]()

- [2.1 Tablas intermedias (N:N)]()

- [2.2 Técnicas - Data Sources (1:N)]()

- [2.3 Data Sources - Técnicas (1:N)]()

[3. GRUPOS - TÉCNICAS]()

- [3.1 Tablas intermedias (N:N)]()

- [3.2 Grupos - Técnicas (1:N)]()

- [3.3 Técnicas - Grupos (1:N)]()

[4. SOFTWARE - TÉCNICAS]()

- [4.1 Tablas intermedias (N:N)]()

- [4.2 Técnicas - Software (1:N)]()

- [4.3 Software - Técnicas (1:N)]()

[5. GRUPOS - SOFTWARE]()

- [4.1 Tablas intermedias (N:N)]()

- [4.2 Grupos - Software (1:N)]()

- [4.3 Software - Grupos (1:N)]()

[6. PLATAFORMAS - TÉCNICAS]()

- [6.1 Tablas intermedias (N:N)]()

- [6.2 Técnica - Plataformas (1:N)]()

- [6.3 Plataforma - Técnicas (1:N)]()


[BONUS. GENERACIÓN LISTADO DE REGLAS DE DETECCIÓN POR TÉCNICA]()

**Descripción de los outputs**

<h3 style="background-color: #FF5733; color: black;">
    1. TÉCNICAS - TÁCTICAS
</h3>

#### 1.1 Tablas intermedias (N:N)

Guardado en: *inter_techniques_tactics*

- Relación N a N de técnicas y tácticas MITRE. Campos: tactic, technique_id, technique, url_technique,tactic_id, tactic_description, url_tactic.
    - [MITRE]_enterprise_n2n_techniques_tactics_df_ddmmYY_hhmm_h.csv
- Relación N a N de técnicas y tácticas CyberProof (filtro sobre aquellas TTP's disponibles con regla de detección). Campos: tactic, technique_id, technique, url_technique,tactic_id, tactic_description, url_tactic
    - [CP]_enterprise_n2n_techniques_tactics_ddmmYY_hhmm_h.csv
- Relación N a N de técnicas y tácticas que NO disponemos en CyberProof. Campos: tactic, technique_id, technique, url_technique,tactic_id, tactic_description, url_tactic
    - [NOCP]_enterprise_n2n_techniques_tactics_ddmmYY_hhmm_h.csv


#### 1.2 Técnicas - Tácticas (1:N)

Guardado en: *technique_tactics_1N*

- Lista de técnicas únicas con las tácticas asociadas MITRE. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [MITRE]_techniques_with_tactics_ddmmYY_hhmm_h.csv
- Lista de técnicas únicas con las tácticas asociadas CyberProof. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [CP]_techniques_with_tactics_ddmmYY_hhmm_h.csv
- Lista de técnicas únicas con las tácticas asociadas que NO disponemos en CyberProof. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [NOCP]_techniques_with_tactics_ddmmYY_hhmm_h.csv


#### 1.3 Tácticas - Técnicas (1:N)

Guardado en: *tactic_techniques_1N*

- Lista de tácticas únicas con las técnicas asociadas MITRE. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [MITRE]_techniques_with_tactics_ddmmYY_hhmm_h.csv
- Lista de tácticas únicas con las técnicas asociadas CyberProof. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [CP]_techniques_with_tactics_ddmmYY_hhmm_h.csv
- Lista de tácticas únicas con las técnicas asociadas que NO disponemos en CyberProof. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [NOCP]_techniques_with_tactics_ddmmYY_hhmm_h.csv

*Nota: Tenemos todas las tácticas cubiertas por al menos una regla de deteccion (TTP asociada) y tenemos 1 cubierta por todas TTP's disponibles (TA0040)

<h3 style="background-color: #FF5733; color: black;">
    2. DATA SOURCES - TÉCNICAS
</h3>

#### 2.1 Tablas intermedias (N:N)

Guardado en: *inter_data_sources_techniques*

- Lista sencilla de data sources. Campos: data_source_id, data_source, data_source_description, url_data_source
    - [MITRE]_data_sources

- Relación N:N de Data Sources y Técnicas (todos los casos, incuyendo técnicas sin data source y data sources sin técnica). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [MITRE]_enterprise_n2n_all_techniques_data_sources_ddmmYY_hhmm_h.csv

- Relación N:N de Data Sources y Técnicas (SÓLO aquellos relacionados). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [MITRE]_enterprise_n2n_techniques_data_sources_ddmmYY_hhmm_h.csv
    
*Nota: TTP's únicas sin data source asociado: 40. TTP's únicas con data source asociado: 597. Data sources únicas sin TTP asociada: 37. Data sources únicas sin TTP asociada: 5

- Relación N:N de Data Sources y Técnicas (SÓLO DISPONIBLES EN CP y relacionados). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [CP]_enterprise_n2n_techniques_data_sources_ddmmYY_hhmm_h.csv

- Relación N:N de Data Sources y Técnicas (NO DISPONIBLES EN CP y relacionados). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [NOCP]_enterprise_n2n_techniques_data_sources_ddmmYY_hhmm_h.csv



#### 2.2 Técnicas - Data Sources (1:N)

Guardado en: *technique_data_sources_1N*

- Relación 1:N entre Técnicas y Data Sources (todas las disponibles en MITRE). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [MITRE]_techniques_with_data_sources_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnicas y Data Sources (SÓLO DISPONIBLES EN CP). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [CP]_techniques_with_data_sources_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnicas y Data Sources (NO DISPONIBLES EN CP). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [NOCP]_techniques_with_data_sources_ddmmYY_hhmm_h.csv

*Nota: Disponemos de 597 TTP's con regla de detección asociada a uno o más Data soruces. 103 TTP's no disponibles y 40 TTP's no tienen Data source asociado.


#### 2.3 Data Sources - Técnicas (1:N)

Guardado en: *data_source_techniques_1N*

- Relación 1:N entre Data Sources y Técnicas (todas las disponibles en MITRE). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [MITRE]_data_source_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Data Sources y Técnicas (SÓLO DISPONIBLES EN CP). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [CP]_data_source_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Data Sources y Técnicas (NO DISPONIBLES EN CP). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [NOCP]_data_source_with_techniques_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    3. GRUPOS - TÉCNICAS
</h3>

#### 3.1 Tablas intermedias (1:N y N:N)

Guardado en: *inter_groups_techniques*

- Lista sencilla de todos los grupos (1:N). Campos: group_id, group, url_group, technique_id, technique, url_technique
    - [MITRE]_all_groups_ddmmYY_hhmm_h.csv

- Misma lista que la anterior pero filtrada por matriz de ataque enterprise (1:N). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [MITRE]_enterprise_groups_ddmmYY_hhmm_h.csv

- Lista completa de grupos relacionados con toda la información relevante. Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [MITRE]_enterprise_all_data_groups_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [CP]_enterprise_all_data_groups_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [NOCP]_enterprise_all_data_groups_ddmmYY_hhmm_h.csv

#### 3.2 Grupos - Técnicas (1:N)

Guardado en: *group_techniques_1N*

- Relación 1:N entre Grupos y Técnicas (todas las disponibles en MITRE). Campos: ggroup_id, group, url_group, technique_id, technique, url_technique.
    - [MITRE]_groups_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Grupos y Técnicas (SÓLO DISPONIBLES EN CP). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [CP]_groups_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Grupos y Técnicas (NO DISPONIBLES EN CP). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [NOCP]_groups_with_techniques_ddmmYY_hhmm_h.csv

#### 3.3 Técnicas - Grupos (1:N)

Guardado en: *technique_groups_1N*

- Relación 1:N entre Técnicas y Grupos (todas las disponibles en MITRE). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [MITRE]_techniques_with_groups_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnicas y Grupos (SÓLO DISPONIBLES EN CP). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [CP]_techniques_with_groups_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnicas y Grupos (NO DISPONIBLES EN CP). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [NOCP]_techniques_with_groups_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    4. SOFTWARE - TÉCNICAS
</h3>

#### 4.1 Tablas intermedias (1:N y N:N)

Guardado en: *inter_software_techniques*

- Lista sencilla de todos los software, incluyendo diferentes de enterprise (1:N). Campos: software_id, software, software_aliases, type, url, matrix
    - [MITRE]_all_software_ddmmYY_hhmm_h.csv

- Lista sencilla de todos los software enterprise (1:N). Campos: software_id, software, software_aliases, type, url, matrix
    - [MITRE]_enterprise_software_ddmmYY_hhmm_h.csv

- Lista completa de software relacionados con las técnicas y toda la información disponible (sólo enterprise). Campos: type, id, url, matrix, created, modified, created_by_ref, modified_by_ref, external_references, object_marking_refs, mitre_version, mitre_attack_spec_version, mitre_deprecated, technique, technique_id, technique_description, tactic, technique_detection, platform, data_sources, defense_bypassed, permissions_required, effective_permissions, system_requirements, network_requirements, remote_support, contributors, tactic_type, impact_type, is_subtechnique, software_id, software, software_aliases, software_description, software_type, url_software, mitre_domains, url_technique.
    - [MITRE]n2n_main_techniques_software_ddmmYY_hhmm_h.csv

- Lista reducida a los campos más importantes. Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [MITRE]_n2n_techniques_software_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [CP]_n2n_techniques_software_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [NOCP]_n2n_techniques_software_ddmmYY_hhmm_h.csv


#### 4.2 Técnica - Software (1:N)

Guardado en: *technique_software_1N*

- Relación 1:N entre Técnica y Software (todas las disponibles en MITRE). Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [MITRE]_technique_with_software_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnica y Software  (SÓLO DISPONIBLES EN CP). Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [CP]_technique_with_software_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnica y Software  (NO DISPONIBLES EN CP). Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [NOCP]_technique_with_software_ddmmYY_hhmm_h.csv


#### 4.3 Software - Técnicas (1:N)

Guardado en: *software_techniques_1N*

- Relación 1:N entre Software y Técnicas (todas las disponibles en MITRE). También incluye otras informaciones como tácticas, platform y data source. Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [MITRE]_software_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Software y Técnicas (SÓLO DISPONIBLES EN CP). Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [CP]_software_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Software y Técnicas (NO DISPONIBLES EN CP).  Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [NOCP]_software_with_techniques_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    5. GRUPOS - SOFTWARE
</h3>

#### 5.1 Tablas intermedias (1:N y N:N)

Guardado en: *inter_groups_software*

- Lista completa de software relacionados con los grupos. Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_n2n_groups_software_ddmmYY_hhmm_h.csv

- Lista completa de software relacionados con los grupos filtrado por matriz enterprise. Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_n2n_enterprise_groups_software_ddmmYY_hhmm_h.csv


#### 5.2 Grupo - Software (1:N)

Guardado en: *group_software_1N*

- Relación 1:N entre Grupo y Software (todas las disponibles en MITRE). Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_groups_with_software_ddmmYY_hhmm_h.csv

- Relación 1:N entre Grupo y Software (todas las disponibles en MITRE) filtrados por la matriz enterprise. Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_enterprise_groups_with_software_ddmmYY_hhmm_h.csv


#### 5.3 Software - Grupo (1:N)

Guardado en: *software_groups_1N*

- Relación 1:N entre Software y Grupo (todas las disponibles en MITRE). Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_software_with_groups_ddmmYY_hhmm_h.csv

- Relación 1:N entre Software y Grupo (todas las disponibles en MITRE) filtrados por la matriz enterprise. Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_enterprise_software_with_groups_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    6. PLATAFORMAS - TÉCNICAS
</h3>

#### 6.1 Tablas intermedias ( N:N)

Guardado en: *inter_techniques_platforms*

- Lista completa de técnicas relacionadas con las plataformas (MITRE - enterprise). Campos: technique_id, technique, url_technique, platform.
    - [MITRE]_n2n_enterprise_techniques_platforms_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [CP]_n2n_enterprise_techniques_platforms_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [NOCP]_n2n_enterprise_techniques_platforms_ddmmYY_hhmm_h.csv


#### 6.2 Técnica - Plataformas (1:N)

Guardado en: *technique_platforms_1N*

- Relación 1:N entre Técnica y Plataformas (todas las disponibles en MITRE - enterprise). Campos: technique_id, technique, url_technique, platform.
    - [MITRE]_enterprise_technique_with_platforms_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [CP]_enterprise_technique_with_platforms_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [NOCP]_enterprise_technique_with_platforms_ddmmYY_hhmm_h.csv


#### 6.3 Plataforma - Técnicas (1:N)

Guardado en: *platform_techniques_1N*

- Relación 1:N entre Plataforma y Técnica (todas las disponibles en MITRE - enterprise). Campos: technique_id, technique, url_technique, platform.
    - [MITRE]_enterprise_platform_with_techniques_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [CP]_enterprise_platform_with_techniques_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [NOCP]_enterprise_platform_with_techniques_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    BONUS. GENERACIÓN LISTADO DE REGLAS DE DETECCIÓN POR TÉCNICA
</h3>


- Listado de reglas de deteccion disponibles en CyberProof asociadas a TTP's (incluyendo tambien las que no se han podido asignar a ninguna y por tanto se asignan a T0000)
    - [CP]_ttp_rules_ddmmYY_hhmm_h.csv

#### Requerimientos

In [1]:
from attackcti import attack_client
import pandas as pd
import datetime
import csv
import os

from IPython.display import display
pd.options.display.max_columns = None

#### Funciones

In [3]:
def delete_special_characters(df):
    chars = r'[^\w\s,-.:]'  # Esto incluye cualquier cosa que no sea una palabra o espacio
    chars_url = r"[\[\]\'{}]"
    lb = r'\n'
    cr = r'\r'
    low_bar = r'_'
    colon_sep = r"': '"
    df = df.fillna('N/A')
    for col in df.columns:
        # Convertimos a str todas las columna
        if df[col].dtype == 'O':
            df[col] = df[col].astype(str)
        elif df[col].dtype == 'bool':
            df[col] = df[col].replace({True: 'True', False: 'False'})
        if col != 'external_references':
            # Aplicamos los reemplazos, importante mantener este orden
            df[col] = df[col].str.replace(colon_sep, ' - ', regex=True)
            df[col] = df[col].str.replace(low_bar, ' ', regex=True)
            df[col] = df[col].str.replace(chars, '', regex=True)
            df[col] = df[col].str.replace(lb, ' ', regex=True)
            df[col] = df[col].str.replace(cr, '', regex=True)
        else:
            df[col] = df[col].str.replace(chars_url, '', regex=True)
            df[col] = df[col].str.replace(colon_sep, ' - ', regex=True)
            df[col] = df[col].str.replace(low_bar, ' ', regex=True)
            df[col] = df[col].str.replace(lb, ' ', regex=True)
            df[col] = df[col].str.replace(cr, '', regex=True)
    return df

In [4]:
# Buscamos en la columna de descripción o informativa
def find_techniques(texto, techniques_enterprise_list):
    if isinstance(texto, str):
        found = []
        for item in techniques_enterprise_list:
            if item in texto:
                found.append(item)
        return ', '.join(found)
    else:
        return ''

In [5]:
def save_df_as_csv(df, name, aux_folder=''):
    now = datetime.datetime.now()
    if not os.path.exists(os.path.join(os.getcwd(), 'outputs', aux_folder)):
        os.makedirs(os.path.join(os.getcwd(), 'outputs', aux_folder))
    file_to_save = os.path.join(os.getcwd(), 'outputs', aux_folder, (name+ '_'+ now.strftime('%d%m%Y_%H%M')+'h.csv'))
    df.to_csv(file_to_save, sep=';', encoding='utf8', index=False, quoting=csv.QUOTE_NONNUMERIC)
    print('Fichero generado correctamente '+ name + '_' +now.strftime('%d%m%Y_%H%M')+'h.csv')

In [6]:
def getListOfFilesSub(dirName):
    # Crea lista de ficheros y subdirectorios
    listOfFile = os.listdir(dirName)
    allFiles = list()
    #Recorre los directorios y subdirectorios y genera una lista con los ficheros encontrados en estos
    for entry in listOfFile:
        fullPath = os.path.join(dirName, entry)
        if os.path.isdir(fullPath):
            allFiles = allFiles + getListOfFilesSub(fullPath)
        else:
            allFiles.append(fullPath)
    #Devuelve la lista con los ficheros
    return allFiles

In [7]:
# Función para quedarnos unicamente con items unicos al agregar
def unique_list(series):
    return list(set(series))

In [8]:
def cp_unique_ttp_with_rules(path):
    # Conjunto para almacenar nombres únicos de carpetas
    unique_folders = set()
    
    # Recorrer el directorio y sus subdirectorios
    for root, dirs, files in os.walk(path):
        for dir_name in dirs:
            # Verificar si el nombre de la carpeta contiene 'T0' o 'T1'
            if 'T0' in dir_name or 'T1' in dir_name:
                # Añadir solo el nombre de la carpeta al conjunto (esto elimina duplicados automáticamente)
                unique_folders.add(os.path.basename(dir_name))
    
    # Convertir el conjunto a una lista para el resultado final
    filtered_folders = list(unique_folders)
    filtered_folders = sorted(filtered_folders, key=len, reverse=True)
    filtered_folders.remove('T0000')
    
    return filtered_folders

In [9]:
def cp_ttps():
    ttps_outputs_path = r'C:\Users\jelopez\Documents\CyberProof\python\develop\download_ttps\saved'
    cp_ttp_available = cp_unique_ttp_with_rules(ttps_outputs_path)
    return cp_ttp_available

In [10]:
# El campo data_sources viene con un formato que no nos sirve para asociar el id y la url, por lo que lo formateamos dando lugar a 2 campos nuevos 
def split_lists(lst):
    if lst is None:
        return [], []
    before_colon = [item.split(': ')[0] for item in lst if item]
    after_colon = [item.split(': ')[1] for item in lst if item]
    return before_colon, after_colon

#### Métodos

In [2]:
lift = attack_client()

##### get_enterprise_techniques

In [3]:
get_enterprise_techniques = lift.get_enterprise_techniques(stix_format=False)
get_enterprise_techniques_df = pd.json_normalize(get_enterprise_techniques)
get_enterprise_techniques_df = get_enterprise_techniques_df[(get_enterprise_techniques_df['mitre_deprecated'] != 'True')]

[taxii2client.v20] [WARNING ] [2024-07-02 09:47:18,461] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-02 09:47:18,532] TAXII Server Response with different amount of objects! Setting per_request=780

##### get_enterprise_tactics

In [13]:
get_enterprise_tactics = lift.get_enterprise_tactics(stix_format=False)
get_enterprise_tactics_df = pd.json_normalize(get_enterprise_tactics)
get_enterprise_tactics_df = get_enterprise_tactics_df[(get_enterprise_tactics_df['mitre_deprecated'] != 'True')]

[taxii2client.v20] [WARNING ] [2024-06-19 17:17:48,530] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 17:17:48,530] TAXII Server Response with different amount of objects! Setting per_request=14

##### get_data_sources

In [14]:
get_data_sources = lift.get_data_sources(stix_format=False)
get_data_sources_df = pd.json_normalize(get_data_sources)

[taxii2client.v20] [WARNING ] [2024-06-19 17:17:54,555] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 17:17:54,557] TAXII Server Response with different amount of objects! Setting per_request=38
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:02,507] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:02,507] TAXII Server Response with different amount of objects! Setting per_request=17
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:09,291] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:09,292] TAXII Server Response with different amount of objects! Setting per_request=6

##### get_groups

In [15]:
get_groups = lift.get_groups(stix_format=False)
get_groups_df = pd.json_normalize(get_groups)
get_groups_df = get_groups_df.sort_values(by='group_id')

[taxii2client.v20] [WARNING ] [2024-06-19 17:18:21,429] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:21,429] TAXII Server Response with different amount of objects! Setting per_request=163
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:25,016] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:25,016] TAXII Server Response with different amount of objects! Setting per_request=13
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:38,376] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 17:18:38,377] TAXII Server Response with different amount of objects! Setting per_request=16

##### get_techniques_used_by_all_groups()

In [73]:
get_techniques_used_by_all_groups = lift.get_techniques_used_by_all_groups(stix_format=False)
get_techniques_used_by_all_groups_df = pd.json_normalize(get_techniques_used_by_all_groups)
get_techniques_used_by_all_groups_df = get_techniques_used_by_all_groups_df.sort_values(by='group_id')

##### get_software()

In [ ]:
get_software = lift.get_software(stix_format=False)
get_software_df = pd.json_normalize(get_software)
get_software_df = get_software_df.sort_values(by='software_id')

[taxii2client.v20] [WARNING ] [2024-06-19 15:21:43,632] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 15:21:43,642] TAXII Server Response with different amount of objects! Setting per_request=595
[taxii2client.v20] [WARNING ] [2024-06-19 15:21:50,315] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 15:21:50,315] TAXII Server Response with different amount of objects! Setting per_request=85
[taxii2client.v20] [WARNING ] [2024-06-19 15:21:54,966] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 15:21:54,968] TAXII Server Response with different amount of objects! Setting per_request=111
[taxii2client.v20] [WARNING ] [2024-06-19 15:22:02,260] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 15:22:02,260] TAXII Server Response with different amount of objects! Setting per_request=2
[taxii2client.v20] [WARNING ] [2024-06-19 15:22:06,544] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-19 15:22:06,544] TAXII Server Response with different amount of objects! Setting per_request=28

#### Parámetros

In [17]:
save_to_file = True

### **1. TÁCTICAS - TÉCNICAS**

#### **1.1 Tablas intermedias (N:N)**

In [18]:
# Comenzamos filtrando el df de técnicas y nos quedamos con las columnas que vamos a necesitar
enterprise_tactics_with_techniques_df = get_enterprise_techniques_df[['technique_id', 'technique','url','tactic']]
print(f"Filas del df: {enterprise_tactics_with_techniques_df.shape[0]}. TTP's únicas: {enterprise_tactics_with_techniques_df['technique_id'].nunique()}")
# Generamos tantas filas como tácticas encontremos dando lugar a una relación 1-1 entre técnicas y tácticas
enterprise_tactics_with_techniques_df = enterprise_tactics_with_techniques_df.explode('tactic')
print(f"Tras explode. Filas del df: {enterprise_tactics_with_techniques_df.shape[0]}. TTP's únicas: {enterprise_tactics_with_techniques_df['technique_id'].nunique()}. Tácticas únicas: {enterprise_tactics_with_techniques_df['tactic'].nunique()}")

# Reordenamos el df
enterprise_tactics_with_techniques_df = enterprise_tactics_with_techniques_df[['tactic', 'technique_id', 'technique', 'url']]
# Ordenamos por las tácticas
enterprise_tactics_with_techniques_df = enterprise_tactics_with_techniques_df.sort_values(by='tactic')
# Renombramos el campo url
enterprise_tactics_with_techniques_df = enterprise_tactics_with_techniques_df.rename(columns={'url': 'url_technique'})
# Llamamos a get_enterprise_tactics_df y nos quedamos con los campos que necesitamos para hacer left join
concat_get_enterprise_tactics_df = get_enterprise_tactics_df[['tactic_id','tactic_shortname','tactic_description','url']]
# Renombramos el campo url y tactic_shortname
concat_get_enterprise_tactics_df = concat_get_enterprise_tactics_df.rename(columns={'url': 'url_tactic', 'tactic_shortname': 'tactic'})
mitre_n2n_enterprise_techniques_tactics = pd.merge(enterprise_tactics_with_techniques_df, concat_get_enterprise_tactics_df, left_on='tactic', right_on='tactic', how='left')
mitre_n2n_enterprise_techniques_tactics.head(3)
print(f"Filas del df: {mitre_n2n_enterprise_techniques_tactics.shape[0]}. TTP's únicas: {mitre_n2n_enterprise_techniques_tactics['technique_id'].nunique()}. Tácticas únicas: {mitre_n2n_enterprise_techniques_tactics['tactic_id'].nunique()}")

Filas del df: 637. TTP's únicas: 637
Tras explode. Filas del df: 830. TTP's únicas: 637. Tácticas únicas: 14
Filas del df: 830. TTP's únicas: 637. Tácticas únicas: 14

**[MITRE] Técnicas - Tácticas (N:N)**

In [35]:
if save_to_file:
    save_df_as_csv(mitre_n2n_enterprise_techniques_tactics, '[MITRE]_enterprise_n2n_techniques_tactics', 'inter_techniques_tactics')

Fichero generado correctamente [MITRE]_enterprise_n2n_techniques_tactics

**[CP] Técnicas - Tácticas (N:N)**

In [19]:
cp_ttp_available = cp_ttps()
cp_n2n_enterprise_techniques_tactics = mitre_n2n_enterprise_techniques_tactics[mitre_n2n_enterprise_techniques_tactics['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {cp_n2n_enterprise_techniques_tactics.shape[0]}. TTP's únicas: {cp_n2n_enterprise_techniques_tactics['technique_id'].nunique()}. Tácticas únicas: {cp_n2n_enterprise_techniques_tactics['tactic_id'].nunique()}")
if save_to_file:
    save_df_as_csv(cp_n2n_enterprise_techniques_tactics, '[CP]_enterprise_n2n_techniques_tactics', 'inter_techniques_tactics')

Filas del df: 679. TTP's únicas: 516. Tácticas únicas: 14

**[NOCP] Técnicas - Tácticas (N:N)**

In [37]:
nocp_n2n_enterprise_techniques_tactics = mitre_n2n_enterprise_techniques_tactics[~mitre_n2n_enterprise_techniques_tactics['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {nocp_n2n_enterprise_techniques_tactics.shape[0]}. TTP's únicas: {nocp_n2n_enterprise_techniques_tactics['technique_id'].nunique()}. Tácticas únicas: {nocp_n2n_enterprise_techniques_tactics['tactic_id'].nunique()}")
if save_to_file:
    save_df_as_csv(nocp_n2n_enterprise_techniques_tactics, '[NOCP]_enterprise_n2n_techniques_tactics', 'inter_techniques_tactics')

Filas del df: 151. TTP's únicas: 121. Tácticas únicas: 13
Fichero generado correctamente [NOCP]_enterprise_n2n_techniques_tactics

#### **1.2 Técnicas - Tácticas (1:N)**

**[MITRE] Técnicas - Tácticas (1:N)**

In [38]:
# Agregamos las columnas por la columna technique_id
mitre_techniques_with_tactics = mitre_n2n_enterprise_techniques_tactics.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'tactic_id': unique_list,
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_techniques_with_tactics, '[MITRE]_techniques_with_tactics', 'technique_tactics_1N')

Fichero generado correctamente [MITRE]_techniques_with_tactics

**[CP] Técnicas - Tácticas (1:N)**

In [39]:
cp_techniques_with_tactics = cp_n2n_enterprise_techniques_tactics.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'tactic_id': unique_list,
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list
    })
if save_to_file:
    save_df_as_csv(cp_techniques_with_tactics, '[CP]_techniques_with_tactics', 'technique_tactics_1N')

Fichero generado correctamente [CP]_techniques_with_tactics

**[NOCP] Técnicas - Tácticas (1:N)**

In [40]:
nocp_techniques_with_tactics = nocp_n2n_enterprise_techniques_tactics.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'tactic_id': unique_list,
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_techniques_with_tactics, '[NOCP]_techniques_with_tactics', 'technique_tactics_1N')

Fichero generado correctamente [NOCP]_techniques_with_tactics

#### **1.3 Tácticas - Técnicas (1:N)**

**[MITRE] Tácticas - Técnicas (1:N)**

In [41]:
# Agregamos las columnas por la columna tactic_id
mitre_tactics_with_techniques = mitre_n2n_enterprise_techniques_tactics.groupby('tactic_id', as_index=False).agg({
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list,
    'technique_id': unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(mitre_tactics_with_techniques, '[MITRE]_tactics_with_techniques', 'tactic_techniques_1N')

Fichero generado correctamente [MITRE]_tactics_with_techniques

**[CP] Tácticas - Técnicas (1:N)**

In [42]:
# Agregamos las columnas por la columna tactic_id
cp_tactics_with_techniques = cp_n2n_enterprise_techniques_tactics.groupby('tactic_id', as_index=False).agg({
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list,
    'technique_id': unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(cp_tactics_with_techniques, '[CP]_tactics_with_techniques', 'tactic_techniques_1N')

Fichero generado correctamente [CP]_tactics_with_techniques

**[NOCP] Tácticas - Técnicas (1:N)**

In [43]:
# Agregamos las columnas por la columna tactic_id
nocp_tactics_with_techniques = nocp_n2n_enterprise_techniques_tactics.groupby('tactic_id', as_index=False).agg({
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list,
    'technique_id': unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(nocp_tactics_with_techniques, '[NOCP]_tactics_with_techniques', 'tactic_techniques_1N')

Fichero generado correctamente [NOCP]_tactics_with_techniques

### **2. DATA SOURCES - TÉCNICAS**

#### **2.1 Tablas intermedias (N:N)**

In [44]:
#Formateamos el df para exportar
data_sources_export_df = get_data_sources_df
data_sources_export_df['data_source_id'] = data_sources_export_df['url'].str.replace('https://attack.mitre.org/datasources/', '')
data_sources_export_df = data_sources_export_df[['data_source_id','data_source','data_source_description','url']].sort_values('data_source')
data_sources_export_df = data_sources_export_df.rename(columns={'url': 'url_data_source'})
if save_to_file:
    save_df_as_csv(data_sources_export_df, '[MITRE]_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [MITRE]_data_sources

In [45]:
data_sources_export_df.head(3)

,data_source_id,data_source,data_source_description,url_data_source
8,DS0026,Active Directory,A database and set of services that allows adm...,https://attack.mitre.org/datasources/DS0026
26,DS0015,Application Log,Events collected by third-party services such ...,https://attack.mitre.org/datasources/DS0015
39,DS0041,Application Vetting,Application vetting report generated by an ext...,https://attack.mitre.org/datasources/DS0041

In [46]:
# Obtenemos de get_enterprise_techniques_df las técnicas con el data source asociado
temp_o2n_techniques_data_sources_df = get_enterprise_techniques_df[['technique_id', 'data_sources','url']]
temp_o2n_techniques_data_sources_df = temp_o2n_techniques_data_sources_df.rename(columns={'url': 'url_technique'})

    
temp_o2n_techniques_data_sources_df[['data_source_simp', 'data_source_detail']] = temp_o2n_techniques_data_sources_df['data_sources'].apply(lambda x: pd.Series(split_lists(x)))
# Antes de unir las tablas debemos desagregar la tabla procendente de get_enterprise_techniques_df en tantas filas como tecnicas y data sources existan
n2n_techniques_data_sources_df = temp_o2n_techniques_data_sources_df.explode(['data_source_simp','data_source_detail'])
# Unimos las tablas para disponer de la información completa
n2n_techniques_data_sources_df = pd.merge(n2n_techniques_data_sources_df, data_sources_export_df, left_on='data_source_simp', right_on='data_source', how='outer') #left
n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[['technique_id', 'url_technique', 'data_source_id', 'data_source', 'data_source_detail', 'url_data_source']]
#Eliminamos duplicados, no es necesario pero a futuro evitar inconsistencias
n2n_techniques_data_sources_df = n2n_techniques_data_sources_df.drop_duplicates()
#Ordenamos el df por la técnica
n2n_techniques_data_sources_df = n2n_techniques_data_sources_df.sort_values('technique_id')
n2n_techniques_data_sources_df.reset_index(drop=True, inplace=True)
n2n_techniques_data_sources_df.head(2)

,technique_id,url_technique,data_source_id,data_source,data_source_detail,url_data_source
0,T1001,https://attack.mitre.org/techniques/T1001,DS0029,Network Traffic,Network Traffic Content,https://attack.mitre.org/datasources/DS0029
1,T1001.001,https://attack.mitre.org/techniques/T1001/001,DS0029,Network Traffic,Network Traffic Content,https://attack.mitre.org/datasources/DS0029

In [47]:
ttps_without_sd_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[n2n_techniques_data_sources_df['data_source_id'].isnull()]
print(f"TTP's únicas sin data source asociado: {ttps_without_sd_n2n_techniques_data_sources_df['technique_id'].nunique()}")
ttps_with_sd_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[~n2n_techniques_data_sources_df['data_source_id'].isnull()]
print(f"TTP's únicas con data source asociado: {ttps_with_sd_n2n_techniques_data_sources_df['technique_id'].nunique()}")
sd_with_ttp_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[~n2n_techniques_data_sources_df['technique_id'].isnull()]
print(f"Data sources únicas con data source asociado: {sd_with_ttp_n2n_techniques_data_sources_df['data_source_id'].nunique()}")
sd_without_ttp_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[n2n_techniques_data_sources_df['technique_id'].isnull()]
print(f"Data sources únicas sin TTP asociada: {sd_without_ttp_n2n_techniques_data_sources_df['data_source_id'].nunique()}")

TTP's únicas sin data source asociado: 40
TTP's únicas con data source asociado: 597
Data sources únicas con data source asociado: 37
Data sources únicas sin TTP asociada: 5

**[MITRE] Guardado Técnicas - Data sources N:N**

In [48]:
# Guardamos la relación entre técnicas y data sources completa: Técnicas con y sin data source; y Data sources con y sin técnica asociada.
if save_to_file:
    save_df_as_csv(n2n_techniques_data_sources_df, '[MITRE]_enterprise_n2n_all_techniques_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [MITRE]_enterprise_n2n_all_techniques_data_sources

In [49]:
# Guardamos la relación entre técnicas y data sources completa: Sólo tecnicas y data sources con relación.
n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[(~n2n_techniques_data_sources_df['technique_id'].isnull()) & (~n2n_techniques_data_sources_df['data_source_id'].isnull())]
if save_to_file:
    save_df_as_csv(n2n_techniques_data_sources_df, '[MITRE]_enterprise_n2n_techniques_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [MITRE]_enterprise_n2n_techniques_data_sources

**[CP] Relación N:N Técnicas y Data Sources**

Filtramos la tabla mitre por aquellas técnicas disponibles en CyberProof

In [50]:
cp_ttp_available = cp_ttps()
cp_ttp_available[:3]

['T1195.001', 'T1021.007', 'T1052.001']

In [51]:
cp_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[n2n_techniques_data_sources_df['technique_id'].isin(cp_ttp_available)]
if save_to_file:
    save_df_as_csv(cp_n2n_techniques_data_sources_df, '[CP]_enterprise_n2n_techniques_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [CP]_enterprise_n2n_techniques_data_sources

**[NOCP] Relación N:N Técnicas y Data Sources**

In [52]:
nocp_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[~n2n_techniques_data_sources_df['technique_id'].isin(cp_ttp_available)]
if save_to_file:
    save_df_as_csv(nocp_n2n_techniques_data_sources_df, '[NOCP]_enterprise_n2n_techniques_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [NOCP]_enterprise_n2n_techniques_data_sources

#### **2.2 Técnicas - Data Sources (1:N)**

**[MITRE] TECHNIQUES - DATASOURCES 1:N**

In [53]:
# Agregamos las columnas por la columna technique_id
mitre_techniques_with_data_sources_df = n2n_techniques_data_sources_df.groupby('technique_id', as_index=False).agg({
    'url_technique':unique_list,
    'data_source_id': unique_list,
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_techniques_with_data_sources_df, '[MITRE]_techniques_with_data_sources_df', 'technique_data_sources_1N')

Fichero generado correctamente [MITRE]_techniques_with_data_sources_df

**[CP] TECHNIQUES - DATASOURCES 1:N**

In [54]:
# Agregamos las columnas por la columna technique_id
cp_techniques_with_data_sources_df = cp_n2n_techniques_data_sources_df.groupby('technique_id', as_index=False).agg({
    'url_technique':unique_list,
    'data_source_id': unique_list,
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list
    })
if save_to_file:
    save_df_as_csv(cp_techniques_with_data_sources_df, '[CP]_techniques_with_data_sources_df', 'technique_data_sources_1N')

Fichero generado correctamente [CP]_techniques_with_data_sources_df

**[NOCP] TECHNIQUES - DATASOURCES 1:N**

In [55]:
# Agregamos las columnas por la columna technique_id
nocp_techniques_with_data_sources_df = nocp_n2n_techniques_data_sources_df.groupby('technique_id', as_index=False).agg({
    'url_technique':unique_list,
    'data_source_id': unique_list,
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_techniques_with_data_sources_df, '[NOCP]_techniques_with_data_sources_df', 'technique_data_sources_1N')

Fichero generado correctamente [NOCP]_techniques_with_data_sources_df

#### **2.3 Data Sources - Técnicas (1:N)**

**[MITRE] TECHNIQUES - DATASOURCES 1:N**

In [56]:
# Agregamos las columnas por la columna technique_id
mitre_data_source_with_techniques_df = n2n_techniques_data_sources_df.groupby('data_source_id', as_index=False).agg({
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list,
    'url_technique':unique_list,
    'technique_id': unique_list
    })
save_df_as_csv(mitre_data_source_with_techniques_df, '[MITRE]_data_source_with_techniques', 'data_source_techniques_1N')

Fichero generado correctamente [MITRE]_data_source_with_techniques

**[CP] TECHNIQUES - DATA SOURCES 1:N**

In [57]:
# Agregamos las columnas por la columna technique_id
cp_data_source_with_techniques_df = cp_n2n_techniques_data_sources_df.groupby('data_source_id', as_index=False).agg({
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list,
    'url_technique':unique_list,
    'technique_id': unique_list
    })
save_df_as_csv(cp_data_source_with_techniques_df, '[CP]_data_source_with_techniques', 'data_source_techniques_1N')

Fichero generado correctamente [CP]_data_source_with_techniques

**[NOCP] TECHNIQUES - DATA SOURCES 1:N**

In [58]:
# Agregamos las columnas por la columna technique_id
nocp_data_source_with_techniques_df = nocp_n2n_techniques_data_sources_df.groupby('data_source_id', as_index=False).agg({
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list,
    'url_technique':unique_list,
    'technique_id': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_data_source_with_techniques_df, '[NOCP]_data_source_with_techniques', 'data_source_techniques_1N')

Fichero generado correctamente [NOCP]_data_source_with_techniques

### **3. GRUPOS - TÉCNICAS**

#### **3.1 Tablas intermedias (N:N)**

In [20]:
groups_df = get_groups_df[['group_id','group','group_aliases','matrix','url']]
groups_df = groups_df.rename(columns={'url': 'url_group'})
if save_to_file:
    save_df_as_csv(groups_df, '[MITRE]_all_groups', 'inter_groups_techniques')
enterprise_groups_df = groups_df[groups_df['matrix'].apply(lambda x: 'enterprise-attack' in x)]
enterprise_groups_df.head(2)
if save_to_file:
    save_df_as_csv(enterprise_groups_df, '[MITRE]_enterprise_groups', 'inter_groups_techniques')

Fichero generado correctamente [MITRE]_all_groups_14062024_1432h.csv
Fichero generado correctamente [MITRE]_enterprise_groups_14062024_1432h.csv

In [60]:

# OLD -> Se obtiene toda la información disponible (data source, platform, etc..) pero de cara a permitir correctamente las relaciones vamos a guardar sólo la información de técnicas y grupos
'''
# Filtramos los items cuya técnica sea de tipo enterprise. La lista de grupos se reduce al no aparecer aquellos con técnica asociada y ahora con tipo enterprise.
mitre_all_info_groups_df = get_techniques_used_by_all_groups_df[get_techniques_used_by_all_groups_df['technique_matrix'].apply(lambda x: 'enterprise-attack' in x)]
# Hacemos una selección de columnas con las que trabajar
mitre_all_info_groups_df = mitre_all_info_groups_df[['group_id','group','url','technique_id', 'technique', 'platform']]
# Renombramos la url de la técnica
mitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={'url': 'url_group'})

# Unimos con Data Sources para complementar la información
mitre_all_info_groups_df = pd.merge(mitre_all_info_groups_df, n2n_techniques_data_sources_df, left_on='technique_id', right_on='technique_id', how='left')
mitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={'url_technique_x': 'url_technique'})

# Ampliamos el df por todos los campos necesarios para llegar a la relación N:N con el detalle de los data sources
mitre_all_info_groups_df = mitre_all_info_groups_df.explode(['data_source','data_source_detail'])

# Unimos con Tácticas para complementar la información
# Importante: No hemos añadido la información de tácticas que se facilita en get_techniques_used_by_all_groups ya que queremos hacer un left join limpio directamente con technique_id
mitre_all_info_groups_df = pd.merge(mitre_all_info_groups_df, mitre_n2n_enterprise_techniques_tactics, left_on='technique_id', right_on='technique_id', how='left')


# Al realizar la unión de tácticas con técnicas se crearan más filas ya que cada técnica puede estar asociada a varias tácticas. Reemplazamos el nombre de algunas columnas generadas y eliminamos las duplicadas. 
mitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={'technique_x': 'technique','url_technique_x': 'url_technique'})
mitre_all_info_groups_df.drop('technique_y', axis=1, inplace=True)
mitre_all_info_groups_df.drop('url_technique_y', axis=1, inplace=True)
mitre_all_info_groups_df = mitre_all_info_groups_df.explode(['platform'])

print(f"Filas del df: {mitre_all_info_groups_df.shape[0]}.  Grupos unicos: {mitre_all_info_groups_df['group_id'].nunique()}. TTP's únicas: {mitre_all_info_groups_df['technique_id'].nunique()}. Platform únicas: {mitre_all_info_groups_df['platform'].nunique()}. Tácticas únicas: {mitre_all_info_groups_df['data_source'].nunique()}. Data Sources únicos: {mitre_all_info_groups_df['data_source'].nunique()}")

'''

'\n# Filtramos los items cuya técnica sea de tipo enterprise. La lista de grupos se reduce al no aparecer aquellos con técnica asociada y ahora con tipo enterprise.\nmitre_all_info_groups_df = get_techniques_used_by_all_groups_df[get_techniques_used_by_all_groups_df[\'technique_matrix\'].apply(lambda x: \'enterprise-attack\' in x)]\n# Hacemos una selección de columnas con las que trabajar\nmitre_all_info_groups_df = mitre_all_info_groups_df[[\'group_id\',\'group\',\'url\',\'technique_id\', \'technique\', \'platform\']]\n# Renombramos la url de la técnica\nmitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={\'url\': \'url_group\'})\n\n# Unimos con Data Sources para complementar la información\nmitre_all_info_groups_df = pd.merge(mitre_all_info_groups_df, n2n_techniques_data_sources_df, left_on=\'technique_id\', right_on=\'technique_id\', how=\'left\')\nmitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={\'url_technique_x\': \'url_technique\'})\n\n# Ampliamos el df por todos los campos necesarios para llegar a la relación N:N con el detalle de los data sources\nmitre_all_info_groups_df = mitre_all_info_groups_df.explode([\'data_source\',\'data_source_detail\'])\n\n# Unimos con Tácticas para complementar la información\n# Importante: No hemos añadido la información de tácticas que se facilita en get_techniques_used_by_all_groups ya que queremos hacer un left join limpio directamente con technique_id\nmitre_all_info_groups_df = pd.merge(mitre_all_info_groups_df, mitre_n2n_enterprise_techniques_tactics, left_on=\'technique_id\', right_on=\'technique_id\', how=\'left\')\n\n\n# Al realizar la unión de tácticas con técnicas se crearan más filas ya que cada técnica puede estar asociada a varias tácticas. Reemplazamos el nombre de algunas columnas generadas y eliminamos las duplicadas. \nmitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={\'technique_x\': \'technique\',\'url_technique_x\': \'url_technique\'})\nmitre_all_info_groups_df.drop(\'technique_y\', axis=1, inplace=True)\nmitre_all_info_groups_df.drop(\'url_technique_y\', axis=1, inplace=True)\nmitre_all_info_groups_df = mitre_all_info_groups_df.explode([\'platform\'])\n\nprint(f"Filas del df: {mitre_all_info_groups_df.shape[0]}.  Grupos unicos: {mitre_all_info_groups_df[\'group_id\'].nunique()}. TTP\'s únicas: {mitre_all_info_groups_df[\'technique_id\'].nunique()}. Platform únicas: {mitre_all_info_groups_df[\'platform\'].nunique()}. Tácticas únicas: {mitre_all_info_groups_df[\'data_source\'].nunique()}. Data Sources únicos: {mitre_all_info_groups_df[\'data_source\'].nunique()}")\n\n'

In [21]:
# Filtramos los items cuya técnica sea de tipo enterprise. La lista de grupos se reduce al no aparecer aquellos con técnica asociada y ahora con tipo enterprise.
mitre_n2n_techniques_groups_df = get_techniques_used_by_all_groups_df[get_techniques_used_by_all_groups_df['technique_matrix'].apply(lambda x: 'enterprise-attack' in x)]
# Hacemos una selección de columnas con las que trabajar
mitre_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df[['group_id','group','url','technique_id', 'technique']]
# Renombramos la url de la técnica
mitre_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df.rename(columns={'url': 'url_group'})

#Unimos con la tabla de técnicas para completar la información relativa a estas
mitre_n2n_techniques_groups_df = pd.merge(mitre_n2n_techniques_groups_df, get_enterprise_techniques_df[['technique_id', 'technique','url']], left_on='technique_id', right_on='technique_id', how='left')

# Renombramos la url de la técnica
mitre_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df.rename(columns={'technique_x': 'technique','url': 'url_technique'})
# Eliminamos la columna sobrante
mitre_n2n_techniques_groups_df.drop('technique_y', axis=1, inplace=True)

print(f"Filas del df: {mitre_n2n_techniques_groups_df.shape[0]}.  Grupos unicos: {mitre_n2n_techniques_groups_df['group_id'].nunique()}. TTP's únicas: {mitre_n2n_techniques_groups_df['technique_id'].nunique()}")

mitre_n2n_techniques_groups_df.head(2)

Filas del df: 3387.  Grupos unicos: 143. TTP's únicas: 421

,group_id,group,url_group,technique_id,technique,url_technique
0,G0001,Axiom,https://attack.mitre.org/groups/G0001,T1560,Archive Collected Data,https://attack.mitre.org/techniques/T1560
1,G0001,Axiom,https://attack.mitre.org/groups/G0001,T1583.002,DNS Server,https://attack.mitre.org/techniques/T1583/002

**[MITRE] Guardado Grupos - Técnicas N:N**

In [22]:
if save_to_file:
    save_df_as_csv(mitre_n2n_techniques_groups_df, '[MITRE]_enterprise_techniques_groups', 'inter_groups_techniques')

Fichero generado correctamente [MITRE]_enterprise_techniques_groups_14062024_1433h.csv

**[CP] Relación Grupos - Técnicas N:N**

In [23]:
cp_ttp_available = cp_ttps()
cp_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df[mitre_n2n_techniques_groups_df['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {cp_n2n_techniques_groups_df.shape[0]}. Grupos únicos: {cp_n2n_techniques_groups_df['group_id'].nunique()}. TTP's únicas: {cp_n2n_techniques_groups_df['technique_id'].nunique()}")
if save_to_file:
    save_df_as_csv(cp_n2n_techniques_groups_df, '[CP]_enterprise_techniques_groups', 'inter_groups_techniques')

Filas del df: 3150. Grupos únicos: 142. TTP's únicas: 363
Fichero generado correctamente [CP]_enterprise_techniques_groups_14062024_1434h.csv

**[NOCP] Relación Grupos - Técnicas N:N**

In [24]:
cp_ttp_available = cp_ttps()
nocp_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df[~mitre_n2n_techniques_groups_df['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {nocp_n2n_techniques_groups_df.shape[0]}. Grupos únicos: {nocp_n2n_techniques_groups_df['group_id'].nunique()}. TTP's únicas: {nocp_n2n_techniques_groups_df['technique_id'].nunique()}")
if save_to_file:
    save_df_as_csv(nocp_n2n_techniques_groups_df, '[NOCP]_enterprise_techniques_groups', 'inter_groups_techniques')

Filas del df: 237. Grupos únicos: 83. TTP's únicas: 58
Fichero generado correctamente [NOCP]_enterprise_techniques_groups_14062024_1434h.csv

#### **3.2 Grupos - Técnicas (1:N)**

**[MITRE] Grupos - Técnicas (1:N)**

In [26]:
# Agregamos las columnas por la columna group_id
mitre_groups_with_techniques_df = mitre_n2n_techniques_groups_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'url_group':unique_list,
    'technique_id': unique_list,
    'technique': unique_list,
    'url_technique': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_groups_with_techniques_df, '[MITRE]_groups_with_techniques', 'group_techniques_1N')

mitre_groups_with_techniques_df.head(2)

Fichero generado correctamente [MITRE]_groups_with_techniques_14062024_1434h.csv

,group_id,group,url_group,technique_id,technique,url_technique
0,G0001,[Axiom],[https://attack.mitre.org/groups/G0001],"[T1001.002, T1005, T1560, T1553, T1546.008, T1...","[Virtual Private Server, Steganography, Subver...",[https://attack.mitre.org/techniques/T1584/005...
1,G0002,[Moafee],[https://attack.mitre.org/groups/G0002],[T1027.001],[Binary Padding],[https://attack.mitre.org/techniques/T1027/001]

In [66]:
print(f"[MITRE] Filas del df: {mitre_groups_with_techniques_df.shape[0]}. Grupos únicos: {mitre_groups_with_techniques_df['group_id'].nunique()}.")

[MITRE] Filas del df: 143. Grupos únicos: 143.

**[CP] Grupos - Técnicas (1:N)**

In [27]:
# Agregamos las columnas por la columna group_id
cp_groups_with_techniques_df = cp_n2n_techniques_groups_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'url_group':unique_list,
    'technique_id': unique_list,
    'technique': unique_list,
    'url_technique': unique_list
    })
if save_to_file:
    save_df_as_csv(cp_groups_with_techniques_df, '[CP]_groups_with_techniques', 'group_techniques_1N')

cp_groups_with_techniques_df.head(2)

Fichero generado correctamente [CP]_groups_with_techniques_14062024_1434h.csv

,group_id,group,url_group,technique_id,technique,url_technique
0,G0001,[Axiom],[https://attack.mitre.org/groups/G0001],"[T1001.002, T1005, T1560, T1553, T1546.008, T1...","[Steganography, Subvert Trust Controls, Data f...","[https://attack.mitre.org/techniques/T1560, ht..."
1,G0002,[Moafee],[https://attack.mitre.org/groups/G0002],[T1027.001],[Binary Padding],[https://attack.mitre.org/techniques/T1027/001]

In [28]:
print(f"[CP] Filas del df: {cp_groups_with_techniques_df.shape[0]}. Grupos únicos: {cp_groups_with_techniques_df['group_id'].nunique()}.")

[CP] Filas del df: 142. Grupos únicos: 142.

**[NOCP] Grupos - Técnicas (1:N)**

In [29]:
# Agregamos las columnas por la columna group_id
nocp_groups_with_techniques_df = nocp_n2n_techniques_groups_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'url_group':unique_list,
    'technique_id': unique_list,
    'technique': unique_list,
    'url_technique': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_groups_with_techniques_df, '[NOCP]_groups_with_techniques', 'group_techniques_1N')

nocp_groups_with_techniques_df.head(2)

Fichero generado correctamente [NOCP]_groups_with_techniques_14062024_1434h.csv

,group_id,group,url_group,technique_id,technique,url_technique
0,G0001,[Axiom],[https://attack.mitre.org/groups/G0001],"[T1583.003, T1583.002, T1584.005]","[Virtual Private Server, Botnet, DNS Server]",[https://attack.mitre.org/techniques/T1584/005...
1,G0003,[Cleaver],[https://attack.mitre.org/groups/G0003],[T1585.001],[Social Media Accounts],[https://attack.mitre.org/techniques/T1585/001]

In [30]:
print(f"[NOCP] Filas del df: {nocp_groups_with_techniques_df.shape[0]}. Grupos únicos: {nocp_groups_with_techniques_df['group_id'].nunique()}.")

[NOCP] Filas del df: 83. Grupos únicos: 83.

#### **3.3 Técnicas - Grupos (1:N)**

**[MITRE] Técnicas - Grupos (1:N)**

In [31]:
# Agregamos las columnas por la columna technique_id
mitre_techniques_with_groups_df = mitre_n2n_techniques_groups_df.groupby('technique_id', as_index=False).agg({
    'technique': unique_list,
    'url_technique': unique_list,
    'group':unique_list,
    'group_id':unique_list,
    'url_group':unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_techniques_with_groups_df, '[MITRE]_techniques_with_groups_df', 'technique_groups_1N')

mitre_techniques_with_groups_df.head(2)

Fichero generado correctamente [MITRE]_techniques_with_groups_df_14062024_1434h.csv

,technique_id,technique,url_technique,group,group_id,url_group
0,T1001.001,[Junk Data],[https://attack.mitre.org/techniques/T1001/001],[APT28],[G0007],[https://attack.mitre.org/groups/G0007]
1,T1001.002,[Steganography],[https://attack.mitre.org/techniques/T1001/002],[Axiom],[G0001],[https://attack.mitre.org/groups/G0001]

In [32]:
print(f"[MITRE] Filas del df: {mitre_techniques_with_groups_df.shape[0]}. TTP's únicas: {mitre_techniques_with_groups_df['technique_id'].nunique()}.")

[MITRE] Filas del df: 421. TTP's únicas: 421.

**[CP] Técnicas - Grupos (1:N)**

In [33]:
# Agregamos las columnas por la columna technique_id
cp_techniques_with_groups_df = cp_n2n_techniques_groups_df.groupby('technique_id', as_index=False).agg({
    'technique': unique_list,
    'url_technique': unique_list,
    'group':unique_list,
    'group_id':unique_list,
    'url_group':unique_list
    })
if save_to_file:
    save_df_as_csv(cp_techniques_with_groups_df, '[CP]_techniques_with_groups_df', 'technique_groups_1N')

cp_techniques_with_groups_df.head(2)

Fichero generado correctamente [CP]_techniques_with_groups_df_14062024_1434h.csv

,technique_id,technique,url_technique,group,group_id,url_group
0,T1001.002,[Steganography],[https://attack.mitre.org/techniques/T1001/002],[Axiom],[G0001],[https://attack.mitre.org/groups/G0001]
1,T1001.003,[Protocol Impersonation],[https://attack.mitre.org/techniques/T1001/003],"[Lazarus Group, Higaisa]","[G0032, G0126]","[https://attack.mitre.org/groups/G0032, https:..."

In [34]:
print(f"[CP] Filas del df: {cp_techniques_with_groups_df.shape[0]}. TTP's únicas: {cp_techniques_with_groups_df['technique_id'].nunique()}.")

[CP] Filas del df: 363. TTP's únicas: 363.

**[NOCP] Técnicas - Grupos (1:N)**

In [35]:
# Agregamos las columnas por la columna technique_id
nocp_techniques_with_groups_df = nocp_n2n_techniques_groups_df.groupby('technique_id', as_index=False).agg({
    'technique': unique_list,
    'url_technique': unique_list,
    'group':unique_list,
    'group_id':unique_list,
    'url_group':unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_techniques_with_groups_df, '[NOCP]_techniques_with_groups_df', 'technique_groups_1N')

nocp_techniques_with_groups_df.head(2)

Fichero generado correctamente [NOCP]_techniques_with_groups_df_14062024_1435h.csv

,technique_id,technique,url_technique,group,group_id,url_group
0,T1001.001,[Junk Data],[https://attack.mitre.org/techniques/T1001/001],[APT28],[G0007],[https://attack.mitre.org/groups/G0007]
1,T1016.002,[Wi-Fi Discovery],[https://attack.mitre.org/techniques/T1016/002],[Magic Hound],[G0059],[https://attack.mitre.org/groups/G0059]

In [36]:
print(f"[NOCP] Filas del df: {nocp_techniques_with_groups_df.shape[0]}. TTP's únicas: {nocp_techniques_with_groups_df['technique_id'].nunique()}.")

[NOCP] Filas del df: 58. TTP's únicas: 58.

### **4. SOFTWARE - TÉCNICAS**

#### **4.1 Tablas intermedias (N:N)**

In [171]:
software_df = get_software_df[['software_id','software','software_aliases','type','url','matrix']]
software_df = software_df.rename(columns={'url': 'url_software'})
if save_to_file:
    save_df_as_csv(software_df, '[MITRE]_all_software', 'inter_software_techniques')
enterprise_software_df = software_df[software_df['matrix'].apply(lambda x: 'enterprise-attack' in x)]
enterprise_software_df.head(2)
if save_to_file:
    save_df_as_csv(enterprise_software_df, '[MITRE]_enterprise_software', 'inter_software_techniques')

Fichero generado correctamente [MITRE]_all_software
Fichero generado correctamente [MITRE]_enterprise_software

PROBLEMA: No soy capaz de relacionar software con técnica.

get_techniques_used_by_software -> NO trae ninguna columna con la que poder identificar el software

get_enterprise_malware, get_enterprise_tools -> Atacando a través de la tipologia del software tampoco soy capaz de identificar ninguna relación

Solución: Tras probar directamente a stix y otras opciones he encontrado el método get_techniques_used_by_software(), al cual si se le pasa el objeto stix2.v20.sdo.Tool correspondiente como unico software del metodo get_software() como parametro este devolverá la tabla con las técnicas asociadas. Por lo tanto, mediante un bucle iremos recorriendo la lista de software (794) y se iran añadiendo a un df donde ademas de las técnicas incorporaremos la información relativa al SW.

In [ ]:
results_df = pd.DataFrame(columns=['type', 'id', 'url', 'matrix', 'created', 'modified', 'created_by_ref',
       'modified_by_ref', 'external_references', 'object_marking_refs',
       'mitre_version', 'mitre_attack_spec_version', 'mitre_deprecated',
       'technique', 'technique_id', 'technique_description', 'tactic',
       'technique_detection', 'platform', 'data_sources', 'defense_bypassed',
       'permissions_required', 'effective_permissions', 'system_requirements',
       'network_requirements', 'remote_support', 'contributors', 'tactic_type',
       'impact_type', 'is_subtechnique', 'software_id', 'software',
       'software_aliases', 'software_description', 'software_type',
       'url_software', 'mitre_domains'])

In [93]:
# En esta parte del código obtenemos la lista de software y uno a uno se lo pasamos al método et_techniques_used_by_software que nos devolverá la tabla con las técnicas utilizadas por cada SW.
# Importante: Este código es lento, aproximadamente tarda 1,5 minutos por petición lo que hace que para los 795 items tarde aproximadamente 20 horas.
# Si se tiene que reejecutar esta parte tambien es posible que falle alguna conexión, en tal caso en lugar de empezar de 0 simplemente no ejecutar la celda anterior y modificar range(len(software)) por range(row, len(software))

software = lift.get_software()

for row in range(len(software)):

    info_row_techniques_software =  lift.get_techniques_used_by_software(software[row], stix_format=False)
    info_row_techniques_software_df = pd.json_normalize(info_row_techniques_software)


    # Recogemos info de software y la añadimos al df
    info_row_techniques_software_df['software_id'] = software[row].external_references[0].external_id

    info_row_techniques_software_df['software'] = software[row].name

    aliases = getattr(software[row], 'x_mitre_aliases', [])
    info_row_techniques_software_df['software_aliases'] = [aliases] * len(info_row_techniques_software_df)

    info_row_techniques_software_df['software_description'] = software[row].description

    info_row_techniques_software_df['software_type'] = software[row].type

    info_row_techniques_software_df['url_software'] = software[row].external_references[0].url
    
    domains = getattr(software[row], 'x_mitre_domains', [])
    info_row_techniques_software_df['mitre_domains'] = [domains] * len(info_row_techniques_software_df)

    print(f"Finalizado {row}: {software[row].name}")


    results_df = pd.concat([results_df,info_row_techniques_software_df])
# Filtramos técnicas deprecadas
results_df = results_df[(results_df['mitre_deprecated'] != 'True')]
# Filtramos SW enterprise
results_df = results_df[results_df['mitre_domains'].apply(lambda x: 'enterprise-attack' in x)]

results_df['url_technique'] = results_df['external_references'].apply(lambda x: x[0]['url'] if x else None)

if save_to_file:
    save_df_as_csv(results_df, '[MITRE]_n2n_main_techniques_software', 'inter_software_techniques')

[taxii2client.v20] [WARNING ] [2024-06-14 09:29:57,827] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:07,079] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:08,397] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:12,602] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:17,020] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:17,058] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:20,540] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:20,557] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:23,791] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:23,817] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:26,930] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:26,945] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:29,948] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:29,948] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 648: FLASHFLOOD

[taxii2client.v20] [WARNING ] [2024-06-14 09:30:36,870] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:40,590] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:46,278] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:53,951] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:57,621] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:30:57,637] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:00,606] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:00,623] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:06,445] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:06,461] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:10,532] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:10,532] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:13,538] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:13,538] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 649: SPACESHIP

[taxii2client.v20] [WARNING ] [2024-06-14 09:31:17,570] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:19,307] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:21,357] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:23,977] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:30,314] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:30,331] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:35,853] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:35,874] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:44,143] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:44,165] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:47,462] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:47,462] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:50,697] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:31:50,698] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 650: NETEAGLE

[taxii2client.v20] [WARNING ] [2024-06-14 09:32:01,279] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:13,867] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:19,438] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:20,589] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:27,695] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:27,713] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:30,881] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:30,898] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:34,980] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:35,004] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:37,858] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:37,858] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:41,907] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:41,907] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 651: NetTraveler

[taxii2client.v20] [WARNING ] [2024-06-14 09:32:46,494] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:53,517] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:32:57,837] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:00,106] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:06,227] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:06,248] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:09,548] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:09,563] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:15,401] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:15,436] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:18,454] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:18,454] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:21,690] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:21,707] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 652: gh0st RAT

[taxii2client.v20] [WARNING ] [2024-06-14 09:33:25,977] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:28,796] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:30,964] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:32,983] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:38,819] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:38,822] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:44,976] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:44,991] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:48,879] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:48,917] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:51,664] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:51,665] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:54,517] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:33:54,517] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 653: BACKSPACE

[taxii2client.v20] [WARNING ] [2024-06-14 09:33:59,538] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:01,810] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:04,092] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:05,221] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:08,362] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:08,379] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:11,314] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:11,331] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:23,091] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:23,129] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:26,744] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:26,761] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:34,734] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:34,750] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 654: Carbanak

[taxii2client.v20] [WARNING ] [2024-06-14 09:34:45,693] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:34:56,535] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:07,544] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:11,665] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:16,989] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:17,002] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:20,121] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:20,121] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:23,608] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:23,645] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:31,067] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:31,080] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:35,268] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:35:35,268] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 655: SHIPSHAPE

[taxii2client.v20] [WARNING ] [2024-06-14 09:35:55,584] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:36:25,365] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:36:45,259] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:36:55,693] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:02,207] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:02,245] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:10,171] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:10,190] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:25,342] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:25,516] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:30,045] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:30,046] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:35,750] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:37:35,750] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 656: Zeroaccess

[taxii2client.v20] [WARNING ] [2024-06-14 09:37:45,734] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:00,235] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:16,373] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:20,788] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:23,826] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:23,862] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:26,859] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:26,876] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:30,029] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:30,079] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:33,198] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:33,213] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:35,868] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:35,870] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 657: GLOOXMAIL

[taxii2client.v20] [WARNING ] [2024-06-14 09:38:45,208] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:48,828] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:52,247] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:54,515] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:57,618] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:38:57,635] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:00,804] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:00,824] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:05,099] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:05,108] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:08,747] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:08,760] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:11,279] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:11,295] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 658: CALENDAR

[taxii2client.v20] [WARNING ] [2024-06-14 09:39:15,414] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:17,001] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:18,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:19,969] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:23,240] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:23,259] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:26,441] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:26,457] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:29,798] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:29,835] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:32,521] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:32,526] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:35,751] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:35,767] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 659: Dyre

[taxii2client.v20] [WARNING ] [2024-06-14 09:39:41,957] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:43,476] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:45,076] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:47,128] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:50,345] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:50,364] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:53,331] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:53,350] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:57,069] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:39:57,106] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:00,006] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:00,006] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:03,089] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:03,089] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 660: CHOPSTICK

[taxii2client.v20] [WARNING ] [2024-06-14 09:40:07,209] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:09,344] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:11,231] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:14,115] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:18,188] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:18,202] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:22,755] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:22,755] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:27,150] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:27,176] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:30,365] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:30,365] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:35,886] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:35,886] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 661: Uroburos

[taxii2client.v20] [WARNING ] [2024-06-14 09:40:45,314] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:48,395] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:52,799] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:40:55,866] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:02,105] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:02,120] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:07,928] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:07,943] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:13,698] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:13,718] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:17,703] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:17,703] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:24,074] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:24,074] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 662: Derusbi

[taxii2client.v20] [WARNING ] [2024-06-14 09:41:29,912] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:36,233] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:42,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:48,160] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:53,499] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:41:53,524] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:05,193] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:05,213] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:13,514] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:13,532] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:16,610] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:16,614] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:20,119] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:20,119] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 663: China Chopper

[taxii2client.v20] [WARNING ] [2024-06-14 09:42:33,899] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:39,937] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:50,863] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:56,367] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:59,887] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:42:59,923] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:03,191] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:03,205] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:09,643] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:09,680] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:12,297] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:12,314] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:16,082] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:16,099] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 664: Regin

[taxii2client.v20] [WARNING ] [2024-06-14 09:43:24,488] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:31,644] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:37,078] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:40,946] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:44,110] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:44,126] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:47,241] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:47,266] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:54,397] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:43:54,420] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:01,203] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:01,203] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:06,023] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:06,023] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 665: Sykipot

[taxii2client.v20] [WARNING ] [2024-06-14 09:44:17,344] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:22,019] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:30,679] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:32,929] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:39,854] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:39,868] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:45,324] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:45,335] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:53,196] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:53,216] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:57,800] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:44:57,800] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:04,539] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:04,539] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 666: BISCUIT

[taxii2client.v20] [WARNING ] [2024-06-14 09:45:10,537] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:13,962] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:16,582] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:18,684] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:21,630] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:21,645] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:24,946] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:24,946] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:32,060] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:32,091] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:35,422] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:35,422] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:38,909] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:38,911] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 667: P2P ZeuS

[taxii2client.v20] [WARNING ] [2024-06-14 09:45:44,822] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:45:58,832] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:03,827] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:10,776] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:16,343] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:16,359] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:27,110] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:27,124] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:31,944] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:31,979] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:35,282] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:35,282] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:39,202] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:39,219] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 668: Ixeshe

[taxii2client.v20] [WARNING ] [2024-06-14 09:46:49,194] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:46:58,065] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:09,959] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:15,180] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:25,521] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:25,538] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:29,125] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:29,125] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:40,441] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:40,471] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:44,004] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:44,004] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:46,873] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:47:46,873] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 669: BS2005

[taxii2client.v20] [WARNING ] [2024-06-14 09:47:53,747] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:01,605] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:09,882] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:12,477] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:16,364] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:16,383] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:19,787] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:19,800] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:23,737] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:23,775] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:27,727] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:27,727] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:30,778] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:30,778] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 670: PlugX

[taxii2client.v20] [WARNING ] [2024-06-14 09:48:36,549] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:41,637] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:48,957] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:48:59,469] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:08,126] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:08,161] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:13,711] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:13,731] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:25,088] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:25,124] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:29,277] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:29,277] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:33,096] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:33,096] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 671: PoisonIvy

[taxii2client.v20] [WARNING ] [2024-06-14 09:49:41,100] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:46,366] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:51,612] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:49:55,329] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:05,857] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:05,874] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:13,831] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:13,845] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:18,435] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:18,458] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:24,942] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:24,942] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:31,629] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:50:31,629] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 672: Taidoor

[taxii2client.v20] [WARNING ] [2024-06-14 09:50:52,195] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:02,810] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:10,594] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:26,022] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:34,095] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:34,130] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:44,255] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:44,269] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:51,685] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:51,695] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:55,956] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:55,956] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:59,955] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:51:59,955] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 673: Lurid

[taxii2client.v20] [WARNING ] [2024-06-14 09:52:08,410] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:14,916] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:19,668] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:30,093] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:38,051] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:38,067] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:41,254] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:41,276] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:46,974] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:46,997] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:51,262] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:51,262] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:53,863] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:52:53,863] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 674: Hikit

[taxii2client.v20] [WARNING ] [2024-06-14 09:53:03,772] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:12,027] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:16,115] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:21,153] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:25,238] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:25,258] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:28,757] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:28,775] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:32,896] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:32,929] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:37,285] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:37,285] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:40,678] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:40,680] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 675: Skeleton Key

[taxii2client.v20] [WARNING ] [2024-06-14 09:53:45,138] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:48,071] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:50,426] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:52,512] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:55,647] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:55,665] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:58,533] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:53:58,552] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:01,852] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:01,870] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:04,438] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:04,438] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:07,659] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:07,659] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 676: TinyZBot

[taxii2client.v20] [WARNING ] [2024-06-14 09:54:11,761] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:13,565] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:16,899] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:20,502] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:23,908] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:23,924] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:27,866] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:27,876] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:31,347] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:31,376] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:33,963] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:33,980] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:36,882] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:36,882] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 677: RIPTIDE

[taxii2client.v20] [WARNING ] [2024-06-14 09:54:41,537] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:43,173] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:44,957] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:46,873] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:50,176] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:50,194] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:53,285] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:53,297] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:56,632] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:56,651] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:59,235] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:54:59,235] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:02,306] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:02,306] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 678: Trojan.Mebromi

[taxii2client.v20] [WARNING ] [2024-06-14 09:55:06,775] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:08,310] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:09,976] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:11,010] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:14,730] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:14,749] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:17,742] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:17,752] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:20,985] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:21,003] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:23,772] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:23,787] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:26,692] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:26,692] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 679: HilalRAT

[taxii2client.v20] [WARNING ] [2024-06-14 09:55:38,136] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:44,888] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:53,914] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:55:57,398] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:01,301] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:01,317] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:05,405] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:05,405] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:08,727] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:08,762] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:11,613] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:11,613] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:17,399] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:17,399] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 680: Phenakite

[taxii2client.v20] [WARNING ] [2024-06-14 09:56:21,390] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:24,956] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:34,147] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:35,165] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:44,404] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:44,424] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:48,377] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:48,377] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:54,463] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:54,496] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:59,654] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:56:59,668] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:02,671] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:02,671] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 681: FlixOnline

[taxii2client.v20] [WARNING ] [2024-06-14 09:57:10,673] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:14,465] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:19,419] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:22,070] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:26,608] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:26,625] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:31,944] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:31,963] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:39,952] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:39,986] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:43,037] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:43,037] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:46,024] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:46,027] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 682: AhRat

[taxii2client.v20] [WARNING ] [2024-06-14 09:57:50,263] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:53,467] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:55,951] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:57:56,850] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:00,017] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:00,036] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:03,330] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:03,338] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:06,407] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:06,593] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:09,493] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:09,509] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:12,611] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:12,611] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 683: BRATA

[taxii2client.v20] [WARNING ] [2024-06-14 09:58:17,684] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:19,284] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:20,551] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:21,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:24,489] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:24,507] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:27,524] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:27,524] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:30,576] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:30,596] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:33,464] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:33,464] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:37,116] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:37,131] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 684: FlyTrap

[taxii2client.v20] [WARNING ] [2024-06-14 09:58:41,854] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:43,354] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:45,173] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:46,225] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:49,227] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:49,242] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:52,146] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:52,158] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:55,348] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:55,375] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:58,489] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:58:58,493] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:01,355] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:01,355] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 685: Escobar

[taxii2client.v20] [WARNING ] [2024-06-14 09:59:05,526] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:08,274] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:09,742] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:10,659] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:14,299] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:14,313] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:17,226] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:17,233] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:20,751] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:20,807] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:24,138] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:24,138] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:28,727] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:28,727] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 686: Chameleon

[taxii2client.v20] [WARNING ] [2024-06-14 09:59:32,381] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:34,298] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:36,148] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:37,334] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:40,518] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:40,536] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:43,970] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:43,973] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:47,026] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:47,042] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:49,759] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:49,759] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:53,364] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:53,364] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 687: Sunbird

[taxii2client.v20] [WARNING ] [2024-06-14 09:59:57,449] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 09:59:59,416] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:01,487] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:03,222] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:08,992] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:09,010] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:14,532] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:14,550] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:21,153] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:21,170] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:26,990] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:27,007] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:30,129] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:00:30,129] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 688: Fakecalls

[taxii2client.v20] [WARNING ] [2024-06-14 10:00:52,563] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:01:16,281] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:01:35,731] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:01:42,187] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:01:56,351] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:01:56,374] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:09,859] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:09,875] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:19,998] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:20,017] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:26,173] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:26,173] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:32,311] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:32,313] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 689: BOULDSPY

[taxii2client.v20] [WARNING ] [2024-06-14 10:02:43,876] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:02:56,380] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:03:24,253] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:03:34,231] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:03:47,107] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:03:47,136] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:03:59,774] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:03:59,793] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:04:17,851] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:04:17,890] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:04:23,454] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:04:23,454] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:04:30,426] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:04:30,428] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 690: Hornbill

[taxii2client.v20] [WARNING ] [2024-06-14 10:04:57,583] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:05:14,781] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:05:31,544] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:05:40,469] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:05:49,575] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:05:49,796] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:05,390] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:05,406] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:19,500] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:19,541] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:23,423] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:23,423] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:29,143] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:29,143] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 691: TangleBot

[taxii2client.v20] [WARNING ] [2024-06-14 10:06:45,041] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:06:53,182] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:09,809] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:19,876] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:28,393] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:28,407] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:34,813] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:34,813] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:38,818] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:38,856] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:42,870] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:42,870] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:48,743] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:07:48,743] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 692: FluBot

[taxii2client.v20] [WARNING ] [2024-06-14 10:07:53,897] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:04,772] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:08,592] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:12,568] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:20,883] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:20,907] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:24,172] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:24,188] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:28,908] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:28,925] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:33,277] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:33,277] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:36,081] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:36,081] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 693: S.O.V.A.

[taxii2client.v20] [WARNING ] [2024-06-14 10:08:41,286] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:44,423] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:08:52,829] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:01,005] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:06,498] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:06,508] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:16,063] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:16,066] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:22,777] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:22,815] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:26,707] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:26,707] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:31,694] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:31,694] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 694: AbstractEmu

[taxii2client.v20] [WARNING ] [2024-06-14 10:09:39,237] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:44,857] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:09:51,506] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:02,736] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:11,610] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:11,610] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:21,736] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:21,752] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:29,775] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:29,808] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:34,314] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:34,314] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:39,115] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:10:39,117] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 695: TianySpy

[taxii2client.v20] [WARNING ] [2024-06-14 10:11:01,319] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:16,865] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:23,789] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:29,224] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:41,136] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:41,151] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:45,723] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:45,738] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:54,664] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:54,845] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:59,866] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:11:59,884] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:12:09,693] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:12:09,693] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 696: SharkBot

[taxii2client.v20] [WARNING ] [2024-06-14 10:12:33,478] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:12:47,023] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:13:08,858] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:13:30,177] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:13:44,638] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:13:44,654] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:13:57,431] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:13:57,449] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:14:08,841] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:14:08,881] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:14:13,679] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:14:13,679] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:14:20,315] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:14:20,319] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 697: Drinik

[taxii2client.v20] [WARNING ] [2024-06-14 10:14:50,241] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:15:12,146] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:15:40,150] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:02,200] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:18,386] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:18,415] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:30,592] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:30,608] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:43,352] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:43,391] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:54,578] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:16:54,578] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:17:03,719] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:17:03,719] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 698: BusyGasper

[taxii2client.v20] [WARNING ] [2024-06-14 10:17:23,937] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:17:39,148] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:17:53,061] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:17:59,750] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:04,969] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:04,988] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:12,203] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:12,210] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:25,554] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:25,572] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:32,563] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:32,563] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:35,330] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:35,330] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 699: Circles

[taxii2client.v20] [WARNING ] [2024-06-14 10:18:46,187] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:18:54,312] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:06,504] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:14,977] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:22,801] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:22,825] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:28,739] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:28,758] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:34,679] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:34,862] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:38,214] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:38,214] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:42,951] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:19:42,951] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 700: FrozenCell

[taxii2client.v20] [WARNING ] [2024-06-14 10:19:55,379] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:04,284] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:10,807] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:14,878] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:20,515] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:20,535] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:24,617] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:24,621] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:34,745] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:34,761] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:38,615] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:38,615] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:50,510] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:20:50,510] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 701: Tiktok Pro

[taxii2client.v20] [WARNING ] [2024-06-14 10:21:04,820] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:21:19,482] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:21:30,107] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:21:47,858] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:21:57,296] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:21:57,315] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:03,792] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:03,806] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:12,193] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:12,243] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:17,630] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:17,646] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:21,897] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:21,901] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 702: CHEMISTGAMES

[taxii2client.v20] [WARNING ] [2024-06-14 10:22:34,679] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:22:49,207] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:02,947] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:14,680] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:19,966] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:19,984] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:25,541] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:25,555] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:37,013] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:37,028] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:41,202] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:41,202] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:43,970] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:43,970] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 703: GoldenEagle

[taxii2client.v20] [WARNING ] [2024-06-14 10:23:48,876] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:23:56,027] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:02,533] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:10,074] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:14,463] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:14,481] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:23,117] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:23,135] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:30,489] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:30,671] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:34,480] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:34,480] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:39,716] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:39,716] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 704: DoubleAgent

[taxii2client.v20] [WARNING ] [2024-06-14 10:24:48,522] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:24:57,281] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:25:09,408] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:25:22,167] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:25:33,286] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:25:33,309] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:25:43,420] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:25:43,433] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:25:54,010] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:25:54,025] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:03,886] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:03,886] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:08,437] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:08,437] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 705: SilkBean

[taxii2client.v20] [WARNING ] [2024-06-14 10:26:19,712] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:30,123] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:37,128] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:44,836] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:52,375] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:52,391] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:58,362] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:26:58,397] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:05,754] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:05,785] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:10,088] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:10,108] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:14,979] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:14,992] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 706: TERRACOTTA

[taxii2client.v20] [WARNING ] [2024-06-14 10:27:25,902] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:31,873] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:43,167] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:49,805] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:53,874] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:53,890] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:58,462] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:27:58,477] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:04,167] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:04,199] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:07,152] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:07,169] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:10,956] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:10,956] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 707: HenBox

[taxii2client.v20] [WARNING ] [2024-06-14 10:28:17,444] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:25,301] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:35,886] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:42,915] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:50,505] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:50,537] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:56,713] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:28:56,727] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:01,930] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:01,968] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:07,385] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:07,389] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:11,389] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:11,406] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 708: Asacub

[taxii2client.v20] [WARNING ] [2024-06-14 10:29:19,712] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:25,851] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:30,873] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:39,429] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:42,965] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:42,987] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:45,855] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:45,886] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:49,204] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:49,223] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:51,906] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:51,906] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:55,628] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:29:55,628] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 709: Red Alert 2.0

[taxii2client.v20] [WARNING ] [2024-06-14 10:29:59,880] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:04,398] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:06,970] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:08,985] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:12,723] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:12,742] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:16,359] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:16,377] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:19,630] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:19,663] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:22,314] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:22,314] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:25,952] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:25,952] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 710: GPlayed

[taxii2client.v20] [WARNING ] [2024-06-14 10:30:30,840] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:32,808] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:35,241] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:40,414] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:43,482] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:43,511] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:46,536] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:46,551] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:49,922] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:49,957] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:53,240] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:53,240] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:56,793] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:30:56,793] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 711: Golden Cup

[taxii2client.v20] [WARNING ] [2024-06-14 10:31:01,964] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:05,368] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:08,286] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:09,986] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:13,092] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:13,106] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:20,499] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:20,679] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:24,699] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:24,717] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:27,519] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:27,523] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:34,694] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:34,694] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 712: CarbonSteal

[taxii2client.v20] [WARNING ] [2024-06-14 10:31:39,428] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:43,702] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:49,287] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:54,200] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:58,295] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:31:58,310] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:03,816] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:03,832] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:08,454] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:08,487] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:14,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:14,490] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:17,208] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:17,211] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 713: Android/AdDisplay.Ashas

[taxii2client.v20] [WARNING ] [2024-06-14 10:32:24,849] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:28,020] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:30,922] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:33,332] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:42,549] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:42,564] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:47,086] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:47,102] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:53,629] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:53,661] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:56,978] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:32:56,982] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:02,648] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:02,648] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 714: AndroidOS/MalLocker.B

[taxii2client.v20] [WARNING ] [2024-06-14 10:33:12,589] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:24,682] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:30,353] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:35,757] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:43,899] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:43,915] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:49,552] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:49,571] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:59,861] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:33:59,894] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:02,981] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:02,981] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:06,732] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:06,735] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 715: Exobot

[taxii2client.v20] [WARNING ] [2024-06-14 10:34:15,573] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:20,530] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:26,720] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:31,988] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:37,344] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:37,359] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:44,984] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:44,984] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:52,542] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:52,556] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:57,592] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:34:57,597] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:04,748] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:04,766] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 716: FakeSpy

[taxii2client.v20] [WARNING ] [2024-06-14 10:35:20,915] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:25,122] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:35,858] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:47,583] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:52,921] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:52,939] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:58,261] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:35:58,276] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:06,546] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:06,589] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:12,071] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:12,071] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:15,058] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:15,058] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 717: eSurv

[taxii2client.v20] [WARNING ] [2024-06-14 10:36:21,495] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:25,365] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:35,624] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:43,435] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:51,504] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:36:51,520] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:04,296] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:04,319] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:12,773] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:12,812] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:20,528] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:20,544] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:26,464] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:26,466] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 718: ViperRAT

[taxii2client.v20] [WARNING ] [2024-06-14 10:37:39,727] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:46,581] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:49,587] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:54,823] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:59,061] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:37:59,076] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:04,595] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:04,597] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:10,485] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:10,519] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:14,043] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:14,047] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:17,307] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:17,309] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 719: Desert Scorpion

[taxii2client.v20] [WARNING ] [2024-06-14 10:38:24,132] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:34,128] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:47,187] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:53,054] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:56,608] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:38:56,639] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:01,277] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:01,279] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:08,502] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:08,685] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:11,486] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:11,486] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:14,175] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:14,187] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 720: Zen

[taxii2client.v20] [WARNING ] [2024-06-14 10:39:20,660] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:22,762] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:25,648] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:26,950] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:30,017] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:30,036] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:32,838] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:32,839] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:36,241] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:36,273] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:38,909] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:38,909] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:41,763] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:41,766] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 721: XLoader for iOS

[taxii2client.v20] [WARNING ] [2024-06-14 10:39:47,101] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:48,733] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:50,488] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:51,385] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:54,506] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:54,529] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:57,324] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:39:57,342] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:00,594] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:00,610] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:03,814] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:03,814] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:06,298] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:06,298] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 722: WolfRAT

[taxii2client.v20] [WARNING ] [2024-06-14 10:40:10,787] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:11,937] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:13,804] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:15,255] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:18,710] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:18,725] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:22,550] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:22,561] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:25,831] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:25,851] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:29,217] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:29,219] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:33,622] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:40:33,622] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 723: Mandrake

[taxii2client.v20] [WARNING ] [2024-06-14 10:40:50,434] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:00,743] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:06,866] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:09,834] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:14,454] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:14,470] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:19,060] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:19,225] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:28,105] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:28,117] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:32,355] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:32,355] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:39,677] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:39,677] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 724: Cerberus

[taxii2client.v20] [WARNING ] [2024-06-14 10:41:49,033] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:41:56,591] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:42:22,427] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:42:37,356] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:42:42,929] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:42:42,944] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:42:49,869] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:42:49,885] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:42:57,039] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:42:57,059] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:00,745] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:00,745] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:04,715] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:04,729] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 725: DEFENSOR ID

[taxii2client.v20] [WARNING ] [2024-06-14 10:43:20,314] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:25,630] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:32,018] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:36,455] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:40,827] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:40,847] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:47,132] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:47,148] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:50,251] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:50,266] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:52,885] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:52,885] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:55,890] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:43:55,890] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 726: EventBot

[taxii2client.v20] [WARNING ] [2024-06-14 10:44:00,875] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:03,546] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:06,017] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:07,914] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:11,237] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:11,251] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:14,236] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:14,236] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:17,738] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:17,757] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:21,377] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:21,377] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:26,397] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:26,397] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 727: INSOMNIA

[taxii2client.v20] [WARNING ] [2024-06-14 10:44:35,321] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:40,876] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:45,478] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:47,032] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:49,983] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:49,999] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:53,404] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:53,419] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:56,873] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:56,887] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:59,493] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:44:59,506] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:02,393] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:02,393] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 728: Agent Smith

[taxii2client.v20] [WARNING ] [2024-06-14 10:45:09,499] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:12,586] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:17,924] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:22,255] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:26,581] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:26,615] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:30,749] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:30,767] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:37,321] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:37,355] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:42,895] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:42,895] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:48,933] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:45:48,933] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 729: Bread

[taxii2client.v20] [WARNING ] [2024-06-14 10:46:10,699] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:16,288] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:28,047] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:35,086] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:42,093] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:42,108] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:48,866] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:48,887] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:59,426] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:46:59,444] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:47:06,132] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:47:06,132] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:47:13,451] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:47:13,451] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 730: TrickMo

[taxii2client.v20] [WARNING ] [2024-06-14 10:47:35,888] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:47:47,329] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:04,244] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:13,990] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:17,671] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:17,687] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:23,759] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:23,778] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:32,102] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:32,151] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:36,288] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:36,288] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:40,340] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:40,340] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 731: Concipit1248

[taxii2client.v20] [WARNING ] [2024-06-14 10:48:53,034] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:48:59,340] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:05,252] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:08,463] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:15,370] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:15,386] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:19,956] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:19,971] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:25,011] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:25,065] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:28,245] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:28,246] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:30,915] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:30,916] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 732: Corona Updates

[taxii2client.v20] [WARNING ] [2024-06-14 10:49:36,119] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:38,122] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:41,708] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:44,375] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:47,461] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:47,482] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:50,898] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:50,915] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:56,088] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:56,120] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:58,796] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:49:58,800] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:03,060] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:03,060] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 733: Ginp

[taxii2client.v20] [WARNING ] [2024-06-14 10:50:07,127] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:13,517] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:17,354] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:21,206] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:27,298] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:27,312] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:32,716] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:32,735] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:41,625] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:41,663] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:47,313] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:47,313] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:52,687] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:50:52,687] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 734: Anubis

[taxii2client.v20] [WARNING ] [2024-06-14 10:51:03,510] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:15,853] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:27,796] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:36,570] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:43,994] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:44,009] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:47,716] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:47,716] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:52,216] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:52,250] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:57,408] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:51:57,408] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:52:01,540] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:52:01,540] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 735: GolfSpy

[taxii2client.v20] [WARNING ] [2024-06-14 10:52:17,605] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:52:31,082] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:52:50,265] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:00,042] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:12,853] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:13,033] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:22,041] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:22,060] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:29,681] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:29,713] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:32,851] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:32,851] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:35,638] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:35,638] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 736: Dvmap

[taxii2client.v20] [WARNING ] [2024-06-14 10:53:44,028] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:53:55,000] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:01,609] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:08,254] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:13,484] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:13,507] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:19,139] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:19,139] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:22,209] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:22,226] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:24,896] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:24,896] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:28,161] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:28,164] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 737: SimBad

[taxii2client.v20] [WARNING ] [2024-06-14 10:54:32,150] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:33,938] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:35,889] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:38,905] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:42,676] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:42,691] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:46,695] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:46,713] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:51,970] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:51,982] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:54,721] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:54,721] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:57,657] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:54:57,660] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 738: ViceLeaker

[taxii2client.v20] [WARNING ] [2024-06-14 10:55:02,708] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:06,844] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:08,948] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:10,879] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:14,342] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:14,355] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:17,390] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:17,402] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:20,586] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:20,614] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:24,650] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:24,654] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:28,680] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:28,680] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 739: Rotexy

[taxii2client.v20] [WARNING ] [2024-06-14 10:55:38,776] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:48,249] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:55:53,767] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:04,010] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:16,804] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:16,823] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:24,278] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:24,294] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:30,950] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:30,966] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:39,373] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:39,390] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:46,828] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:56:46,829] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 740: Monokle

[taxii2client.v20] [WARNING ] [2024-06-14 10:56:57,598] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:57:09,650] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:57:25,913] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:57:34,436] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:57:43,412] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:57:43,427] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:57:49,950] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:57:49,965] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:01,675] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:01,713] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:06,832] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:06,832] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:11,298] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:11,298] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 741: Gustuff

[taxii2client.v20] [WARNING ] [2024-06-14 10:58:25,484] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:34,986] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:37,705] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:41,526] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:44,645] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:44,663] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:47,747] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:47,747] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:51,016] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:51,054] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:54,154] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:54,154] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:57,221] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:58:57,221] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 742: Exodus

[taxii2client.v20] [WARNING ] [2024-06-14 10:59:04,278] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:08,699] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:11,499] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:13,185] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:16,321] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:16,341] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:20,657] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:20,675] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:27,232] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:27,264] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:33,370] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:33,370] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:37,619] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:37,623] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 743: Riltok

[taxii2client.v20] [WARNING ] [2024-06-14 10:59:45,461] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:49,481] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:52,257] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 10:59:56,373] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:04,111] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:04,294] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:12,766] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:12,785] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:21,924] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:21,958] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:24,996] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:25,012] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:30,666] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:00:30,666] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 744: Triada

[taxii2client.v20] [WARNING ] [2024-06-14 11:00:59,673] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:01:37,389] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:01:57,041] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:02:12,967] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:02:27,528] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:02:27,548] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:02:37,889] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:02:37,889] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:03:01,409] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:03:01,443] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:03:06,632] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:03:06,644] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:03:20,074] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:03:20,074] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 745: Pallas

[taxii2client.v20] [WARNING ] [2024-06-14 11:03:41,560] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:04:01,676] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:04:36,870] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:04:54,167] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:05:17,038] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:05:17,056] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:05:30,232] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:05:30,251] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:05:55,359] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:05:55,395] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:06:00,976] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:06:00,976] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:06:10,365] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:06:10,365] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 746: Allwinner

[taxii2client.v20] [WARNING ] [2024-06-14 11:06:30,550] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:06:42,859] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:06:51,634] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:06:59,171] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:12,734] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:12,749] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:19,925] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:19,939] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:28,698] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:28,731] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:35,421] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:35,421] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:40,092] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:40,106] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 747: Judy

[taxii2client.v20] [WARNING ] [2024-06-14 11:07:52,018] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:07:57,815] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:16,019] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:28,581] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:32,649] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:32,674] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:36,172] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:36,185] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:40,323] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:40,357] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:48,264] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:48,264] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:53,767] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:08:53,767] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 748: XLoader for Android

[taxii2client.v20] [WARNING ] [2024-06-14 11:09:06,412] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:18,321] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:32,433] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:41,191] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:47,811] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:47,830] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:52,520] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:52,533] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:59,022] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:09:59,042] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:10:04,513] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:10:04,513] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:10:10,483] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:10:10,483] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 749: Tangelo

[taxii2client.v20] [WARNING ] [2024-06-14 11:10:21,692] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:10:30,481] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:10:45,661] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:10:56,953] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:11,298] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:11,316] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:22,526] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:22,552] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:30,831] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:30,867] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:37,603] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:37,605] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:41,775] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:11:41,775] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 750: Marcher

[taxii2client.v20] [WARNING ] [2024-06-14 11:11:53,366] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:07,363] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:20,375] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:32,653] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:42,773] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:42,799] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:49,830] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:49,848] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:59,305] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:12:59,338] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:05,194] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:05,194] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:08,802] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:08,804] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 751: SpyDealer

[taxii2client.v20] [WARNING ] [2024-06-14 11:13:23,341] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:34,751] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:40,433] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:44,025] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:54,105] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:54,119] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:57,821] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:13:57,837] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:07,461] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:07,502] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:16,237] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:16,237] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:20,589] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:20,589] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 752: Skygofree

[taxii2client.v20] [WARNING ] [2024-06-14 11:14:32,649] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:36,902] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:41,075] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:45,126] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:49,669] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:49,684] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:53,519] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:53,533] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:56,788] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:14:56,802] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:01,290] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:01,306] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:04,293] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:04,293] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 753: Stealth Mango

[taxii2client.v20] [WARNING ] [2024-06-14 11:15:13,877] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:15,420] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:17,920] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:19,691] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:26,527] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:26,545] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:29,880] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:29,900] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:34,019] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:34,035] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:36,652] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:36,652] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:39,656] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:39,656] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 754: RedDrop

[taxii2client.v20] [WARNING ] [2024-06-14 11:15:45,560] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:15:54,052] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:05,927] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:13,950] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:20,638] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:20,666] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:25,113] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:25,128] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:32,751] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:32,788] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:39,340] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:39,340] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:44,367] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:44,367] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 755: RuMMS

[taxii2client.v20] [WARNING ] [2024-06-14 11:16:52,149] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:16:59,788] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:03,292] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:15,669] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:26,193] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:26,214] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:34,521] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:34,533] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:37,656] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:37,669] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:41,340] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:41,340] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:44,453] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:44,457] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 756: YiSpecter

[taxii2client.v20] [WARNING ] [2024-06-14 11:17:50,364] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:52,714] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:53,999] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:17:55,817] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:00,406] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:00,422] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:04,475] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:04,490] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:09,579] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:09,613] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:12,580] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:12,580] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:16,420] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:16,435] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 757: ANDROIDOS_ANSERVER.A

[taxii2client.v20] [WARNING ] [2024-06-14 11:18:23,240] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:24,825] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:28,912] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:35,966] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:40,740] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:40,758] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:45,528] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:45,544] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:55,252] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:55,288] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:58,633] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:18:58,635] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:05,962] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:05,965] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 758: BrainTest

[taxii2client.v20] [WARNING ] [2024-06-14 11:19:24,376] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:36,967] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:43,275] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:48,413] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:52,347] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:52,370] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:57,968] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:19:57,985] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:20:12,182] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:20:12,216] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:20:15,666] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:20:15,682] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:20:23,775] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:20:23,775] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 759: AndroRAT

[taxii2client.v20] [WARNING ] [2024-06-14 11:20:33,116] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:20:59,386] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:21:14,836] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:21:34,331] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:21:53,316] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:21:53,350] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:10,578] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:10,595] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:15,935] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:15,988] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:24,724] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:24,724] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:37,854] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:37,854] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 760: Adups

[taxii2client.v20] [WARNING ] [2024-06-14 11:22:48,561] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:22:59,471] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:23:16,468] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:23:25,609] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:23:36,919] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:23:36,953] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:23:54,384] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:23:54,403] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:24:16,949] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:24:16,969] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:24:21,223] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:24:21,223] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:24:30,194] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:24:30,211] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 761: Trojan-SMS.AndroidOS.OpFake.a

[taxii2client.v20] [WARNING ] [2024-06-14 11:24:52,173] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:25:17,049] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:25:35,984] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:25:55,499] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:26:26,339] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:26:26,361] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:26:38,002] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:26:38,019] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:26:50,762] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:26:50,800] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:26:55,917] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:26:55,917] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:27:04,105] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:27:04,105] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 762: Trojan-SMS.AndroidOS.Agent.ao

[taxii2client.v20] [WARNING ] [2024-06-14 11:27:11,677] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:27:26,156] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:27:36,648] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:27:48,124] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:27:56,017] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:27:56,041] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:01,519] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:01,535] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:12,678] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:12,695] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:22,419] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:22,419] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:33,729] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:33,729] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 763: Trojan-SMS.AndroidOS.FakeInst.a

[taxii2client.v20] [WARNING ] [2024-06-14 11:28:40,916] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:43,823] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:48,979] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:50,817] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:56,765] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:28:56,783] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:00,985] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:01,006] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:05,755] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:05,796] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:09,408] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:09,408] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:12,528] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:12,528] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 764: SpyNote RAT

[taxii2client.v20] [WARNING ] [2024-06-14 11:29:17,850] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:23,139] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:29,812] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:35,780] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:39,287] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:39,316] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:43,071] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:43,087] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:47,056] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:47,080] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:50,145] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:50,145] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:52,760] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:29:52,764] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 765: Android/Chuli.A

[taxii2client.v20] [WARNING ] [2024-06-14 11:29:59,318] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:04,072] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:07,393] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:14,145] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:17,401] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:17,417] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:20,401] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:20,403] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:27,457] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:27,476] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:31,713] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:31,713] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:35,799] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:30:35,799] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 766: OldBoot

[taxii2client.v20] [WARNING ] [2024-06-14 11:30:49,426] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:04,813] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:14,178] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:19,149] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:23,422] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:23,436] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:27,922] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:27,926] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:31,910] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:31,953] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:35,550] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:35,563] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:39,149] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:39,149] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 767: ZergHelper

[taxii2client.v20] [WARNING ] [2024-06-14 11:31:47,466] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:53,161] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:31:59,586] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:15,571] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:27,727] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:27,744] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:33,563] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:33,577] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:51,995] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:52,162] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:56,813] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:32:56,813] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:02,805] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:02,806] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 768: OBAD

[taxii2client.v20] [WARNING ] [2024-06-14 11:33:19,633] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:27,422] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:32,412] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:36,012] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:39,084] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:39,102] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:42,501] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:42,504] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:46,507] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:46,532] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:49,627] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:49,627] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:52,262] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:33:52,275] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 769: Pegasus for iOS

[taxii2client.v20] [WARNING ] [2024-06-14 11:33:56,315] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:02,604] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:05,155] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:07,072] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:11,562] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:11,575] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:14,947] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:14,965] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:18,466] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:18,497] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:21,951] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:21,967] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:24,606] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:24,609] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 770: KeyRaider

[taxii2client.v20] [WARNING ] [2024-06-14 11:34:29,173] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:30,845] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:34,162] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:36,179] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:39,532] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:39,552] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:42,788] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:42,801] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:46,140] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:46,157] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:48,775] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:48,775] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:51,859] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:51,859] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 771: PJApps

[taxii2client.v20] [WARNING ] [2024-06-14 11:34:56,483] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:34:58,434] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:01,704] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:04,435] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:07,790] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:07,790] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:10,874] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:10,874] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:14,146] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:14,328] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:17,433] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:17,433] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:20,316] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:20,332] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 772: Gooligan

[taxii2client.v20] [WARNING ] [2024-06-14 11:35:24,886] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:29,942] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:34,963] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:44,204] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:47,171] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:47,187] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:51,258] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:51,261] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:58,630] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:35:58,650] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:03,786] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:03,788] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:07,922] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:07,922] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 773: HummingBad

[taxii2client.v20] [WARNING ] [2024-06-14 11:36:15,665] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:18,881] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:22,737] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:29,292] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:32,461] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:32,478] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:36,698] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:36,713] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:48,241] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:48,272] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:53,629] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:53,643] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:57,329] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:36:57,329] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 774: XcodeGhost

[taxii2client.v20] [WARNING ] [2024-06-14 11:37:01,535] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:05,788] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:09,556] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:11,857] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:15,146] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:15,163] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:18,930] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:18,947] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:26,889] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:26,925] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:30,944] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:30,959] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:34,596] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:34,596] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 775: Twitoor

[taxii2client.v20] [WARNING ] [2024-06-14 11:37:41,532] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:45,453] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:49,458] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:53,109] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:57,366] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:37:57,380] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:00,417] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:00,417] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:03,804] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:03,837] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:07,689] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:07,689] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:10,742] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:10,742] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 776: X-Agent for Android

[taxii2client.v20] [WARNING ] [2024-06-14 11:38:16,295] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:18,275] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:20,016] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:21,500] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:24,551] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:24,556] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:27,555] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:27,573] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:30,873] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:30,892] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:33,976] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:33,976] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:36,963] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:36,963] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 777: DualToy

[taxii2client.v20] [WARNING ] [2024-06-14 11:38:40,798] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:43,086] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:45,289] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:46,822] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:50,827] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:50,841] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:54,494] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:38:54,512] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:02,588] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:02,604] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:08,988] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:08,988] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:12,876] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:12,876] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 778: Pegasus for Android

[taxii2client.v20] [WARNING ] [2024-06-14 11:39:19,900] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:21,618] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:23,433] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:24,687] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:27,755] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:27,774] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:31,873] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:31,875] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:39,483] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:39,516] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:43,085] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:43,101] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:45,809] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:45,811] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 779: MazarBOT

[taxii2client.v20] [WARNING ] [2024-06-14 11:39:50,090] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:52,159] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:53,644] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:39:54,946] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:00,414] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:00,432] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:04,578] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:04,586] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:08,307] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:08,322] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:11,277] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:11,277] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:14,293] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:14,296] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 780: DroidJack

[taxii2client.v20] [WARNING ] [2024-06-14 11:40:18,598] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:21,616] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:23,002] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:24,418] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:28,191] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:28,205] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:31,324] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:31,343] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:34,728] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:34,763] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:39,515] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:39,515] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:42,618] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:42,618] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 781: HummingWhale

[taxii2client.v20] [WARNING ] [2024-06-14 11:40:49,539] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:53,594] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:56,497] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:40:58,827] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:03,582] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:03,599] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:06,620] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:06,636] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:10,624] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:10,651] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:13,309] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:13,325] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:16,614] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:16,618] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 782: Charger

[taxii2client.v20] [WARNING ] [2024-06-14 11:41:20,913] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:22,298] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:24,580] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:32,976] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:39,081] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:39,097] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:44,019] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:44,019] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:48,654] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:48,842] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:51,956] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:51,957] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:55,478] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:41:55,478] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 783: ShiftyBug

[taxii2client.v20] [WARNING ] [2024-06-14 11:42:04,953] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:11,120] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:17,141] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:19,397] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:22,369] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:22,383] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:25,552] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:25,570] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:28,926] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:28,941] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:31,543] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:31,543] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:34,645] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:34,645] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 784: RCSAndroid

[taxii2client.v20] [WARNING ] [2024-06-14 11:42:40,665] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:45,185] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:48,272] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:50,788] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:53,760] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:53,775] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:57,563] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:42:57,579] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:00,951] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:00,982] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:07,769] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:07,788] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:11,007] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:11,010] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 785: DressCode

[taxii2client.v20] [WARNING ] [2024-06-14 11:43:15,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:18,696] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:23,399] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:28,273] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:32,226] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:32,241] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:35,661] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:35,677] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:38,646] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:38,663] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:41,263] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:41,268] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:44,334] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:44,334] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 786: Dendroid

[taxii2client.v20] [WARNING ] [2024-06-14 11:43:48,905] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:50,590] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:52,091] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:52,942] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:56,076] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:56,244] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:59,180] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:43:59,199] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:03,283] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:03,305] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:06,482] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:06,486] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:11,070] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:11,073] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 787: WireLurker

[taxii2client.v20] [WARNING ] [2024-06-14 11:44:15,127] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:16,944] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:18,446] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:21,099] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:24,869] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:24,885] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:28,256] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:28,270] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:31,574] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:31,590] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:34,211] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:34,225] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:37,412] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:37,412] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 788: NotCompatible

[taxii2client.v20] [WARNING ] [2024-06-14 11:44:41,466] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:44,866] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:47,673] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:51,373] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:55,212] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:55,226] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:58,546] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:44:58,563] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:04,383] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:04,401] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:07,903] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:07,903] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:10,906] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:10,906] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 789: INCONTROLLER

[taxii2client.v20] [WARNING ] [2024-06-14 11:45:14,826] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:16,760] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:18,645] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:20,515] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:24,904] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:24,919] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:29,319] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:29,340] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:34,725] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:34,758] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:37,962] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:37,978] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:42,166] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:42,166] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 790: VPNFilter

[taxii2client.v20] [WARNING ] [2024-06-14 11:45:51,289] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:56,794] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:45:59,813] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:01,731] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:04,936] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:04,965] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:10,103] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:10,125] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:13,373] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:13,391] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:16,115] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:16,118] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:19,296] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:19,296] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 791: Triton

[taxii2client.v20] [WARNING ] [2024-06-14 11:46:36,058] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:40,397] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:46,702] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:50,507] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:56,521] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:46:56,527] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:04,920] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:04,933] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:14,624] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:14,660] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:17,515] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:17,520] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:20,464] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:20,464] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 792: PLC-Blaster

[taxii2client.v20] [WARNING ] [2024-06-14 11:47:28,119] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:30,541] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:32,793] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:35,313] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:38,609] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:38,630] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:42,348] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:42,364] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:47,118] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:47,135] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:50,155] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:50,173] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:52,957] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-14 11:47:52,972] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 793: ACAD/Medre.A

**[MITRE] Guardado Software - Técnicas N:N**

In [147]:
# Filtramos la información que necesitamos
mitre_n2n_techniques_software_df = results_df[['technique_id', 'technique', 'url_technique','software_id','software','software_description','software_type','url_software']]

if save_to_file:
    save_df_as_csv(mitre_n2n_techniques_software_df, '[MITRE]_n2n_techniques_software', 'inter_software_techniques')

Fichero generado correctamente [MITRE]n2n_techniques_software14062024_1340h.csv

**[CP] Relación Software - Técnicas N:N**

In [149]:
cp_ttp_available = cp_ttps()
cp_n2n_techniques_software_df = mitre_n2n_techniques_software_df[mitre_n2n_techniques_software_df['technique_id'].isin(cp_ttp_available)]
cp_n2n_techniques_software_df.shape

(8555, 8)

In [150]:
if save_to_file:
    save_df_as_csv(cp_n2n_techniques_software_df, '[CP]_n2n_techniques_software', 'inter_software_techniques')

Fichero generado correctamente [CP]n2n_techniques_software14062024_1348h.csv

**[NOCP] Relación Grupos - Técnicas N:N**

In [151]:
nocp_n2n_techniques_software_df = mitre_n2n_techniques_software_df[~mitre_n2n_techniques_software_df['technique_id'].isin(cp_ttp_available)]
nocp_n2n_techniques_software_df.shape

(522, 8)

In [152]:
if save_to_file:
    save_df_as_csv(nocp_n2n_techniques_software_df, '[NOCP]_n2n_techniques_software', 'inter_software_techniques')

Fichero generado correctamente [NOCP]n2n_techniques_software14062024_1348h.csv

#### **4.2 Técnica - Software (1:N)**

**[MITRE] Técnica - Software (1:N)**

In [156]:
# Agregamos las columnas por la columna techniques_id
mitre_technique_with_software_df = mitre_n2n_techniques_software_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_technique_with_software_df, '[MITRE]_technique_with_software', 'technique_software_1N')

mitre_technique_with_software_df.head(2)

Fichero generado correctamente [MITRE]_technique_with_software14062024_1352h.csv

,technique_id,technique,url_technique,software_id,software,software_description,software_type,url_software
0,T0800,[Activate Firmware Update Mode],[https://attack.mitre.org/techniques/T0800],[S0604],[Industroyer],[[Industroyer](https://attack.mitre.org/softwa...,[malware],[https://attack.mitre.org/software/S0604]
1,T0801,[Monitor Process State],[https://attack.mitre.org/techniques/T0801],"[S0604, S0603, S1072]","[Industroyer, Industroyer2, Stuxnet]",[[Stuxnet](https://attack.mitre.org/software/S...,[malware],"[https://attack.mitre.org/software/S0604, http..."

In [158]:
print(f"[MITRE] Filas del df: {mitre_technique_with_software_df.shape[0]}. Técnicas únicas: {mitre_technique_with_software_df['technique_id'].nunique()}.")

[MITRE] Filas del df: 489. Técnicas únicas: 489.

**[CP] Técnica - Software (1:N)**

In [159]:
# Agregamos las columnas por la columna techniques_id
cp_technique_with_software_df = cp_n2n_techniques_software_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(cp_technique_with_software_df, '[CP]_technique_with_software', 'technique_software_1N')

cp_technique_with_software_df.head(2)

Fichero generado correctamente [CP]_technique_with_software14062024_1356h.csv

,technique_id,technique,url_technique,software_id,software,software_description,software_type,url_software
0,T0802,[Automated Collection],[https://attack.mitre.org/techniques/T0802],"[S0604, S1072, S0093]","[Backdoor.Oldrea, Industroyer, Industroyer2]",[[Backdoor.Oldrea](https://attack.mitre.org/so...,[malware],"[https://attack.mitre.org/software/S0604, http..."
1,T0807,[Command-Line Interface],[https://attack.mitre.org/techniques/T0807],"[S0604, S0603]","[Industroyer, Stuxnet]",[[Industroyer](https://attack.mitre.org/softwa...,[malware],"[https://attack.mitre.org/software/S0604, http..."

In [160]:
print(f"[CP] Filas del df: {cp_technique_with_software_df.shape[0]}. TTP's únicas: {cp_technique_with_software_df['technique_id'].nunique()}.")

[CP] Filas del df: 412. TTP's únicas: 412.

**[NOCP] Técnica - Software (1:N)**

In [163]:
# Agregamos las columnas por la columna techniques_id
nocp_technique_with_software_df = nocp_n2n_techniques_software_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_technique_with_software_df, '[NOCP]_technique_with_software', 'technique_software_1N')

nocp_technique_with_software_df.head(2)

Fichero generado correctamente [NOCP]_technique_with_software14062024_1358h.csv

,technique_id,technique,url_technique,software_id,software,software_description,software_type,url_software
0,T0800,[Activate Firmware Update Mode],[https://attack.mitre.org/techniques/T0800],[S0604],[Industroyer],[[Industroyer](https://attack.mitre.org/softwa...,[malware],[https://attack.mitre.org/software/S0604]
1,T0801,[Monitor Process State],[https://attack.mitre.org/techniques/T0801],"[S0604, S0603, S1072]","[Industroyer, Industroyer2, Stuxnet]",[[Stuxnet](https://attack.mitre.org/software/S...,[malware],"[https://attack.mitre.org/software/S0604, http..."

In [162]:
print(f"[NOCP] Filas del df: {nocp_technique_with_software_df.shape[0]}. TTP's únicas: {nocp_technique_with_software_df['technique_id'].nunique()}.")

[NOCP] Filas del df: 77. TTP's únicas: 77.

#### **4.3 Software - Técnicas (1:N)**

**[MITRE] Software - Técnicas (1:N)**

In [165]:
mitre_software_with_techniques_df = mitre_n2n_techniques_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list,
    'technique_id':unique_list,
    'technique': unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(mitre_software_with_techniques_df, '[MITRE]_software_with_techniques', 'software_techniques_1N')

mitre_software_with_techniques_df.head(2)

Fichero generado correctamente [MITRE]_software_with_techniques14062024_1402h.csv

,software_id,software,software_description,software_type,url_software,technique_id,technique,url_technique
0,S0001,[Trojan.Mebromi],[[Trojan.Mebromi](https://attack.mitre.org/sof...,[malware],[https://attack.mitre.org/software/S0001],[T1542.001],[System Firmware],[https://attack.mitre.org/techniques/T1542/001]
1,S0002,[Mimikatz],[[Mimikatz](https://attack.mitre.org/software/...,[tool],[https://attack.mitre.org/software/S0002],"[T1649, T1003.006, T1558.001, T1003.002, T1552...","[Security Account Manager, Pass the Hash, SID-...",[https://attack.mitre.org/techniques/T1134/005...

In [166]:
print(f"[MITRE] Filas del df: {mitre_software_with_techniques_df.shape[0]}. Software únicos: {mitre_software_with_techniques_df['software_id'].nunique()}.")

[MITRE] Filas del df: 677. Software únicos: 677.

**[CP] Software - Técnicas (1:N)**

In [167]:
cp_software_with_techniques_df = cp_n2n_techniques_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list,
    'technique_id':unique_list,
    'technique': unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(cp_software_with_techniques_df, '[CP]_software_with_techniques', 'software_techniques_1N')

cp_software_with_techniques_df.head(2)

Fichero generado correctamente [CP]_software_with_techniques14062024_1403h.csv

,software_id,software,software_description,software_type,url_software,technique_id,technique,url_technique
0,S0001,[Trojan.Mebromi],[[Trojan.Mebromi](https://attack.mitre.org/sof...,[malware],[https://attack.mitre.org/software/S0001],[T1542.001],[System Firmware],[https://attack.mitre.org/techniques/T1542/001]
1,S0002,[Mimikatz],[[Mimikatz](https://attack.mitre.org/software/...,[tool],[https://attack.mitre.org/software/S0002],"[T1649, T1003.006, T1558.001, T1003.002, T1552...","[Security Account Manager, Pass the Hash, SID-...",[https://attack.mitre.org/techniques/T1134/005...

In [169]:
print(f"[CP] Filas del df: {cp_software_with_techniques_df.shape[0]}. Software únicos: {cp_software_with_techniques_df['software_id'].nunique()}.")

[CP] Filas del df: 674. Software únicos: 674.

**[NOCP] Software - Técnicas (1:N)**

In [170]:
nocp_software_with_techniques_df = nocp_n2n_techniques_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list,
    'technique_id':unique_list,
    'technique': unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(nocp_software_with_techniques_df, '[NOCP]_software_with_techniques', 'software_techniques_1N')

nocp_software_with_techniques_df.head(2)

Fichero generado correctamente [NOCP]_software_with_techniques_14062024_1405h.csv

,software_id,software,software_description,software_type,url_software,technique_id,technique,url_technique
0,S0003,[RIPTIDE],[[RIPTIDE](https://attack.mitre.org/software/S...,[malware],[https://attack.mitre.org/software/S0003],[T1573.001],[Symmetric Cryptography],[https://attack.mitre.org/techniques/T1573/001]
1,S0009,[Hikit],[[Hikit](https://attack.mitre.org/software/S00...,[malware],[https://attack.mitre.org/software/S0009],[T1573.001],[Symmetric Cryptography],[https://attack.mitre.org/techniques/T1573/001]

In [171]:
print(f"[NOCP] Filas del df: {nocp_software_with_techniques_df.shape[0]}. Software únicos: {nocp_software_with_techniques_df['software_id'].nunique()}.")

[NOCP] Filas del df: 323. Software únicos: 323.

### **5. GRUPOS - SOFTWARE**

#### **5.1 Tablas intermedias (N:N)**

In [56]:
# Creamos un dataframe vacío con los campos a rellenar
results_df = pd.DataFrame(columns=['type', 'id', 'url', 'matrix', 'created', 'modified', 'created_by_ref',
       'modified_by_ref', 'external_references', 'object_marking_refs',
       'mitre_version', 'mitre_attack_spec_version', 'mitre_deprecated',
       'software', 'software_id', 'software_description', 'software_labels',
       'software_aliases', 'software_platform', 'old_software_id',
       'contributors', 'group_id', 'group', 'group_description',
       'group_aliases', 'url_group'])

In [65]:
# En este bucle vamos a ir recorriendo cada uno de los grupo y retornando todas los sotfware utilizados por estos. Iremos uniendo toda la información en el df anteriormente creado vacío.
for row in range(row, len(get_groups_df)):
    temp_software_by_group = lift.get_software_used_by_group(get_groups_df.iloc[row], stix_format=False)
    temp_software_by_group_df = pd.json_normalize(temp_software_by_group)

    temp_software_by_group_df['group_id'] = get_groups_df.iloc[row].group_id
    temp_software_by_group_df['group'] = get_groups_df.iloc[row].group
    temp_software_by_group_df['group_description'] = get_groups_df.iloc[row].group_description

    aliases = get_groups_df.iloc[row].group_aliases
    temp_software_by_group_df['group_aliases'] = [aliases] * len(temp_software_by_group_df)

    domains = get_groups_df.iloc[row].matrix
    temp_software_by_group_df['matrix'] = [domains] * len(temp_software_by_group_df)

    temp_software_by_group_df['url_group'] = get_groups_df.iloc[row].url
    temp_software_by_group_df['type'] = get_groups_df.iloc[row].type

    results_df = pd.concat([results_df, temp_software_by_group_df])

    print(f"Finalizado {row}: {get_groups_df.iloc[row].group}")

# Eliminamos duplicados, no debería darse ninguno pero en caso de ejecutar por lotes (cuando se pierde la conexión) es posible que por error humano dupliquemos alguna fila
results_df = results_df.drop_duplicates(subset=['group_id', 'software_id'], keep='last')
# Renombramos la columna url
results_df = results_df.rename(columns={'url': 'url_software'})

[taxii2client.v20] [WARNING ] [2024-06-17 10:31:15,596] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:21,134] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:27,973] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:33,628] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:40,517] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:40,533] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:46,021] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:46,038] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:50,538] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:31:50,539] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 61: PLATINUM

[taxii2client.v20] [WARNING ] [2024-06-17 10:32:08,704] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:10,958] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:17,429] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:21,600] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:24,453] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:24,469] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:27,839] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:27,858] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:30,057] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:30,057] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:39,032] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:39,032] TAXII Server Response with different amount of objects! Setting per_request=5

Finalizado 62: MuddyWater

[taxii2client.v20] [WARNING ] [2024-06-17 10:32:47,135] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:50,105] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:53,694] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:56,044] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:59,848] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:32:59,872] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:03,539] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:03,555] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:06,073] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:06,073] TAXII Server Response with different amount of objects! Setting per_request=3
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:09,058] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:09,058] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 63: Dark Caracal

[taxii2client.v20] [WARNING ] [2024-06-17 10:33:19,915] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:26,454] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:29,374] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:34,579] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:38,034] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:38,047] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:43,901] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:43,902] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:46,020] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:46,020] TAXII Server Response with different amount of objects! Setting per_request=8

Finalizado 64: Orangeworm

[taxii2client.v20] [WARNING ] [2024-06-17 10:33:57,007] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:33:58,530] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:00,132] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:01,298] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:05,352] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:05,372] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:09,055] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:09,072] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:12,191] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:12,191] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 65: APT19

[taxii2client.v20] [WARNING ] [2024-06-17 10:34:20,613] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:22,166] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:24,785] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:26,637] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:29,523] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:29,539] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:33,042] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:33,058] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:35,260] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:34:35,260] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 66: Rancor

[taxii2client.v20] [WARNING ] [2024-06-17 10:34:51,407] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:00,715] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:03,820] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:06,102] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:10,656] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:10,685] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:19,712] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:19,717] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:24,785] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:24,785] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 67: Thrip

[taxii2client.v20] [WARNING ] [2024-06-17 10:35:45,701] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:35:53,291] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:06,252] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:16,527] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:23,032] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:23,052] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:31,039] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:31,059] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:35,692] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:35,693] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 68: Leafminer

[taxii2client.v20] [WARNING ] [2024-06-17 10:36:48,887] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:36:54,659] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:37:01,395] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:37:16,559] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:37:24,766] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:37:24,783] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:37:35,130] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:37:35,141] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:37:44,766] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:37:44,766] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 69: Gorgon Group

[taxii2client.v20] [WARNING ] [2024-06-17 10:38:03,781] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:09,169] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:15,486] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:17,126] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:21,863] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:21,881] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:25,566] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:25,566] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:27,751] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:27,751] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 70: DarkHydrus

[taxii2client.v20] [WARNING ] [2024-06-17 10:38:39,878] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:42,197] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:50,470] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:53,956] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:58,894] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:38:58,910] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:07,467] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:07,484] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:12,221] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:12,221] TAXII Server Response with different amount of objects! Setting per_request=6

Finalizado 71: Cobalt Group

[taxii2client.v20] [WARNING ] [2024-06-17 10:39:27,801] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:30,520] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:45,432] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:52,588] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:58,223] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:39:58,243] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:05,532] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:05,667] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:09,154] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:09,155] TAXII Server Response with different amount of objects! Setting per_request=6

Finalizado 72: Tropic Trooper

[taxii2client.v20] [WARNING ] [2024-06-17 10:40:24,331] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:34,376] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:37,778] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:47,416] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:59,710] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:40:59,731] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:07,286] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:07,286] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:10,669] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:10,670] TAXII Server Response with different amount of objects! Setting per_request=6
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:16,657] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:16,657] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 73: APT38

[taxii2client.v20] [WARNING ] [2024-06-17 10:41:21,978] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:24,497] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:27,783] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:30,085] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:34,171] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:34,188] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:37,845] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:37,858] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:41,044] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:41:41,044] TAXII Server Response with different amount of objects! Setting per_request=5

Finalizado 74: SilverTerrier

[taxii2client.v20] [WARNING ] [2024-06-17 10:42:04,329] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:42:16,282] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:42:20,659] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:42:23,179] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:42:27,165] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:42:27,182] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:42:31,985] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:42:32,002] TAXII Server Response with different amount of objects! Setting per_request=1350

Finalizado 75: Gallmaker

[taxii2client.v20] [WARNING ] [2024-06-17 10:42:43,061] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:42:50,138] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:03,111] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:09,683] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:14,237] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:14,253] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:18,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:18,490] TAXII Server Response with different amount of objects! Setting per_request=1350

Finalizado 76: FIN4

[taxii2client.v20] [WARNING ] [2024-06-17 10:43:24,312] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:27,664] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:31,701] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:34,270] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:38,457] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:38,483] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:42,527] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:42,543] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:44,812] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:44,813] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:56,755] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:43:56,755] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 77: APT39

[taxii2client.v20] [WARNING ] [2024-06-17 10:44:05,562] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:07,280] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:08,602] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:10,238] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:13,486] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:13,502] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:17,127] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:17,142] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:20,787] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:20,787] TAXII Server Response with different amount of objects! Setting per_request=2
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:27,097] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:27,097] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 78: TEMP.Veles

[taxii2client.v20] [WARNING ] [2024-06-17 10:44:35,087] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:40,528] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:42,309] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:46,096] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:49,914] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:49,915] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:53,368] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:53,388] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:55,504] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:44:55,505] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 79: The White Company

[taxii2client.v20] [WARNING ] [2024-06-17 10:45:05,913] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:07,997] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:10,086] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:13,468] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:16,504] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:16,524] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:19,509] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:19,509] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:21,844] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:21,844] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 80: WIRTE

[taxii2client.v20] [WARNING ] [2024-06-17 10:45:30,399] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:32,501] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:34,805] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:43,076] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:47,817] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:47,830] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:56,453] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:56,453] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:58,672] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:45:58,672] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 81: Silence

[taxii2client.v20] [WARNING ] [2024-06-17 10:46:11,469] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:14,184] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:17,838] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:20,682] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:26,648] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:26,662] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:31,735] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:31,747] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:37,003] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:37,003] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:44,260] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:46:44,260] TAXII Server Response with different amount of objects! Setting per_request=6

Finalizado 82: TA505

[taxii2client.v20] [WARNING ] [2024-06-17 10:47:05,927] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:16,489] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:28,429] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:31,949] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:36,102] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:36,122] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:39,656] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:39,671] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:42,074] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:42,074] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:50,848] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:47:50,848] TAXII Server Response with different amount of objects! Setting per_request=6

Finalizado 83: GALLIUM

[taxii2client.v20] [WARNING ] [2024-06-17 10:48:06,944] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:18,047] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:31,326] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:37,920] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:44,058] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:44,075] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:49,229] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:49,246] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:51,898] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:48:51,898] TAXII Server Response with different amount of objects! Setting per_request=10

Finalizado 84: Kimsuky

[taxii2client.v20] [WARNING ] [2024-06-17 10:49:00,971] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:04,159] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:08,201] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:13,966] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:16,903] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:16,918] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:19,988] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:20,004] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:22,425] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:22,425] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 85: Machete

[taxii2client.v20] [WARNING ] [2024-06-17 10:49:30,946] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:32,681] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:34,599] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:35,483] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:38,619] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:38,647] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:41,439] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:41,462] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:43,893] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:43,893] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:51,197] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:51,197] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:58,422] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:49:58,422] TAXII Server Response with different amount of objects! Setting per_request=7

Finalizado 86: APT41

[taxii2client.v20] [WARNING ] [2024-06-17 10:50:07,943] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:10,629] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:12,781] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:14,485] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:17,283] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:17,299] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:20,568] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:20,571] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:24,675] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:24,675] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 87: Bouncing Golf

[taxii2client.v20] [WARNING ] [2024-06-17 10:50:31,996] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:33,448] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:35,785] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:36,853] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:43,476] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:43,489] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:49,504] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:49,514] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:51,747] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:50:51,747] TAXII Server Response with different amount of objects! Setting per_request=6

Finalizado 88: BlackTech

[taxii2client.v20] [WARNING ] [2024-06-17 10:51:07,459] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:14,964] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:17,817] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:23,339] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:28,707] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:28,710] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:32,630] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:32,646] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:35,668] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:35,668] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 89: APT-C-36

[taxii2client.v20] [WARNING ] [2024-06-17 10:51:46,608] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:51:52,363] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:04,890] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:11,929] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:15,649] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:15,666] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:18,463] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:18,471] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:20,770] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:20,770] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 90: Inception

[taxii2client.v20] [WARNING ] [2024-06-17 10:52:31,845] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:33,363] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:35,031] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:36,701] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:40,069] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:40,088] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:43,555] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:43,565] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:45,774] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:45,774] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:52,812] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:52,812] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:57,653] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:52:57,653] TAXII Server Response with different amount of objects! Setting per_request=1
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:02,507] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:02,507] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 91: Wizard Spider

[taxii2client.v20] [WARNING ] [2024-06-17 10:53:11,178] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:12,879] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:14,521] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:16,766] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:19,705] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:19,720] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:22,821] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:22,821] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:24,956] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:24,956] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 92: Mofang

[taxii2client.v20] [WARNING ] [2024-06-17 10:53:35,525] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:38,233] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:41,903] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:43,057] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:46,607] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:46,623] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:49,509] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:49,509] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:53,229] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:53:53,229] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 93: DarkVishnya

[taxii2client.v20] [WARNING ] [2024-06-17 10:54:03,662] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:06,623] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:13,395] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:14,682] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:19,619] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:19,635] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:22,451] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:22,473] TAXII Server Response with different amount of objects! Setting per_request=1350

Finalizado 94: Rocke

[taxii2client.v20] [WARNING ] [2024-06-17 10:54:26,680] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:29,325] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:31,777] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:33,578] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:37,025] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:37,031] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:39,868] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:39,868] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:42,886] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:42,886] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 95: Whitefly

[taxii2client.v20] [WARNING ] [2024-06-17 10:54:50,961] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:52,297] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:53,845] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:54,731] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:58,203] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:54:58,218] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:01,263] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:01,272] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:03,437] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:03,437] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 96: Blue Mockingbird

[taxii2client.v20] [WARNING ] [2024-06-17 10:55:15,797] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:17,148] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:20,000] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:24,636] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:29,191] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:29,208] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:32,680] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:32,680] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:36,819] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:36,820] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 97: Windshift

[taxii2client.v20] [WARNING ] [2024-06-17 10:55:45,938] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:53,609] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:55:58,218] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:05,121] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:12,318] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:12,328] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:15,347] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:15,347] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:17,466] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:17,466] TAXII Server Response with different amount of objects! Setting per_request=6

Finalizado 98: Chimera

[taxii2client.v20] [WARNING ] [2024-06-17 10:56:31,829] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:33,333] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:44,123] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:48,744] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:52,231] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:52,248] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:55,150] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:55,170] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:57,806] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:56:57,806] TAXII Server Response with different amount of objects! Setting per_request=2
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:04,009] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:04,009] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 99: GOLD SOUTHFIELD

[taxii2client.v20] [WARNING ] [2024-06-17 10:57:10,647] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:17,187] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:21,908] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:24,229] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:30,632] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:30,636] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:34,270] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:34,270] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:36,458] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:36,458] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 100: Fox Kitten

[taxii2client.v20] [WARNING ] [2024-06-17 10:57:44,979] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:46,631] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:48,669] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:50,118] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:53,271] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:53,287] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:56,132] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:56,140] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:59,009] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:57:59,009] TAXII Server Response with different amount of objects! Setting per_request=8

Finalizado 101: Indrik Spider

[taxii2client.v20] [WARNING ] [2024-06-17 10:58:07,836] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:09,802] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:11,987] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:14,173] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:17,276] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:17,292] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:20,478] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:20,482] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:22,593] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:22,593] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 102: Evilnum

[taxii2client.v20] [WARNING ] [2024-06-17 10:58:31,222] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:32,523] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:33,891] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:35,392] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:38,645] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:38,662] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:41,581] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:41,598] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:43,781] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:43,781] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 103: Sidewinder

[taxii2client.v20] [WARNING ] [2024-06-17 10:58:52,488] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:54,361] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:55,908] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:58:57,061] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:00,201] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:00,216] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:03,069] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:03,085] TAXII Server Response with different amount of objects! Setting per_request=1350

Finalizado 104: Silent Librarian

[taxii2client.v20] [WARNING ] [2024-06-17 10:59:07,722] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:10,158] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:12,777] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:14,395] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:17,618] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:17,641] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:20,834] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:20,851] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:23,507] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:23,507] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 105: Volatile Cedar

[taxii2client.v20] [WARNING ] [2024-06-17 10:59:31,561] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:33,779] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:36,248] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:37,483] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:41,670] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:41,689] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:45,857] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:45,874] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:48,860] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:48,860] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 106: Windigo

[taxii2client.v20] [WARNING ] [2024-06-17 10:59:57,751] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 10:59:59,370] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:00:02,706] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:00:06,228] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:00:13,082] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:00:13,099] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:00:20,075] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:00:20,089] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:00:26,590] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:00:26,591] TAXII Server Response with different amount of objects! Setting per_request=5

Finalizado 107: HAFNIUM

[taxii2client.v20] [WARNING ] [2024-06-17 11:01:09,450] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:01:33,202] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:02:05,801] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:02:22,544] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:02:36,733] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:02:36,750] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:02:46,896] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:02:46,914] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:02:52,702] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:02:52,702] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 108: Higaisa

[taxii2client.v20] [WARNING ] [2024-06-17 11:03:19,031] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:03:51,499] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:04:01,776] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:04:06,890] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:04:19,009] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:04:19,023] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:04:29,262] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:04:29,273] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:04:35,766] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:04:35,767] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 109: TA551

[taxii2client.v20] [WARNING ] [2024-06-17 11:04:51,305] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:04,022] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:16,951] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:19,252] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:25,975] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:25,990] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:40,484] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:40,498] TAXII Server Response with different amount of objects! Setting per_request=1350

Finalizado 110: ZIRCONIUM

[taxii2client.v20] [WARNING ] [2024-06-17 11:05:47,619] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:52,614] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:05:57,532] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:06:03,469] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:06:15,412] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:06:15,428] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:06:22,801] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:06:22,813] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:06:27,115] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:06:27,116] TAXII Server Response with different amount of objects! Setting per_request=5

Finalizado 111: Mustang Panda

[taxii2client.v20] [WARNING ] [2024-06-17 11:06:38,045] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:06:47,538] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:11,154] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:19,447] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:27,352] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:27,368] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:33,071] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:33,082] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:37,447] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:37,448] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 112: Ajax Security Team

[taxii2client.v20] [WARNING ] [2024-06-17 11:07:51,302] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:07:53,177] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:02,890] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:12,457] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:21,057] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:21,072] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:30,671] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:30,682] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:37,728] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:37,729] TAXII Server Response with different amount of objects! Setting per_request=6

Finalizado 113: Tonto Team

[taxii2client.v20] [WARNING ] [2024-06-17 11:08:47,252] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:51,218] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:08:55,145] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:01,580] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:08,549] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:08,565] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:14,918] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:14,930] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:18,717] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:18,717] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 114: Nomadic Octopus

[taxii2client.v20] [WARNING ] [2024-06-17 11:09:31,398] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:35,414] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:37,878] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:41,505] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:48,391] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:48,407] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:52,524] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:52,534] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:55,287] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:09:55,288] TAXII Server Response with different amount of objects! Setting per_request=5

Finalizado 115: Transparent Tribe

[taxii2client.v20] [WARNING ] [2024-06-17 11:10:19,684] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:10:29,497] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:10:37,880] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:10:43,236] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:10:53,826] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:10:53,842] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:11:00,437] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:11:00,448] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:11:06,734] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:11:06,735] TAXII Server Response with different amount of objects! Setting per_request=5

Finalizado 116: BackdoorDiplomacy

[taxii2client.v20] [WARNING ] [2024-06-17 11:11:26,387] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:11:36,203] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:11:49,330] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:01,710] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:07,183] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:07,200] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:11,935] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:11,950] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:18,785] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:18,785] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 117: IndigoZebra

[taxii2client.v20] [WARNING ] [2024-06-17 11:12:33,476] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:42,564] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:51,629] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:12:55,189] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:02,889] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:02,904] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:08,697] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:08,709] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:11,483] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:11,484] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 118: Ferocious Kitten

[taxii2client.v20] [WARNING ] [2024-06-17 11:13:26,579] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:29,984] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:41,170] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:13:52,529] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:06,125] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:06,271] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:13,718] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:13,729] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:19,217] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:19,218] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 119: Andariel

[taxii2client.v20] [WARNING ] [2024-06-17 11:14:38,006] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:42,785] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:53,663] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:14:58,498] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:15:10,466] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:15:10,481] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:15:16,741] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:15:16,752] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:15:19,770] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:15:19,771] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 120: TeamTNT

[taxii2client.v20] [WARNING ] [2024-06-17 11:15:31,879] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:15:43,442] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:15:48,186] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:16:02,707] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:16:13,463] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:16:13,479] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:16:28,903] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:16:28,915] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:16:34,703] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:16:34,703] TAXII Server Response with different amount of objects! Setting per_request=7

Finalizado 121: LazyScripter

[taxii2client.v20] [WARNING ] [2024-06-17 11:16:55,503] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:03,248] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:22,614] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:29,973] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:35,758] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:35,772] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:42,542] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:42,553] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:48,114] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:48,116] TAXII Server Response with different amount of objects! Setting per_request=1
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:51,925] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:17:51,925] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 122: Confucius

[taxii2client.v20] [WARNING ] [2024-06-17 11:18:04,061] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:11,846] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:16,669] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:19,563] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:23,375] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:23,392] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:31,176] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:31,190] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:33,594] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:33,596] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 123: Aquatic Panda

[taxii2client.v20] [WARNING ] [2024-06-17 11:18:51,539] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:18:59,891] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:19:18,867] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:19:29,548] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:19:43,230] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:19:43,245] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:19:49,258] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:19:49,271] TAXII Server Response with different amount of objects! Setting per_request=1350

Finalizado 124: ALLANITE

[taxii2client.v20] [WARNING ] [2024-06-17 11:20:00,987] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:20:12,208] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:20:22,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:20:31,706] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:20:42,375] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:20:42,409] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:20:55,202] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:20:55,216] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:21:03,888] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:21:03,889] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 11:21:18,111] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:21:18,111] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 125: HEXANE

[taxii2client.v20] [WARNING ] [2024-06-17 11:21:38,031] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:21:56,862] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:07,775] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:11,852] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:21,642] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:21,657] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:26,975] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:26,988] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:29,662] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:29,663] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 126: BITTER

[taxii2client.v20] [WARNING ] [2024-06-17 11:22:41,997] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:45,614] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:22:56,510] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:23:08,125] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:23:18,998] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:23:19,014] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:23:25,295] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:23:25,306] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:23:30,884] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:23:30,885] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 127: Ember Bear

[taxii2client.v20] [WARNING ] [2024-06-17 11:23:46,722] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:23:51,949] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:02,453] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:05,284] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:08,920] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:08,935] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:12,532] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:12,543] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:14,700] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:14,700] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 128: LAPSUS$

[taxii2client.v20] [WARNING ] [2024-06-17 11:24:23,451] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:27,906] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:29,636] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:32,205] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:36,739] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:36,755] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:42,525] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:42,537] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:46,039] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:24:46,040] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 129: POLONIUM

[taxii2client.v20] [WARNING ] [2024-06-17 11:24:57,689] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:06,197] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:16,810] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:19,168] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:23,435] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:23,452] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:27,785] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:27,796] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:30,263] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:30,264] TAXII Server Response with different amount of objects! Setting per_request=9

Finalizado 130: Earth Lusca

[taxii2client.v20] [WARNING ] [2024-06-17 11:25:52,633] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:25:58,934] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:26:24,211] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:26:37,691] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:26:47,958] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:26:47,973] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:26:53,683] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:26:53,694] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:26:56,289] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:26:56,290] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 131: Aoqin Dragon

[taxii2client.v20] [WARNING ] [2024-06-17 11:27:06,518] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:13,859] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:19,029] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:24,570] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:32,874] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:32,889] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:38,649] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:38,661] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:41,668] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:27:41,669] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 132: SideCopy

[taxii2client.v20] [WARNING ] [2024-06-17 11:27:57,566] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:03,509] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:06,253] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:12,983] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:16,017] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:16,032] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:18,956] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:18,968] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:21,218] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:21,219] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 133: Moses Staff

[taxii2client.v20] [WARNING ] [2024-06-17 11:28:34,856] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:38,017] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:45,382] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:50,655] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:56,307] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:56,323] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:59,784] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:28:59,794] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:03,631] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:03,632] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 134: EXOTIC LILY

[taxii2client.v20] [WARNING ] [2024-06-17 11:29:16,659] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:23,179] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:28,699] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:32,325] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:38,738] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:38,752] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:44,755] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:44,768] TAXII Server Response with different amount of objects! Setting per_request=1350

Finalizado 135: CURIUM

[taxii2client.v20] [WARNING ] [2024-06-17 11:29:50,142] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:52,152] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:55,246] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:29:56,258] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:03,950] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:03,964] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:07,520] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:07,531] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:09,987] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:09,988] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 136: Metador

[taxii2client.v20] [WARNING ] [2024-06-17 11:30:25,833] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:30,297] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:42,247] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:30:56,301] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:31:05,745] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:31:05,762] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:31:19,038] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:31:19,163] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:31:23,276] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:31:23,276] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 137: LuminousMoth

[taxii2client.v20] [WARNING ] [2024-06-17 11:31:46,286] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:31:52,333] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:31:57,341] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:32:04,974] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:32:11,869] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:32:11,885] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:32:19,011] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:32:19,022] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:32:23,972] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:32:23,973] TAXII Server Response with different amount of objects! Setting per_request=5

Finalizado 138: Scattered Spider

[taxii2client.v20] [WARNING ] [2024-06-17 11:32:44,817] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:32:59,240] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:11,045] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:18,995] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:27,770] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:27,786] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:33,044] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:33,055] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:36,373] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:36,374] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 139: FIN13

[taxii2client.v20] [WARNING ] [2024-06-17 11:33:46,839] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:33:53,867] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:02,014] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:13,662] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:19,238] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:19,254] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:23,859] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:23,870] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:26,260] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:26,260] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:33,715] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:33,715] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 140: Volt Typhoon

[taxii2client.v20] [WARNING ] [2024-06-17 11:34:46,805] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:48,583] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:50,263] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:34:52,160] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:00,002] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:00,020] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:03,174] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:03,185] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:05,411] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:05,412] TAXII Server Response with different amount of objects! Setting per_request=9

Finalizado 141: TA2541

[taxii2client.v20] [WARNING ] [2024-06-17 11:35:15,676] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:21,139] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:25,854] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:33,206] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:42,113] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:42,128] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:50,104] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:50,115] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:54,724] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:35:54,725] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 142: MoustachedBouncer

[taxii2client.v20] [WARNING ] [2024-06-17 11:36:23,040] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:36:37,062] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:36:41,079] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:36:48,151] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:36:59,117] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:36:59,133] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:04,374] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:04,385] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:07,842] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:07,843] TAXII Server Response with different amount of objects! Setting per_request=2

Finalizado 143: Mustard Tempest

[taxii2client.v20] [WARNING ] [2024-06-17 11:37:17,150] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:20,447] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:35,604] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:46,166] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:56,388] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:37:56,402] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:03,232] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:03,243] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:08,373] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:08,374] TAXII Server Response with different amount of objects! Setting per_request=8

Finalizado 144: Cinnamon Tempest

[taxii2client.v20] [WARNING ] [2024-06-17 11:38:25,446] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:29,182] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:33,205] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:38,949] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:45,958] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:45,974] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:50,899] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:50,900] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:53,932] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:38:53,932] TAXII Server Response with different amount of objects! Setting per_request=9

Finalizado 145: ToddyCat

[taxii2client.v20] [WARNING ] [2024-06-17 11:39:05,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:07,571] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:10,528] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:13,551] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:16,720] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:16,736] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:21,862] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:21,873] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:27,769] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:27,770] TAXII Server Response with different amount of objects! Setting per_request=10
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:33,912] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:33,913] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 146: APT5

[taxii2client.v20] [WARNING ] [2024-06-17 11:39:45,124] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:47,358] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:52,937] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:39:56,811] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:00,182] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:00,197] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:03,591] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:03,603] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:06,356] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:06,357] TAXII Server Response with different amount of objects! Setting per_request=6

Finalizado 147: Akira

[taxii2client.v20] [WARNING ] [2024-06-17 11:40:15,050] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:16,800] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:19,427] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:20,397] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:25,645] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:25,661] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:28,804] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:28,815] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:30,961] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:30,962] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 148: Malteiro

[taxii2client.v20] [WARNING ] [2024-06-17 11:40:51,762] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:40:55,796] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:01,976] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:06,495] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:10,645] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:10,661] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:13,619] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:13,630] TAXII Server Response with different amount of objects! Setting per_request=1350

Finalizado 149: CyberAv3ngers

[taxii2client.v20] [WARNING ] [2024-06-17 11:41:17,775] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:21,326] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:29,490] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:36,677] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:46,102] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:46,116] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:54,561] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:54,571] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:57,691] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:41:57,693] TAXII Server Response with different amount of objects! Setting per_request=1
[taxii2client.v20] [WARNING ] [2024-06-17 11:42:02,101] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:42:02,102] TAXII Server Response with different amount of objects! Setting per_request=3

Finalizado 150: APT-C-23

[taxii2client.v20] [WARNING ] [2024-06-17 11:42:10,550] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:42:22,772] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:42:35,639] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:42:48,373] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:42:58,292] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:42:58,311] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-06-17 11:43:05,726] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:43:05,738] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-06-17 11:43:12,030] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-06-17 11:43:12,031] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 151: UNC788

**[MITRE] Guardado Grupos - Software N:N**

Nota: En este caso no disponemos de un filtro que aplique sobre ninguno de las dos categorías directamente por lo que solo generaremos outputs MITRE.

In [147]:
n2n_groups_software_df = results_df[['group_id', 'group', 'group_aliases', 'url_group', 'software_id', 'software', 'software_aliases', 'url_software']]
print(f"[MITRE] Filas del df: {n2n_groups_software_df.shape[0]}. Software únicos: {n2n_groups_software_df['software_id'].nunique()}. Grupos únicos: {n2n_groups_software_df['group_id'].nunique()}.")

[MITRE] Filas del df: 932. Software únicos: 509. Grupos únicos: 138.

In [148]:
# Guardamos la relación entre grupos y software completa:
if save_to_file:
    save_df_as_csv(n2n_groups_software_df, '[MITRE]_n2n_groups_software', 'inter_groups_software')

Fichero generado correctamente [MITRE]_n2n_groups_software_17062024_1422h.csv

In [149]:

n2n_enterprise_groups_software_df = results_df[['group_id', 'group', 'group_aliases', 'url_group', 'software_id', 'software', 'software_aliases', 'url_software', 'matrix']]
n2n_enterprise_groups_software_df = n2n_enterprise_groups_software_df[n2n_enterprise_groups_software_df['matrix'].apply(lambda x: 'enterprise-attack' in x)]
n2n_enterprise_groups_software_df.drop('matrix', axis=1, inplace=True)
if save_to_file:
    save_df_as_csv(n2n_enterprise_groups_software_df, '[MITRE]_n2n_enterprise_groups_software', 'inter_groups_software')

Fichero generado correctamente [MITRE]_n2n_enterprise_groups_software_17062024_1422h.csv

#### **5.2 Grupo - Software (1:N)**

In [150]:
# Agregamos las columnas por la columna group_id
mitre_groups_with_software_df = n2n_groups_software_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'group_aliases': unique_list,
    'url_group': unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_aliases': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_groups_with_software_df, '[MITRE]_groups_with_software', 'group_software_1N')

mitre_groups_with_software_df.head(2)

Fichero generado correctamente [MITRE]_groups_with_software_17062024_1422h.csv

,group_id,group,group_aliases,url_group,software_id,software,software_aliases,url_software
0,G0001,[Axiom],"[(Axiom, Group 72)]",[https://attack.mitre.org/groups/G0001],"[S0009, S0412, S0203, S0012, S0021, S0013, S06...","[gh0st RAT, Hydraq, Zox, ZxShell, Hikit, Derus...","[(Derusbi, PHOTO), (Zox, Gresim, ZoxRPC, ZoxPN...","[https://attack.mitre.org/software/S0412, http..."
1,G0002,[Moafee],"[(Moafee,)]",[https://attack.mitre.org/groups/G0002],[S0012],[PoisonIvy],"[(PoisonIvy, Breut, Poison Ivy, Darkmoon)]",[https://attack.mitre.org/software/S0012]

In [151]:
# Agregamos las columnas por la columna group_id
mitre_enterprise_groups_with_software_df = n2n_enterprise_groups_software_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'group_aliases': unique_list,
    'url_group': unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_aliases': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_enterprise_groups_with_software_df, '[MITRE]_enterprise_groups_with_software', 'group_software_1N')

mitre_enterprise_groups_with_software_df.head(2)

Fichero generado correctamente [MITRE]_enterprise_groups_with_software_17062024_1422h.csv

,group_id,group,group_aliases,url_group,software_id,software,software_aliases,url_software
0,G0001,[Axiom],"[(Axiom, Group 72)]",[https://attack.mitre.org/groups/G0001],"[S0009, S0412, S0203, S0012, S0021, S0013, S06...","[gh0st RAT, Hydraq, Zox, ZxShell, Hikit, Derus...","[(Derusbi, PHOTO), (Zox, Gresim, ZoxRPC, ZoxPN...","[https://attack.mitre.org/software/S0412, http..."
1,G0002,[Moafee],"[(Moafee,)]",[https://attack.mitre.org/groups/G0002],[S0012],[PoisonIvy],"[(PoisonIvy, Breut, Poison Ivy, Darkmoon)]",[https://attack.mitre.org/software/S0012]

#### **5.3 Software - Grupo (1:N)**

In [152]:
# Agregamos las columnas por la columna group_id
mitre_software_with_groups_df = n2n_groups_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_aliases': unique_list,
    'url_software': unique_list,
    'group_id': unique_list,
    'group':unique_list,
    'group_aliases': unique_list,
    'url_group': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_software_with_groups_df, '[MITRE]_software_with_groups', 'software_groups_1N')

mitre_software_with_groups_df.head(2)

Fichero generado correctamente [MITRE]_software_with_groups_17062024_1422h.csv

,software_id,software,software_aliases,url_software,group_id,group,group_aliases,url_group
0,S0002,[Mimikatz],"[(Mimikatz,)]",[https://attack.mitre.org/software/S0002],"[G0006, G0059, G0049, G1024, G0060, G0045, G00...","[GALLIUM, Scattered Spider, APT38, APT41, Tont...","[(Leafminer, Raspite), (Wizard Spider, UNC1878...","[https://attack.mitre.org/groups/G0010, https:..."
1,S0003,[RIPTIDE],"[(RIPTIDE,)]",[https://attack.mitre.org/software/S0003],[G0005],[APT12],"[(APT12, IXESHE, DynCalc, Numbered Panda, DNSC...",[https://attack.mitre.org/groups/G0005]

In [153]:
# Agregamos las columnas por la columna group_id
mitre_enterprise_software_with_groups_df = n2n_enterprise_groups_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_aliases': unique_list,
    'url_software': unique_list,
    'group_id': unique_list,
    'group':unique_list,
    'group_aliases': unique_list,
    'url_group': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_enterprise_software_with_groups_df, '[MITRE]_enterprise_software_with_groups', 'software_groups_1N')

mitre_enterprise_software_with_groups_df.head(2)

Fichero generado correctamente [MITRE]_enterprise_software_with_groups_17062024_1423h.csv

,software_id,software,software_aliases,url_software,group_id,group,group_aliases,url_group
0,S0002,[Mimikatz],"[(Mimikatz,)]",[https://attack.mitre.org/software/S0002],"[G0006, G0059, G0049, G1024, G0060, G0045, G00...","[GALLIUM, Scattered Spider, APT38, APT41, Tont...","[(Leafminer, Raspite), (Wizard Spider, UNC1878...","[https://attack.mitre.org/groups/G0010, https:..."
1,S0003,[RIPTIDE],"[(RIPTIDE,)]",[https://attack.mitre.org/software/S0003],[G0005],[APT12],"[(APT12, IXESHE, DynCalc, Numbered Panda, DNSC...",[https://attack.mitre.org/groups/G0005]

### **6. PLATAFORMAS - TÉCNICAS**

#### **6.1 Tablas intermedias (N:N)**

In [19]:
mitre_n2n_enterprise_techniques_platforms_df = get_enterprise_techniques_df[['technique_id', 'technique', 'url', 'platform']]
mitre_n2n_enterprise_techniques_platforms_df = mitre_n2n_enterprise_techniques_platforms_df.rename(columns={'url': 'url_technique'})
mitre_n2n_enterprise_techniques_platforms_df = mitre_n2n_enterprise_techniques_platforms_df.explode('platform')
print(f"Filas del df: {mitre_n2n_enterprise_techniques_platforms_df.shape[0]}. TTP's únicas: {mitre_n2n_enterprise_techniques_platforms_df['technique_id'].nunique()}. Plataformas únicas: {mitre_n2n_enterprise_techniques_platforms_df['platform'].nunique()}")

Filas del df: 1654. TTP's únicas: 637. Plataformas únicas: 11

**[MITRE] Técnicas - Plataformas (N:N)**

In [20]:
if save_to_file:
    save_df_as_csv(mitre_n2n_enterprise_techniques_platforms_df, '[MITRE]_n2n_enterprise_techniques_platforms', 'inter_techniques_platforms')

Fichero generado correctamente [MITRE]_n2n_enterprise_techniques_platforms_19062024_1523h.csv

**[CP] Técnicas - Plataformas (N:N)**

In [21]:
cp_ttp_available = cp_ttps()
cp_n2n_enterprise_techniques_platforms_df = mitre_n2n_enterprise_techniques_platforms_df[mitre_n2n_enterprise_techniques_platforms_df['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {cp_n2n_enterprise_techniques_platforms_df.shape[0]}. TTP's únicas: {cp_n2n_enterprise_techniques_platforms_df['technique_id'].nunique()}. Plataformas únicas: {cp_n2n_enterprise_techniques_platforms_df['platform'].nunique()}")
if save_to_file:
    save_df_as_csv(cp_n2n_enterprise_techniques_platforms_df, '[CP]_n2n_enterprise_techniques_platforms', 'inter_techniques_platforms')

Filas del df: 1424. TTP's únicas: 516. Plataformas únicas: 11
Fichero generado correctamente [CP]_n2n_enterprise_techniques_platforms_19062024_1523h.csv

**[NOCP] Técnicas - Plataformas (N:N)**

In [22]:
nocp_ttp_available = cp_ttps()
nocp_n2n_enterprise_techniques_platforms_df = mitre_n2n_enterprise_techniques_platforms_df[~mitre_n2n_enterprise_techniques_platforms_df['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {nocp_n2n_enterprise_techniques_platforms_df.shape[0]}. TTP's únicas: {nocp_n2n_enterprise_techniques_platforms_df['technique_id'].nunique()}. Plataformas únicas: {nocp_n2n_enterprise_techniques_platforms_df['platform'].nunique()}")
if save_to_file:
    save_df_as_csv(nocp_n2n_enterprise_techniques_platforms_df, '[NOCP]_n2n_enterprise_techniques_platforms', 'inter_techniques_platforms')

Filas del df: 230. TTP's únicas: 121. Plataformas únicas: 11
Fichero generado correctamente [NOCP]_n2n_enterprise_techniques_platforms_19062024_1523h.csv

#### **6.2 Técnica - Plataformas (1:N)**

**[MITRE] Técnica - Plataformas (1:N)**

In [23]:
# Agregamos las columnas por la columna technique_id
mitre_technique_with_platforms_df = mitre_n2n_enterprise_techniques_platforms_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'platform': unique_list
    })

if save_to_file:
    save_df_as_csv(mitre_technique_with_platforms_df, '[MITRE]_enterprise_technique_with_platforms', 'technique_platforms_1N')

Fichero generado correctamente [MITRE]_enterprise_technique_with_platforms_19062024_1523h.csv

**[CP] Técnica - Plataformas (1:N)**

In [24]:
# Agregamos las columnas por la columna technique_id
cp_technique_with_platforms_df = cp_n2n_enterprise_techniques_platforms_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'platform': unique_list
    })

if save_to_file:
    save_df_as_csv(cp_technique_with_platforms_df, '[CP]_enterprise_technique_with_platforms', 'technique_platforms_1N')

Fichero generado correctamente [CP]_enterprise_technique_with_platforms_19062024_1523h.csv

**[NOCP] Técnica - Plataformas (1:N)**

In [25]:
# Agregamos las columnas por la columna technique_id
nocp_technique_with_platforms_df = nocp_n2n_enterprise_techniques_platforms_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'platform': unique_list
    })

if save_to_file:
    save_df_as_csv(nocp_technique_with_platforms_df, '[NOCP]_enterprise_technique_with_platforms', 'technique_platforms_1N')

Fichero generado correctamente [NOCP]_enterprise_technique_with_platforms_19062024_1523h.csv

#### **6.3 Plataforma - Técnicas (1:N)**

**[MITRE] Plataforma - Técnicas (1:N)**

In [26]:
# Agregamos las columnas por la columna technique_id
mitre_platform_with_techniques_df = mitre_n2n_enterprise_techniques_platforms_df.groupby('platform', as_index=False).agg({
    'technique_id':unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(mitre_platform_with_techniques_df, '[MITRE]_enterprise_platform_with_techniques', 'platform_techniques_1N')

Fichero generado correctamente [MITRE]_enterprise_platform_with_techniques_19062024_1523h.csv

**[CP] Plataforma - Técnicas (1:N)**

In [27]:
# Agregamos las columnas por la columna technique_id
cp_platform_with_techniques_df = cp_n2n_enterprise_techniques_platforms_df.groupby('platform', as_index=False).agg({
    'technique_id':unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(cp_platform_with_techniques_df, '[CP]_enterprise_platform_with_techniques', 'platform_techniques_1N')

Fichero generado correctamente [CP]_enterprise_platform_with_techniques_19062024_1523h.csv

**[NOCP] Plataforma - Técnicas (1:N)**

In [28]:
# Agregamos las columnas por la columna technique_id
nocp_platform_with_techniques_df = nocp_n2n_enterprise_techniques_platforms_df.groupby('platform', as_index=False).agg({
    'technique_id':unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(nocp_platform_with_techniques_df, '[NOCP]_enterprise_platform_with_techniques', 'platform_techniques_1N')

Fichero generado correctamente [NOCP]_enterprise_platform_with_techniques_19062024_1523h.csv

### **BONUS. LISTADO DE REGLAS DE DETECCIÓN POR TÉCNICA (TTP ID)**

**Importante:** Debe haberse ejecutado previamente el codigo de obtención de las reglas de detección y clasificación por TTP

In [20]:
def get_rules_from_path(path):
    # Listas para almacenar los resultados
    sources = []
    ttps = []
    file_names = []
    file_extension = []

    # Recorremos la path accediendo a cada directorio para poder añadirlo a una lista
    for root, dirs, files in os.walk(path):
        for file in files:
            # Extensión del archivo
            ext = os.path.splitext(file)[1].lower()
            if ext in ['.csv', '.yaml','.yml', '.toml', '.md', '.txt', '.yar']:
                # Última y penúltima subcarpeta
                path_split = root.split(os.sep)
                ttp = path_split[-1]
                source = path_split[-2] if len(path_split) > 1 else ''
                # Añadimos elementos a las listas
                sources.append(source)
                ttps.append(ttp)
                file_names.append(file)
                file_extension.append(ext)

    df = pd.DataFrame({'source': sources, 'TTP': ttps, 'rule': file_names, 'file_extension': file_extension})

    return df

In [71]:
technique_matrix = '' # Dejamos preparado para el futuro cercano la posibilidad de lectura de tecnicas por matriz
path = os.path.join(os.path.dirname(os.getcwd()), 'download_ttps\saved', technique_matrix)
ttp_rules_df = get_rules_from_path(path)
if save_to_file:
    save_df_as_csv(ttp_rules_df, '[CP]_ttp_rules')

#### **Excepcional: pedido listado de técnicas, tácticas y reglas de detección**

In [72]:
ttp_rules_df.head(2)

   source    TTP                   rule file_extension
0  atomic  T0000       av_exploiting.md            .md
1  atomic  T0000  av_password_dumper.md            .md

In [46]:
count_ttp_rules_df = ttp_rules_df.groupby('TTP').size().reset_index(name='num_rules')
count_ttp_rules_df['TTP'] = count_ttp_rules_df['TTP'].str.upper()
count_ttp_rules_df.head(2)

     TTP  num_rules
0  T0000       2128
1  T0802         10

**MITRE**

In [35]:
mitre_n2n_techniques_tactics_rules = pd.merge(mitre_n2n_enterprise_techniques_tactics, count_ttp_rules_df, how='left', left_on='technique_id', right_on='TTP')
mitre_n2n_techniques_tactics_rules['num_rules'] = mitre_n2n_techniques_tactics_rules['num_rules'].fillna(0).astype(int)
mitre_n2n_techniques_tactics_rules = mitre_n2n_techniques_tactics_rules[['technique_id', 'technique', 'tactic', 'num_rules']]
mitre_n2n_techniques_tactics_rules = mitre_n2n_techniques_tactics_rules.sort_values(by='num_rules', ascending=False)
save_df_as_csv(mitre_n2n_techniques_tactics_rules, '[MITRE]_techniques_tactics_rules')

,tactic,technique_id,technique,url_technique,tactic_id,tactic_description,url_tactic,TTP,num_rules
0,collection,T1074.002,Remote Data Staging,https://attack.mitre.org/techniques/T1074/002,TA0009,The adversary is trying to gather data of inte...,https://attack.mitre.org/tactics/TA0009,T1074.002,2
1,collection,T1602.001,SNMP (MIB Dump),https://attack.mitre.org/techniques/T1602/001,TA0009,The adversary is trying to gather data of inte...,https://attack.mitre.org/tactics/TA0009,T1602.001,3
2,collection,T1602,Data from Configuration Repository,https://attack.mitre.org/techniques/T1602,TA0009,The adversary is trying to gather data of inte...,https://attack.mitre.org/tactics/TA0009,T1602,4

**CYBERPROOF**

In [44]:
cp_n2n_techniques_tactics_rules = pd.merge(cp_n2n_enterprise_techniques_tactics, count_ttp_rules_df, how='left', left_on='technique_id', right_on='TTP')
cp_n2n_techniques_tactics_rules['num_rules'] = cp_n2n_techniques_tactics_rules['num_rules'].fillna(0).astype(int)
cp_n2n_techniques_tactics_rules = cp_n2n_techniques_tactics_rules[['technique_id', 'technique', 'tactic', 'num_rules']]
cp_n2n_techniques_tactics_rules = cp_n2n_techniques_tactics_rules.sort_values(by='num_rules', ascending=False)
save_df_as_csv(cp_n2n_techniques_tactics_rules, '[CP]_techniques_tactics_rules')

Fichero generado correctamente [CP]_techniques_tactics_rules_19062024_1735h.csv