In [28]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on 2024-06-18

@author: Juan Enrique López Marcos

@description: Jupyter Notebook creado para obtener las relaciones entre items de MITRE principalmente con las Técnicas (Tácticas, Data Sources, Software, Grupos). Adicionalmente se incluye una funcionalidad que permite retornar el listado de reglas de detección por técnica disponibles en CP. 

"""

'\nCreated on 2024-06-18\n\n@author: Juan Enrique López Marcos\n\n@description: Jupyter Notebook creado para obtener las relaciones entre items de MITRE principalmente con las Técnicas (Tácticas, Data Sources, Software, Grupos). Adicionalmente se incluye una funcionalidad que permite retornar el listado de reglas de detección por técnica disponibles en CP. \n\n'

**Índice de contenidos**

[1. TÉCNICAS - TÁCTICAS]()

- [1.1 Tablas intermedias (N:N)]()

- [1.2 Técnicas - Tácticas (1:N)]()

- [1.3 Tácticas - Técnicas (1:N)]()

[2. DATA SOURCES - TÉCNICAS]()

- [2.1 Tablas intermedias (N:N)]()

- [2.2 Técnicas - Data Sources (1:N)]()

- [2.3 Data Sources - Técnicas (1:N)]()

[3. GRUPOS - TÉCNICAS]()

- [3.1 Tablas intermedias (N:N)]()

- [3.2 Grupos - Técnicas (1:N)]()

- [3.3 Técnicas - Grupos (1:N)]()

[4. SOFTWARE - TÉCNICAS]()

- [4.1 Tablas intermedias (N:N)]()

- [4.2 Técnicas - Software (1:N)]()

- [4.3 Software - Técnicas (1:N)]()

[5. GRUPOS - SOFTWARE]()

- [4.1 Tablas intermedias (N:N)]()

- [4.2 Grupos - Software (1:N)]()

- [4.3 Software - Grupos (1:N)]()

[6. PLATAFORMAS - TÉCNICAS]()

- [6.1 Tablas intermedias (N:N)]()

- [6.2 Técnica - Plataformas (1:N)]()

- [6.3 Plataforma - Técnicas (1:N)]()


[BONUS. GENERACIÓN LISTADO DE REGLAS DE DETECCIÓN POR TÉCNICA]()

**Descripción de los outputs**

<h3 style="background-color: #FF5733; color: black;">
    1. TÉCNICAS - TÁCTICAS
</h3>

#### 1.1 Tablas intermedias (N:N)

Guardado en: *inter_techniques_tactics*

- Relación N a N de técnicas y tácticas MITRE. Campos: tactic, technique_id, technique, url_technique,tactic_id, tactic_description, url_tactic.
    - [MITRE]_enterprise_n2n_techniques_tactics_df_ddmmYY_hhmm_h.csv
- Relación N a N de técnicas y tácticas CyberProof (filtro sobre aquellas TTP's disponibles con regla de detección). Campos: tactic, technique_id, technique, url_technique,tactic_id, tactic_description, url_tactic
    - [CP]_enterprise_n2n_techniques_tactics_ddmmYY_hhmm_h.csv
- Relación N a N de técnicas y tácticas que NO disponemos en CyberProof. Campos: tactic, technique_id, technique, url_technique,tactic_id, tactic_description, url_tactic
    - [NOCP]_enterprise_n2n_techniques_tactics_ddmmYY_hhmm_h.csv


#### 1.2 Técnicas - Tácticas (1:N)

Guardado en: *technique_tactics_1N*

- Lista de técnicas únicas con las tácticas asociadas MITRE. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [MITRE]_techniques_with_tactics_ddmmYY_hhmm_h.csv
- Lista de técnicas únicas con las tácticas asociadas CyberProof. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [CP]_techniques_with_tactics_ddmmYY_hhmm_h.csv
- Lista de técnicas únicas con las tácticas asociadas que NO disponemos en CyberProof. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [NOCP]_techniques_with_tactics_ddmmYY_hhmm_h.csv


#### 1.3 Tácticas - Técnicas (1:N)

Guardado en: *tactic_techniques_1N*

- Lista de tácticas únicas con las técnicas asociadas MITRE. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [MITRE]_techniques_with_tactics_ddmmYY_hhmm_h.csv
- Lista de tácticas únicas con las técnicas asociadas CyberProof. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [CP]_techniques_with_tactics_ddmmYY_hhmm_h.csv
- Lista de tácticas únicas con las técnicas asociadas que NO disponemos en CyberProof. Campos: technique_id, technique, url_technique, tactic_id, tactic, tactic_description, url_tactic.
    - [NOCP]_techniques_with_tactics_ddmmYY_hhmm_h.csv

*Nota: Tenemos todas las tácticas cubiertas por al menos una regla de deteccion (TTP asociada) y tenemos 1 cubierta por todas TTP's disponibles (TA0040)

<h3 style="background-color: #FF5733; color: black;">
    2. DATA SOURCES - TÉCNICAS
</h3>

#### 2.1 Tablas intermedias (N:N)

Guardado en: *inter_data_sources_techniques*

- Lista sencilla de data sources. Campos: data_source_id, data_source, data_source_description, url_data_source
    - [MITRE]_data_sources

- Relación N:N de Data Sources y Técnicas (todos los casos, incuyendo técnicas sin data source y data sources sin técnica). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [MITRE]_enterprise_n2n_all_techniques_data_sources_ddmmYY_hhmm_h.csv

- Relación N:N de Data Sources y Técnicas (SÓLO aquellos relacionados). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [MITRE]_enterprise_n2n_techniques_data_sources_ddmmYY_hhmm_h.csv
    
*Nota: TTP's únicas sin data source asociado: 40. TTP's únicas con data source asociado: 597. Data sources únicas sin TTP asociada: 37. Data sources únicas sin TTP asociada: 5

- Relación N:N de Data Sources y Técnicas (SÓLO DISPONIBLES EN CP y relacionados). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [CP]_enterprise_n2n_techniques_data_sources_ddmmYY_hhmm_h.csv

- Relación N:N de Data Sources y Técnicas (NO DISPONIBLES EN CP y relacionados). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [NOCP]_enterprise_n2n_techniques_data_sources_ddmmYY_hhmm_h.csv



#### 2.2 Técnicas - Data Sources (1:N)

Guardado en: *technique_data_sources_1N*

- Relación 1:N entre Técnicas y Data Sources (todas las disponibles en MITRE). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [MITRE]_techniques_with_data_sources_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnicas y Data Sources (SÓLO DISPONIBLES EN CP). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [CP]_techniques_with_data_sources_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnicas y Data Sources (NO DISPONIBLES EN CP). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [NOCP]_techniques_with_data_sources_ddmmYY_hhmm_h.csv

*Nota: Disponemos de 597 TTP's con regla de detección asociada a uno o más Data soruces. 103 TTP's no disponibles y 40 TTP's no tienen Data source asociado.


#### 2.3 Data Sources - Técnicas (1:N)

Guardado en: *data_source_techniques_1N*

- Relación 1:N entre Data Sources y Técnicas (todas las disponibles en MITRE). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [MITRE]_data_source_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Data Sources y Técnicas (SÓLO DISPONIBLES EN CP). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [CP]_data_source_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Data Sources y Técnicas (NO DISPONIBLES EN CP). Campos: technique_id, url_technique, data_source_id, data_source, data_source_detail, url_data_source
    - [NOCP]_data_source_with_techniques_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    3. GRUPOS - TÉCNICAS
</h3>

#### 3.1 Tablas intermedias (1:N y N:N)

Guardado en: *inter_groups_techniques*

- Lista sencilla de todos los grupos (1:N). Campos: group_id, group, url_group, technique_id, technique, url_technique
    - [MITRE]_all_groups_ddmmYY_hhmm_h.csv

- Misma lista que la anterior pero filtrada por matriz de ataque enterprise (1:N). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [MITRE]_enterprise_groups_ddmmYY_hhmm_h.csv

- Lista completa de grupos relacionados con toda la información relevante. Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [MITRE]_enterprise_all_data_groups_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [CP]_enterprise_all_data_groups_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [NOCP]_enterprise_all_data_groups_ddmmYY_hhmm_h.csv

#### 3.2 Grupos - Técnicas (1:N)

Guardado en: *group_techniques_1N*

- Relación 1:N entre Grupos y Técnicas (todas las disponibles en MITRE). Campos: ggroup_id, group, url_group, technique_id, technique, url_technique.
    - [MITRE]_groups_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Grupos y Técnicas (SÓLO DISPONIBLES EN CP). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [CP]_groups_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Grupos y Técnicas (NO DISPONIBLES EN CP). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [NOCP]_groups_with_techniques_ddmmYY_hhmm_h.csv

#### 3.3 Técnicas - Grupos (1:N)

Guardado en: *technique_groups_1N*

- Relación 1:N entre Técnicas y Grupos (todas las disponibles en MITRE). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [MITRE]_techniques_with_groups_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnicas y Grupos (SÓLO DISPONIBLES EN CP). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [CP]_techniques_with_groups_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnicas y Grupos (NO DISPONIBLES EN CP). Campos: group_id, group, url_group, technique_id, technique, url_technique.
    - [NOCP]_techniques_with_groups_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    4. SOFTWARE - TÉCNICAS
</h3>

#### 4.1 Tablas intermedias (1:N y N:N)

Guardado en: *inter_software_techniques*

- Lista sencilla de todos los software, incluyendo diferentes de enterprise (1:N). Campos: software_id, software, software_aliases, type, url, matrix
    - [MITRE]_all_software_ddmmYY_hhmm_h.csv

- Lista sencilla de todos los software enterprise (1:N). Campos: software_id, software, software_aliases, type, url, matrix
    - [MITRE]_enterprise_software_ddmmYY_hhmm_h.csv

- Lista completa de software relacionados con las técnicas y toda la información disponible (sólo enterprise). Campos: type, id, url, matrix, created, modified, created_by_ref, modified_by_ref, external_references, object_marking_refs, mitre_version, mitre_attack_spec_version, mitre_deprecated, technique, technique_id, technique_description, tactic, technique_detection, platform, data_sources, defense_bypassed, permissions_required, effective_permissions, system_requirements, network_requirements, remote_support, contributors, tactic_type, impact_type, is_subtechnique, software_id, software, software_aliases, software_description, software_type, url_software, mitre_domains, url_technique.
    - [MITRE]n2n_main_techniques_software_ddmmYY_hhmm_h.csv

- Lista reducida a los campos más importantes. Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [MITRE]_n2n_techniques_software_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [CP]_n2n_techniques_software_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [NOCP]_n2n_techniques_software_ddmmYY_hhmm_h.csv


#### 4.2 Técnica - Software (1:N)

Guardado en: *technique_software_1N*

- Relación 1:N entre Técnica y Software (todas las disponibles en MITRE). Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [MITRE]_technique_with_software_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnica y Software  (SÓLO DISPONIBLES EN CP). Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [CP]_technique_with_software_ddmmYY_hhmm_h.csv

- Relación 1:N entre Técnica y Software  (NO DISPONIBLES EN CP). Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [NOCP]_technique_with_software_ddmmYY_hhmm_h.csv


#### 4.3 Software - Técnicas (1:N)

Guardado en: *software_techniques_1N*

- Relación 1:N entre Software y Técnicas (todas las disponibles en MITRE). También incluye otras informaciones como tácticas, platform y data source. Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [MITRE]_software_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Software y Técnicas (SÓLO DISPONIBLES EN CP). Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [CP]_software_with_techniques_ddmmYY_hhmm_h.csv

- Relación 1:N entre Software y Técnicas (NO DISPONIBLES EN CP).  Campos: technique_id, technique, url_technique, software_id, software, software_description, software_type, url_software.
    - [NOCP]_software_with_techniques_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    5. GRUPOS - SOFTWARE
</h3>

#### 5.1 Tablas intermedias (1:N y N:N)

Guardado en: *inter_groups_software*

- Lista completa de software relacionados con los grupos. Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_n2n_groups_software_ddmmYY_hhmm_h.csv

- Lista completa de software relacionados con los grupos filtrado por matriz enterprise. Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_n2n_enterprise_groups_software_ddmmYY_hhmm_h.csv


#### 5.2 Grupo - Software (1:N)

Guardado en: *group_software_1N*

- Relación 1:N entre Grupo y Software (todas las disponibles en MITRE). Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_groups_with_software_ddmmYY_hhmm_h.csv

- Relación 1:N entre Grupo y Software (todas las disponibles en MITRE) filtrados por la matriz enterprise. Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_enterprise_groups_with_software_ddmmYY_hhmm_h.csv


#### 5.3 Software - Grupo (1:N)

Guardado en: *software_groups_1N*

- Relación 1:N entre Software y Grupo (todas las disponibles en MITRE). Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_software_with_groups_ddmmYY_hhmm_h.csv

- Relación 1:N entre Software y Grupo (todas las disponibles en MITRE) filtrados por la matriz enterprise. Campos: group_id, group, group_aliases, url_group, software_id, software, software_aliases, url_software.
    - [MITRE]_enterprise_software_with_groups_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    6. PLATAFORMAS - TÉCNICAS
</h3>

#### 6.1 Tablas intermedias ( N:N)

Guardado en: *inter_techniques_platforms*

- Lista completa de técnicas relacionadas con las plataformas (MITRE - enterprise). Campos: technique_id, technique, url_technique, platform.
    - [MITRE]_n2n_enterprise_techniques_platforms_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [CP]_n2n_enterprise_techniques_platforms_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [NOCP]_n2n_enterprise_techniques_platforms_ddmmYY_hhmm_h.csv


#### 6.2 Técnica - Plataformas (1:N)

Guardado en: *technique_platforms_1N*

- Relación 1:N entre Técnica y Plataformas (todas las disponibles en MITRE - enterprise). Campos: technique_id, technique, url_technique, platform.
    - [MITRE]_enterprise_technique_with_platforms_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [CP]_enterprise_technique_with_platforms_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [NOCP]_enterprise_technique_with_platforms_ddmmYY_hhmm_h.csv


#### 6.3 Plataforma - Técnicas (1:N)

Guardado en: *platform_techniques_1N*

- Relación 1:N entre Plataforma y Técnica (todas las disponibles en MITRE - enterprise). Campos: technique_id, technique, url_technique, platform.
    - [MITRE]_enterprise_platform_with_techniques_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [CP]_enterprise_platform_with_techniques_ddmmYY_hhmm_h.csv

- Filtramos la lista completa por las técnicas NO disponibles en CP. Campos: technique_id, technique, url_technique, platform.
    - [NOCP]_enterprise_platform_with_techniques_ddmmYY_hhmm_h.csv

<h3 style="background-color: #FF5733; color: black;">
    BONUS. GENERACIÓN LISTADO DE REGLAS DE DETECCIÓN POR TÉCNICA
</h3>


- Listado de reglas de deteccion disponibles en CyberProof asociadas a TTP's (incluyendo tambien las que no se han podido asignar a ninguna y por tanto se asignan a T0000)
    - [CP]_ttp_rules_ddmmYY_hhmm_h.csv

#### Requerimientos

In [29]:
from attackcti import attack_client
import pandas as pd
import datetime
import csv
import os

from IPython.display import display
pd.options.display.max_columns = None

#### Funciones

In [30]:
def delete_special_characters(df):
    chars = r'[^\w\s,-.:]'  # Esto incluye cualquier cosa que no sea una palabra o espacio
    chars_url = r"[\[\]\'{}]"
    lb = r'\n'
    cr = r'\r'
    low_bar = r'_'
    colon_sep = r"': '"
    df = df.fillna('N/A')
    for col in df.columns:
        # Convertimos a str todas las columna
        if df[col].dtype == 'O':
            df[col] = df[col].astype(str)
        elif df[col].dtype == 'bool':
            df[col] = df[col].replace({True: 'True', False: 'False'})
        if col != 'external_references':
            # Aplicamos los reemplazos, importante mantener este orden
            df[col] = df[col].str.replace(colon_sep, ' - ', regex=True)
            df[col] = df[col].str.replace(low_bar, ' ', regex=True)
            df[col] = df[col].str.replace(chars, '', regex=True)
            df[col] = df[col].str.replace(lb, ' ', regex=True)
            df[col] = df[col].str.replace(cr, '', regex=True)
        else:
            df[col] = df[col].str.replace(chars_url, '', regex=True)
            df[col] = df[col].str.replace(colon_sep, ' - ', regex=True)
            df[col] = df[col].str.replace(low_bar, ' ', regex=True)
            df[col] = df[col].str.replace(lb, ' ', regex=True)
            df[col] = df[col].str.replace(cr, '', regex=True)
    return df

In [31]:
# Buscamos en la columna de descripción o informativa
def find_techniques(texto, techniques_enterprise_list):
    if isinstance(texto, str):
        found = []
        for item in techniques_enterprise_list:
            if item in texto:
                found.append(item)
        return ', '.join(found)
    else:
        return ''

In [32]:
def save_df_as_csv(df, name, aux_folder=''):
    now = datetime.datetime.now()
    if not os.path.exists(os.path.join(os.getcwd(), 'outputs', 'attackcti', aux_folder)):
        os.makedirs(os.path.join(os.getcwd(), 'outputs', 'attackcti', aux_folder))
    file_to_save = os.path.join(os.getcwd(), 'outputs', 'attackcti', aux_folder, (name+ '_'+ now.strftime('%d%m%Y_%H%M')+'h.csv'))
    df.to_csv(file_to_save, sep=';', encoding='utf8', index=False, quoting=csv.QUOTE_NONNUMERIC)
    print('Fichero generado correctamente '+ name + '_' +now.strftime('%d%m%Y_%H%M')+'h.csv')

In [33]:
def getListOfFilesSub(dirName):
    # Crea lista de ficheros y subdirectorios
    listOfFile = os.listdir(dirName)
    allFiles = list()
    #Recorre los directorios y subdirectorios y genera una lista con los ficheros encontrados en estos
    for entry in listOfFile:
        fullPath = os.path.join(dirName, entry)
        if os.path.isdir(fullPath):
            allFiles = allFiles + getListOfFilesSub(fullPath)
        else:
            allFiles.append(fullPath)
    #Devuelve la lista con los ficheros
    return allFiles

In [34]:
# Función para quedarnos unicamente con items unicos al agregar
def unique_list(series):
    return list(set(series))

In [35]:
def cp_unique_ttp_with_rules(path):
    # Conjunto para almacenar nombres únicos de carpetas
    unique_folders = set()
    
    # Recorrer el directorio y sus subdirectorios
    for root, dirs, files in os.walk(path):
        for dir_name in dirs:
            # Verificar si el nombre de la carpeta contiene 'T0' o 'T1'
            if 'T0' in dir_name or 'T1' in dir_name:
                # Añadir solo el nombre de la carpeta al conjunto (esto elimina duplicados automáticamente)
                unique_folders.add(os.path.basename(dir_name))
    
    # Convertir el conjunto a una lista para el resultado final
    filtered_folders = list(unique_folders)
    filtered_folders = sorted(filtered_folders, key=len, reverse=True)
    filtered_folders.remove('T0000')
    
    return filtered_folders

In [49]:
def cp_ttps():
    # ttps_outputs_path = r'C:\Users\jelopez\Documents\CyberProof\python\develop\download_ttps\saved'
    ttps_outputs_path = r'C:\Users\jelopez\Documents\CyberProof\python\develop\get_rules_and_classify_by_ttp\outputs\enterprise'
    cp_ttp_available = cp_unique_ttp_with_rules(ttps_outputs_path)
    return cp_ttp_available

In [37]:
# El campo data_sources viene con un formato que no nos sirve para asociar el id y la url, por lo que lo formateamos dando lugar a 2 campos nuevos 
def split_lists(lst):
    if lst is None:
        return [], []
    before_colon = [item.split(': ')[0] for item in lst if item]
    after_colon = [item.split(': ')[1] for item in lst if item]
    return before_colon, after_colon

#### Métodos

In [38]:
lift = attack_client()

##### get_enterprise_techniques

In [39]:
get_enterprise_techniques = lift.get_enterprise_techniques(stix_format=False)
get_enterprise_techniques_df = pd.json_normalize(get_enterprise_techniques)
get_enterprise_techniques_df = get_enterprise_techniques_df[(get_enterprise_techniques_df['mitre_deprecated'] != 'True')]

[taxii2client.v20] [WARNING ] [2024-07-03 08:58:04,740] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:04,759] TAXII Server Response with different amount of objects! Setting per_request=780

##### get_enterprise_tactics

In [40]:
get_enterprise_tactics = lift.get_enterprise_tactics(stix_format=False)
get_enterprise_tactics_df = pd.json_normalize(get_enterprise_tactics)
get_enterprise_tactics_df = get_enterprise_tactics_df[(get_enterprise_tactics_df['mitre_deprecated'] != 'True')]

[taxii2client.v20] [WARNING ] [2024-07-03 08:58:07,007] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:07,007] TAXII Server Response with different amount of objects! Setting per_request=14

##### get_data_sources

In [41]:
get_data_sources = lift.get_data_sources(stix_format=False)
get_data_sources_df = pd.json_normalize(get_data_sources)

[taxii2client.v20] [WARNING ] [2024-07-03 08:58:10,244] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:10,244] TAXII Server Response with different amount of objects! Setting per_request=38
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:13,295] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:13,310] TAXII Server Response with different amount of objects! Setting per_request=17
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:15,922] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:15,922] TAXII Server Response with different amount of objects! Setting per_request=6

##### get_groups

In [42]:
get_groups = lift.get_groups(stix_format=False)
get_groups_df = pd.json_normalize(get_groups)
get_groups_df = get_groups_df.sort_values(by='group_id')

[taxii2client.v20] [WARNING ] [2024-07-03 08:58:19,383] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:19,383] TAXII Server Response with different amount of objects! Setting per_request=163
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:22,138] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:22,138] TAXII Server Response with different amount of objects! Setting per_request=13
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:25,501] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:25,501] TAXII Server Response with different amount of objects! Setting per_request=16

##### get_techniques_used_by_all_groups()

In [43]:
get_techniques_used_by_all_groups = lift.get_techniques_used_by_all_groups(stix_format=False)
get_techniques_used_by_all_groups_df = pd.json_normalize(get_techniques_used_by_all_groups)
get_techniques_used_by_all_groups_df = get_techniques_used_by_all_groups_df.sort_values(by='group_id')

[taxii2client.v20] [WARNING ] [2024-07-03 08:58:28,808] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:28,823] TAXII Server Response with different amount of objects! Setting per_request=163
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:31,263] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:31,263] TAXII Server Response with different amount of objects! Setting per_request=13
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:35,729] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:35,729] TAXII Server Response with different amount of objects! Setting per_request=16
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:40,320] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:40,335] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:42,960] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:42,964] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:45,972] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:45,972] TAXII Server Response with different amount of objects! Setting per_request=95
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:50,038] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:51,727] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:53,212] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:58:54,479] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:01,368] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:01,385] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:04,688] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:04,705] TAXII Server Response with different amount of objects! Setting per_request=1350

##### get_software()

In [44]:
get_software = lift.get_software(stix_format=False)
get_software_df = pd.json_normalize(get_software)
get_software_df = get_software_df.sort_values(by='software_id')

[taxii2client.v20] [WARNING ] [2024-07-03 08:59:10,446] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:10,462] TAXII Server Response with different amount of objects! Setting per_request=595
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:12,947] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:12,963] TAXII Server Response with different amount of objects! Setting per_request=85
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:15,866] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:15,875] TAXII Server Response with different amount of objects! Setting per_request=111
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:18,587] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:18,587] TAXII Server Response with different amount of objects! Setting per_request=2
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:22,003] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 08:59:22,003] TAXII Server Response with different amount of objects! Setting per_request=28

#### Parámetros

In [45]:
save_to_file = True

### **1. TÁCTICAS - TÉCNICAS**

#### **1.1 Tablas intermedias (N:N)**

In [46]:
# Comenzamos filtrando el df de técnicas y nos quedamos con las columnas que vamos a necesitar
enterprise_tactics_with_techniques_df = get_enterprise_techniques_df[['technique_id', 'technique','url','tactic']]
print(f"Filas del df: {enterprise_tactics_with_techniques_df.shape[0]}. TTP's únicas: {enterprise_tactics_with_techniques_df['technique_id'].nunique()}")
# Generamos tantas filas como tácticas encontremos dando lugar a una relación 1-1 entre técnicas y tácticas
enterprise_tactics_with_techniques_df = enterprise_tactics_with_techniques_df.explode('tactic')
print(f"Tras explode. Filas del df: {enterprise_tactics_with_techniques_df.shape[0]}. TTP's únicas: {enterprise_tactics_with_techniques_df['technique_id'].nunique()}. Tácticas únicas: {enterprise_tactics_with_techniques_df['tactic'].nunique()}")

# Reordenamos el df
enterprise_tactics_with_techniques_df = enterprise_tactics_with_techniques_df[['tactic', 'technique_id', 'technique', 'url']]
# Ordenamos por las tácticas
enterprise_tactics_with_techniques_df = enterprise_tactics_with_techniques_df.sort_values(by='tactic')
# Renombramos el campo url
enterprise_tactics_with_techniques_df = enterprise_tactics_with_techniques_df.rename(columns={'url': 'url_technique'})
# Llamamos a get_enterprise_tactics_df y nos quedamos con los campos que necesitamos para hacer left join
concat_get_enterprise_tactics_df = get_enterprise_tactics_df[['tactic_id','tactic_shortname','tactic_description','url']]
# Renombramos el campo url y tactic_shortname
concat_get_enterprise_tactics_df = concat_get_enterprise_tactics_df.rename(columns={'url': 'url_tactic', 'tactic_shortname': 'tactic'})
mitre_n2n_enterprise_techniques_tactics = pd.merge(enterprise_tactics_with_techniques_df, concat_get_enterprise_tactics_df, left_on='tactic', right_on='tactic', how='left')
mitre_n2n_enterprise_techniques_tactics.head(3)
print(f"Filas del df: {mitre_n2n_enterprise_techniques_tactics.shape[0]}. TTP's únicas: {mitre_n2n_enterprise_techniques_tactics['technique_id'].nunique()}. Tácticas únicas: {mitre_n2n_enterprise_techniques_tactics['tactic_id'].nunique()}")

Filas del df: 637. TTP's únicas: 637
Tras explode. Filas del df: 830. TTP's únicas: 637. Tácticas únicas: 14
Filas del df: 830. TTP's únicas: 637. Tácticas únicas: 14

**[MITRE] Técnicas - Tácticas (N:N)**

In [47]:
if save_to_file:
    save_df_as_csv(mitre_n2n_enterprise_techniques_tactics, '[MITRE-attactcti]_enterprise_n2n_techniques_tactics', 'inter_techniques_tactics')

Fichero generado correctamente [MITRE-attactcti]_enterprise_n2n_techniques_tactics_03072024_0859h.csv

**[CP] Técnicas - Tácticas (N:N)**

In [50]:
cp_ttp_available = cp_ttps()
cp_n2n_enterprise_techniques_tactics = mitre_n2n_enterprise_techniques_tactics[mitre_n2n_enterprise_techniques_tactics['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {cp_n2n_enterprise_techniques_tactics.shape[0]}. TTP's únicas: {cp_n2n_enterprise_techniques_tactics['technique_id'].nunique()}. Tácticas únicas: {cp_n2n_enterprise_techniques_tactics['tactic_id'].nunique()}")
if save_to_file:
    save_df_as_csv(cp_n2n_enterprise_techniques_tactics, '[CP-attactcti]_enterprise_n2n_techniques_tactics', 'inter_techniques_tactics')

Filas del df: 686. TTP's únicas: 521. Tácticas únicas: 14
Fichero generado correctamente [CP-attactcti]_enterprise_n2n_techniques_tactics_03072024_0908h.csv

**[NOCP] Técnicas - Tácticas (N:N)**

In [51]:
nocp_n2n_enterprise_techniques_tactics = mitre_n2n_enterprise_techniques_tactics[~mitre_n2n_enterprise_techniques_tactics['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {nocp_n2n_enterprise_techniques_tactics.shape[0]}. TTP's únicas: {nocp_n2n_enterprise_techniques_tactics['technique_id'].nunique()}. Tácticas únicas: {nocp_n2n_enterprise_techniques_tactics['tactic_id'].nunique()}")
if save_to_file:
    save_df_as_csv(nocp_n2n_enterprise_techniques_tactics, '[NOCP-attactcti]_enterprise_n2n_techniques_tactics', 'inter_techniques_tactics')

Filas del df: 144. TTP's únicas: 116. Tácticas únicas: 13
Fichero generado correctamente [NOCP-attactcti]_enterprise_n2n_techniques_tactics_03072024_0908h.csv

#### **1.2 Técnicas - Tácticas (1:N)**

**[MITRE] Técnicas - Tácticas (1:N)**

In [52]:
# Agregamos las columnas por la columna technique_id
mitre_techniques_with_tactics = mitre_n2n_enterprise_techniques_tactics.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'tactic_id': unique_list,
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_techniques_with_tactics, '[MITRE-attactcti]_techniques_with_tactics', 'technique_tactics_1N')

Fichero generado correctamente [MITRE-attactcti]_techniques_with_tactics_03072024_0908h.csv

**[CP] Técnicas - Tácticas (1:N)**

In [53]:
cp_techniques_with_tactics = cp_n2n_enterprise_techniques_tactics.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'tactic_id': unique_list,
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list
    })
if save_to_file:
    save_df_as_csv(cp_techniques_with_tactics, '[CP-attactcti]_techniques_with_tactics', 'technique_tactics_1N')

Fichero generado correctamente [CP-attactcti]_techniques_with_tactics_03072024_0908h.csv

**[NOCP] Técnicas - Tácticas (1:N)**

In [54]:
nocp_techniques_with_tactics = nocp_n2n_enterprise_techniques_tactics.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'tactic_id': unique_list,
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_techniques_with_tactics, '[NOCP-attactcti]_techniques_with_tactics', 'technique_tactics_1N')

Fichero generado correctamente [NOCP-attactcti]_techniques_with_tactics_03072024_0908h.csv

#### **1.3 Tácticas - Técnicas (1:N)**

**[MITRE] Tácticas - Técnicas (1:N)**

In [55]:
# Agregamos las columnas por la columna tactic_id
mitre_tactics_with_techniques = mitre_n2n_enterprise_techniques_tactics.groupby('tactic_id', as_index=False).agg({
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list,
    'technique_id': unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(mitre_tactics_with_techniques, '[MITRE-attactcti]_tactics_with_techniques', 'tactic_techniques_1N')

Fichero generado correctamente [MITRE-attactcti]_tactics_with_techniques_03072024_0908h.csv

**[CP] Tácticas - Técnicas (1:N)**

In [56]:
# Agregamos las columnas por la columna tactic_id
cp_tactics_with_techniques = cp_n2n_enterprise_techniques_tactics.groupby('tactic_id', as_index=False).agg({
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list,
    'technique_id': unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(cp_tactics_with_techniques, '[CP-attactcti]_tactics_with_techniques', 'tactic_techniques_1N')

Fichero generado correctamente [CP-attactcti]_tactics_with_techniques_03072024_0908h.csv

**[NOCP] Tácticas - Técnicas (1:N)**

In [57]:
# Agregamos las columnas por la columna tactic_id
nocp_tactics_with_techniques = nocp_n2n_enterprise_techniques_tactics.groupby('tactic_id', as_index=False).agg({
    'tactic': unique_list,
    'tactic_description': unique_list,
    'url_tactic': unique_list,
    'technique_id': unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(nocp_tactics_with_techniques, '[NOCP-attactcti]_tactics_with_techniques', 'tactic_techniques_1N')

Fichero generado correctamente [NOCP-attactcti]_tactics_with_techniques_03072024_0908h.csv

### **2. DATA SOURCES - TÉCNICAS**

#### **2.1 Tablas intermedias (N:N)**

In [58]:
#Formateamos el df para exportar
data_sources_export_df = get_data_sources_df
data_sources_export_df['data_source_id'] = data_sources_export_df['url'].str.replace('https://attack.mitre.org/datasources/', '')
data_sources_export_df = data_sources_export_df[['data_source_id','data_source','data_source_description','url']].sort_values('data_source')
data_sources_export_df = data_sources_export_df.rename(columns={'url': 'url_data_source'})
if save_to_file:
    save_df_as_csv(data_sources_export_df, '[MITRE-attactcti]_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [MITRE-attactcti]_data_sources_03072024_0908h.csv

In [59]:
data_sources_export_df.head(3)

,data_source_id,data_source,data_source_description,url_data_source
8,DS0026,Active Directory,A database and set of services that allows adm...,https://attack.mitre.org/datasources/DS0026
26,DS0015,Application Log,Events collected by third-party services such ...,https://attack.mitre.org/datasources/DS0015
39,DS0041,Application Vetting,Application vetting report generated by an ext...,https://attack.mitre.org/datasources/DS0041

In [60]:
# Obtenemos de get_enterprise_techniques_df las técnicas con el data source asociado
temp_o2n_techniques_data_sources_df = get_enterprise_techniques_df[['technique_id', 'data_sources','url']]
temp_o2n_techniques_data_sources_df = temp_o2n_techniques_data_sources_df.rename(columns={'url': 'url_technique'})

    
temp_o2n_techniques_data_sources_df[['data_source_simp', 'data_source_detail']] = temp_o2n_techniques_data_sources_df['data_sources'].apply(lambda x: pd.Series(split_lists(x)))
# Antes de unir las tablas debemos desagregar la tabla procendente de get_enterprise_techniques_df en tantas filas como tecnicas y data sources existan
n2n_techniques_data_sources_df = temp_o2n_techniques_data_sources_df.explode(['data_source_simp','data_source_detail'])
# Unimos las tablas para disponer de la información completa
n2n_techniques_data_sources_df = pd.merge(n2n_techniques_data_sources_df, data_sources_export_df, left_on='data_source_simp', right_on='data_source', how='outer') #left
n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[['technique_id', 'url_technique', 'data_source_id', 'data_source', 'data_source_detail', 'url_data_source']]
#Eliminamos duplicados, no es necesario pero a futuro evitar inconsistencias
n2n_techniques_data_sources_df = n2n_techniques_data_sources_df.drop_duplicates()
#Ordenamos el df por la técnica
n2n_techniques_data_sources_df = n2n_techniques_data_sources_df.sort_values('technique_id')
n2n_techniques_data_sources_df.reset_index(drop=True, inplace=True)
n2n_techniques_data_sources_df.head(2)

,technique_id,url_technique,data_source_id,data_source,data_source_detail,url_data_source
0,T1001,https://attack.mitre.org/techniques/T1001,DS0029,Network Traffic,Network Traffic Content,https://attack.mitre.org/datasources/DS0029
1,T1001.001,https://attack.mitre.org/techniques/T1001/001,DS0029,Network Traffic,Network Traffic Content,https://attack.mitre.org/datasources/DS0029

In [61]:
ttps_without_sd_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[n2n_techniques_data_sources_df['data_source_id'].isnull()]
print(f"TTP's únicas sin data source asociado: {ttps_without_sd_n2n_techniques_data_sources_df['technique_id'].nunique()}")
ttps_with_sd_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[~n2n_techniques_data_sources_df['data_source_id'].isnull()]
print(f"TTP's únicas con data source asociado: {ttps_with_sd_n2n_techniques_data_sources_df['technique_id'].nunique()}")
sd_with_ttp_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[~n2n_techniques_data_sources_df['technique_id'].isnull()]
print(f"Data sources únicas con data source asociado: {sd_with_ttp_n2n_techniques_data_sources_df['data_source_id'].nunique()}")
sd_without_ttp_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[n2n_techniques_data_sources_df['technique_id'].isnull()]
print(f"Data sources únicas sin TTP asociada: {sd_without_ttp_n2n_techniques_data_sources_df['data_source_id'].nunique()}")

TTP's únicas sin data source asociado: 40
TTP's únicas con data source asociado: 597
Data sources únicas con data source asociado: 37
Data sources únicas sin TTP asociada: 5

**[MITRE] Guardado Técnicas - Data sources N:N**

In [62]:
# Guardamos la relación entre técnicas y data sources completa: Técnicas con y sin data source; y Data sources con y sin técnica asociada.
if save_to_file:
    save_df_as_csv(n2n_techniques_data_sources_df, '[MITRE-attactcti]_enterprise_n2n_all_techniques_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [MITRE-attactcti]_enterprise_n2n_all_techniques_data_sources_03072024_0908h.csv

In [63]:
# Guardamos la relación entre técnicas y data sources completa: Sólo tecnicas y data sources con relación.
n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[(~n2n_techniques_data_sources_df['technique_id'].isnull()) & (~n2n_techniques_data_sources_df['data_source_id'].isnull())]
if save_to_file:
    save_df_as_csv(n2n_techniques_data_sources_df, '[MITRE-attactcti]_enterprise_n2n_techniques_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [MITRE-attactcti]_enterprise_n2n_techniques_data_sources_03072024_0908h.csv

**[CP] Relación N:N Técnicas y Data Sources**

Filtramos la tabla mitre por aquellas técnicas disponibles en CyberProof

In [64]:
cp_ttp_available = cp_ttps()
cp_ttp_available[:3]

[' T1059.003', ' T1070.001', ' T1021.001']

In [65]:
cp_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[n2n_techniques_data_sources_df['technique_id'].isin(cp_ttp_available)]
if save_to_file:
    save_df_as_csv(cp_n2n_techniques_data_sources_df, '[CP-attactcti]_enterprise_n2n_techniques_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [CP-attactcti]_enterprise_n2n_techniques_data_sources_03072024_0908h.csv

**[NOCP] Relación N:N Técnicas y Data Sources**

In [66]:
nocp_n2n_techniques_data_sources_df = n2n_techniques_data_sources_df[~n2n_techniques_data_sources_df['technique_id'].isin(cp_ttp_available)]
if save_to_file:
    save_df_as_csv(nocp_n2n_techniques_data_sources_df, '[NOCP-attactcti]_enterprise_n2n_techniques_data_sources', 'inter_data_sources_techniques')

Fichero generado correctamente [NOCP-attactcti]_enterprise_n2n_techniques_data_sources_03072024_0908h.csv

#### **2.2 Técnicas - Data Sources (1:N)**

**[MITRE] TECHNIQUES - DATASOURCES 1:N**

In [67]:
# Agregamos las columnas por la columna technique_id
mitre_techniques_with_data_sources_df = n2n_techniques_data_sources_df.groupby('technique_id', as_index=False).agg({
    'url_technique':unique_list,
    'data_source_id': unique_list,
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_techniques_with_data_sources_df, '[MITRE]_techniques_with_data_sources_df', 'technique_data_sources_1N')

Fichero generado correctamente [MITRE]_techniques_with_data_sources_df_03072024_0908h.csv

**[CP] TECHNIQUES - DATASOURCES 1:N**

In [68]:
# Agregamos las columnas por la columna technique_id
cp_techniques_with_data_sources_df = cp_n2n_techniques_data_sources_df.groupby('technique_id', as_index=False).agg({
    'url_technique':unique_list,
    'data_source_id': unique_list,
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list
    })
if save_to_file:
    save_df_as_csv(cp_techniques_with_data_sources_df, '[CP-attactcti]_techniques_with_data_sources_df', 'technique_data_sources_1N')

Fichero generado correctamente [CP-attactcti]_techniques_with_data_sources_df_03072024_0908h.csv

**[NOCP] TECHNIQUES - DATASOURCES 1:N**

In [69]:
# Agregamos las columnas por la columna technique_id
nocp_techniques_with_data_sources_df = nocp_n2n_techniques_data_sources_df.groupby('technique_id', as_index=False).agg({
    'url_technique':unique_list,
    'data_source_id': unique_list,
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_techniques_with_data_sources_df, '[NOCP-attactcti]_techniques_with_data_sources_df', 'technique_data_sources_1N')

Fichero generado correctamente [NOCP-attactcti]_techniques_with_data_sources_df_03072024_0908h.csv

#### **2.3 Data Sources - Técnicas (1:N)**

**[MITRE] TECHNIQUES - DATASOURCES 1:N**

In [70]:
# Agregamos las columnas por la columna technique_id
mitre_data_source_with_techniques_df = n2n_techniques_data_sources_df.groupby('data_source_id', as_index=False).agg({
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list,
    'url_technique':unique_list,
    'technique_id': unique_list
    })
save_df_as_csv(mitre_data_source_with_techniques_df, '[MITRE-attactcti]_data_source_with_techniques', 'data_source_techniques_1N')

Fichero generado correctamente [MITRE-attactcti]_data_source_with_techniques_03072024_0908h.csv

**[CP] TECHNIQUES - DATA SOURCES 1:N**

In [71]:
# Agregamos las columnas por la columna technique_id
cp_data_source_with_techniques_df = cp_n2n_techniques_data_sources_df.groupby('data_source_id', as_index=False).agg({
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list,
    'url_technique':unique_list,
    'technique_id': unique_list
    })
save_df_as_csv(cp_data_source_with_techniques_df, '[CP-attactcti]_data_source_with_techniques', 'data_source_techniques_1N')

Fichero generado correctamente [CP-attactcti]_data_source_with_techniques_03072024_0908h.csv

**[NOCP] TECHNIQUES - DATA SOURCES 1:N**

In [72]:
# Agregamos las columnas por la columna technique_id
nocp_data_source_with_techniques_df = nocp_n2n_techniques_data_sources_df.groupby('data_source_id', as_index=False).agg({
    'data_source': unique_list,
    'data_source_detail': unique_list,
    'url_data_source': unique_list,
    'url_technique':unique_list,
    'technique_id': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_data_source_with_techniques_df, '[NOCP-attactcti]_data_source_with_techniques', 'data_source_techniques_1N')

Fichero generado correctamente [NOCP-attactcti]_data_source_with_techniques_03072024_0908h.csv

### **3. GRUPOS - TÉCNICAS**

#### **3.1 Tablas intermedias (N:N)**

In [73]:
groups_df = get_groups_df[['group_id','group','group_aliases','matrix','url']]
groups_df = groups_df.rename(columns={'url': 'url_group'})
if save_to_file:
    save_df_as_csv(groups_df, '[MITRE-attactcti]_all_groups', 'inter_groups_techniques')
enterprise_groups_df = groups_df[groups_df['matrix'].apply(lambda x: 'enterprise-attack' in x)]
enterprise_groups_df.head(2)
if save_to_file:
    save_df_as_csv(enterprise_groups_df, '[MITRE-attactcti]_enterprise_groups', 'inter_groups_techniques')

Fichero generado correctamente [MITRE-attactcti]_all_groups_03072024_0908h.csv
Fichero generado correctamente [MITRE-attactcti]_enterprise_groups_03072024_0908h.csv

In [74]:

# OLD -> Se obtiene toda la información disponible (data source, platform, etc..) pero de cara a permitir correctamente las relaciones vamos a guardar sólo la información de técnicas y grupos
'''
# Filtramos los items cuya técnica sea de tipo enterprise. La lista de grupos se reduce al no aparecer aquellos con técnica asociada y ahora con tipo enterprise.
mitre_all_info_groups_df = get_techniques_used_by_all_groups_df[get_techniques_used_by_all_groups_df['technique_matrix'].apply(lambda x: 'enterprise-attack' in x)]
# Hacemos una selección de columnas con las que trabajar
mitre_all_info_groups_df = mitre_all_info_groups_df[['group_id','group','url','technique_id', 'technique', 'platform']]
# Renombramos la url de la técnica
mitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={'url': 'url_group'})

# Unimos con Data Sources para complementar la información
mitre_all_info_groups_df = pd.merge(mitre_all_info_groups_df, n2n_techniques_data_sources_df, left_on='technique_id', right_on='technique_id', how='left')
mitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={'url_technique_x': 'url_technique'})

# Ampliamos el df por todos los campos necesarios para llegar a la relación N:N con el detalle de los data sources
mitre_all_info_groups_df = mitre_all_info_groups_df.explode(['data_source','data_source_detail'])

# Unimos con Tácticas para complementar la información
# Importante: No hemos añadido la información de tácticas que se facilita en get_techniques_used_by_all_groups ya que queremos hacer un left join limpio directamente con technique_id
mitre_all_info_groups_df = pd.merge(mitre_all_info_groups_df, mitre_n2n_enterprise_techniques_tactics, left_on='technique_id', right_on='technique_id', how='left')


# Al realizar la unión de tácticas con técnicas se crearan más filas ya que cada técnica puede estar asociada a varias tácticas. Reemplazamos el nombre de algunas columnas generadas y eliminamos las duplicadas. 
mitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={'technique_x': 'technique','url_technique_x': 'url_technique'})
mitre_all_info_groups_df.drop('technique_y', axis=1, inplace=True)
mitre_all_info_groups_df.drop('url_technique_y', axis=1, inplace=True)
mitre_all_info_groups_df = mitre_all_info_groups_df.explode(['platform'])

print(f"Filas del df: {mitre_all_info_groups_df.shape[0]}.  Grupos unicos: {mitre_all_info_groups_df['group_id'].nunique()}. TTP's únicas: {mitre_all_info_groups_df['technique_id'].nunique()}. Platform únicas: {mitre_all_info_groups_df['platform'].nunique()}. Tácticas únicas: {mitre_all_info_groups_df['data_source'].nunique()}. Data Sources únicos: {mitre_all_info_groups_df['data_source'].nunique()}")

'''

'\n# Filtramos los items cuya técnica sea de tipo enterprise. La lista de grupos se reduce al no aparecer aquellos con técnica asociada y ahora con tipo enterprise.\nmitre_all_info_groups_df = get_techniques_used_by_all_groups_df[get_techniques_used_by_all_groups_df[\'technique_matrix\'].apply(lambda x: \'enterprise-attack\' in x)]\n# Hacemos una selección de columnas con las que trabajar\nmitre_all_info_groups_df = mitre_all_info_groups_df[[\'group_id\',\'group\',\'url\',\'technique_id\', \'technique\', \'platform\']]\n# Renombramos la url de la técnica\nmitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={\'url\': \'url_group\'})\n\n# Unimos con Data Sources para complementar la información\nmitre_all_info_groups_df = pd.merge(mitre_all_info_groups_df, n2n_techniques_data_sources_df, left_on=\'technique_id\', right_on=\'technique_id\', how=\'left\')\nmitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={\'url_technique_x\': \'url_technique\'})\n\n# Ampliamos el df por todos los campos necesarios para llegar a la relación N:N con el detalle de los data sources\nmitre_all_info_groups_df = mitre_all_info_groups_df.explode([\'data_source\',\'data_source_detail\'])\n\n# Unimos con Tácticas para complementar la información\n# Importante: No hemos añadido la información de tácticas que se facilita en get_techniques_used_by_all_groups ya que queremos hacer un left join limpio directamente con technique_id\nmitre_all_info_groups_df = pd.merge(mitre_all_info_groups_df, mitre_n2n_enterprise_techniques_tactics, left_on=\'technique_id\', right_on=\'technique_id\', how=\'left\')\n\n\n# Al realizar la unión de tácticas con técnicas se crearan más filas ya que cada técnica puede estar asociada a varias tácticas. Reemplazamos el nombre de algunas columnas generadas y eliminamos las duplicadas. \nmitre_all_info_groups_df = mitre_all_info_groups_df.rename(columns={\'technique_x\': \'technique\',\'url_technique_x\': \'url_technique\'})\nmitre_all_info_groups_df.drop(\'technique_y\', axis=1, inplace=True)\nmitre_all_info_groups_df.drop(\'url_technique_y\', axis=1, inplace=True)\nmitre_all_info_groups_df = mitre_all_info_groups_df.explode([\'platform\'])\n\nprint(f"Filas del df: {mitre_all_info_groups_df.shape[0]}.  Grupos unicos: {mitre_all_info_groups_df[\'group_id\'].nunique()}. TTP\'s únicas: {mitre_all_info_groups_df[\'technique_id\'].nunique()}. Platform únicas: {mitre_all_info_groups_df[\'platform\'].nunique()}. Tácticas únicas: {mitre_all_info_groups_df[\'data_source\'].nunique()}. Data Sources únicos: {mitre_all_info_groups_df[\'data_source\'].nunique()}")\n\n'

In [75]:
# Filtramos los items cuya técnica sea de tipo enterprise. La lista de grupos se reduce al no aparecer aquellos con técnica asociada y ahora con tipo enterprise.
mitre_n2n_techniques_groups_df = get_techniques_used_by_all_groups_df[get_techniques_used_by_all_groups_df['technique_matrix'].apply(lambda x: 'enterprise-attack' in x)]
# Hacemos una selección de columnas con las que trabajar
mitre_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df[['group_id','group','url','technique_id', 'technique']]
# Renombramos la url de la técnica
mitre_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df.rename(columns={'url': 'url_group'})

#Unimos con la tabla de técnicas para completar la información relativa a estas
mitre_n2n_techniques_groups_df = pd.merge(mitre_n2n_techniques_groups_df, get_enterprise_techniques_df[['technique_id', 'technique','url']], left_on='technique_id', right_on='technique_id', how='left')

# Renombramos la url de la técnica
mitre_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df.rename(columns={'technique_x': 'technique','url': 'url_technique'})
# Eliminamos la columna sobrante
mitre_n2n_techniques_groups_df.drop('technique_y', axis=1, inplace=True)

print(f"Filas del df: {mitre_n2n_techniques_groups_df.shape[0]}.  Grupos unicos: {mitre_n2n_techniques_groups_df['group_id'].nunique()}. TTP's únicas: {mitre_n2n_techniques_groups_df['technique_id'].nunique()}")

mitre_n2n_techniques_groups_df.head(2)

Filas del df: 3387.  Grupos unicos: 143. TTP's únicas: 421

,group_id,group,url_group,technique_id,technique,url_technique
0,G0001,Axiom,https://attack.mitre.org/groups/G0001,T1560,Archive Collected Data,https://attack.mitre.org/techniques/T1560
1,G0001,Axiom,https://attack.mitre.org/groups/G0001,T1583.002,DNS Server,https://attack.mitre.org/techniques/T1583/002

**[MITRE] Guardado Grupos - Técnicas N:N**

In [76]:
if save_to_file:
    save_df_as_csv(mitre_n2n_techniques_groups_df, '[MITRE-attactcti]_enterprise_techniques_groups', 'inter_groups_techniques')

Fichero generado correctamente [MITRE-attactcti]_enterprise_techniques_groups_03072024_0908h.csv

**[CP] Relación Grupos - Técnicas N:N**

In [77]:
cp_ttp_available = cp_ttps()
cp_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df[mitre_n2n_techniques_groups_df['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {cp_n2n_techniques_groups_df.shape[0]}. Grupos únicos: {cp_n2n_techniques_groups_df['group_id'].nunique()}. TTP's únicas: {cp_n2n_techniques_groups_df['technique_id'].nunique()}")
if save_to_file:
    save_df_as_csv(cp_n2n_techniques_groups_df, '[CP-attactcti]_enterprise_techniques_groups', 'inter_groups_techniques')

Filas del df: 3163. Grupos únicos: 142. TTP's únicas: 365
Fichero generado correctamente [CP-attactcti]_enterprise_techniques_groups_03072024_0908h.csv

**[NOCP] Relación Grupos - Técnicas N:N**

In [78]:
cp_ttp_available = cp_ttps()
nocp_n2n_techniques_groups_df = mitre_n2n_techniques_groups_df[~mitre_n2n_techniques_groups_df['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {nocp_n2n_techniques_groups_df.shape[0]}. Grupos únicos: {nocp_n2n_techniques_groups_df['group_id'].nunique()}. TTP's únicas: {nocp_n2n_techniques_groups_df['technique_id'].nunique()}")
if save_to_file:
    save_df_as_csv(nocp_n2n_techniques_groups_df, '[NOCP-attactcti]_enterprise_techniques_groups', 'inter_groups_techniques')

Filas del df: 224. Grupos únicos: 81. TTP's únicas: 56
Fichero generado correctamente [NOCP-attactcti]_enterprise_techniques_groups_03072024_0908h.csv

#### **3.2 Grupos - Técnicas (1:N)**

**[MITRE] Grupos - Técnicas (1:N)**

In [79]:
# Agregamos las columnas por la columna group_id
mitre_groups_with_techniques_df = mitre_n2n_techniques_groups_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'url_group':unique_list,
    'technique_id': unique_list,
    'technique': unique_list,
    'url_technique': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_groups_with_techniques_df, '[MITRE-attactcti]_groups_with_techniques', 'group_techniques_1N')

mitre_groups_with_techniques_df.head(2)

Fichero generado correctamente [MITRE-attactcti]_groups_with_techniques_03072024_0908h.csv

,group_id,group,url_group,technique_id,technique,url_technique
0,G0001,[Axiom],[https://attack.mitre.org/groups/G0001],"[T1546.008, T1583.003, T1203, T1560, T1189, T1...","[Exploitation for Client Execution, Remote Des...",[https://attack.mitre.org/techniques/T1563/002...
1,G0002,[Moafee],[https://attack.mitre.org/groups/G0002],[T1027.001],[Binary Padding],[https://attack.mitre.org/techniques/T1027/001]

In [80]:
print(f"[MITRE] Filas del df: {mitre_groups_with_techniques_df.shape[0]}. Grupos únicos: {mitre_groups_with_techniques_df['group_id'].nunique()}.")

[MITRE] Filas del df: 143. Grupos únicos: 143.

**[CP] Grupos - Técnicas (1:N)**

In [81]:
# Agregamos las columnas por la columna group_id
cp_groups_with_techniques_df = cp_n2n_techniques_groups_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'url_group':unique_list,
    'technique_id': unique_list,
    'technique': unique_list,
    'url_technique': unique_list
    })
if save_to_file:
    save_df_as_csv(cp_groups_with_techniques_df, '[CP-attactcti]_groups_with_techniques', 'group_techniques_1N')

cp_groups_with_techniques_df.head(2)

Fichero generado correctamente [CP-attactcti]_groups_with_techniques_03072024_0908h.csv

,group_id,group,url_group,technique_id,technique,url_technique
0,G0001,[Axiom],[https://attack.mitre.org/groups/G0001],"[T1546.008, T1203, T1560, T1189, T1021.001, T1...","[Exploitation for Client Execution, Remote Des...","[https://attack.mitre.org/techniques/T1553, ht..."
1,G0002,[Moafee],[https://attack.mitre.org/groups/G0002],[T1027.001],[Binary Padding],[https://attack.mitre.org/techniques/T1027/001]

In [82]:
print(f"[CP] Filas del df: {cp_groups_with_techniques_df.shape[0]}. Grupos únicos: {cp_groups_with_techniques_df['group_id'].nunique()}.")

[CP] Filas del df: 142. Grupos únicos: 142.

**[NOCP] Grupos - Técnicas (1:N)**

In [83]:
# Agregamos las columnas por la columna group_id
nocp_groups_with_techniques_df = nocp_n2n_techniques_groups_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'url_group':unique_list,
    'technique_id': unique_list,
    'technique': unique_list,
    'url_technique': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_groups_with_techniques_df, '[NOCP-attactcti]_groups_with_techniques', 'group_techniques_1N')

nocp_groups_with_techniques_df.head(2)

Fichero generado correctamente [NOCP-attactcti]_groups_with_techniques_03072024_0908h.csv

,group_id,group,url_group,technique_id,technique,url_technique
0,G0001,[Axiom],[https://attack.mitre.org/groups/G0001],"[T1583.003, T1583.002, T1584.005]","[Botnet, Virtual Private Server, DNS Server]",[https://attack.mitre.org/techniques/T1584/005...
1,G0003,[Cleaver],[https://attack.mitre.org/groups/G0003],[T1585.001],[Social Media Accounts],[https://attack.mitre.org/techniques/T1585/001]

In [84]:
print(f"[NOCP] Filas del df: {nocp_groups_with_techniques_df.shape[0]}. Grupos únicos: {nocp_groups_with_techniques_df['group_id'].nunique()}.")

[NOCP] Filas del df: 81. Grupos únicos: 81.

#### **3.3 Técnicas - Grupos (1:N)**

**[MITRE] Técnicas - Grupos (1:N)**

In [85]:
# Agregamos las columnas por la columna technique_id
mitre_techniques_with_groups_df = mitre_n2n_techniques_groups_df.groupby('technique_id', as_index=False).agg({
    'technique': unique_list,
    'url_technique': unique_list,
    'group':unique_list,
    'group_id':unique_list,
    'url_group':unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_techniques_with_groups_df, '[MITRE-attactcti]_techniques_with_groups_df', 'technique_groups_1N')

mitre_techniques_with_groups_df.head(2)

Fichero generado correctamente [MITRE-attactcti]_techniques_with_groups_df_03072024_0908h.csv

,technique_id,technique,url_technique,group,group_id,url_group
0,T1001.001,[Junk Data],[https://attack.mitre.org/techniques/T1001/001],[APT28],[G0007],[https://attack.mitre.org/groups/G0007]
1,T1001.002,[Steganography],[https://attack.mitre.org/techniques/T1001/002],[Axiom],[G0001],[https://attack.mitre.org/groups/G0001]

In [86]:
print(f"[MITRE] Filas del df: {mitre_techniques_with_groups_df.shape[0]}. TTP's únicas: {mitre_techniques_with_groups_df['technique_id'].nunique()}.")

[MITRE] Filas del df: 421. TTP's únicas: 421.

**[CP] Técnicas - Grupos (1:N)**

In [87]:
# Agregamos las columnas por la columna technique_id
cp_techniques_with_groups_df = cp_n2n_techniques_groups_df.groupby('technique_id', as_index=False).agg({
    'technique': unique_list,
    'url_technique': unique_list,
    'group':unique_list,
    'group_id':unique_list,
    'url_group':unique_list
    })
if save_to_file:
    save_df_as_csv(cp_techniques_with_groups_df, '[CP-attactcti]_techniques_with_groups_df', 'technique_groups_1N')

cp_techniques_with_groups_df.head(2)

Fichero generado correctamente [CP-attactcti]_techniques_with_groups_df_03072024_0908h.csv

,technique_id,technique,url_technique,group,group_id,url_group
0,T1001.002,[Steganography],[https://attack.mitre.org/techniques/T1001/002],[Axiom],[G0001],[https://attack.mitre.org/groups/G0001]
1,T1001.003,[Protocol Impersonation],[https://attack.mitre.org/techniques/T1001/003],"[Lazarus Group, Higaisa]","[G0126, G0032]","[https://attack.mitre.org/groups/G0126, https:..."

In [88]:
print(f"[CP] Filas del df: {cp_techniques_with_groups_df.shape[0]}. TTP's únicas: {cp_techniques_with_groups_df['technique_id'].nunique()}.")

[CP] Filas del df: 365. TTP's únicas: 365.

**[NOCP] Técnicas - Grupos (1:N)**

In [89]:
# Agregamos las columnas por la columna technique_id
nocp_techniques_with_groups_df = nocp_n2n_techniques_groups_df.groupby('technique_id', as_index=False).agg({
    'technique': unique_list,
    'url_technique': unique_list,
    'group':unique_list,
    'group_id':unique_list,
    'url_group':unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_techniques_with_groups_df, '[NOCP-attactcti]_techniques_with_groups_df', 'technique_groups_1N')

nocp_techniques_with_groups_df.head(2)

Fichero generado correctamente [NOCP-attactcti]_techniques_with_groups_df_03072024_0908h.csv

,technique_id,technique,url_technique,group,group_id,url_group
0,T1001.001,[Junk Data],[https://attack.mitre.org/techniques/T1001/001],[APT28],[G0007],[https://attack.mitre.org/groups/G0007]
1,T1016.002,[Wi-Fi Discovery],[https://attack.mitre.org/techniques/T1016/002],[Magic Hound],[G0059],[https://attack.mitre.org/groups/G0059]

In [90]:
print(f"[NOCP] Filas del df: {nocp_techniques_with_groups_df.shape[0]}. TTP's únicas: {nocp_techniques_with_groups_df['technique_id'].nunique()}.")

[NOCP] Filas del df: 56. TTP's únicas: 56.

### **4. SOFTWARE - TÉCNICAS**

#### **4.1 Tablas intermedias (N:N)**

In [91]:
software_df = get_software_df[['software_id','software','software_aliases','type','url','matrix']]
software_df = software_df.rename(columns={'url': 'url_software'})
if save_to_file:
    save_df_as_csv(software_df, '[MITRE-attactcti]_all_software', 'inter_software_techniques')
enterprise_software_df = software_df[software_df['matrix'].apply(lambda x: 'enterprise-attack' in x)]
enterprise_software_df.head(2)
if save_to_file:
    save_df_as_csv(enterprise_software_df, '[MITRE-attactcti]_enterprise_software', 'inter_software_techniques')

Fichero generado correctamente [MITRE-attactcti]_all_software_03072024_0908h.csv

Fichero generado correctamente [MITRE-attactcti]_enterprise_software_03072024_0908h.csv

PROBLEMA: No soy capaz de relacionar software con técnica.

get_techniques_used_by_software -> NO trae ninguna columna con la que poder identificar el software

get_enterprise_malware, get_enterprise_tools -> Atacando a través de la tipologia del software tampoco soy capaz de identificar ninguna relación

Solución: Tras probar directamente a stix y otras opciones he encontrado el método get_techniques_used_by_software(), al cual si se le pasa el objeto stix2.v20.sdo.Tool correspondiente como unico software del metodo get_software() como parametro este devolverá la tabla con las técnicas asociadas. Por lo tanto, mediante un bucle iremos recorriendo la lista de software (794) y se iran añadiendo a un df donde ademas de las técnicas incorporaremos la información relativa al SW.

In [92]:
results_df = pd.DataFrame(columns=['type', 'id', 'url', 'matrix', 'created', 'modified', 'created_by_ref',
       'modified_by_ref', 'external_references', 'object_marking_refs',
       'mitre_version', 'mitre_attack_spec_version', 'mitre_deprecated',
       'technique', 'technique_id', 'technique_description', 'tactic',
       'technique_detection', 'platform', 'data_sources', 'defense_bypassed',
       'permissions_required', 'effective_permissions', 'system_requirements',
       'network_requirements', 'remote_support', 'contributors', 'tactic_type',
       'impact_type', 'is_subtechnique', 'software_id', 'software',
       'software_aliases', 'software_description', 'software_type',
       'url_software', 'mitre_domains'])

In [93]:
# En esta parte del código obtenemos la lista de software y uno a uno se lo pasamos al método get_techniques_used_by_software que nos devolverá la tabla con las técnicas utilizadas por cada SW.
# Importante: Este código es lento, aproximadamente tarda 1,5 minutos por petición lo que hace que para los 795 items tarde aproximadamente 20 horas.
# Si se tiene que reejecutar esta parte tambien es posible que falle alguna conexión, en tal caso en lugar de empezar de 0 simplemente no ejecutar la celda anterior y modificar range(len(software)) por range(row, len(software))

software = lift.get_software()

for row in range(len(software)):

    info_row_techniques_software =  lift.get_techniques_used_by_software(software[row], stix_format=False)
    info_row_techniques_software_df = pd.json_normalize(info_row_techniques_software)


    # Recogemos info de software y la añadimos al df
    info_row_techniques_software_df['software_id'] = software[row].external_references[0].external_id

    info_row_techniques_software_df['software'] = software[row].name

    aliases = getattr(software[row], 'x_mitre_aliases', [])
    info_row_techniques_software_df['software_aliases'] = [aliases] * len(info_row_techniques_software_df)

    info_row_techniques_software_df['software_description'] = software[row].description

    info_row_techniques_software_df['software_type'] = software[row].type

    info_row_techniques_software_df['url_software'] = software[row].external_references[0].url
    
    domains = getattr(software[row], 'x_mitre_domains', [])
    info_row_techniques_software_df['mitre_domains'] = [domains] * len(info_row_techniques_software_df)

    print(f"Finalizado {row}: {software[row].name}")


    results_df = pd.concat([results_df,info_row_techniques_software_df])
# Filtramos técnicas deprecadas
results_df = results_df[(results_df['mitre_deprecated'] != 'True')]
# Filtramos SW enterprise
results_df = results_df[results_df['mitre_domains'].apply(lambda x: 'enterprise-attack' in x)]

results_df['url_technique'] = results_df['external_references'].apply(lambda x: x[0]['url'] if x else None)

if save_to_file:
    save_df_as_csv(results_df, '[MITRE]_n2n_main_techniques_software', 'inter_software_techniques')

[taxii2client.v20] [WARNING ] [2024-07-03 09:09:01,949] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:01,964] TAXII Server Response with different amount of objects! Setting per_request=595
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:04,578] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:04,578] TAXII Server Response with different amount of objects! Setting per_request=85
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:09,625] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:09,629] TAXII Server Response with different amount of objects! Setting per_request=111
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:14,939] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:14,939] TAXII Server Response with different amount of objects! Setting per_request=2
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:19,148] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:19,148] TAXII Server Response with different amount of objects! Setting per_request=28
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:29,608] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:32,659] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:34,380] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:36,579] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:40,101] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:40,116] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:42,942] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:42,959] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:46,287] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:46,311] TAXII Server Response with different amount of objects! Setting per_request=780
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:49,293] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:49,293] TAXII Server Response with different amount of objects! Setting per_request=187
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:52,517] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:09:52,526] TAXII Server Response with different amount of objects! Setting per_request=95

Finalizado 0: Pacu

[taxii2client.v20] [WARNING ] [2024-07-03 09:09:59,652] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:10:05,641] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.

KeyboardInterrupt:

**[MITRE] Guardado Software - Técnicas N:N**

In [ ]:
# Filtramos la información que necesitamos
mitre_n2n_techniques_software_df = results_df[['technique_id', 'technique', 'url_technique','software_id','software','software_description','software_type','url_software']]

if save_to_file:
    save_df_as_csv(mitre_n2n_techniques_software_df, '[MITRE-attactcti]_n2n_techniques_software', 'inter_software_techniques')

Fichero generado correctamente [MITRE]n2n_techniques_software14062024_1340h.csv

**[CP] Relación Software - Técnicas N:N**

In [ ]:
cp_ttp_available = cp_ttps()
cp_n2n_techniques_software_df = mitre_n2n_techniques_software_df[mitre_n2n_techniques_software_df['technique_id'].isin(cp_ttp_available)]
cp_n2n_techniques_software_df.shape

(8555, 8)

In [ ]:
if save_to_file:
    save_df_as_csv(cp_n2n_techniques_software_df, '[CP-attactcti]_n2n_techniques_software', 'inter_software_techniques')

Fichero generado correctamente [CP]n2n_techniques_software14062024_1348h.csv

**[NOCP] Relación Grupos - Técnicas N:N**

In [ ]:
nocp_n2n_techniques_software_df = mitre_n2n_techniques_software_df[~mitre_n2n_techniques_software_df['technique_id'].isin(cp_ttp_available)]
nocp_n2n_techniques_software_df.shape

(522, 8)

In [ ]:
if save_to_file:
    save_df_as_csv(nocp_n2n_techniques_software_df, '[NOCP-attactcti]_n2n_techniques_software', 'inter_software_techniques')

Fichero generado correctamente [NOCP]n2n_techniques_software14062024_1348h.csv

#### **4.2 Técnica - Software (1:N)**

**[MITRE] Técnica - Software (1:N)**

In [ ]:
# Agregamos las columnas por la columna techniques_id
mitre_technique_with_software_df = mitre_n2n_techniques_software_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_technique_with_software_df, '[MITRE-attactcti]_technique_with_software', 'technique_software_1N')

mitre_technique_with_software_df.head(2)

Fichero generado correctamente [MITRE]_technique_with_software14062024_1352h.csv

,technique_id,technique,url_technique,software_id,software,software_description,software_type,url_software
0,T0800,[Activate Firmware Update Mode],[https://attack.mitre.org/techniques/T0800],[S0604],[Industroyer],[[Industroyer](https://attack.mitre.org/softwa...,[malware],[https://attack.mitre.org/software/S0604]
1,T0801,[Monitor Process State],[https://attack.mitre.org/techniques/T0801],"[S0604, S0603, S1072]","[Industroyer, Industroyer2, Stuxnet]",[[Stuxnet](https://attack.mitre.org/software/S...,[malware],"[https://attack.mitre.org/software/S0604, http..."

In [ ]:
print(f"[MITRE] Filas del df: {mitre_technique_with_software_df.shape[0]}. Técnicas únicas: {mitre_technique_with_software_df['technique_id'].nunique()}.")

[MITRE] Filas del df: 489. Técnicas únicas: 489.

**[CP] Técnica - Software (1:N)**

In [ ]:
# Agregamos las columnas por la columna techniques_id
cp_technique_with_software_df = cp_n2n_techniques_software_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(cp_technique_with_software_df, '[CP-attactcti]_technique_with_software', 'technique_software_1N')

cp_technique_with_software_df.head(2)

Fichero generado correctamente [CP]_technique_with_software14062024_1356h.csv

,technique_id,technique,url_technique,software_id,software,software_description,software_type,url_software
0,T0802,[Automated Collection],[https://attack.mitre.org/techniques/T0802],"[S0604, S1072, S0093]","[Backdoor.Oldrea, Industroyer, Industroyer2]",[[Backdoor.Oldrea](https://attack.mitre.org/so...,[malware],"[https://attack.mitre.org/software/S0604, http..."
1,T0807,[Command-Line Interface],[https://attack.mitre.org/techniques/T0807],"[S0604, S0603]","[Industroyer, Stuxnet]",[[Industroyer](https://attack.mitre.org/softwa...,[malware],"[https://attack.mitre.org/software/S0604, http..."

In [ ]:
print(f"[CP] Filas del df: {cp_technique_with_software_df.shape[0]}. TTP's únicas: {cp_technique_with_software_df['technique_id'].nunique()}.")

[CP] Filas del df: 412. TTP's únicas: 412.

**[NOCP] Técnica - Software (1:N)**

In [ ]:
# Agregamos las columnas por la columna techniques_id
nocp_technique_with_software_df = nocp_n2n_techniques_software_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(nocp_technique_with_software_df, '[NOCP-attactcti]_technique_with_software', 'technique_software_1N')

nocp_technique_with_software_df.head(2)

Fichero generado correctamente [NOCP]_technique_with_software14062024_1358h.csv

,technique_id,technique,url_technique,software_id,software,software_description,software_type,url_software
0,T0800,[Activate Firmware Update Mode],[https://attack.mitre.org/techniques/T0800],[S0604],[Industroyer],[[Industroyer](https://attack.mitre.org/softwa...,[malware],[https://attack.mitre.org/software/S0604]
1,T0801,[Monitor Process State],[https://attack.mitre.org/techniques/T0801],"[S0604, S0603, S1072]","[Industroyer, Industroyer2, Stuxnet]",[[Stuxnet](https://attack.mitre.org/software/S...,[malware],"[https://attack.mitre.org/software/S0604, http..."

In [ ]:
print(f"[NOCP] Filas del df: {nocp_technique_with_software_df.shape[0]}. TTP's únicas: {nocp_technique_with_software_df['technique_id'].nunique()}.")

[NOCP] Filas del df: 77. TTP's únicas: 77.

#### **4.3 Software - Técnicas (1:N)**

**[MITRE] Software - Técnicas (1:N)**

In [ ]:
mitre_software_with_techniques_df = mitre_n2n_techniques_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list,
    'technique_id':unique_list,
    'technique': unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(mitre_software_with_techniques_df, '[MITRE-attactcti]_software_with_techniques', 'software_techniques_1N')

mitre_software_with_techniques_df.head(2)

Fichero generado correctamente [MITRE]_software_with_techniques14062024_1402h.csv

,software_id,software,software_description,software_type,url_software,technique_id,technique,url_technique
0,S0001,[Trojan.Mebromi],[[Trojan.Mebromi](https://attack.mitre.org/sof...,[malware],[https://attack.mitre.org/software/S0001],[T1542.001],[System Firmware],[https://attack.mitre.org/techniques/T1542/001]
1,S0002,[Mimikatz],[[Mimikatz](https://attack.mitre.org/software/...,[tool],[https://attack.mitre.org/software/S0002],"[T1649, T1003.006, T1558.001, T1003.002, T1552...","[Security Account Manager, Pass the Hash, SID-...",[https://attack.mitre.org/techniques/T1134/005...

In [ ]:
print(f"[MITRE] Filas del df: {mitre_software_with_techniques_df.shape[0]}. Software únicos: {mitre_software_with_techniques_df['software_id'].nunique()}.")

[MITRE] Filas del df: 677. Software únicos: 677.

**[CP] Software - Técnicas (1:N)**

In [ ]:
cp_software_with_techniques_df = cp_n2n_techniques_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list,
    'technique_id':unique_list,
    'technique': unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(cp_software_with_techniques_df, '[CP-attactcti]_software_with_techniques', 'software_techniques_1N')

cp_software_with_techniques_df.head(2)

Fichero generado correctamente [CP]_software_with_techniques14062024_1403h.csv

,software_id,software,software_description,software_type,url_software,technique_id,technique,url_technique
0,S0001,[Trojan.Mebromi],[[Trojan.Mebromi](https://attack.mitre.org/sof...,[malware],[https://attack.mitre.org/software/S0001],[T1542.001],[System Firmware],[https://attack.mitre.org/techniques/T1542/001]
1,S0002,[Mimikatz],[[Mimikatz](https://attack.mitre.org/software/...,[tool],[https://attack.mitre.org/software/S0002],"[T1649, T1003.006, T1558.001, T1003.002, T1552...","[Security Account Manager, Pass the Hash, SID-...",[https://attack.mitre.org/techniques/T1134/005...

In [ ]:
print(f"[CP] Filas del df: {cp_software_with_techniques_df.shape[0]}. Software únicos: {cp_software_with_techniques_df['software_id'].nunique()}.")

[CP] Filas del df: 674. Software únicos: 674.

**[NOCP] Software - Técnicas (1:N)**

In [ ]:
nocp_software_with_techniques_df = nocp_n2n_techniques_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_description': unique_list,
    'software_type': unique_list,
    'url_software': unique_list,
    'technique_id':unique_list,
    'technique': unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(nocp_software_with_techniques_df, '[NOCP-attactcti]_software_with_techniques', 'software_techniques_1N')

nocp_software_with_techniques_df.head(2)

Fichero generado correctamente [NOCP]_software_with_techniques_14062024_1405h.csv

,software_id,software,software_description,software_type,url_software,technique_id,technique,url_technique
0,S0003,[RIPTIDE],[[RIPTIDE](https://attack.mitre.org/software/S...,[malware],[https://attack.mitre.org/software/S0003],[T1573.001],[Symmetric Cryptography],[https://attack.mitre.org/techniques/T1573/001]
1,S0009,[Hikit],[[Hikit](https://attack.mitre.org/software/S00...,[malware],[https://attack.mitre.org/software/S0009],[T1573.001],[Symmetric Cryptography],[https://attack.mitre.org/techniques/T1573/001]

In [ ]:
print(f"[NOCP] Filas del df: {nocp_software_with_techniques_df.shape[0]}. Software únicos: {nocp_software_with_techniques_df['software_id'].nunique()}.")

[NOCP] Filas del df: 323. Software únicos: 323.

### **5. GRUPOS - SOFTWARE**

#### **5.1 Tablas intermedias (N:N)**

In [94]:
# Creamos un dataframe vacío con los campos a rellenar
results_df = pd.DataFrame(columns=['type', 'id', 'url', 'matrix', 'created', 'modified', 'created_by_ref',
       'modified_by_ref', 'external_references', 'object_marking_refs',
       'mitre_version', 'mitre_attack_spec_version', 'mitre_deprecated',
       'software', 'software_id', 'software_description', 'software_labels',
       'software_aliases', 'software_platform', 'old_software_id',
       'contributors', 'group_id', 'group', 'group_description',
       'group_aliases', 'url_group'])

In [112]:
# En este bucle vamos a ir recorriendo cada uno de los grupo y retornando todas los sotfware utilizados por estos. Iremos uniendo toda la información en el df anteriormente creado vacío.
for row in range(row, len(get_groups_df)):
    temp_software_by_group = lift.get_software_used_by_group(get_groups_df.iloc[row], stix_format=False)
    temp_software_by_group_df = pd.json_normalize(temp_software_by_group)

    temp_software_by_group_df['group_id'] = get_groups_df.iloc[row].group_id
    temp_software_by_group_df['group'] = get_groups_df.iloc[row].group
    temp_software_by_group_df['group_description'] = get_groups_df.iloc[row].group_description

    aliases = get_groups_df.iloc[row].group_aliases
    temp_software_by_group_df['group_aliases'] = [aliases] * len(temp_software_by_group_df)

    domains = get_groups_df.iloc[row].matrix
    temp_software_by_group_df['matrix'] = [domains] * len(temp_software_by_group_df)

    temp_software_by_group_df['url_group'] = get_groups_df.iloc[row].url
    temp_software_by_group_df['type'] = get_groups_df.iloc[row].type

    results_df = pd.concat([results_df, temp_software_by_group_df])

    print(f"Finalizado {row}: {get_groups_df.iloc[row].group}")

# Eliminamos duplicados, no debería darse ninguno pero en caso de ejecutar por lotes (cuando se pierde la conexión) es posible que por error humano dupliquemos alguna fila
results_df = results_df.drop_duplicates(subset=['group_id', 'software_id'], keep='last')
# Renombramos la columna url
results_df = results_df.rename(columns={'url': 'url_software'})

[taxii2client.v20] [WARNING ] [2024-07-03 09:12:30,229] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:12:52,397] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:13:12,645] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:13:21,702] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:13:32,036] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:13:32,051] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-07-03 09:13:38,885] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:13:38,896] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-07-03 09:13:42,246] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:13:42,247] TAXII Server Response with different amount of objects! Setting per_request=1

Finalizado 1: Moafee

[taxii2client.v20] [WARNING ] [2024-07-03 09:13:55,618] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:06,691] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:13,493] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:16,664] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:20,858] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:20,889] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:24,832] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:24,846] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:28,299] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:28,300] TAXII Server Response with different amount of objects! Setting per_request=4

Finalizado 2: Cleaver

[taxii2client.v20] [WARNING ] [2024-07-03 09:14:42,665] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:54,188] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:14:59,113] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:15:03,785] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:15:07,568] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:15:07,580] TAXII Server Response with different amount of objects! Setting per_request=1644
[taxii2client.v20] [WARNING ] [2024-07-03 09:15:12,931] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:15:12,947] TAXII Server Response with different amount of objects! Setting per_request=1350
[taxii2client.v20] [WARNING ] [2024-07-03 09:15:18,469] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-07-03 09:15:18,469] TAXII Server Response with different amount of objects! Setting per_request=10

KeyboardInterrupt:

**[MITRE] Guardado Grupos - Software N:N**

Nota: En este caso no disponemos de un filtro que aplique sobre ninguno de las dos categorías directamente por lo que solo generaremos outputs MITRE.

In [ ]:
n2n_groups_software_df = results_df[['group_id', 'group', 'group_aliases', 'url_group', 'software_id', 'software', 'software_aliases', 'url_software']]
print(f"[MITRE] Filas del df: {n2n_groups_software_df.shape[0]}. Software únicos: {n2n_groups_software_df['software_id'].nunique()}. Grupos únicos: {n2n_groups_software_df['group_id'].nunique()}.")

[MITRE] Filas del df: 932. Software únicos: 509. Grupos únicos: 138.

In [ ]:
# Guardamos la relación entre grupos y software completa:
if save_to_file:
    save_df_as_csv(n2n_groups_software_df, '[MITRE-attactcti]_n2n_groups_software', 'inter_groups_software')

Fichero generado correctamente [MITRE]_n2n_groups_software_17062024_1422h.csv

In [ ]:

n2n_enterprise_groups_software_df = results_df[['group_id', 'group', 'group_aliases', 'url_group', 'software_id', 'software', 'software_aliases', 'url_software', 'matrix']]
n2n_enterprise_groups_software_df = n2n_enterprise_groups_software_df[n2n_enterprise_groups_software_df['matrix'].apply(lambda x: 'enterprise-attack' in x)]
n2n_enterprise_groups_software_df.drop('matrix', axis=1, inplace=True)
if save_to_file:
    save_df_as_csv(n2n_enterprise_groups_software_df, '[MITRE-attactcti]_n2n_enterprise_groups_software', 'inter_groups_software')

Fichero generado correctamente [MITRE]_n2n_enterprise_groups_software_17062024_1422h.csv

#### **5.2 Grupo - Software (1:N)**

In [ ]:
# Agregamos las columnas por la columna group_id
mitre_groups_with_software_df = n2n_groups_software_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'group_aliases': unique_list,
    'url_group': unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_aliases': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_groups_with_software_df, '[MITRE]_groups_with_software', 'group_software_1N')

mitre_groups_with_software_df.head(2)

Fichero generado correctamente [MITRE]_groups_with_software_17062024_1422h.csv

,group_id,group,group_aliases,url_group,software_id,software,software_aliases,url_software
0,G0001,[Axiom],"[(Axiom, Group 72)]",[https://attack.mitre.org/groups/G0001],"[S0009, S0412, S0203, S0012, S0021, S0013, S06...","[gh0st RAT, Hydraq, Zox, ZxShell, Hikit, Derus...","[(Derusbi, PHOTO), (Zox, Gresim, ZoxRPC, ZoxPN...","[https://attack.mitre.org/software/S0412, http..."
1,G0002,[Moafee],"[(Moafee,)]",[https://attack.mitre.org/groups/G0002],[S0012],[PoisonIvy],"[(PoisonIvy, Breut, Poison Ivy, Darkmoon)]",[https://attack.mitre.org/software/S0012]

In [ ]:
# Agregamos las columnas por la columna group_id
mitre_enterprise_groups_with_software_df = n2n_enterprise_groups_software_df.groupby('group_id', as_index=False).agg({
    'group':unique_list,
    'group_aliases': unique_list,
    'url_group': unique_list,
    'software_id': unique_list,
    'software': unique_list,
    'software_aliases': unique_list,
    'url_software': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_enterprise_groups_with_software_df, '[MITRE-attactcti]_enterprise_groups_with_software', 'group_software_1N')

mitre_enterprise_groups_with_software_df.head(2)

Fichero generado correctamente [MITRE]_enterprise_groups_with_software_17062024_1422h.csv

,group_id,group,group_aliases,url_group,software_id,software,software_aliases,url_software
0,G0001,[Axiom],"[(Axiom, Group 72)]",[https://attack.mitre.org/groups/G0001],"[S0009, S0412, S0203, S0012, S0021, S0013, S06...","[gh0st RAT, Hydraq, Zox, ZxShell, Hikit, Derus...","[(Derusbi, PHOTO), (Zox, Gresim, ZoxRPC, ZoxPN...","[https://attack.mitre.org/software/S0412, http..."
1,G0002,[Moafee],"[(Moafee,)]",[https://attack.mitre.org/groups/G0002],[S0012],[PoisonIvy],"[(PoisonIvy, Breut, Poison Ivy, Darkmoon)]",[https://attack.mitre.org/software/S0012]

#### **5.3 Software - Grupo (1:N)**

In [ ]:
# Agregamos las columnas por la columna group_id
mitre_software_with_groups_df = n2n_groups_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_aliases': unique_list,
    'url_software': unique_list,
    'group_id': unique_list,
    'group':unique_list,
    'group_aliases': unique_list,
    'url_group': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_software_with_groups_df, '[MITRE-attactcti]_software_with_groups', 'software_groups_1N')

mitre_software_with_groups_df.head(2)

Fichero generado correctamente [MITRE]_software_with_groups_17062024_1422h.csv

,software_id,software,software_aliases,url_software,group_id,group,group_aliases,url_group
0,S0002,[Mimikatz],"[(Mimikatz,)]",[https://attack.mitre.org/software/S0002],"[G0006, G0059, G0049, G1024, G0060, G0045, G00...","[GALLIUM, Scattered Spider, APT38, APT41, Tont...","[(Leafminer, Raspite), (Wizard Spider, UNC1878...","[https://attack.mitre.org/groups/G0010, https:..."
1,S0003,[RIPTIDE],"[(RIPTIDE,)]",[https://attack.mitre.org/software/S0003],[G0005],[APT12],"[(APT12, IXESHE, DynCalc, Numbered Panda, DNSC...",[https://attack.mitre.org/groups/G0005]

In [ ]:
# Agregamos las columnas por la columna group_id
mitre_enterprise_software_with_groups_df = n2n_enterprise_groups_software_df.groupby('software_id', as_index=False).agg({
    'software': unique_list,
    'software_aliases': unique_list,
    'url_software': unique_list,
    'group_id': unique_list,
    'group':unique_list,
    'group_aliases': unique_list,
    'url_group': unique_list
    })
if save_to_file:
    save_df_as_csv(mitre_enterprise_software_with_groups_df, '[MITRE]_enterprise_software_with_groups', 'software_groups_1N')

mitre_enterprise_software_with_groups_df.head(2)

Fichero generado correctamente [MITRE]_enterprise_software_with_groups_17062024_1423h.csv

,software_id,software,software_aliases,url_software,group_id,group,group_aliases,url_group
0,S0002,[Mimikatz],"[(Mimikatz,)]",[https://attack.mitre.org/software/S0002],"[G0006, G0059, G0049, G1024, G0060, G0045, G00...","[GALLIUM, Scattered Spider, APT38, APT41, Tont...","[(Leafminer, Raspite), (Wizard Spider, UNC1878...","[https://attack.mitre.org/groups/G0010, https:..."
1,S0003,[RIPTIDE],"[(RIPTIDE,)]",[https://attack.mitre.org/software/S0003],[G0005],[APT12],"[(APT12, IXESHE, DynCalc, Numbered Panda, DNSC...",[https://attack.mitre.org/groups/G0005]

### **6. PLATAFORMAS - TÉCNICAS**

#### **6.1 Tablas intermedias (N:N)**

In [98]:
mitre_n2n_enterprise_techniques_platforms_df = get_enterprise_techniques_df[['technique_id', 'technique', 'url', 'platform']]
mitre_n2n_enterprise_techniques_platforms_df = mitre_n2n_enterprise_techniques_platforms_df.rename(columns={'url': 'url_technique'})
mitre_n2n_enterprise_techniques_platforms_df = mitre_n2n_enterprise_techniques_platforms_df.explode('platform')
print(f"Filas del df: {mitre_n2n_enterprise_techniques_platforms_df.shape[0]}. TTP's únicas: {mitre_n2n_enterprise_techniques_platforms_df['technique_id'].nunique()}. Plataformas únicas: {mitre_n2n_enterprise_techniques_platforms_df['platform'].nunique()}")

Filas del df: 1654. TTP's únicas: 637. Plataformas únicas: 11

**[MITRE] Técnicas - Plataformas (N:N)**

In [99]:
if save_to_file:
    save_df_as_csv(mitre_n2n_enterprise_techniques_platforms_df, '[MITRE-attactcti]_n2n_enterprise_techniques_platforms', 'inter_techniques_platforms')

Fichero generado correctamente [MITRE-attactcti]_n2n_enterprise_techniques_platforms_03072024_0911h.csv

**[CP] Técnicas - Plataformas (N:N)**

In [100]:
cp_ttp_available = cp_ttps()
cp_n2n_enterprise_techniques_platforms_df = mitre_n2n_enterprise_techniques_platforms_df[mitre_n2n_enterprise_techniques_platforms_df['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {cp_n2n_enterprise_techniques_platforms_df.shape[0]}. TTP's únicas: {cp_n2n_enterprise_techniques_platforms_df['technique_id'].nunique()}. Plataformas únicas: {cp_n2n_enterprise_techniques_platforms_df['platform'].nunique()}")
if save_to_file:
    save_df_as_csv(cp_n2n_enterprise_techniques_platforms_df, '[CP-attactcti]_n2n_enterprise_techniques_platforms', 'inter_techniques_platforms')

Filas del df: 1436. TTP's únicas: 521. Plataformas únicas: 11
Fichero generado correctamente [CP-attactcti]_n2n_enterprise_techniques_platforms_03072024_0911h.csv

**[NOCP] Técnicas - Plataformas (N:N)**

In [101]:
nocp_ttp_available = cp_ttps()
nocp_n2n_enterprise_techniques_platforms_df = mitre_n2n_enterprise_techniques_platforms_df[~mitre_n2n_enterprise_techniques_platforms_df['technique_id'].isin(cp_ttp_available)]
print(f"Filas del df: {nocp_n2n_enterprise_techniques_platforms_df.shape[0]}. TTP's únicas: {nocp_n2n_enterprise_techniques_platforms_df['technique_id'].nunique()}. Plataformas únicas: {nocp_n2n_enterprise_techniques_platforms_df['platform'].nunique()}")
if save_to_file:
    save_df_as_csv(nocp_n2n_enterprise_techniques_platforms_df, '[NOCP-attactcti]_n2n_enterprise_techniques_platforms', 'inter_techniques_platforms')

Filas del df: 218. TTP's únicas: 116. Plataformas únicas: 11
Fichero generado correctamente [NOCP-attactcti]_n2n_enterprise_techniques_platforms_03072024_0911h.csv

#### **6.2 Técnica - Plataformas (1:N)**

**[MITRE] Técnica - Plataformas (1:N)**

In [102]:
# Agregamos las columnas por la columna technique_id
mitre_technique_with_platforms_df = mitre_n2n_enterprise_techniques_platforms_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'platform': unique_list
    })

if save_to_file:
    save_df_as_csv(mitre_technique_with_platforms_df, '[MITRE-attactcti]_enterprise_technique_with_platforms', 'technique_platforms_1N')

Fichero generado correctamente [MITRE-attactcti]_enterprise_technique_with_platforms_03072024_0911h.csv

**[CP] Técnica - Plataformas (1:N)**

In [103]:
# Agregamos las columnas por la columna technique_id
cp_technique_with_platforms_df = cp_n2n_enterprise_techniques_platforms_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'platform': unique_list
    })

if save_to_file:
    save_df_as_csv(cp_technique_with_platforms_df, '[CP-attactcti]_enterprise_technique_with_platforms', 'technique_platforms_1N')

Fichero generado correctamente [CP-attactcti]_enterprise_technique_with_platforms_03072024_0911h.csv

**[NOCP] Técnica - Plataformas (1:N)**

In [104]:
# Agregamos las columnas por la columna technique_id
nocp_technique_with_platforms_df = nocp_n2n_enterprise_techniques_platforms_df.groupby('technique_id', as_index=False).agg({
    'technique':unique_list,
    'url_technique':unique_list,
    'platform': unique_list
    })

if save_to_file:
    save_df_as_csv(nocp_technique_with_platforms_df, '[NOCP-attactcti]_enterprise_technique_with_platforms', 'technique_platforms_1N')

Fichero generado correctamente [NOCP-attactcti]_enterprise_technique_with_platforms_03072024_0911h.csv

#### **6.3 Plataforma - Técnicas (1:N)**

**[MITRE] Plataforma - Técnicas (1:N)**

In [105]:
# Agregamos las columnas por la columna technique_id
mitre_platform_with_techniques_df = mitre_n2n_enterprise_techniques_platforms_df.groupby('platform', as_index=False).agg({
    'technique_id':unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(mitre_platform_with_techniques_df, '[MITRE-attactcti]_enterprise_platform_with_techniques', 'platform_techniques_1N')

Fichero generado correctamente [MITRE-attactcti]_enterprise_platform_with_techniques_03072024_0911h.csv

**[CP] Plataforma - Técnicas (1:N)**

In [106]:
# Agregamos las columnas por la columna technique_id
cp_platform_with_techniques_df = cp_n2n_enterprise_techniques_platforms_df.groupby('platform', as_index=False).agg({
    'technique_id':unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(cp_platform_with_techniques_df, '[CP-attactcti]_enterprise_platform_with_techniques', 'platform_techniques_1N')

Fichero generado correctamente [CP-attactcti]_enterprise_platform_with_techniques_03072024_0911h.csv

**[NOCP] Plataforma - Técnicas (1:N)**

In [107]:
# Agregamos las columnas por la columna technique_id
nocp_platform_with_techniques_df = nocp_n2n_enterprise_techniques_platforms_df.groupby('platform', as_index=False).agg({
    'technique_id':unique_list,
    'technique':unique_list,
    'url_technique':unique_list
    })

if save_to_file:
    save_df_as_csv(nocp_platform_with_techniques_df, '[NOCP-attactcti]_enterprise_platform_with_techniques', 'platform_techniques_1N')

Fichero generado correctamente [NOCP-attactcti]_enterprise_platform_with_techniques_03072024_0911h.csv

### **BONUS. LISTADO DE REGLAS DE DETECCIÓN POR TÉCNICA (TTP ID)**

**Importante:** Debe haberse ejecutado previamente el codigo de obtención de las reglas de detección y clasificación por TTP

In [108]:
def get_rules_from_path(path):
    # Listas para almacenar los resultados
    sources = []
    ttps = []
    file_names = []
    file_extension = []

    # Recorremos la path accediendo a cada directorio para poder añadirlo a una lista
    for root, dirs, files in os.walk(path):
        for file in files:
            # Extensión del archivo
            ext = os.path.splitext(file)[1].lower()
            if ext in ['.csv', '.yaml','.yml', '.toml', '.md', '.txt', '.yar']:
                # Última y penúltima subcarpeta
                path_split = root.split(os.sep)
                ttp = path_split[-1]
                source = path_split[-2] if len(path_split) > 1 else ''
                # Añadimos elementos a las listas
                sources.append(source)
                ttps.append(ttp)
                file_names.append(file)
                file_extension.append(ext)

    df = pd.DataFrame({'source': sources, 'TTP': ttps, 'rule': file_names, 'file_extension': file_extension})

    return df

In [109]:
technique_matrix = '' # Dejamos preparado para el futuro cercano la posibilidad de lectura de tecnicas por matriz
path = os.path.join(os.path.dirname(os.getcwd()), 'download_ttps\saved', technique_matrix)
ttp_rules_df = get_rules_from_path(path)
if save_to_file:
    save_df_as_csv(ttp_rules_df, '[CP-attactcti]_ttp_rules')

Fichero generado correctamente [CP-attactcti]_ttp_rules_03072024_0911h.csv

#### **Excepcional: pedido listado de técnicas, tácticas y reglas de detección**

In [110]:
ttp_rules_df.head(2)

Empty DataFrame
Columns: [source, TTP, rule, file_extension]
Index: []

In [111]:
count_ttp_rules_df = ttp_rules_df.groupby('TTP').size().reset_index(name='num_rules')
count_ttp_rules_df['TTP'] = count_ttp_rules_df['TTP'].str.upper()
count_ttp_rules_df.head(2)

AttributeError: Can only use .str accessor with string values!

**MITRE**

In [ ]:
mitre_n2n_techniques_tactics_rules = pd.merge(mitre_n2n_enterprise_techniques_tactics, count_ttp_rules_df, how='left', left_on='technique_id', right_on='TTP')
mitre_n2n_techniques_tactics_rules['num_rules'] = mitre_n2n_techniques_tactics_rules['num_rules'].fillna(0).astype(int)
mitre_n2n_techniques_tactics_rules = mitre_n2n_techniques_tactics_rules[['technique_id', 'technique', 'tactic', 'num_rules']]
mitre_n2n_techniques_tactics_rules = mitre_n2n_techniques_tactics_rules.sort_values(by='num_rules', ascending=False)
save_df_as_csv(mitre_n2n_techniques_tactics_rules, '[MITRE]_techniques_tactics_rules')

,tactic,technique_id,technique,url_technique,tactic_id,tactic_description,url_tactic,TTP,num_rules
0,collection,T1074.002,Remote Data Staging,https://attack.mitre.org/techniques/T1074/002,TA0009,The adversary is trying to gather data of inte...,https://attack.mitre.org/tactics/TA0009,T1074.002,2
1,collection,T1602.001,SNMP (MIB Dump),https://attack.mitre.org/techniques/T1602/001,TA0009,The adversary is trying to gather data of inte...,https://attack.mitre.org/tactics/TA0009,T1602.001,3
2,collection,T1602,Data from Configuration Repository,https://attack.mitre.org/techniques/T1602,TA0009,The adversary is trying to gather data of inte...,https://attack.mitre.org/tactics/TA0009,T1602,4

**CYBERPROOF**

In [ ]:
cp_n2n_techniques_tactics_rules = pd.merge(cp_n2n_enterprise_techniques_tactics, count_ttp_rules_df, how='left', left_on='technique_id', right_on='TTP')
cp_n2n_techniques_tactics_rules['num_rules'] = cp_n2n_techniques_tactics_rules['num_rules'].fillna(0).astype(int)
cp_n2n_techniques_tactics_rules = cp_n2n_techniques_tactics_rules[['technique_id', 'technique', 'tactic', 'num_rules']]
cp_n2n_techniques_tactics_rules = cp_n2n_techniques_tactics_rules.sort_values(by='num_rules', ascending=False)
save_df_as_csv(cp_n2n_techniques_tactics_rules, '[CP-attactcti]_techniques_tactics_rules')

Fichero generado correctamente [CP]_techniques_tactics_rules_19062024_1735h.csv