In [41]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
Created on 2024-08-14
Last modified on 2024-08-14
@author: Juan Enrique López
@description: Jupyter Notebook cuyo cometido es generar archivos md con la información relativa a las relaciones entre las propiedades Mitre con la finalidad de filtrar vía Obsidian.
Por el momento solo se generan las relaciones desde la vista 1:N donde 1 es la propiedad Mitre y N las técnicas asociadas

'''

'\nCreated on 2024-08-14\nLast modified on 2024-08-14\n@author: Juan Enrique López\n@description: Jupyter Notebook cuyo cometido es generar archivos md con la información relativa a las relaciones entre las propiedades Mitre con la finalidad de filtrar vía Obsidian.\nPor el momento solo se generan las relaciones desde la vista 1:N donde 1 es la propiedad Mitre y N las técnicas asociadas\n\n'

**IMPORTANTE - REQUERIMIENTOS PREVIOS**

- Requiere haber ejecutado previamente dentro de este mismo módulo **mitre_relationships** el notebook **[stix2]_mitre_relationships.ipynb** y disponer de la carpeta "outputs/stix2".

In [42]:
import os
import pandas as pd
import shutil
# import requests
from stix2 import Filter, MemoryStore

#### **Parámetros**

In [43]:
mitre_domain = 'enterprise' # enterprise, mobile, ics
input_path = os.path.join(os.getcwd(),'outputs', 'stix2', mitre_domain, 'relations')

In [44]:
output_folder = os.path.join(os.getcwd(),'outputs')
output_folder

'c:\\Users\\jelopez\\Documents\\CyberProof\\python\\develop\\mitre_relationships\\outputs'

#### **Funciones**

In [45]:
def format_cols_for_md(column):
    '''
    Función para aplicar los reemplazos que permitan en el .md relacionar elementos.
    '''
    column = column.apply(lambda x: f'[[{x}]]')
    return column

In [46]:
def replace_chars_add_bracket(column):
    '''
    Función encargada de reemplazar caracteres en una columna dada con el objetivo añadir una lista de elementos enlazados para Obsidian.
    '''
    if column.dtype == "object":  # Verifica que la columna sea de tipo string
        column = column.str.replace("['", '[[', regex=False)
        column = column.str.replace("']", ']]', regex=False)
        column = column.str.replace("', '", ']] [[', regex=False)
    return column

In [47]:
def replace_chars(column):
    '''
    Función encargada de reemplazar caracteres en una columna dada con el objetivo de suprimir caracteres que enlazan dentro de Obsidian.
    '''
    if column.dtype == "object":  # Verifica que la columna sea de tipo string
        column = column.str.replace("['", '', regex=False)
        column = column.str.replace("']", '', regex=False)
        column = column.str.replace("'", '', regex=False)
    return column

#### **Ejecución**

##### **1. Tácticas - Técnicas**

In [48]:
input_file = f'[MITRE]_{mitre_domain}_techniques_tactic_N1.csv'
tactics_relations_df = pd.read_csv(os.path.join(input_path, 'techniques_tactics', input_file), sep=';', quotechar='"')
tactics_relations_df.head(3)

,tactic_ID,tactic,technique_ID,technique
0,TA0001,['Initial Access'],"['T1566.004', 'T1078.002', 'T1190', 'T1566', '...","['Trusted Relationship', 'Drive-by Compromise'..."
1,TA0002,['Execution'],"['T1059.009', 'T1053.002', 'T1047', 'T1204.002...","['Windows Management Instrumentation', 'Deploy..."
2,TA0003,['Persistence'],"['T1546.006', 'T1098.001', 'T1078.002', 'T1574...","['Registry Run Keys / Startup Folder', 'Outloo..."

In [49]:
add_bracket = ['tactic_ID','platform_ID','platform','group_ID','data_source_ID']
replace_bracket = ['technique_ID']
for col in tactics_relations_df.columns:
    if col in add_bracket:
        print(col)
        tactics_relations_df[col] = format_cols_for_md(tactics_relations_df[col])
    elif col in replace_bracket:
        tactics_relations_df[col] = replace_chars_add_bracket(tactics_relations_df[col])
    else:
        tactics_relations_df[col] =  replace_chars(tactics_relations_df[col])
tactics_relations_df.columns = tactics_relations_df.columns.str.replace('_', ' ', regex=False)
tactics_relations_df.head(3)

tactic_ID

,tactic ID,tactic,technique ID,technique
0,[[TA0001]],Initial Access,[[T1566.004]] [[T1078.002]] [[T1190]] [[T1566]...,"Trusted Relationship, Drive-by Compromise, Spe..."
1,[[TA0002]],Execution,[[T1059.009]] [[T1053.002]] [[T1047]] [[T1204....,"Windows Management Instrumentation, Deploy Con..."
2,[[TA0003]],Persistence,[[T1546.006]] [[T1098.001]] [[T1078.002]] [[T1...,"Registry Run Keys / Startup Folder, Outlook Fo..."

In [50]:
for index, row in tactics_relations_df.iterrows():
    # Obtener el tactic_ID sin los corchetes
    tactic_id = row['tactic ID'].strip('[]')
    
    # Crear la ruta del archivo
    folder_path = os.path.join(output_folder, 'mitre properties', 'relations_md', mitre_domain, 'tactics_techniques', tactic_id)
    os.makedirs(folder_path, exist_ok=True)
    
    # Crear el nombre del archivo .md
    filename = f'relations_{tactic_id}.md'
    file_path = os.path.join(folder_path, filename)
    
    # Escribir el contenido en el archivo .md
    with open(file_path, 'w') as file:
        # Propiedades
        file.write("---\n")
        file.write("Tactic: true\n")
        file.write("Tactic relations: true\n")
        file.write("---\n\n")
        
        # Escribir el título con tactic_ID
        file.write(f"### {tactic_id}\n\n")
        
        # Escribir los detalles de la táctica
        file.write(f"**tactic ID**\n{row['tactic ID']}\n\n")
        file.write(f"**related techniques**\n{row['technique ID']}\n\n")

        file.close()
    print(f"Archivo '{filename}' creado en la carpeta '{file_path}' con éxito.")

Archivo 'relations_TA0001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0001\relations_TA0001.md' con éxito.
Archivo 'relations_TA0002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0002\relations_TA0002.md' con éxito.
Archivo 'relations_TA0003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0003\relations_TA0003.md' con éxito.
Archivo 'relations_TA0004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0004\relations_TA0004.md' con éxito.
Archivo 'relations_TA0005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0005\relations_TA0005.md' con éxito.
Archivo 'relations_TA0006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0006\relations_TA0006.md' con éxito.
Archivo 'relations_TA0007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0007\relations_TA0007.md' con éxito.
Archivo 'relations_TA0008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0008\relations_TA0008.md' con éxito.
Archivo 'relations_TA0009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0009\relations_TA0009.md' con éxito.
Archivo 'relations_TA0010.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0010\relations_TA0010.md' con éxito.
Archivo 'relations_TA0011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0011\relations_TA0011.md' con éxito.
Archivo 'relations_TA0040.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0040\relations_TA0040.md' con éxito.
Archivo 'relations_TA0042.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0042\relations_TA0042.md' con éxito.
Archivo 'relations_TA0043.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\tactics_techniques\TA0043\relations_TA0043.md' con éxito.

##### **2. Software - Técnicas**

In [51]:
input_file = f'[MITRE]_{mitre_domain}_techniques_software_N1.csv'
software_relations_df = pd.read_csv(os.path.join(input_path, 'techniques_software', input_file), sep=';', quotechar='"')
software_relations_df.head(3)

,software_ID,software,technique_ID,technique
0,S0001,['Trojan.Mebromi'],['T1542.001'],['System Firmware']
1,S0002,['Mimikatz'],"['T1003.006', 'T1550.003', 'T1552.004', 'T1003...","['Pass the Hash', 'Credentials from Password S..."
2,S0003,['RIPTIDE'],"['T1071.001', 'T1573.001']","['Web Protocols', 'Symmetric Cryptography']"

In [52]:
add_bracket = ['tactic_ID','platform_ID','platform','group_ID','data_source_ID', 'software_ID']
replace_bracket = ['technique_ID']
for col in software_relations_df.columns:
    if col in add_bracket:
        print(col)
        software_relations_df[col] = format_cols_for_md(software_relations_df[col])
    elif col in replace_bracket:
        software_relations_df[col] = replace_chars_add_bracket(software_relations_df[col])
    else:
        software_relations_df[col] =  replace_chars(software_relations_df[col])
software_relations_df.columns = software_relations_df.columns.str.replace('_', ' ', regex=False)
software_relations_df.head(3)

software_ID

,software ID,software,technique ID,technique
0,[[S0001]],Trojan.Mebromi,[[T1542.001]],System Firmware
1,[[S0002]],Mimikatz,[[T1003.006]] [[T1550.003]] [[T1552.004]] [[T1...,"Pass the Hash, Credentials from Password Store..."
2,[[S0003]],RIPTIDE,[[T1071.001]] [[T1573.001]],"Web Protocols, Symmetric Cryptography"

In [53]:
for index, row in software_relations_df.iterrows():
    # Obtener el software_id sin los corchetes
    software_id = row['software ID'].strip('[]')
    
    # Crear la ruta del archivo
    folder_path = os.path.join(output_folder, 'mitre properties', 'relations_md', mitre_domain, 'software_techniques', software_id)
    os.makedirs(folder_path, exist_ok=True)
    
    # Crear el nombre del archivo .md
    filename = f'relations_{software_id}.md'
    file_path = os.path.join(folder_path, filename)
    
    # Escribir el contenido en el archivo .md
    with open(file_path, 'w') as file:
        # Propiedades
        file.write("---\n")
        file.write("Software: true\n")
        file.write("Software relations: true\n")
        file.write("---\n\n")
        
        # Escribir el título con software_id
        file.write(f"### {software_id}\n\n")
        
        # Escribir los detalles de la táctica
        file.write(f"**software ID**\n{row['software ID']}\n\n")
        file.write(f"**related techniques**\n{row['technique ID']}\n\n")

        file.close()
    print(f"Archivo '{filename}' creado en la carpeta '{file_path}' con éxito.")

Archivo 'relations_S0001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0001\relations_S0001.md' con éxito.
Archivo 'relations_S0002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0002\relations_S0002.md' con éxito.
Archivo 'relations_S0003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0003\relations_S0003.md' con éxito.
Archivo 'relations_S0004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0004\relations_S0004.md' con éxito.
Archivo 'relations_S0005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0005\relations_S0005.md' con éxito.
Archivo 'relations_S0006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0006\relations_S0006.md' con éxito.
Archivo 'relations_S0007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0007\relations_S0007.md' con éxito.

Archivo 'relations_S0008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0008\relations_S0008.md' con éxito.
Archivo 'relations_S0009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0009\relations_S0009.md' con éxito.
Archivo 'relations_S0010.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0010\relations_S0010.md' con éxito.
Archivo 'relations_S0011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0011\relations_S0011.md' con éxito.
Archivo 'relations_S0012.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0012\relations_S0012.md' con éxito.
Archivo 'relations_S0013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0013\relations_S0013.md' con éxito.
Archivo 'relations_S0014.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0014\relations_S0014.md' con éxito.
Archivo 'relations_S0015.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0015\relations_S0015.md' con éxito.
Archivo 'relations_S0016.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0016\relations_S0016.md' con éxito.
Archivo 'relations_S0017.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0017\relations_S0017.md' con éxito.
Archivo 'relations_S0018.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0018\relations_S0018.md' con éxito.
Archivo 'relations_S0019.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0019\relations_S0019.md' con éxito.
Archivo 'relations_S0020.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0020\relations_S0020.md' con éxito.
Archivo 'relations_S0021.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0021\relations_S0021.md' con éxito.
Archivo 'relations_S0022.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0022\relations_S0022.md' con éxito.
Archivo 'relations_S0023.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0023\relations_S0023.md' con éxito.
Archivo 'relations_S0024.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0024\relations_S0024.md' con éxito.
Archivo 'relations_S0025.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0025\relations_S0025.md' con éxito.
Archivo 'relations_S0026.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0026\relations_S0026.md' con éxito.
Archivo 'relations_S0027.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0027\relations_S0027.md' con éxito.
Archivo 'relations_S0028.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0028\relations_S0028.md' con éxito.
Archivo 'relations_S0029.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0029\relations_S0029.md' con éxito.
Archivo 'relations_S0030.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0030\relations_S0030.md' con éxito.
Archivo 'relations_S0031.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0031\relations_S0031.md' con éxito.
Archivo 'relations_S0032.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0032\relations_S0032.md' con éxito.
Archivo 'relations_S0033.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0033\relations_S0033.md' con éxito.
Archivo 'relations_S0034.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0034\relations_S0034.md' con éxito.
Archivo 'relations_S0035.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0035\relations_S0035.md' con éxito.
Archivo 'relations_S0036.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0036\relations_S0036.md' con éxito.
Archivo 'relations_S0037.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0037\relations_S0037.md' con éxito.
Archivo 'relations_S0038.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0038\relations_S0038.md' con éxito.
Archivo 'relations_S0039.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0039\relations_S0039.md' con éxito.
Archivo 'relations_S0040.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0040\relations_S0040.md' con éxito.
Archivo 'relations_S0041.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0041\relations_S0041.md' con éxito.
Archivo 'relations_S0042.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0042\relations_S0042.md' con éxito.
Archivo 'relations_S0043.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0043\relations_S0043.md' con éxito.
Archivo 'relations_S0044.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0044\relations_S0044.md' con éxito.
Archivo 'relations_S0045.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0045\relations_S0045.md' con éxito.
Archivo 'relations_S0046.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0046\relations_S0046.md' con éxito.
Archivo 'relations_S0047.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0047\relations_S0047.md' con éxito.
Archivo 'relations_S0048.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0048\relations_S0048.md' con éxito.
Archivo 'relations_S0049.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0049\relations_S0049.md' con éxito.
Archivo 'relations_S0050.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0050\relations_S0050.md' con éxito.
Archivo 'relations_S0051.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0051\relations_S0051.md' con éxito.
Archivo 'relations_S0052.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0052\relations_S0052.md' con éxito.
Archivo 'relations_S0053.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0053\relations_S0053.md' con éxito.
Archivo 'relations_S0054.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0054\relations_S0054.md' con éxito.
Archivo 'relations_S0055.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0055\relations_S0055.md' con éxito.
Archivo 'relations_S0056.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0056\relations_S0056.md' con éxito.
Archivo 'relations_S0057.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0057\relations_S0057.md' con éxito.
Archivo 'relations_S0058.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0058\relations_S0058.md' con éxito.
Archivo 'relations_S0059.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0059\relations_S0059.md' con éxito.
Archivo 'relations_S0060.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0060\relations_S0060.md' con éxito.
Archivo 'relations_S0061.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0061\relations_S0061.md' con éxito.
Archivo 'relations_S0062.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0062\relations_S0062.md' con éxito.
Archivo 'relations_S0063.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0063\relations_S0063.md' con éxito.
Archivo 'relations_S0064.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0064\relations_S0064.md' con éxito.
Archivo 'relations_S0065.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0065\relations_S0065.md' con éxito.
Archivo 'relations_S0066.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0066\relations_S0066.md' con éxito.
Archivo 'relations_S0067.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0067\relations_S0067.md' con éxito.
Archivo 'relations_S0068.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0068\relations_S0068.md' con éxito.
Archivo 'relations_S0069.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0069\relations_S0069.md' con éxito.
Archivo 'relations_S0070.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0070\relations_S0070.md' con éxito.
Archivo 'relations_S0071.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0071\relations_S0071.md' con éxito.
Archivo 'relations_S0072.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0072\relations_S0072.md' con éxito.
Archivo 'relations_S0073.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0073\relations_S0073.md' con éxito.
Archivo 'relations_S0074.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0074\relations_S0074.md' con éxito.
Archivo 'relations_S0075.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0075\relations_S0075.md' con éxito.
Archivo 'relations_S0076.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0076\relations_S0076.md' con éxito.
Archivo 'relations_S0077.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0077\relations_S0077.md' con éxito.
Archivo 'relations_S0078.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0078\relations_S0078.md' con éxito.
Archivo 'relations_S0079.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0079\relations_S0079.md' con éxito.
Archivo 'relations_S0080.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0080\relations_S0080.md' con éxito.
Archivo 'relations_S0081.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0081\relations_S0081.md' con éxito.
Archivo 'relations_S0082.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0082\relations_S0082.md' con éxito.
Archivo 'relations_S0083.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0083\relations_S0083.md' con éxito.
Archivo 'relations_S0084.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0084\relations_S0084.md' con éxito.
Archivo 'relations_S0085.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0085\relations_S0085.md' con éxito.
Archivo 'relations_S0086.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0086\relations_S0086.md' con éxito.
Archivo 'relations_S0087.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0087\relations_S0087.md' con éxito.
Archivo 'relations_S0088.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0088\relations_S0088.md' con éxito.
Archivo 'relations_S0089.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0089\relations_S0089.md' con éxito.
Archivo 'relations_S0090.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0090\relations_S0090.md' con éxito.
Archivo 'relations_S0091.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0091\relations_S0091.md' con éxito.
Archivo 'relations_S0092.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0092\relations_S0092.md' con éxito.
Archivo 'relations_S0093.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\software_techniques\S0093\relations_S0093.md' con éxito.

##### **4. Data Sources**

In [54]:
input_file = f'[MITRE]_{mitre_domain}_techniques_datasource_N1.csv'
datasources_relations_df = pd.read_csv(os.path.join(input_path, 'techniques_datasources', input_file), sep=';', quotechar='"')
datasources_relations_df.head(3)

,data_source_ID,data_source,technique_ID,technique
0,DS0001,['Firmware'],"['T1542.001', 'T1495', 'T1564.005', 'T1542', '...","['TFTP Boot', 'Rootkit', 'Firmware Corruption'..."
1,DS0002,['User Account'],"['T1098.001', 'T1078.002', 'T1556.005', 'T1136...","['Unsecured Credentials', 'Use Alternate Authe..."
2,DS0003,['Scheduled Job'],"['T1053.002', 'T1053.007', 'T1036.004', 'T1053...","['Masquerade Task or Service', 'At', 'Schedule..."

In [55]:
add_bracket = ['tactic_ID','platform_ID','platform','group_ID','data_source_ID', 'software_ID']
replace_bracket = ['technique_ID']
for col in datasources_relations_df.columns:
    if col in add_bracket:
        print(col)
        datasources_relations_df[col] = format_cols_for_md(datasources_relations_df[col])
    elif col in replace_bracket:
        datasources_relations_df[col] = replace_chars_add_bracket(datasources_relations_df[col])
    else:
        datasources_relations_df[col] =  replace_chars(datasources_relations_df[col])
datasources_relations_df.columns = datasources_relations_df.columns.str.replace('_', ' ', regex=False)
datasources_relations_df.head(3)

data_source_ID

,data source ID,data source,technique ID,technique
0,[[DS0001]],Firmware,[[T1542.001]] [[T1495]] [[T1564.005]] [[T1542]...,"TFTP Boot, Rootkit, Firmware Corruption, Hidde..."
1,[[DS0002]],User Account,[[T1098.001]] [[T1078.002]] [[T1556.005]] [[T1...,"Unsecured Credentials, Use Alternate Authentic..."
2,[[DS0003]],Scheduled Job,[[T1053.002]] [[T1053.007]] [[T1036.004]] [[T1...,"Masquerade Task or Service, At, Scheduled Task..."

In [56]:
for index, row in datasources_relations_df.iterrows():
    # Obtener el datasource_id sin los corchetes
    datasource_id = row['data source ID'].strip('[]')
    
    # Crear la ruta del archivo
    folder_path = os.path.join(output_folder, 'mitre properties', 'relations_md', mitre_domain, 'datasources_techniques', datasource_id)
    os.makedirs(folder_path, exist_ok=True)
    
    # Crear el nombre del archivo .md
    filename = f'relations_{datasource_id}.md'
    file_path = os.path.join(folder_path, filename)
    
    # Escribir el contenido en el archivo .md
    with open(file_path, 'w') as file:
        # Propiedades
        file.write("---\n")
        file.write("Data source: true\n")
        file.write("Data source relations: true\n")
        file.write("---\n\n")
        
        # Escribir el título con datasource_id
        file.write(f"### {datasource_id}\n\n")
        
        # Escribir los detalles de la táctica
        file.write(f"**data source ID**\n{row['data source ID']}\n\n")
        file.write(f"**related techniques**\n{row['technique ID']}\n\n")

        file.close()
    print(f"Archivo '{filename}' creado en la carpeta '{file_path}' con éxito.")

Archivo 'relations_DS0001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0001\relations_DS0001.md' con éxito.

Archivo 'relations_DS0002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0002\relations_DS0002.md' con éxito.
Archivo 'relations_DS0003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0003\relations_DS0003.md' con éxito.
Archivo 'relations_DS0004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0004\relations_DS0004.md' con éxito.
Archivo 'relations_DS0005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0005\relations_DS0005.md' con éxito.
Archivo 'relations_DS0006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0006\relations_DS0006.md' con éxito.
Archivo 'relations_DS0007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0007\relations_DS0007.md' con éxito.
Archivo 'relations_DS0008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0008\relations_DS0008.md' con éxito.
Archivo 'relations_DS0009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0009\relations_DS0009.md' con éxito.
Archivo 'relations_DS0010.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0010\relations_DS0010.md' con éxito.
Archivo 'relations_DS0011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0011\relations_DS0011.md' con éxito.
Archivo 'relations_DS0012.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0012\relations_DS0012.md' con éxito.
Archivo 'relations_DS0013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0013\relations_DS0013.md' con éxito.
Archivo 'relations_DS0014.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0014\relations_DS0014.md' con éxito.
Archivo 'relations_DS0015.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0015\relations_DS0015.md' con éxito.
Archivo 'relations_DS0016.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0016\relations_DS0016.md' con éxito.
Archivo 'relations_DS0017.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0017\relations_DS0017.md' con éxito.
Archivo 'relations_DS0018.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0018\relations_DS0018.md' con éxito.
Archivo 'relations_DS0019.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0019\relations_DS0019.md' con éxito.
Archivo 'relations_DS0020.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0020\relations_DS0020.md' con éxito.
Archivo 'relations_DS0021.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0021\relations_DS0021.md' con éxito.
Archivo 'relations_DS0022.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0022\relations_DS0022.md' con éxito.
Archivo 'relations_DS0023.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0023\relations_DS0023.md' con éxito.
Archivo 'relations_DS0024.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0024\relations_DS0024.md' con éxito.
Archivo 'relations_DS0025.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0025\relations_DS0025.md' con éxito.
Archivo 'relations_DS0026.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0026\relations_DS0026.md' con éxito.
Archivo 'relations_DS0027.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0027\relations_DS0027.md' con éxito.
Archivo 'relations_DS0028.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0028\relations_DS0028.md' con éxito.
Archivo 'relations_DS0029.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0029\relations_DS0029.md' con éxito.
Archivo 'relations_DS0030.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0030\relations_DS0030.md' con éxito.
Archivo 'relations_DS0032.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0032\relations_DS0032.md' con éxito.
Archivo 'relations_DS0033.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0033\relations_DS0033.md' con éxito.
Archivo 'relations_DS0034.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0034\relations_DS0034.md' con éxito.
Archivo 'relations_DS0035.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0035\relations_DS0035.md' con éxito.
Archivo 'relations_DS0036.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0036\relations_DS0036.md' con éxito.
Archivo 'relations_DS0037.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0037\relations_DS0037.md' con éxito.
Archivo 'relations_DS0038.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\datasources_techniques\DS0038\relations_DS0038.md' con éxito.

##### **5. Grupos Técnicas**

In [57]:
input_file = f'[MITRE]_{mitre_domain}_techniques_group_N1.csv'
groups_relations_df = pd.read_csv(os.path.join(input_path, 'techniques_groups', input_file), sep=';', quotechar='"')
groups_relations_df.head(3)

,group_ID,group,technique_ID,technique
0,G0001,['Axiom'],"['T1021.001', 'T1583.003', 'T1546.008', 'T1189...","['Valid Accounts', 'OS Credential Dumping', 'E..."
1,G0002,['Moafee'],['T1027.001'],['Binary Padding']
2,G0003,['Cleaver'],"['T1588.002', 'T1587.001', 'T1585.001', 'T1557...","['Malware', 'Social Media Accounts', 'LSASS Me..."

In [58]:
add_bracket = ['tactic_ID','platform_ID','platform','group_ID','data_source_ID', 'software_ID']
replace_bracket = ['technique_ID']
for col in groups_relations_df.columns:
    if col in add_bracket:
        print(col)
        groups_relations_df[col] = format_cols_for_md(groups_relations_df[col])
    elif col in replace_bracket:
        groups_relations_df[col] = replace_chars_add_bracket(groups_relations_df[col])
    else:
        groups_relations_df[col] =  replace_chars(groups_relations_df[col])
groups_relations_df.columns = groups_relations_df.columns.str.replace('_', ' ', regex=False)
groups_relations_df.head(3)

group_ID

,group ID,group,technique ID,technique
0,[[G0001]],Axiom,[[T1021.001]] [[T1583.003]] [[T1546.008]] [[T1...,"Valid Accounts, OS Credential Dumping, Exploit..."
1,[[G0002]],Moafee,[[T1027.001]],Binary Padding
2,[[G0003]],Cleaver,[[T1588.002]] [[T1587.001]] [[T1585.001]] [[T1...,"Malware, Social Media Accounts, LSASS Memory, ..."

In [59]:
for index, row in groups_relations_df.iterrows():
    # Obtener el group_id sin los corchetes
    group_id = row['group ID'].strip('[]')
    
    # Crear la ruta del archivo
    folder_path = os.path.join(output_folder, 'mitre properties', 'relations_md', mitre_domain, 'groups_techniques', group_id)
    os.makedirs(folder_path, exist_ok=True)
    
    # Crear el nombre del archivo .md
    filename = f'relations_{group_id}.md'
    file_path = os.path.join(folder_path, filename)
    
    # Escribir el contenido en el archivo .md
    with open(file_path, 'w') as file:
        # Propiedades
        file.write("---\n")
        file.write("Group: true\n")
        file.write("Group relations: true\n")
        file.write("---\n\n")
        
        # Escribir el título con group_id
        file.write(f"### {group_id}\n\n")
        
        # Escribir los detalles de la táctica
        file.write(f"**group ID**\n{row['group ID']}\n\n")
        file.write(f"**related techniques**\n{row['technique ID']}\n\n")

        file.close()
    print(f"Archivo '{filename}' creado en la carpeta '{file_path}' con éxito.")

Archivo 'relations_G0001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0001\relations_G0001.md' con éxito.
Archivo 'relations_G0002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0002\relations_G0002.md' con éxito.
Archivo 'relations_G0003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0003\relations_G0003.md' con éxito.
Archivo 'relations_G0004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0004\relations_G0004.md' con éxito.
Archivo 'relations_G0005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0005\relations_G0005.md' con éxito.
Archivo 'relations_G0006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0006\relations_G0006.md' con éxito.
Archivo 'relations_G0007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0007\relations_G0007.md' con éxito.
Archivo 'relations_G0008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0008\relations_G0008.md' con éxito.
Archivo 'relations_G0009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0009\relations_G0009.md' con éxito.
Archivo 'relations_G0010.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0010\relations_G0010.md' con éxito.
Archivo 'relations_G0011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0011\relations_G0011.md' con éxito.
Archivo 'relations_G0012.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0012\relations_G0012.md' con éxito.
Archivo 'relations_G0013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0013\relations_G0013.md' con éxito.
Archivo 'relations_G0016.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0016\relations_G0016.md' con éxito.
Archivo 'relations_G0018.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0018\relations_G0018.md' con éxito.
Archivo 'relations_G0019.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0019\relations_G0019.md' con éxito.
Archivo 'relations_G0020.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0020\relations_G0020.md' con éxito.
Archivo 'relations_G0021.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0021\relations_G0021.md' con éxito.
Archivo 'relations_G0022.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0022\relations_G0022.md' con éxito.

Archivo 'relations_G0023.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0023\relations_G0023.md' con éxito.
Archivo 'relations_G0024.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0024\relations_G0024.md' con éxito.
Archivo 'relations_G0025.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0025\relations_G0025.md' con éxito.
Archivo 'relations_G0026.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0026\relations_G0026.md' con éxito.
Archivo 'relations_G0027.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0027\relations_G0027.md' con éxito.
Archivo 'relations_G0028.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0028\relations_G0028.md' con éxito.
Archivo 'relations_G0029.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0029\relations_G0029.md' con éxito.
Archivo 'relations_G0032.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0032\relations_G0032.md' con éxito.
Archivo 'relations_G0033.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0033\relations_G0033.md' con éxito.
Archivo 'relations_G0034.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0034\relations_G0034.md' con éxito.
Archivo 'relations_G0035.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0035\relations_G0035.md' con éxito.
Archivo 'relations_G0036.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0036\relations_G0036.md' con éxito.
Archivo 'relations_G0037.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0037\relations_G0037.md' con éxito.
Archivo 'relations_G0038.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0038\relations_G0038.md' con éxito.
Archivo 'relations_G0039.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0039\relations_G0039.md' con éxito.
Archivo 'relations_G0040.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0040\relations_G0040.md' con éxito.
Archivo 'relations_G0041.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0041\relations_G0041.md' con éxito.
Archivo 'relations_G0043.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0043\relations_G0043.md' con éxito.
Archivo 'relations_G0044.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0044\relations_G0044.md' con éxito.
Archivo 'relations_G0045.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0045\relations_G0045.md' con éxito.
Archivo 'relations_G0046.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0046\relations_G0046.md' con éxito.
Archivo 'relations_G0047.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0047\relations_G0047.md' con éxito.
Archivo 'relations_G0048.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0048\relations_G0048.md' con éxito.
Archivo 'relations_G0049.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0049\relations_G0049.md' con éxito.
Archivo 'relations_G0050.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0050\relations_G0050.md' con éxito.
Archivo 'relations_G0051.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0051\relations_G0051.md' con éxito.
Archivo 'relations_G0052.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0052\relations_G0052.md' con éxito.
Archivo 'relations_G0053.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0053\relations_G0053.md' con éxito.
Archivo 'relations_G0054.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0054\relations_G0054.md' con éxito.
Archivo 'relations_G0056.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0056\relations_G0056.md' con éxito.
Archivo 'relations_G0059.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0059\relations_G0059.md' con éxito.
Archivo 'relations_G0060.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0060\relations_G0060.md' con éxito.
Archivo 'relations_G0061.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0061\relations_G0061.md' con éxito.
Archivo 'relations_G0062.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0062\relations_G0062.md' con éxito.
Archivo 'relations_G0063.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0063\relations_G0063.md' con éxito.
Archivo 'relations_G0064.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0064\relations_G0064.md' con éxito.
Archivo 'relations_G0065.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0065\relations_G0065.md' con éxito.
Archivo 'relations_G0066.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0066\relations_G0066.md' con éxito.
Archivo 'relations_G0067.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0067\relations_G0067.md' con éxito.
Archivo 'relations_G0068.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0068\relations_G0068.md' con éxito.
Archivo 'relations_G0069.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0069\relations_G0069.md' con éxito.
Archivo 'relations_G0070.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0070\relations_G0070.md' con éxito.
Archivo 'relations_G0071.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0071\relations_G0071.md' con éxito.
Archivo 'relations_G0073.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0073\relations_G0073.md' con éxito.
Archivo 'relations_G0075.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0075\relations_G0075.md' con éxito.
Archivo 'relations_G0076.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0076\relations_G0076.md' con éxito.
Archivo 'relations_G0077.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0077\relations_G0077.md' con éxito.
Archivo 'relations_G0078.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0078\relations_G0078.md' con éxito.
Archivo 'relations_G0079.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0079\relations_G0079.md' con éxito.
Archivo 'relations_G0080.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0080\relations_G0080.md' con éxito.
Archivo 'relations_G0081.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0081\relations_G0081.md' con éxito.
Archivo 'relations_G0082.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0082\relations_G0082.md' con éxito.
Archivo 'relations_G0083.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0083\relations_G0083.md' con éxito.
Archivo 'relations_G0084.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0084\relations_G0084.md' con éxito.
Archivo 'relations_G0085.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0085\relations_G0085.md' con éxito.
Archivo 'relations_G0087.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0087\relations_G0087.md' con éxito.
Archivo 'relations_G0089.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0089\relations_G0089.md' con éxito.
Archivo 'relations_G0090.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0090\relations_G0090.md' con éxito.
Archivo 'relations_G0091.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0091\relations_G0091.md' con éxito.
Archivo 'relations_G0092.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0092\relations_G0092.md' con éxito.
Archivo 'relations_G0093.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0093\relations_G0093.md' con éxito.
Archivo 'relations_G0094.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0094\relations_G0094.md' con éxito.
Archivo 'relations_G0095.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0095\relations_G0095.md' con éxito.
Archivo 'relations_G0096.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0096\relations_G0096.md' con éxito.
Archivo 'relations_G0098.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0098\relations_G0098.md' con éxito.
Archivo 'relations_G0099.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0099\relations_G0099.md' con éxito.
Archivo 'relations_G0100.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0100\relations_G0100.md' con éxito.
Archivo 'relations_G0102.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0102\relations_G0102.md' con éxito.
Archivo 'relations_G0103.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0103\relations_G0103.md' con éxito.
Archivo 'relations_G0105.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0105\relations_G0105.md' con éxito.
Archivo 'relations_G0106.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0106\relations_G0106.md' con éxito.
Archivo 'relations_G0107.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0107\relations_G0107.md' con éxito.
Archivo 'relations_G0108.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0108\relations_G0108.md' con éxito.
Archivo 'relations_G0112.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0112\relations_G0112.md' con éxito.
Archivo 'relations_G0114.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0114\relations_G0114.md' con éxito.
Archivo 'relations_G0115.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0115\relations_G0115.md' con éxito.
Archivo 'relations_G0117.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0117\relations_G0117.md' con éxito.
Archivo 'relations_G0119.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0119\relations_G0119.md' con éxito.
Archivo 'relations_G0120.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0120\relations_G0120.md' con éxito.
Archivo 'relations_G0121.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0121\relations_G0121.md' con éxito.
Archivo 'relations_G0122.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0122\relations_G0122.md' con éxito.
Archivo 'relations_G0123.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0123\relations_G0123.md' con éxito.
Archivo 'relations_G0124.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0124\relations_G0124.md' con éxito.
Archivo 'relations_G0125.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0125\relations_G0125.md' con éxito.
Archivo 'relations_G0126.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0126\relations_G0126.md' con éxito.
Archivo 'relations_G0127.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0127\relations_G0127.md' con éxito.
Archivo 'relations_G0128.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\groups_techniques\G0128\relations_G0128.md' con éxito.

##### **6. Plataformas - Técnicas**

In [60]:
input_file = f'[MITRE]_{mitre_domain}_techniques_platform_N1.csv'
platforms_relations_df = pd.read_csv(os.path.join(input_path, 'techniques_platforms', input_file), sep=';', quotechar='"')
platforms_relations_df.head(3)

,platform,technique_ID,technique
0,Azure AD,"['T1059.009', 'T1098.001', 'T1548', 'T1528', '...","['Unsecured Credentials', 'Conditional Access ..."
1,Containers,"['T1068', 'T1190', 'T1136.001', 'T1496', 'T152...","['Unsecured Credentials', 'Use Alternate Authe..."
2,Google Workspace,"['T1059.009', 'T1566.004', 'T1564.008', 'T1048...","['Unsecured Credentials', 'Use Alternate Authe..."

In [61]:
add_bracket = ['tactic_ID','platform_ID','platform','group_ID','data_source_ID', 'software_ID']
replace_bracket = ['technique_ID']
for col in platforms_relations_df.columns:
    if col in add_bracket:
        print(col)
        platforms_relations_df[col] = format_cols_for_md(platforms_relations_df[col])
    elif col in replace_bracket:
        platforms_relations_df[col] = replace_chars_add_bracket(platforms_relations_df[col])
    else:
        platforms_relations_df[col] =  replace_chars(platforms_relations_df[col])
platforms_relations_df.columns = platforms_relations_df.columns.str.replace('_', ' ', regex=False)
platforms_relations_df.head(3)

platform

,platform,technique ID,technique
0,[[Azure AD]],[[T1059.009]] [[T1098.001]] [[T1548]] [[T1528]...,"Unsecured Credentials, Conditional Access Poli..."
1,[[Containers]],[[T1068]] [[T1190]] [[T1136.001]] [[T1496]] [[...,"Unsecured Credentials, Use Alternate Authentic..."
2,[[Google Workspace]],[[T1059.009]] [[T1566.004]] [[T1564.008]] [[T1...,"Unsecured Credentials, Use Alternate Authentic..."

In [62]:
for index, row in platforms_relations_df.iterrows():
    # Obtener el platform sin los corchetes
    platform = row['platform'].strip('[]')
    
    # Crear la ruta del archivo
    folder_path = os.path.join(output_folder, 'mitre properties', 'relations_md', mitre_domain, 'platforms_techniques', platform)
    os.makedirs(folder_path, exist_ok=True)
    
    # Crear el nombre del archivo .md
    filename = f'relations_{platform}.md'
    file_path = os.path.join(folder_path, filename)
    
    # Escribir el contenido en el archivo .md
    with open(file_path, 'w') as file:
        # Propiedades
        file.write("---\n")
        file.write("Platform: true\n")
        file.write("Platform relations: true\n")
        file.write("---\n\n")
        
        # Escribir el título con platform
        file.write(f"### {platform}\n\n")
        
        # Escribir los detalles de la táctica
        file.write(f"**platform**\n{row['platform']}\n\n")
        file.write(f"**related techniques**\n{row['technique ID']}\n\n")

        file.close()
    print(f"Archivo '{filename}' creado en la carpeta '{file_path}' con éxito.")

Archivo 'relations_Azure AD.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\Azure AD\relations_Azure AD.md' con éxito.
Archivo 'relations_Containers.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\Containers\relations_Containers.md' con éxito.
Archivo 'relations_Google Workspace.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\Google Workspace\relations_Google Workspace.md' con éxito.
Archivo 'relations_IaaS.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\IaaS\relations_IaaS.md' con éxito.
Archivo 'relations_Linux.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\Linux\relations_Linux.md' con éxito.
Archivo 'relations_Network.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\Network\relations_Network.md' con éxito.
Archivo 'relations_nan.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\nan\relations_nan.md' con éxito.
Archivo 'relations_Office 365.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\Office 365\relations_Office 365.md' con éxito.
Archivo 'relations_PRE.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\PRE\relations_PRE.md' con éxito.
Archivo 'relations_SaaS.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\SaaS\relations_SaaS.md' con éxito.
Archivo 'relations_Windows.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\Windows\relations_Windows.md' con éxito.
Archivo 'relations_macOS.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\mitre properties\relations_md\enterprise\platforms_techniques\macOS\relations_macOS.md' con éxito.