In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
Created on 2024-08-14
Last modified on 2024-08-14
@author: Juan Enrique López
@description: Jupyter Notebook cuyo cometido es generar archivos md con la información relativa a cada propiedad Mitre con la finalidad de filtrar vía Obsidian.

'''

'\nCreated on 2024-08-14\nLast modified on 2024-08-14\n@author: Juan Enrique López\n@description: Jupyter Notebook cuyo cometido es generar archivos md con la información relativa a cada propiedad Mitre con la finalidad de filtrar vía Obsidian.\n\n'

**IMPORTANTE - REQUERIMIENTOS PREVIOS**

- Requiere haber ejecutado previamente dentro de este mismo módulo **mitre_relationships** el notebook **[stix2]_mitre_relationships.ipynb** y disponer de la carpeta "outputs/stix2".

In [2]:
import os
import pandas as pd
import shutil
# import requests
from stix2 import Filter, MemoryStore

#### **Parámetros**

In [3]:
mitre_domain = 'enterprise' # enterprise, mobile, ics
input_path = os.path.join(os.getcwd(),'outputs', 'stix2', mitre_domain, 'information')

In [4]:
output_folder = os.path.join(os.getcwd(),'outputs')
output_folder

'c:\\Users\\jelopez\\Documents\\CyberProof\\python\\develop\\mitre_relationships\\outputs'

#### **Funciones**

In [5]:
def format_cols_for_md(column):
    '''
    Función para aplicar los reemplazos que permitan en el .md relacionar elementos.
    '''
    column = column.apply(lambda x: f'[[{x}]]')
    return column

In [6]:
def replace_chars(column):
    '''
    Función encargada de reemplazar caracteres en una columna dada con el objetivo de suprimir caracteres que enlazan dentro de Obsidian.
    '''
    if column.dtype == "object":  # Verifica que la columna sea de tipo string
        column = column.str.replace("['", '', regex=False)
        column = column.str.replace("']", '', regex=False)
        column = column.str.replace("'", '', regex=False)
    return column

In [7]:
def generate_technique_information_md(df, base_folder, mitre_property, mitre_domain):
    '''
    Función encargada de recorrer la tabla de técnicas y generar las estructura de carpetas junto con el archivo .md relativo a cada propiedad.
    '''
    # Iterar sobre cada fila del DataFrame
    for index, row in df.iterrows():
        # Obtener el technique_ID sin los corchetes
        technique_id = row['technique ID'].strip('[]')
        
        # Crear la ruta del archivo
        folder_path = os.path.join(base_folder, 'information_md', mitre_domain, mitre_property, technique_id)
        os.makedirs(folder_path, exist_ok=True)
        
        # Crear el nombre del archivo .md
        filename = f'{technique_id}.md'
        file_path = os.path.join(folder_path, filename)
        
        # Escribir el contenido en el archivo .md
        with open(file_path, 'w') as file:
            # Propiedades
            file.write("---\n")
            file.write("Technique: true\n")
            file.write("---\n\n")
            
            # Escribir el título con technique_ID
            file.write(f"### {technique_id}\n\n")
            
            # Escribir los detalles de la técnica
            file.write(f"**technique ID**\n{row['technique ID']}\n\n")
            file.write(f"**technique**\n{row['technique']}\n\n")
            file.write(f"**technique url**\n{row['technique url']}\n\n")
            file.write(f"**technique description**\n{row['technique description']}\n\n")
            file.write(f"**matrix domains**\n{row['matrix domains']}\n\n")
            file.close()
        
        print(f"Archivo '{filename}' creado en la carpeta '{folder_path}' con éxito.")

In [8]:
def generate_tactic_information_md(df, base_folder, mitre_property, mitre_domain):
    '''
    Función encargada de recorrer la tabla de tácticas y generar las estructura de carpetas junto con el archivo .md relativo a cada propiedad.
    '''
    # Iterar sobre cada fila del DataFrame
    for index, row in df.iterrows():
        # Obtener el tactic_ID sin los corchetes
        tactic_id = row['tactic ID'].strip('[]')
        
        # Crear la ruta del archivo
        folder_path = os.path.join(base_folder, 'information_md',mitre_domain, mitre_property, tactic_id)
        os.makedirs(folder_path, exist_ok=True)
        
        # Crear el nombre del archivo .md
        filename = f'{tactic_id}.md'
        file_path = os.path.join(folder_path, filename)
        
        # Escribir el contenido en el archivo .md
        with open(file_path, 'w') as file:
            # Propiedades
            file.write("---\n")
            file.write("Tactic: true\n")
            file.write("---\n\n")
            
            # Escribir el título con tactic_ID
            file.write(f"### {tactic_id}\n\n")
            
            # Escribir los detalles de la táctica
            file.write(f"**tactic ID**\n{row['tactic ID']}\n\n")
            file.write(f"**tactic**\n{row['tactic']}\n\n")
            file.write(f"**tactic url**\n{row['tactic url']}\n\n")
            file.write(f"**tactic description**\n{row['tactic description']}\n\n")
            file.write(f"**matrix domains**\n{row['matrix domains']}\n\n")
            file.close()
        
        print(f"Archivo '{filename}' creado en la carpeta '{folder_path}' con éxito.")

In [9]:
def generate_platform_information_md(df, base_folder, mitre_property, mitre_domain):
    '''
    Función encargada de recorrer la tabla de plataformas y generar las estructura de carpetas junto con el archivo .md relativo a cada propiedad.
    '''
    for index, row in df.iterrows():
        platform = row['platform'].strip('[]')
        folder_path = os.path.join(base_folder, 'information_md', mitre_domain, mitre_property, platform)
        os.makedirs(folder_path, exist_ok=True)
        filename = f'{platform}.md'
        file_path = os.path.join(folder_path, filename)
        
        with open(file_path, 'w') as file:
            file.write("---\n")
            file.write("Platform: true\n")
            file.write("---\n\n")
        
            file.write(f"### {platform}\n\n")

            file.write(f"**platform**\n{row['platform']}\n\n")
            file.close()

        print(f"Archivo '{filename}' creado en la carpeta '{folder_path}' con éxito.")

In [10]:
def generate_datasource_information_md(df, base_folder, mitre_property, mitre_domain):
    '''
    Función encargada de recorrer la tabla de plataformas y generar las estructura de carpetas junto con el archivo .md relativo a cada propiedad.
    '''
    for index, row in df.iterrows():
        data_source_id = row['data source ID'].strip('[]')
        
        # Crear la ruta del archivo
        folder_path = os.path.join(base_folder, 'information_md', mitre_domain, mitre_property, data_source_id)
        os.makedirs(folder_path, exist_ok=True)
        
        filename = f'{data_source_id}.md'
        file_path = os.path.join(folder_path, filename)
        
        with open(file_path, 'w') as file:
            file.write("---\n")
            file.write("Data source: true\n")
            file.write("---\n\n")
            
            file.write(f"### {data_source_id}\n\n")
            
            file.write(f"**data source ID**\n{row['data source ID']}\n\n")
            file.write(f"**data source**\n{row['data source']}\n\n")
            file.write(f"**data source url**\n{row['data source url']}\n\n")
            file.write(f"**data source description**\n{row['data source description']}\n\n")
            file.write(f"**matrix domains**\n{row['matrix domains']}\n\n")
            file.close()
        
        print(f"Archivo '{filename}' creado en la carpeta '{folder_path}' con éxito.")

In [11]:
def generate_group_information_md(df, base_folder, mitre_property, mitre_domain):
    '''
    Función encargada de recorrer la tabla de grupos y generar las estructura de carpetas junto con el archivo .md relativo a cada propiedad.
    '''
    for index, row in df.iterrows():
        group_id = row['group ID'].strip('[]')
        
        folder_path = os.path.join(base_folder, 'information_md', mitre_domain, mitre_property, group_id)
        os.makedirs(folder_path, exist_ok=True)
        
        filename = f'{group_id}.md'
        file_path = os.path.join(folder_path, filename)
        
        with open(file_path, 'w') as file:
            file.write("---\n")
            file.write("Group: true\n")
            file.write("---\n\n")
            
            file.write(f"### {group_id}\n\n")
            
            file.write(f"**group ID**\n{row['group ID']}\n\n")
            file.write(f"**group**\n{row['group']}\n\n")
            file.write(f"**group aliases**\n{row['group aliases']}\n\n")
            file.write(f"**group url**\n{row['group url']}\n\n")
            # file.write(f"**group description**\n{row['group description']}\n\n")
            file.write(f"**group description**\n{row['group description'].replace('[', '').replace(']', '')}\n\n")
            file.write(f"**matrix domains**\n{row['matrix domains']}\n\n")
            file.close()
        
        print(f"Archivo '{filename}' creado en la carpeta '{folder_path}' con éxito.")

In [12]:
def generate_software_information_md(df, base_folder, mitre_property, mitre_domain):
    '''
    Función encargada de recorrer la tabla de software y generar las estructura de carpetas junto con el archivo .md relativo a cada propiedad.
    '''
    for index, row in df.iterrows():
        software_id = row['software ID'].strip('[]')
        folder_path = os.path.join(base_folder, 'information_md', mitre_domain, mitre_property, software_id)
        os.makedirs(folder_path, exist_ok=True)
    
        filename = f'{software_id}.md'
        file_path = os.path.join(folder_path, filename)
        
        with open(file_path, 'w') as file:
            file.write("---\n")
            file.write("Software: true\n")
            file.write("---\n\n")
        
            file.write(f"### {software_id}\n\n")

            file.write(f"**software ID**\n{row['software ID']}\n\n")
            file.write(f"**software**\n{row['software']}\n\n")
            file.write(f"**software type**\n{row['software type']}\n\n")
            file.write(f"**software url**\n{row['software url']}\n\n")
            file.write(f"**software description**\n{row['software description']}\n\n")
            file.write(f"**matrix domains**\n{row['matrix domains']}\n\n")
            file.close()
        print(f"Archivo '{filename}' creado en la carpeta '{folder_path}' con éxito.")

#### **Ejecución**

##### **1. Técnicas**

In [13]:
input_file = f'[MITRE]_{mitre_domain}_techniques.csv'
techniques_information_df = pd.read_csv(os.path.join(input_path, 'techniques', input_file), sep=';', quotechar='"')
techniques_information_df.head(3)

,technique_ID,technique,technique_url,technique_description,technique_deprecated,technique_revoked,matrix_domains
0,T1055.011,Extra Window Memory Injection,https://attack.mitre.org/techniques/T1055/011,Adversaries may inject malicious code into pro...,False,False,['enterprise-attack']
1,T1053.005,Scheduled Task,https://attack.mitre.org/techniques/T1053/005,Adversaries may abuse the Windows Task Schedul...,False,False,['enterprise-attack']
2,T1205.002,Socket Filters,https://attack.mitre.org/techniques/T1205/002,Adversaries may attach filters to a network so...,False,False,['enterprise-attack']

In [14]:
column_list = ['technique_ID','tactic_ID','platform_ID','platform','group_ID','data_source_ID']
for col in techniques_information_df.columns:
    if col in column_list:
        print(col)
        techniques_information_df[col] = format_cols_for_md(techniques_information_df[col])
    else:
        techniques_information_df[col] =  replace_chars(techniques_information_df[col])
techniques_information_df.columns = techniques_information_df.columns.str.replace('_', ' ', regex=False)
techniques_information_df.head(3)

technique_ID

,technique ID,technique,technique url,technique description,technique deprecated,technique revoked,matrix domains
0,[[T1055.011]],Extra Window Memory Injection,https://attack.mitre.org/techniques/T1055/011,Adversaries may inject malicious code into pro...,False,False,enterprise-attack
1,[[T1053.005]],Scheduled Task,https://attack.mitre.org/techniques/T1053/005,Adversaries may abuse the Windows Task Schedul...,False,False,enterprise-attack
2,[[T1205.002]],Socket Filters,https://attack.mitre.org/techniques/T1205/002,Adversaries may attach filters to a network so...,False,False,enterprise-attack

In [15]:
generate_technique_information_md(techniques_information_df, output_folder, 'techniques', mitre_domain)

Archivo 'T1055.011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1055.011' con éxito.
Archivo 'T1053.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1053.005' con éxito.
Archivo 'T1205.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1205.002' con éxito.
Archivo 'T1560.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1560.001' con éxito.
Archivo 'T1021.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1021.005' con éxito.
Archivo 'T1047.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1047' con éxito.
Archivo 'T1113.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1113' con éxito.
Archivo 'T1027.011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1027.011' con éxito.
Archivo 'T1037.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1037' con éxito.
Archivo 'T1557.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1557' con éxito.
Archivo 'T1033.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1033' con éxito.
Archivo 'T1583.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1583' con éxito.
Archivo 'T1218.011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1218.011' con éxito.
Archivo 'T1613.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1613' con éxito.
Archivo 'T1583.007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1583.007' con éxito.
Archivo 'T1132.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1132.001' con éxito.
Archivo 'T1027.009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1027.009' con éxito.
Archivo 'T1556.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1556.003' con éxito.
Archivo 'T1578.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1578.004' con éxito.
Archivo 'T1592.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1592' con éxito.
Archivo 'T1596.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1596.003' con éxito.
Archivo 'T1056.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1056.001' con éxito.
Archivo 'T1564.012.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1564.012' con éxito.
Archivo 'T1222.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1222.002' con éxito.
Archivo 'T1110.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1110.001' con éxito.
Archivo 'T1216.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1216.001' con éxito.
Archivo 'T1597.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1597.002' con éxito.
Archivo 'T1003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1003' con éxito.
Archivo 'T1129.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1129' con éxito.
Archivo 'T1602.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1602' con éxito.
Archivo 'T1561.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1561.002' con éxito.
Archivo 'T1498.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1498.001' con éxito.
Archivo 'T1574.007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1574.007' con éxito.
Archivo 'T1213.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1213.002' con éxito.
Archivo 'T1006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1006' con éxito.
Archivo 'T1588.007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1588.007' con éxito.
Archivo 'T1564.008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1564.008' con éxito.
Archivo 'T1491.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1491.002' con éxito.
Archivo 'T1027.013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1027.013' con éxito.
Archivo 'T1590.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1590.005' con éxito.
Archivo 'T1499.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1499.001' con éxito.
Archivo 'T1014.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1014' con éxito.
Archivo 'T1546.013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1546.013' con éxito.
Archivo 'T1059.007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1059.007' con éxito.
Archivo 'T1590.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1590.002' con éxito.
Archivo 'T1123.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1123' con éxito.
Archivo 'T1543.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1543' con éxito.
Archivo 'T1133.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1133' con éxito.
Archivo 'T1546.006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1546.006' con éxito.
Archivo 'T1539.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1539' con éxito.
Archivo 'T1053.007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1053.007' con éxito.
Archivo 'T1568.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1568.002' con éxito.
Archivo 'T1036.007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1036.007' con éxito.
Archivo 'T1548.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1548.002' con éxito.

Archivo 'T1016.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1016.001' con éxito.
Archivo 'T1548.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1548.003' con éxito.
Archivo 'T1560.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1560.003' con éxito.
Archivo 'T1578.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1578' con éxito.
Archivo 'T1584.008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1584.008' con éxito.
Archivo 'T1583.008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1583.008' con éxito.
Archivo 'T1069.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1069' con éxito.
Archivo 'T1114.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1114' con éxito.
Archivo 'T1003.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1003.002' con éxito.
Archivo 'T1596.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1596.002' con éxito.
Archivo 'T1542.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1542.001' con éxito.
Archivo 'T1594.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1594' con éxito.
Archivo 'T1069.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1069.003' con éxito.
Archivo 'T1574.011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1574.011' con éxito.
Archivo 'T1596.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1596.001' con éxito.
Archivo 'T1499.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1499.003' con éxito.
Archivo 'T1195.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1195.001' con éxito.
Archivo 'T1588.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1588.004' con éxito.
Archivo 'T1583.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1583.002' con éxito.
Archivo 'T1561.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1561' con éxito.
Archivo 'T1071.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1071.004' con éxito.
Archivo 'T1552.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1552.005' con éxito.
Archivo 'T1555.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1555.002' con éxito.
Archivo 'T1615.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1615' con éxito.
Archivo 'T1542.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1542.003' con éxito.
Archivo 'T1025.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1025' con éxito.
Archivo 'T1218.013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1218.013' con éxito.
Archivo 'T1074.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1074.001' con éxito.
Archivo 'T1036.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1036.005' con éxito.
Archivo 'T1587.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1587.003' con éxito.
Archivo 'T1565.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1565.001' con éxito.
Archivo 'T1110.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1110.002' con éxito.
Archivo 'T1114.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1114.001' con éxito.
Archivo 'T1555.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1555.001' con éxito.
Archivo 'T1547.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1547' con éxito.
Archivo 'T1003.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1003.004' con éxito.
Archivo 'T1600.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1600' con éxito.
Archivo 'T1606.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1606.002' con éxito.
Archivo 'T1036.008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1036.008' con éxito.
Archivo 'T1489.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1489' con éxito.
Archivo 'T1587.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1587.001' con éxito.
Archivo 'T1652.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1652' con éxito.
Archivo 'T1087.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1087.002' con éxito.
Archivo 'T1547.014.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1547.014' con éxito.
Archivo 'T1564.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1564' con éxito.
Archivo 'T1559.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1559.002' con éxito.
Archivo 'T1204.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1204.002' con éxito.
Archivo 'T1591.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1591.003' con éxito.
Archivo 'T1592.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1592.001' con éxito.
Archivo 'T1080.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1080' con éxito.
Archivo 'T1484.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1484.002' con éxito.
Archivo 'T1573.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1573.001' con éxito.
Archivo 'T1087.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1087.001' con éxito.
Archivo 'T1586.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1586.001' con éxito.
Archivo 'T1562.009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1562.009' con éxito.
Archivo 'T1542.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1542.005' con éxito.
Archivo 'T1543.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1543.003' con éxito.
Archivo 'T1568.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1568.001' con éxito.
Archivo 'T1497.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1497.001' con éxito.
Archivo 'T1053.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1053.003' con éxito.
Archivo 'T1069.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1069.002' con éxito.
Archivo 'T1588.006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1588.006' con éxito.
Archivo 'T1566.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1566.002' con éxito.
Archivo 'T1070.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1070.002' con éxito.
Archivo 'T1499.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1499.004' con éxito.
Archivo 'T1137.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1137' con éxito.
Archivo 'T1218.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1218.004' con éxito.
Archivo 'T1598.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1598.003' con éxito.
Archivo 'T1021.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1021.004' con éxito.
Archivo 'T1098.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1098.003' con éxito.
Archivo 'T1547.012.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1547.012' con éxito.
Archivo 'T1566.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1566.001' con éxito.
Archivo 'T1027.008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1027.008' con éxito.
Archivo 'T1559.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1559.001' con éxito.
Archivo 'T1574.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1574.001' con éxito.
Archivo 'T1119.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1119' con éxito.
Archivo 'T1115.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1115' con éxito.
Archivo 'T1003.007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1003.007' con éxito.
Archivo 'T1583.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1583.005' con éxito.
Archivo 'T1555.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1555.005' con éxito.
Archivo 'T1553.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1553.001' con éxito.
Archivo 'T1608.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1608.004' con éxito.
Archivo 'T1007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1007' con éxito.
Archivo 'T1040.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1040' con éxito.
Archivo 'T1553.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1553.002' con éxito.
Archivo 'T1530.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1530' con éxito.
Archivo 'T1565.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1565.003' con éxito.
Archivo 'T1552.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1552.002' con éxito.
Archivo 'T1135.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1135' con éxito.
Archivo 'T1120.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1120' con éxito.
Archivo 'T1036.009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1036.009' con éxito.
Archivo 'T1590.004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1590.004' con éxito.
Archivo 'T1587.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1587.002' con éxito.
Archivo 'T1222.001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1222.001' con éxito.
Archivo 'T1137.006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1137.006' con éxito.
Archivo 'T1505.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1505.002' con éxito.
Archivo 'T1082.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1082' con éxito.
Archivo 'T1071.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1071' con éxito.
Archivo 'T1574.014.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1574.014' con éxito.
Archivo 'T1074.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1074.002' con éxito.
Archivo 'T1098.006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1098.006' con éxito.
Archivo 'T1053.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1053' con éxito.
Archivo 'T1218.007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1218.007' con éxito.
Archivo 'T1590.003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1590.003' con éxito.
Archivo 'T1498.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1498.002' con éxito.
Archivo 'T1556.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1556.002' con éxito.
Archivo 'T1505.005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1505.005' con éxito.
Archivo 'T1059.002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1059.002' con éxito.
Archivo 'T1176.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\techniques\T1176' con éxito.

##### **2. Tácticas**

In [16]:
input_file = f'[MITRE]_{mitre_domain}_tactics.csv'
tactics_information_df = pd.read_csv(os.path.join(input_path, 'tactics', input_file), sep=';', quotechar='"')
tactics_information_df.head(3)

,tactic_ID,tactic,tactic_url,tactic_description,matrix_domains
0,TA0006,Credential Access,https://attack.mitre.org/tactics/TA0006,The adversary is trying to steal account names...,['enterprise-attack']
1,TA0002,Execution,https://attack.mitre.org/tactics/TA0002,The adversary is trying to run malicious code....,['enterprise-attack']
2,TA0040,Impact,https://attack.mitre.org/tactics/TA0040,"The adversary is trying to manipulate, interru...",['enterprise-attack']

In [17]:
column_list = ['technique_ID','tactic_ID','platform_ID','platform','group_ID','data_source_ID']
for col in tactics_information_df.columns:
    if col in column_list:
        print(col)
        tactics_information_df[col] = format_cols_for_md(tactics_information_df[col])
    else:
        tactics_information_df[col] =  replace_chars(tactics_information_df[col])
tactics_information_df.columns = tactics_information_df.columns.str.replace('_', ' ', regex=False)
tactics_information_df.head(3)

tactic_ID

,tactic ID,tactic,tactic url,tactic description,matrix domains
0,[[TA0006]],Credential Access,https://attack.mitre.org/tactics/TA0006,The adversary is trying to steal account names...,enterprise-attack
1,[[TA0002]],Execution,https://attack.mitre.org/tactics/TA0002,The adversary is trying to run malicious code....,enterprise-attack
2,[[TA0040]],Impact,https://attack.mitre.org/tactics/TA0040,"The adversary is trying to manipulate, interru...",enterprise-attack

In [18]:
generate_tactic_information_md(tactics_information_df, output_folder, 'tactics', mitre_domain)

Archivo 'TA0006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0006' con éxito.
Archivo 'TA0002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0002' con éxito.
Archivo 'TA0040.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0040' con éxito.
Archivo 'TA0003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0003' con éxito.
Archivo 'TA0004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0004' con éxito.
Archivo 'TA0008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0008' con éxito.
Archivo 'TA0005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0005' con éxito.
Archivo 'TA0010.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0010' con éxito.
Archivo 'TA0007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0007' con éxito.
Archivo 'TA0009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0009' con éxito.
Archivo 'TA0042.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0042' con éxito.
Archivo 'TA0043.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0043' con éxito.
Archivo 'TA0011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0011' con éxito.
Archivo 'TA0001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\tactics\TA0001' con éxito.

##### **3. Plataformas**

In [19]:
input_file = f'[MITRE]_{mitre_domain}_platforms.csv'
platforms_information_df = pd.read_csv(os.path.join(input_path, 'platforms', input_file), sep=';', quotechar='"')
platforms_information_df.head(3)

           platform
0          Azure AD
1        Containers
2  Google Workspace

In [20]:
column_list = ['technique_ID','tactic_ID','platform_ID','platform','group_ID','data_source_ID']
for col in platforms_information_df.columns:
    if col in column_list:
        print(col)
        platforms_information_df[col] = format_cols_for_md(platforms_information_df[col])
    else:
        platforms_information_df[col] =  replace_chars(platforms_information_df[col])
platforms_information_df.columns = platforms_information_df.columns.str.replace('_', ' ', regex=False)
platforms_information_df.head(3)

platform

               platform
0          [[Azure AD]]
1        [[Containers]]
2  [[Google Workspace]]

In [21]:
generate_platform_information_md(platforms_information_df, output_folder, 'platforms', mitre_domain)

Archivo 'Azure AD.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\Azure AD' con éxito.
Archivo 'Containers.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\Containers' con éxito.
Archivo 'Google Workspace.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\Google Workspace' con éxito.
Archivo 'IaaS.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\IaaS' con éxito.
Archivo 'Linux.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\Linux' con éxito.
Archivo 'Network.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\Network' con éxito.
Archivo 'nan.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\nan' con éxito.
Archivo 'Office 365.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\Office 365' con éxito.
Archivo 'PRE.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\PRE' con éxito.
Archivo 'SaaS.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\SaaS' con éxito.
Archivo 'Windows.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\Windows' con éxito.
Archivo 'macOS.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\platforms\macOS' con éxito.

##### **4. Data Sources**

In [22]:
input_file = f'[MITRE]_{mitre_domain}_datasources.csv'
datasources_information_df = pd.read_csv(os.path.join(input_path, 'datasources', input_file), sep=';', quotechar='"')
datasources_information_df.head(3)

,data_source_ID,data_source,data_source_url,data_source_description,data_source_deprecated,data_source_revoked,matrix_domains
0,DS0029,Network Traffic,https://attack.mitre.org/datasources/DS0029,"Data transmitted across a network (ex: Web, DN...",False,False,"['enterprise-attack', 'mobile-attack']"
1,DS0030,Instance,https://attack.mitre.org/datasources/DS0030,A virtual server environment which runs worklo...,False,False,['enterprise-attack']
2,DS0019,Service,https://attack.mitre.org/datasources/DS0019,A computer process that is configured to execu...,False,False,['enterprise-attack']

In [23]:
column_list = ['technique_ID','tactic_ID','platform_ID','platform','group_ID','data_source_ID']
for col in datasources_information_df.columns:
    if col in column_list:
        print(col)
        datasources_information_df[col] = format_cols_for_md(datasources_information_df[col])
    else:
        datasources_information_df[col] =  replace_chars(datasources_information_df[col])
datasources_information_df.columns = datasources_information_df.columns.str.replace('_', ' ', regex=False)
datasources_information_df.head(3)

data_source_ID

,data source ID,data source,data source url,data source description,data source deprecated,data source revoked,matrix domains
0,[[DS0029]],Network Traffic,https://attack.mitre.org/datasources/DS0029,"Data transmitted across a network (ex: Web, DN...",False,False,"enterprise-attack, mobile-attack"
1,[[DS0030]],Instance,https://attack.mitre.org/datasources/DS0030,A virtual server environment which runs worklo...,False,False,enterprise-attack
2,[[DS0019]],Service,https://attack.mitre.org/datasources/DS0019,A computer process that is configured to execu...,False,False,enterprise-attack

In [24]:
generate_datasource_information_md(datasources_information_df, output_folder, 'data sources', mitre_domain)

Archivo 'DS0029.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0029' con éxito.
Archivo 'DS0030.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0030' con éxito.
Archivo 'DS0019.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0019' con éxito.
Archivo 'DS0022.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0022' con éxito.
Archivo 'DS0009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0009' con éxito.
Archivo 'DS0002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0002' con éxito.
Archivo 'DS0006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0006' con éxito.
Archivo 'DS0035.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0035' con éxito.
Archivo 'DS0028.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0028' con éxito.
Archivo 'DS0024.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0024' con éxito.
Archivo 'DS0017.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0017' con éxito.
Archivo 'DS0010.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0010' con éxito.
Archivo 'DS0003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0003' con éxito.
Archivo 'DS0026.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0026' con éxito.
Archivo 'DS0032.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0032' con éxito.
Archivo 'DS0023.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0023' con éxito.
Archivo 'DS0011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0011' con éxito.
Archivo 'DS0027.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0027' con éxito.
Archivo 'DS0016.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0016' con éxito.
Archivo 'DS0015.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0015' con éxito.
Archivo 'DS0012.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0012' con éxito.
Archivo 'DS0037.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0037' con éxito.
Archivo 'DS0001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0001' con éxito.
Archivo 'DS0020.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0020' con éxito.
Archivo 'DS0036.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0036' con éxito.
Archivo 'DS0007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0007' con éxito.
Archivo 'DS0004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0004' con éxito.
Archivo 'DS0013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0013' con éxito.
Archivo 'DS0033.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0033' con éxito.
Archivo 'DS0005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0005' con éxito.
Archivo 'DS0025.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0025' con éxito.
Archivo 'DS0038.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0038' con éxito.
Archivo 'DS0008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0008' con éxito.
Archivo 'DS0021.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0021' con éxito.
Archivo 'DS0018.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0018' con éxito.
Archivo 'DS0034.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0034' con éxito.
Archivo 'DS0014.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0014' con éxito.
Archivo 'DS0031.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\data sources\DS0031' con éxito.

##### **5. Grupos**

In [25]:
input_file = f'[MITRE]_{mitre_domain}_groups.csv'
groups_information_df = pd.read_csv(os.path.join(input_path, 'groups', input_file), sep=';', quotechar='"')
groups_information_df.head(3)

,group_ID,group,group_aliases,group_url,group_description,group_deprecated,group_revoked,matrix_domains
0,G0001,Axiom,"['Axiom', 'Group 72']",https://attack.mitre.org/groups/G0001,[Axiom](https://attack.mitre.org/groups/G0001)...,False,False,['enterprise-attack']
1,G0002,Moafee,['Moafee'],https://attack.mitre.org/groups/G0002,[Moafee](https://attack.mitre.org/groups/G0002...,False,False,['enterprise-attack']
2,G0003,Cleaver,"['Cleaver', 'Threat Group 2889', 'TG-2889']",https://attack.mitre.org/groups/G0003,[Cleaver](https://attack.mitre.org/groups/G000...,False,False,['enterprise-attack']

In [26]:
column_list = ['technique_ID','tactic_ID','platform_ID','platform','group_ID','data_source_ID']
for col in groups_information_df.columns:
    if col in column_list:
        print(col)
        groups_information_df[col] = format_cols_for_md(groups_information_df[col])
    else:
        groups_information_df[col] =  replace_chars(groups_information_df[col])
groups_information_df.columns = groups_information_df.columns.str.replace('_', ' ', regex=False)
groups_information_df.head(3)

group_ID

,group ID,group,group aliases,group url,group description,group deprecated,group revoked,matrix domains
0,[[G0001]],Axiom,"Axiom, Group 72",https://attack.mitre.org/groups/G0001,[Axiom](https://attack.mitre.org/groups/G0001)...,False,False,enterprise-attack
1,[[G0002]],Moafee,Moafee,https://attack.mitre.org/groups/G0002,[Moafee](https://attack.mitre.org/groups/G0002...,False,False,enterprise-attack
2,[[G0003]],Cleaver,"Cleaver, Threat Group 2889, TG-2889",https://attack.mitre.org/groups/G0003,[Cleaver](https://attack.mitre.org/groups/G000...,False,False,enterprise-attack

In [27]:
generate_group_information_md(groups_information_df, output_folder, 'groups', mitre_domain)

Archivo 'G0001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0001' con éxito.
Archivo 'G0002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0002' con éxito.
Archivo 'G0003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0003' con éxito.
Archivo 'G0004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0004' con éxito.
Archivo 'G0005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0005' con éxito.
Archivo 'G0006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0006' con éxito.

Archivo 'G0007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0007' con éxito.
Archivo 'G0008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0008' con éxito.
Archivo 'G0009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0009' con éxito.
Archivo 'G0010.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0010' con éxito.
Archivo 'G0011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0011' con éxito.
Archivo 'G0012.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0012' con éxito.
Archivo 'G0013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0013' con éxito.
Archivo 'G0016.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0016' con éxito.
Archivo 'G0017.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0017' con éxito.
Archivo 'G0018.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0018' con éxito.
Archivo 'G0019.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0019' con éxito.
Archivo 'G0020.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0020' con éxito.
Archivo 'G0021.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0021' con éxito.
Archivo 'G0022.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0022' con éxito.
Archivo 'G0023.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0023' con éxito.
Archivo 'G0024.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0024' con éxito.
Archivo 'G0025.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0025' con éxito.
Archivo 'G0026.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0026' con éxito.
Archivo 'G0027.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0027' con éxito.
Archivo 'G0028.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0028' con éxito.
Archivo 'G0029.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0029' con éxito.
Archivo 'G0030.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0030' con éxito.
Archivo 'G0032.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0032' con éxito.
Archivo 'G0033.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0033' con éxito.
Archivo 'G0034.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0034' con éxito.
Archivo 'G0035.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0035' con éxito.
Archivo 'G0036.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0036' con éxito.
Archivo 'G0037.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0037' con éxito.
Archivo 'G0038.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0038' con éxito.
Archivo 'G0039.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0039' con éxito.
Archivo 'G0040.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0040' con éxito.
Archivo 'G0041.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0041' con éxito.
Archivo 'G0043.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0043' con éxito.
Archivo 'G0044.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0044' con éxito.
Archivo 'G0045.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0045' con éxito.
Archivo 'G0046.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0046' con éxito.
Archivo 'G0047.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0047' con éxito.
Archivo 'G0048.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0048' con éxito.
Archivo 'G0049.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0049' con éxito.
Archivo 'G0050.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0050' con éxito.
Archivo 'G0051.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0051' con éxito.
Archivo 'G0052.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0052' con éxito.
Archivo 'G0053.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0053' con éxito.
Archivo 'G0054.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0054' con éxito.
Archivo 'G0055.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0055' con éxito.
Archivo 'G0056.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0056' con éxito.
Archivo 'G0059.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0059' con éxito.
Archivo 'G0060.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0060' con éxito.
Archivo 'G0061.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0061' con éxito.
Archivo 'G0062.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0062' con éxito.
Archivo 'G0063.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0063' con éxito.
Archivo 'G0064.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0064' con éxito.
Archivo 'G0065.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0065' con éxito.
Archivo 'G0066.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0066' con éxito.
Archivo 'G0067.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0067' con éxito.
Archivo 'G0068.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0068' con éxito.
Archivo 'G0069.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0069' con éxito.
Archivo 'G0070.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0070' con éxito.
Archivo 'G0071.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0071' con éxito.
Archivo 'G0073.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0073' con éxito.
Archivo 'G0075.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0075' con éxito.
Archivo 'G0076.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0076' con éxito.
Archivo 'G0077.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0077' con éxito.
Archivo 'G0078.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0078' con éxito.
Archivo 'G0079.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0079' con éxito.
Archivo 'G0080.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0080' con éxito.
Archivo 'G0081.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0081' con éxito.
Archivo 'G0082.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0082' con éxito.
Archivo 'G0083.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0083' con éxito.
Archivo 'G0084.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0084' con éxito.
Archivo 'G0085.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0085' con éxito.
Archivo 'G0087.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0087' con éxito.
Archivo 'G0088.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0088' con éxito.
Archivo 'G0089.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0089' con éxito.
Archivo 'G0090.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0090' con éxito.
Archivo 'G0091.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0091' con éxito.
Archivo 'G0092.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0092' con éxito.
Archivo 'G0093.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0093' con éxito.
Archivo 'G0094.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0094' con éxito.
Archivo 'G0095.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0095' con éxito.
Archivo 'G0096.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0096' con éxito.
Archivo 'G0098.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0098' con éxito.
Archivo 'G0099.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0099' con éxito.
Archivo 'G0100.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0100' con éxito.
Archivo 'G0102.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0102' con éxito.
Archivo 'G0103.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0103' con éxito.
Archivo 'G0105.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0105' con éxito.
Archivo 'G0106.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0106' con éxito.
Archivo 'G0107.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0107' con éxito.
Archivo 'G0108.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0108' con éxito.
Archivo 'G0112.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0112' con éxito.
Archivo 'G0114.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0114' con éxito.
Archivo 'G0115.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0115' con éxito.
Archivo 'G0117.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0117' con éxito.
Archivo 'G0119.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0119' con éxito.
Archivo 'G0120.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0120' con éxito.
Archivo 'G0121.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0121' con éxito.
Archivo 'G0122.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0122' con éxito.
Archivo 'G0123.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0123' con éxito.
Archivo 'G0124.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0124' con éxito.
Archivo 'G0125.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0125' con éxito.
Archivo 'G0126.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0126' con éxito.
Archivo 'G0127.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0127' con éxito.
Archivo 'G0128.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0128' con éxito.
Archivo 'G0129.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0129' con éxito.
Archivo 'G0130.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0130' con éxito.
Archivo 'G0131.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0131' con éxito.
Archivo 'G0133.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0133' con éxito.
Archivo 'G0134.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0134' con éxito.
Archivo 'G0135.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0135' con éxito.
Archivo 'G0136.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0136' con éxito.
Archivo 'G0137.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0137' con éxito.
Archivo 'G0138.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0138' con éxito.
Archivo 'G0139.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0139' con éxito.
Archivo 'G0140.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\groups\G0140' con éxito.

##### **6. Software**

In [28]:
input_file = f'[MITRE]_{mitre_domain}_software.csv'
software_information_df = pd.read_csv(os.path.join(input_path, 'software', input_file), sep=';', quotechar='"')
software_information_df.head(3)

,software_ID,software,software_type,software_url,software_description,software_deprecated,software_revoked,matrix_domains
0,S0001,Trojan.Mebromi,malware,https://attack.mitre.org/software/S0001,[Trojan.Mebromi](https://attack.mitre.org/soft...,False,False,['enterprise-attack']
1,S0002,Mimikatz,tool,https://attack.mitre.org/software/S0002,[Mimikatz](https://attack.mitre.org/software/S...,False,False,['enterprise-attack']
2,S0003,RIPTIDE,malware,https://attack.mitre.org/software/S0003,[RIPTIDE](https://attack.mitre.org/software/S0...,False,False,['enterprise-attack']

In [29]:
column_list = ['technique_ID','tactic_ID','platform_ID','platform','group_ID','data_source_ID']
for col in software_information_df.columns:
    if col in column_list:
        print(col)
        software_information_df[col] = format_cols_for_md(software_information_df[col])
    else:
        software_information_df[col] =  replace_chars(software_information_df[col])
software_information_df.columns = software_information_df.columns.str.replace('_', ' ', regex=False)
software_information_df.head(3)

,software ID,software,software type,software url,software description,software deprecated,software revoked,matrix domains
0,S0001,Trojan.Mebromi,malware,https://attack.mitre.org/software/S0001,[Trojan.Mebromi](https://attack.mitre.org/soft...,False,False,enterprise-attack
1,S0002,Mimikatz,tool,https://attack.mitre.org/software/S0002,[Mimikatz](https://attack.mitre.org/software/S...,False,False,enterprise-attack
2,S0003,RIPTIDE,malware,https://attack.mitre.org/software/S0003,[RIPTIDE](https://attack.mitre.org/software/S0...,False,False,enterprise-attack

In [30]:
generate_software_information_md(software_information_df, output_folder, 'software', mitre_domain)

Archivo 'S0001.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0001' con éxito.
Archivo 'S0002.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0002' con éxito.
Archivo 'S0003.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0003' con éxito.
Archivo 'S0004.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0004' con éxito.
Archivo 'S0005.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0005' con éxito.
Archivo 'S0006.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0006' con éxito.
Archivo 'S0007.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0007' con éxito.
Archivo 'S0008.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0008' con éxito.
Archivo 'S0009.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0009' con éxito.
Archivo 'S0010.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0010' con éxito.
Archivo 'S0011.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0011' con éxito.
Archivo 'S0012.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0012' con éxito.
Archivo 'S0013.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0013' con éxito.
Archivo 'S0014.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0014' con éxito.
Archivo 'S0015.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0015' con éxito.
Archivo 'S0016.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0016' con éxito.
Archivo 'S0017.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0017' con éxito.
Archivo 'S0018.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0018' con éxito.
Archivo 'S0019.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0019' con éxito.
Archivo 'S0020.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0020' con éxito.
Archivo 'S0021.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0021' con éxito.
Archivo 'S0022.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0022' con éxito.
Archivo 'S0023.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0023' con éxito.
Archivo 'S0024.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0024' con éxito.
Archivo 'S0025.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0025' con éxito.
Archivo 'S0026.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0026' con éxito.
Archivo 'S0027.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0027' con éxito.
Archivo 'S0028.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0028' con éxito.
Archivo 'S0029.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0029' con éxito.
Archivo 'S0030.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0030' con éxito.
Archivo 'S0031.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0031' con éxito.
Archivo 'S0032.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0032' con éxito.
Archivo 'S0033.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0033' con éxito.
Archivo 'S0034.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0034' con éxito.
Archivo 'S0035.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0035' con éxito.
Archivo 'S0036.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0036' con éxito.
Archivo 'S0037.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0037' con éxito.
Archivo 'S0038.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0038' con éxito.
Archivo 'S0039.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0039' con éxito.
Archivo 'S0040.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0040' con éxito.
Archivo 'S0041.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0041' con éxito.
Archivo 'S0042.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0042' con éxito.
Archivo 'S0043.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0043' con éxito.
Archivo 'S0044.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0044' con éxito.
Archivo 'S0045.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0045' con éxito.
Archivo 'S0046.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0046' con éxito.
Archivo 'S0047.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0047' con éxito.
Archivo 'S0048.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0048' con éxito.
Archivo 'S0049.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0049' con éxito.
Archivo 'S0050.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0050' con éxito.
Archivo 'S0051.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0051' con éxito.
Archivo 'S0052.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0052' con éxito.
Archivo 'S0053.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0053' con éxito.
Archivo 'S0054.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0054' con éxito.
Archivo 'S0055.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0055' con éxito.
Archivo 'S0056.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0056' con éxito.
Archivo 'S0057.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0057' con éxito.
Archivo 'S0058.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0058' con éxito.
Archivo 'S0059.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0059' con éxito.
Archivo 'S0060.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0060' con éxito.
Archivo 'S0061.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0061' con éxito.
Archivo 'S0062.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0062' con éxito.
Archivo 'S0063.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0063' con éxito.
Archivo 'S0064.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0064' con éxito.
Archivo 'S0065.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0065' con éxito.
Archivo 'S0066.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0066' con éxito.
Archivo 'S0067.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0067' con éxito.
Archivo 'S0068.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0068' con éxito.
Archivo 'S0069.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0069' con éxito.
Archivo 'S0070.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0070' con éxito.
Archivo 'S0071.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0071' con éxito.
Archivo 'S0072.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0072' con éxito.
Archivo 'S0073.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0073' con éxito.
Archivo 'S0074.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0074' con éxito.
Archivo 'S0075.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0075' con éxito.
Archivo 'S0076.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0076' con éxito.
Archivo 'S0077.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0077' con éxito.
Archivo 'S0078.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0078' con éxito.
Archivo 'S0079.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0079' con éxito.
Archivo 'S0080.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0080' con éxito.
Archivo 'S0081.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0081' con éxito.
Archivo 'S0082.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0082' con éxito.
Archivo 'S0083.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0083' con éxito.
Archivo 'S0084.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0084' con éxito.
Archivo 'S0085.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0085' con éxito.
Archivo 'S0086.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0086' con éxito.
Archivo 'S0087.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0087' con éxito.
Archivo 'S0088.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0088' con éxito.
Archivo 'S0089.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0089' con éxito.
Archivo 'S0090.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0090' con éxito.
Archivo 'S0091.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0091' con éxito.
Archivo 'S0092.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0092' con éxito.
Archivo 'S0093.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0093' con éxito.
Archivo 'S0094.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0094' con éxito.
Archivo 'S0095.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0095' con éxito.
Archivo 'S0096.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0096' con éxito.
Archivo 'S0097.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0097' con éxito.
Archivo 'S0098.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0098' con éxito.
Archivo 'S0099.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0099' con éxito.
Archivo 'S0100.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0100' con éxito.
Archivo 'S0101.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0101' con éxito.
Archivo 'S0102.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0102' con éxito.
Archivo 'S0103.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0103' con éxito.
Archivo 'S0104.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0104' con éxito.
Archivo 'S0105.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0105' con éxito.
Archivo 'S0106.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0106' con éxito.
Archivo 'S0107.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0107' con éxito.
Archivo 'S0108.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0108' con éxito.
Archivo 'S0109.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0109' con éxito.
Archivo 'S0110.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0110' con éxito.
Archivo 'S0111.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0111' con éxito.
Archivo 'S0112.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0112' con éxito.
Archivo 'S0113.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0113' con éxito.
Archivo 'S0114.md' creado en la carpeta 'c:\Users\jelopez\Documents\CyberProof\python\develop\mitre_relationships\outputs\information_md\enterprise\software\S0114' con éxito.