In [ ]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on 2024-05-27

@author: Juan Enrique López

@description: Jupyter Notebook creado para descargar las reglas de diferentes fuentes y clasificarlas por TTP

"""

In [1]:
from attackcti import attack_client
import pandas as pd
import re
import wget
import zipfile

import os
from os import remove


from shutil import rmtree
import shutil
from toml import TomlDecodeError
import re
import csv
import yaml
import toml
import yara

from collections import Counter

import numpy as np
import sys
import json

In [2]:
#temp_path = os.environ['TEMP']

temp_path = r'C:\Users\jelopez\Downloads'

path_actual = os.getcwd()

save_path = os.path.join(path_actual, 'saved')

In [3]:
# En primer lugar creamos la carpeta donde vamos a guardar las TTP's asociadas a esta fuente
def create_output_folder(path):
    if not os.path.exists(path):
        os.makedirs(path)

In [4]:
def download_unzip(url_zip, temp_path):
    #Descarga el fichero pasado por parametro
    wget.download(url_zip, os.path.join(temp_path, 'temp.zip'))
    #Descomprimir el fichero descargado y se borra el fichero descargado
    f_zip = zipfile.ZipFile(os.path.join(temp_path, 'temp.zip'))
    try:
        f_zip.extractall(path=temp_path)
    except:
        print('ERROR: MAX_PATH longer than 256 characters')
    f_zip.close()
    remove(os.path.join(temp_path, 'temp.zip'))

In [5]:
def download_folder_unzip(ruta, folder, temp_path):
    try:
        archivo_zip = wget.download(ruta, os.path.join(temp_path, 'temp.zip'))
        with zipfile.ZipFile(archivo_zip, 'r') as f_zip:
            for archivo in f_zip.namelist():
                if archivo.startswith(folder):
                    f_zip.extract(archivo, path=temp_path)
        os.remove(archivo_zip)
        print("Descarga y descompresión completadas correctamente.")
    except Exception as e:
        print('Error:', e)

In [6]:
def getListOfFilesSub(dirName):
    # Crea lista de ficheros y subdirectorios
    listOfFile = os.listdir(dirName)
    allFiles = list()
    #Recorre los directorios y subdirectorios y genera una lista con los ficheros encontrados en estos
    for entry in listOfFile:
        fullPath = os.path.join(dirName, entry)
        if os.path.isdir(fullPath):
            allFiles = allFiles + getListOfFilesSub(fullPath)
        else:
            allFiles.append(fullPath)
    #Devuelve la lista con los ficheros
    return allFiles

In [7]:
def get_folders(path):
    if not os.path.exists(path):
        raise ValueError("La ruta proporcionada no existe.")
    if not os.path.isdir(path):
        raise ValueError("La ruta proporcionada no es un directorio.")
    folders = [name for name in os.listdir(path) if os.path.isdir(os.path.join(path, name))]
    return folders

In [8]:
def techniques():
    lift = attack_client()
    #Solicitud a la libreria attackcti la extraccion de las tecnicas Enterprise y normalizar el json en un dataframe
    techniques = lift.get_enterprise_techniques(stix_format=False)
    techniques = pd.json_normalize(techniques)
    #Eliminar las tecnicas deprecadas y revocadas
    techniques = techniques[(techniques['mitre_deprecated'] != True)]
    # Eliminamos duplicados y convertimos en lista
    techniques = techniques['technique_id'].drop_duplicates().tolist()
    techniques = sorted(techniques, key=len, reverse=True)
    return techniques

In [9]:
techniques_enterprise = techniques()
techniques_enterprise[0:3]

[taxii2client.v20] [WARNING ] [2024-05-28 12:31:44,653] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-05-28 12:31:44,677] TAXII Server Response with different amount of objects! Setting per_request=780

['T1059.010', 'T1564.012', 'T1027.013']

In [10]:
# Buscamos en la columna de descripción o informativa
def find_techniques(texto):
    if isinstance(texto, str):
        found = []
        for item in techniques_enterprise:
            if item in texto:
                found.append(item)
        return ', '.join(found)
    else:
        return ''

In [11]:
def find_techniques_in_list(cadena, techniques_enterprise):
    for item in techniques_enterprise:
        if item in cadena:
            return item
    return None

In [12]:
def clean_names(name):
    delete_chars = r'[\/\\|,";:#\[\]]'
    name = re.sub(delete_chars, '', name)
    name = " ".join(name.split())
    return name.strip()

In [13]:
def copy_file_to_path(item_path, save_path, ttp_name):
    if not os.path.exists(os.path.join(save_path, ttp_name)):
        os.makedirs(os.path.join(save_path, ttp_name))
    shutil.copy(item_path,os.path.join(save_path, ttp_name))
    print('Copiado correctamente a la carpeta de la TTP: '+ ttp_name)

In [14]:
class NotTTPatTags(Exception):
    def __init__(self, mensaje):
        self.mensaje = mensaje
        super().__init__(self.mensaje)

In [15]:
def get_unique_items(list_paths):
    from pathlib import Path
    unique_list = []
    for item_path in list_paths:
        unique_list.append(Path(item_path).name)
    unique_list = list(set(unique_list))
    return unique_list

In [16]:
def copy_files_between_paths(path_source, path_destiny):
    if not os.path.exists(path_source):
        raise ValueError(f"El directorio de origen '{path_source}' no existe.")
    if not os.path.isdir(path_source):
        raise ValueError(f"'{path_source}' no es un directorio.")
    # Si el directorio de destino no existe, crearlo
    if not os.path.exists(path_destiny):
        os.makedirs(path_destiny)
    for item in os.listdir(path_source):
        if item != '.DS_Store': 
            src_path = os.path.join(path_source, item)
            dst_path = os.path.join(path_destiny, item)
            if os.path.isdir(src_path):
                shutil.copytree(src_path, dst_path, dirs_exist_ok=True)
            else:
                shutil.copy2(src_path, dst_path)

In [17]:
#Función para devolver el numero de reglas que han sido asignadas a 2 o más ttps

def count_duplicate_rules(paths):
    # Extraer nombres de archivo de las rutas
    filenames = [os.path.basename(path) for path in paths]
    # Contar archivos repetidos
    file_counts = Counter(filenames)
    # Obtener solo los archivos que están repetidos
    duplicates = {filename: count for filename, count in file_counts.items() if count > 1}
    return duplicates

In [16]:
# path_techniques = 'C:/Users/jelopez/Documents/CyberProof/python/recursos/id_tecnicas_16052024.csv'
# techniques_enterprise = pd.read_csv(path_techniques)
# techniques_enterprise = techniques_enterprise['ID Tecnica'].to_list()
# techniques_enterprise = sorted(techniques_enterprise, key=len, reverse=True)
# techniques_enterprise[:3]

['T1059.010', 'T1564.012', 'T1027.013']

#### TTP's Mappings

In [18]:
zip_mappings = 'https://github.com/center-for-threat-informed-defense/security-stack-mappings/archive/refs/heads/main.zip'
save_path_mappings = os.path.join(save_path, 'mappings')
unzip_folder = r'security-stack-mappings-main/mappings/'

In [20]:
download_folder_unzip(zip_mappings, unzip_folder, temp_path)

Descarga y descompresión completadas correctamente.

In [22]:
create_output_folder(save_path_mappings)

In [23]:
files = getListOfFilesSub(os.path.join(temp_path, unzip_folder))
len(files)

343

In [ ]:
# Vamos a utilizar el mismo metodo que en yaras y atomic de tal forma que leemos todo el contenido del archivo y mapeamos con las técnicas disponibles

In [25]:
num_yamls = []
ttp_in_filename = []
content_in_yaml = []
no_content_in_yaml = []
ttp_in_yaml = []
error_load = []
no_ttp_in_content_or_filename = []


for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yaml' or extension == '.yml':
        with open(item, 'r', encoding='utf-8') as file:
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y se revisa el nombre del fichero antes de copiar el fichero a la carpeta T0000
                yaml_content = file.read()
                yaml_content = yaml_content.upper()
                num_yamls.append(item)
                # Revisamos que se haya podido obtener texto del contenido del .yaml 
                if isinstance(yaml_content, str):
                    ttps = find_techniques(yaml_content)
                    ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                    content_in_yaml.append(item)
                else:
                    #Si el contenido no dispone de texto, buscamos ttps en el propio nombre del fichero
                    ttps = find_techniques(item.upper())
                    ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                    no_content_in_yaml.append(item)
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_yaml.append(item)
                            copy_file_to_path(item, save_path_mappings, ttp)
                
                #En cualquier caso, siempre buscamos ttp en el nombre del fichero
                ttps = find_techniques(item.upper())
                ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_filename.append(item)
                            copy_file_to_path(item, save_path_mappings, ttp)
                else:
                    copy_file_to_path(item, save_path_mappings, 'T0000')

            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except Exception as e:
                print(f"Error al intentar leer el archivo markdown: {e}")
                error_load.append(item)
                ttps = find_techniques(item.upper())
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_filename.append(item)
                            copy_file_to_path(item, save_path_mappings, ttp)
                else:
                    copy_file_to_path(item, save_path_mappings, 'T0000')

Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110.004
Copiado correctamente a la carpeta de la TTP: T1110.003
Copiado correctamente a la carpeta de la TTP: T1110.002
Copiado correctamente a la carpeta de la TTP: T1110.001
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1562.008
Copiado correctamente a la carpeta de la TTP: T1595.002
Copiado correctamente a la carpeta de la TTP: T1595.001
Copiado correctamente a la carpeta de la TTP: T1098.004
Copiado correctamente a la carpeta de la TTP: T1562.006
Copiado correctamente a la carpeta de la TTP: T1071.004
Copiado correctamente a la carpeta de la TTP: T1071.003
Copiado correctamente a la carpeta de la TTP: T1071.002
Copiado correctamente a la carpeta de la TTP: T1071.001
Copiado correctamente a la carpeta de la TTP: T1048.003
Copiado correctamente a la carpeta de la TTP: T1090.003
Copiado correctamente a la carpeta de la TTP: T1090.002
Copiado correctamente a la carpeta de la TTP: T1090.001
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.001
Copiado correctamente a la carpeta de la TTP: T1568.002
Copiado correctamente a la carpeta de la TTP: T1567.002
Copiado correctamente a la carpeta de la TTP: T1567.001
Copiado correctamente a la carpeta de la TTP: T1498.002
Copiado correctamente a la carpeta de la TTP: T1498.001
Copiado correctamente a la carpeta de la TTP: T1566.003
Copiado correctamente a la carpeta de la TTP: T1566.002
Copiado correctamente a la carpeta de la TTP: T1566.001
Copiado correctamente a la carpeta de la TTP: T1565.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1491.002
Copiado correctamente a la carpeta de la TTP: T1491.001
Copiado correctamente a la carpeta de la TTP: T1552.005
Copiado correctamente a la carpeta de la TTP: T1110.004
Copiado correctamente a la carpeta de la TTP: T1110.003
Copiado correctamente a la carpeta de la TTP: T1110.001
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1098.001
Copiado correctamente a la carpeta de la TTP: T1595
Copiado correctamente a la carpeta de la TTP: T1580
Copiado correctamente a la carpeta de la TTP: T1571
Copiado correctamente a la carpeta de la TTP: T1568
Copiado correctamente a la carpeta de la TTP: T1567
Copiado correctamente a la carpeta de la TTP: T1566
Copiado correctamente a la carpeta de la TTP: T1565
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1531
Copiado correctamente a la carpeta de la TTP: T1530
Copiado correctamente a la carpeta de la TTP: T1526
Copiado correctamente a la carpeta de la TTP: T1498
Copiado correctamente a la carpeta de la TTP: T1496
Copiado correctamente a la carpeta de la TTP: T1491
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1189
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1071
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1041
Copiado correctamente a la carpeta de la TTP: T1029
Copiado correctamente a la carpeta de la TTP: T1020
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1599.001
Copiado correctamente a la carpeta de la TTP: T1053.006
Copiado correctamente a la carpeta de la TTP: T1595.002
Copiado correctamente a la carpeta de la TTP: T1595.001
Copiado correctamente a la carpeta de la TTP: T1562.006
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.003
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1003.008
Copiado correctamente a la carpeta de la TTP: T1003.007
Copiado correctamente a la carpeta de la TTP: T1110.004
Copiado correctamente a la carpeta de la TTP: T1110.003
Copiado correctamente a la carpeta de la TTP: T1110.002
Copiado correctamente a la carpeta de la TTP: T1110.001
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1222.002
Copiado correctamente a la carpeta de la TTP: T1070.006
Copiado correctamente a la carpeta de la TTP: T1070.005
Copiado correctamente a la carpeta de la TTP: T1070.004
Copiado correctamente a la carpeta de la TTP: T1070.003
Copiado correctamente a la carpeta de la TTP: T1548.003
Copiado correctamente a la carpeta de la TTP: T1070.002
Copiado correctamente a la carpeta de la TTP: T1543.002
Copiado correctamente a la carpeta de la TTP: T1037.004
Copiado correctamente a la carpeta de la TTP: T1053.003
Copiado correctamente a la carpeta de la TTP: T1599
Copiado correctamente a la carpeta de la TTP: T1595
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1543
Copiado correctamente a la carpeta de la TTP: T1529
Copiado correctamente a la carpeta de la TTP: T1489
Copiado correctamente a la carpeta de la TTP: T1222
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1212
Copiado correctamente a la carpeta de la TTP: T1189
Copiado correctamente a la carpeta de la TTP: T1211
Copiado correctamente a la carpeta de la TTP: T1210
Copiado correctamente a la carpeta de la TTP: T1203
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1037
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1567.002
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1567
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1530
Copiado correctamente a la carpeta de la TTP: T1537
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1602.002
Copiado correctamente a la carpeta de la TTP: T1542.005
Copiado correctamente a la carpeta de la TTP: T1602.001
Copiado correctamente a la carpeta de la TTP: T1557.002
Copiado correctamente a la carpeta de la TTP: T1595.002
Copiado correctamente a la carpeta de la TTP: T1595.001
Copiado correctamente a la carpeta de la TTP: T1590.006
Copiado correctamente a la carpeta de la TTP: T1590.005
Copiado correctamente a la carpeta de la TTP: T1590.004
Copiado correctamente a la carpeta de la TTP: T1590.001
Copiado correctamente a la carpeta de la TTP: T1205.001
Copiado correctamente a la carpeta de la TTP: T1048.003
Copiado correctamente a la carpeta de la TTP: T1048.002
Copiado correctamente a la carpeta de la TTP: T1048.001
Copiado correctamente a la carpeta de la TTP: T1090.003
Copiado correctamente a la carpeta de la TTP: T1090.002
Copiado correctamente a la carpeta de la TTP: T1090.001
Copiado correctamente a la carpeta de la TTP: T1565.002
Copiado correctamente a la carpeta de la TTP: T1499.003
Copiado correctamente a la carpeta de la TTP: T1499.002
Copiado correctamente a la carpeta de la TTP: T1499.001
Copiado correctamente a la carpeta de la TTP: T1557.001
Copiado correctamente a la carpeta de la TTP: T1021.006
Copiado correctamente a la carpeta de la TTP: T1021.005
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1602
Copiado correctamente a la carpeta de la TTP: T1595
Copiado correctamente a la carpeta de la TTP: T1590
Copiado correctamente a la carpeta de la TTP: T1571
Copiado correctamente a la carpeta de la TTP: T1570
Copiado correctamente a la carpeta de la TTP: T1565
Copiado correctamente a la carpeta de la TTP: T1557
Copiado correctamente a la carpeta de la TTP: T1542
Copiado correctamente a la carpeta de la TTP: T1499
Copiado correctamente a la carpeta de la TTP: T1498
Copiado correctamente a la carpeta de la TTP: T1482
Copiado correctamente a la carpeta de la TTP: T1219
Copiado correctamente a la carpeta de la TTP: T1205
Copiado correctamente a la carpeta de la TTP: T1199
Copiado correctamente a la carpeta de la TTP: T1210
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1095
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1072
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1040
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1018
Copiado correctamente a la carpeta de la TTP: T1008
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1565.001
Copiado correctamente a la carpeta de la TTP: T1561.002
Copiado correctamente a la carpeta de la TTP: T1561.001
Copiado correctamente a la carpeta de la TTP: T1491.002
Copiado correctamente a la carpeta de la TTP: T1491.001
Copiado correctamente a la carpeta de la TTP: T1565
Copiado correctamente a la carpeta de la TTP: T1561
Copiado correctamente a la carpeta de la TTP: T1491
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1588.004
Copiado correctamente a la carpeta de la TTP: T1588.003
Copiado correctamente a la carpeta de la TTP: T1553.004
Copiado correctamente a la carpeta de la TTP: T1553.002
Copiado correctamente a la carpeta de la TTP: T1552.004
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1588
Copiado correctamente a la carpeta de la TTP: T1553
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1610
Copiado correctamente a la carpeta de la TTP: T1496
Copiado correctamente a la carpeta de la TTP: T1040
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1552.007
Copiado correctamente a la carpeta de la TTP: T1204.003
Copiado correctamente a la carpeta de la TTP: T1053.007
Copiado correctamente a la carpeta de la TTP: T1020.001
Copiado correctamente a la carpeta de la TTP: T1562.008
Copiado correctamente a la carpeta de la TTP: T1562.007
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1498.002
Copiado correctamente a la carpeta de la TTP: T1498.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1499.004
Copiado correctamente a la carpeta de la TTP: T1499.003
Copiado correctamente a la carpeta de la TTP: T1499.002
Copiado correctamente a la carpeta de la TTP: T1499.001
Copiado correctamente a la carpeta de la TTP: T1491.002
Copiado correctamente a la carpeta de la TTP: T1491.001
Copiado correctamente a la carpeta de la TTP: T1552.005
Copiado correctamente a la carpeta de la TTP: T1110.004
Copiado correctamente a la carpeta de la TTP: T1110.003
Copiado correctamente a la carpeta de la TTP: T1110.002
Copiado correctamente a la carpeta de la TTP: T1110.001
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1136.003
Copiado correctamente a la carpeta de la TTP: T1098.001
Copiado correctamente a la carpeta de la TTP: T1613
Copiado correctamente a la carpeta de la TTP: T1611
Copiado correctamente a la carpeta de la TTP: T1610
Copiado correctamente a la carpeta de la TTP: T1609
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1557
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1525
Copiado correctamente a la carpeta de la TTP: T1538
Copiado correctamente a la carpeta de la TTP: T1530
Copiado correctamente a la carpeta de la TTP: T1499
Copiado correctamente a la carpeta de la TTP: T1498
Copiado correctamente a la carpeta de la TTP: T1496
Copiado correctamente a la carpeta de la TTP: T1491
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1212
Copiado correctamente a la carpeta de la TTP: T1211
Copiado correctamente a la carpeta de la TTP: T1204
Copiado correctamente a la carpeta de la TTP: T1210
Copiado correctamente a la carpeta de la TTP: T1203
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1119
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T1040
Copiado correctamente a la carpeta de la TTP: T1020
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110.004
Copiado correctamente a la carpeta de la TTP: T1110.003
Copiado correctamente a la carpeta de la TTP: T1110.001
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1098.001
Copiado correctamente a la carpeta de la TTP: T1550
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1020.001
Copiado correctamente a la carpeta de la TTP: T1562.008
Copiado correctamente a la carpeta de la TTP: T1048.003
Copiado correctamente a la carpeta de la TTP: T1048.002
Copiado correctamente a la carpeta de la TTP: T1048.001
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1552.004
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1557
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1530
Copiado correctamente a la carpeta de la TTP: T1496
Copiado correctamente a la carpeta de la TTP: T1095
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1071
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1041
Copiado correctamente a la carpeta de la TTP: T1040
Copiado correctamente a la carpeta de la TTP: T1020
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1588.004
Copiado correctamente a la carpeta de la TTP: T1588.003
Copiado correctamente a la carpeta de la TTP: T1552.004
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1588
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1542.005
Copiado correctamente a la carpeta de la TTP: T1595.002
Copiado correctamente a la carpeta de la TTP: T1595.001
Copiado correctamente a la carpeta de la TTP: T1590.006
Copiado correctamente a la carpeta de la TTP: T1590.005
Copiado correctamente a la carpeta de la TTP: T1590.004
Copiado correctamente a la carpeta de la TTP: T1590.001
Copiado correctamente a la carpeta de la TTP: T1205.001
Copiado correctamente a la carpeta de la TTP: T1071.004
Copiado correctamente a la carpeta de la TTP: T1071.003
Copiado correctamente a la carpeta de la TTP: T1071.002
Copiado correctamente a la carpeta de la TTP: T1071.001
Copiado correctamente a la carpeta de la TTP: T1048.003
Copiado correctamente a la carpeta de la TTP: T1048.002
Copiado correctamente a la carpeta de la TTP: T1048.001
Copiado correctamente a la carpeta de la TTP: T1090.003
Copiado correctamente a la carpeta de la TTP: T1090.002
Copiado correctamente a la carpeta de la TTP: T1498.002
Copiado correctamente a la carpeta de la TTP: T1498.001
Copiado correctamente a la carpeta de la TTP: T1499.003
Copiado correctamente a la carpeta de la TTP: T1499.002
Copiado correctamente a la carpeta de la TTP: T1499.001
Copiado correctamente a la carpeta de la TTP: T1021.006
Copiado correctamente a la carpeta de la TTP: T1021.005
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1595
Copiado correctamente a la carpeta de la TTP: T1590
Copiado correctamente a la carpeta de la TTP: T1572
Copiado correctamente a la carpeta de la TTP: T1571
Copiado correctamente a la carpeta de la TTP: T1542
Copiado correctamente a la carpeta de la TTP: T1530
Copiado correctamente a la carpeta de la TTP: T1499
Copiado correctamente a la carpeta de la TTP: T1498
Copiado correctamente a la carpeta de la TTP: T1219
Copiado correctamente a la carpeta de la TTP: T1205
Copiado correctamente a la carpeta de la TTP: T1187
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1104
Copiado correctamente a la carpeta de la TTP: T1095
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1071
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1041
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1018
Copiado correctamente a la carpeta de la TTP: T1008
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1087.004
Copiado correctamente a la carpeta de la TTP: T1580
Copiado correctamente a la carpeta de la TTP: T1538
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1565.002
Copiado correctamente a la carpeta de la TTP: T1565.001
Copiado correctamente a la carpeta de la TTP: T1561.002

In [29]:
print('Reglas totales para asignar: '+str(len(num_yamls)))
rules_unique = get_unique_items(num_yamls)
print('Reglas únicas para asignar: '+str(len(rules_unique)))
print('Reglas que retornan error de lectura: '+str(len(error_load)))

Reglas totales para asignar: 126
Reglas únicas para asignar: 126
Reglas que retornan error de lectura: 0

In [27]:
print('El archivo ha sido abierto y dispone de contenido: '+str(len(content_in_yaml)))
print('El archivo ha sido abierto y NO dispone de contenido: '+str(len(no_content_in_yaml)))
print('Se ha podido identificar al menos una TTP en el contenido del archivo: '+str(len(ttp_in_yaml)))
print('Se ha podido identificar al menos una TTP en el nombre del archivo: '+str(len(ttp_in_filename)))

El archivo ha sido abierto y dispone de contenido: 126
El archivo ha sido abierto y NO dispone de contenido: 0
Se ha podido identificar al menos una TTP en el contenido del archivo: 1846
Se ha podido identificar al menos una TTP en el nombre del archivo: 0

In [28]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_mappings))))
try:
    t0000_count = len(getListOfFilesSub(os.path.join(save_path_mappings, 'T0000')))
    print('Reglas sin TTP asignada (T0000):', t0000_count)
except FileNotFoundError:
    t0000_count = 0
    print('Reglas sin TTP asignada (T0000): 0')
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_mappings)) - t0000_count))
print('Reglas asignadas a 2 o más TTP: '+str(len(count_duplicate_rules(getListOfFilesSub(save_path_mappings)))))

Número de TTPs únicas identificadas (puede incluir T0000): 407
Reglas sin TTP asignada (T0000): 126
Reglas asignadas a TTP: 1846
Reglas asignadas a 2 o más TTP: 108

#### TTP's Azure/Azure-Sentinel/tree/master/Hunting Queries

In [ ]:
path_hunting = 'https://github.com/Azure/Azure-Sentinel/tree/master/Hunting%20Queries'

save_path_hunting = os.path.join(save_path, 'Azure-Sentinel Hunting Queries')

zip_sentinel = 'https://github.com/Azure/Azure-Sentinel/archive/refs/heads/master.zip'

In [ ]:
create_output_folder(save_path_hunting)

In [ ]:
download_unzip(zip_sentinel, temp_path)

In [30]:
files = getListOfFilesSub(temp_path+r'\Azure-Sentinel-master\Hunting Queries')

['C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\Discorddownloadinvokedfromcmdline(ASIMVersion).yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_Certutil-LOLBins.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_cscript_summary.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_Dev-0056CommandLineActivityNovember2021(ASIMVersion).yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_enumeration_user_and_group.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_ExchangePowerShellSnapin.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_HostExportingMailboxAndRemovingExport.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_Invoke-PowerShellTcpOneLine.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_NishangReverseTCPShellBase64.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_persistence_create_account.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_PowerCatDownload.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_powershell_downloads.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_ProcessEntropy.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_SolarWindsInventory.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_Suspicious_enumeration_using_adfind.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_uncommon_processes.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\imProcess_Windows System Shutdown-Reboot(T1529).yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimProcess\\inProcess_SignedBinaryProxyExecutionRundll32.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\ASimRegistry\\Crashdumpdisabledonhost(ASIMVersion).yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\AccountAddedtoPrivilegedPIMGroup.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\AccountMFAModifications.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\AppRequiredResourceAccessUpdate.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\BitLockerKeyRetrieval.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\ConsentToApplicationDiscovery.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\NonredeemedGuesUserInvites.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\RareAuditActivityByApp.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\RareAuditActivityByUser.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\StsRefreshTokenModification.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\UserGrantedAccess_AllAuditActivity.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\UserGrantedAccess_GrantsOthersAccess.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AuditLogs\\UsersAuthenticatingtoOtherAzureADTenants.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AWSCloudTrail\\AWS_IAM_PolicyChange.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AWSCloudTrail\\AWS_IAM_PrivilegeEscalationbyAttachment.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AWSCloudTrail\\AWS_PrivilegedRoleAttachedToInstance.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AWSCloudTrail\\AWS_SuspiciousCredentialTokenAccessOfValid_IAM_Roles.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AWSCloudTrail\\AWS_Unused_UnsupportedCloudRegions.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\AnalyticsRulesAdministrativeOperations.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\AnomalousAzureOperationModel.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\Anomalous_Listing_Of_Storage_Keys.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\Azure-CloudShell-Usage.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\AzureAdministrationFromVPS.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\AzureNSG_AdministrativeOperations.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\AzureRunCommandFromAzureIP.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\AzureSentinelConnectors_AdministrativeOperations.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\AzureSentinelWorkbooks_AdministrativeOperation.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\AzureVirtualNetworkSubnets_AdministrativeOperationset.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\Common_Deployed_Resources.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\Creating_Anomalous_Number_Of_Resources.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\Granting_Permissions_to_Account.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\PortOpenedForAzureResource.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureActivity\\Rare_Custom_Script_Extension.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\AAD Conditional Access Disabled.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\Addtional Org Admin Added.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADOBuildCheckDeleted.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADOBuildDeletedAfterPipelineMod.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADOInternalUpstreamPacakgeFeedAdded.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADONewAgentPoolCreated.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADONewPackageFeedCreated.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADONewPATOperation.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADONewReleaseApprover.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADOReleasePipelineCreated.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\ADOVariableCreatedDeleted.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\AzDODisplayNameSwapping.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\AzDOPrPolicyBypassers.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\Guest users access enabled.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\Project visibility changed to public.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\Public project created.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDevOpsAuditing\\Public Projects enabled.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDiagnostics\\AzureKeyVaultAccessManipulation.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDiagnostics\\CriticalPortsOpened.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDiagnostics\\SpringShellExploitationAttempt.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDiagnostics\\SpringshellWebshellUsage.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureDiagnostics\\WAF_log4j_vulnerability.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureStorage\\AzureStorageFileCreateAccessDelete.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureStorage\\AzureStorageFileCreatedQuicklyDeleted.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureStorage\\AzureStorageFileOnEndpoint.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureStorage\\AzureStorageMassDeletion.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureStorage\\AzureStorageUploadFromVPS.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\AzureStorage\\AzureStorageUploadLinkAccount.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous AAD Account Manipulation.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Account Creation.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Activity Role Assignment.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Code Execution.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Data Access.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Defensive Mechanism Modification.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Failed Logon.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Geo Location Logon.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Login to Devices.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Password Reset.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous RDP Activity.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Resource Access.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Role Assignment.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\BehaviorAnalytics\\Anomalous Sign-in Activity.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\CloudAppEvents\\SetPolicyConfigInCloudAppEvents.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\CommonSecurityLog\\AbnormallyLargeJPEGFiledDownloadedfromNewSource.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\CommonSecurityLog\\B64IPInURL.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\CommonSecurityLog\\NetworkConnectionToNewExternalLDAPServer.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\CommonSecurityLog\\RiskyCommandB64EncodedInUrl.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\DNS_CommonlyAbusedTLDs.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\DNS_DomainAnomalousLookupIncrease.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\DNS_FullNameAnomalousLookupIncrease.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\DNS_HighPercentNXDomainCount.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\DNS_HighReverseDNSCount.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\DNS_LongURILookup.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\DNS_WannaCry.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\Solorigate-DNS-Pattern.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\DnsEvents\\Solorigate-Encoded-Domain-URL.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\First Time User Invite and Add Member to Org.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\Inactive or New Account Usage.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\Mass Deletion of Repositories .yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\Oauth App Restrictions Disabled.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\Org Repositories Default Permissions Change.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\Repository Permission Switched to Public.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\Suspicious Fork Activity.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\Unusual Number of Repository Clones.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\User First Time Repository Delete Activity.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\GitHub\\User Grant Access and Grants Other Access.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\CrossServiceADXQueries.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\CrossWorkspaceQueryAnomolies.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\MultipleLargeQueriesByUser.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\NewClientRunningQueries.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\NewServicePrincipalRunningQueries.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\NewUserCallingSensitiveWatchlist.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\NewUserRunningQueries.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\QueryDataVolumeAnomolies.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\QueryLookingForSecrets.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\UserReturningMoreDataThanDailyAverage.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\LAQueryLogs\\UserRunningMultipleQueriesThatFail.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\ASR rules\\ASR-rules-categorized-detection-graph.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\Abuse.ch Recent Threat Feed (1).yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\Abuse.ch Recent Threat Feed.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\Abusing settingcontent-ms.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\APT Baby Shark.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\apt sofacy zebrocy.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\apt sofacy.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\apt ta17 293a ps.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\apt tropictrooper.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\apt unidentified nov 18 (1).yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\apt unidentified nov 18.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\APT29 thinktanks.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\Bazacall\\Bazacall Emails.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\Bazacall\\Cobalt Strike Lateral Movement.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\Bazacall\\Dropping payload via certutil.yaml',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\Azure-Sentinel-master\\Hunting Queries\\Microsoft 365 Defender\\Campaigns\\Bazacall\\Excel file download domain pattern.yaml',

In [70]:
for item in files:
    root,extension = os.path.splitext(item)
    if extension == '.yaml':
        with open(item) as file:
            documents = yaml.full_load(file)
            ttp = documents.get('relevantTechniques', [])
            print(item)
            if isinstance(ttp, list) and len(ttp)>=1:
                for i in range(len(ttp)):
                    if not os.path.exists(os.path.join(save_path_hunting, ttp[i])):
                        os.makedirs(os.path.join(save_path_hunting, ttp[i]))
                    shutil.copy(item,os.path.join(save_path_hunting, ttp[i]))
                    print('Copiado correctamente')

C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\Discorddownloadinvokedfromcmdline(ASIMVersion).yaml
Copiado correctamente
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_Certutil-LOLBins.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_cscript_summary.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_Dev-0056CommandLineActivityNovember2021(ASIMVersion).yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_enumeration_user_and_group.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_ExchangePowerShellSnapin.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_HostExportingMailboxAndRemovingExport.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_Invoke-PowerShellTcpOneLine.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_NishangReverseTCPShellBase64.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_persistence_create_account.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_PowerCatDownload.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_powershell_downloads.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_ProcessEntropy.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_SolarWindsInventory.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_Suspicious_enumeration_using_adfind.yaml
Copiado correctamente
Copiado correctamente
Copiado correctamente
Copiado correctamente
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_uncommon_processes.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\imProcess_Windows System Shutdown-Reboot(T1529).yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimProcess\inProcess_SignedBinaryProxyExecutionRundll32.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\ASimRegistry\Crashdumpdisabledonhost(ASIMVersion).yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\AccountAddedtoPrivilegedPIMGroup.yaml
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\AccountMFAModifications.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\AppRequiredResourceAccessUpdate.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\BitLockerKeyRetrieval.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\ConsentToApplicationDiscovery.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\NonredeemedGuesUserInvites.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\RareAuditActivityByApp.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\RareAuditActivityByUser.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\StsRefreshTokenModification.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\UserGrantedAccess_AllAuditActivity.yaml
Copiado correctamente
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\UserGrantedAccess_GrantsOthersAccess.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AuditLogs\UsersAuthenticatingtoOtherAzureADTenants.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AWSCloudTrail\AWS_IAM_PolicyChange.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AWSCloudTrail\AWS_IAM_PrivilegeEscalationbyAttachment.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AWSCloudTrail\AWS_PrivilegedRoleAttachedToInstance.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AWSCloudTrail\AWS_SuspiciousCredentialTokenAccessOfValid_IAM_Roles.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AWSCloudTrail\AWS_Unused_UnsupportedCloudRegions.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\AnalyticsRulesAdministrativeOperations.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\AnomalousAzureOperationModel.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\Anomalous_Listing_Of_Storage_Keys.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\Azure-CloudShell-Usage.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\AzureAdministrationFromVPS.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\AzureNSG_AdministrativeOperations.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\AzureRunCommandFromAzureIP.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\AzureSentinelConnectors_AdministrativeOperations.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\AzureSentinelWorkbooks_AdministrativeOperation.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\AzureVirtualNetworkSubnets_AdministrativeOperationset.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\Common_Deployed_Resources.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\Creating_Anomalous_Number_Of_Resources.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\Granting_Permissions_to_Account.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\PortOpenedForAzureResource.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureActivity\Rare_Custom_Script_Extension.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\AAD Conditional Access Disabled.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\Addtional Org Admin Added.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADOBuildCheckDeleted.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADOBuildDeletedAfterPipelineMod.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADOInternalUpstreamPacakgeFeedAdded.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADONewAgentPoolCreated.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADONewPackageFeedCreated.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADONewPATOperation.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADONewReleaseApprover.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADOReleasePipelineCreated.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\ADOVariableCreatedDeleted.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\AzDODisplayNameSwapping.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\AzDOPrPolicyBypassers.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\Guest users access enabled.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\Project visibility changed to public.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\Public project created.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDevOpsAuditing\Public Projects enabled.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDiagnostics\AzureKeyVaultAccessManipulation.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDiagnostics\CriticalPortsOpened.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDiagnostics\SpringShellExploitationAttempt.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDiagnostics\SpringshellWebshellUsage.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureDiagnostics\WAF_log4j_vulnerability.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureStorage\AzureStorageFileCreateAccessDelete.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureStorage\AzureStorageFileCreatedQuicklyDeleted.yaml
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureStorage\AzureStorageFileOnEndpoint.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureStorage\AzureStorageMassDeletion.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureStorage\AzureStorageUploadFromVPS.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\AzureStorage\AzureStorageUploadLinkAccount.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous AAD Account Manipulation.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Account Creation.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Activity Role Assignment.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Code Execution.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Data Access.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Defensive Mechanism Modification.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Failed Logon.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Geo Location Logon.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Login to Devices.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Password Reset.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous RDP Activity.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Resource Access.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Role Assignment.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\BehaviorAnalytics\Anomalous Sign-in Activity.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\CloudAppEvents\SetPolicyConfigInCloudAppEvents.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\CommonSecurityLog\AbnormallyLargeJPEGFiledDownloadedfromNewSource.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\CommonSecurityLog\B64IPInURL.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\CommonSecurityLog\NetworkConnectionToNewExternalLDAPServer.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\CommonSecurityLog\RiskyCommandB64EncodedInUrl.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\DNS_CommonlyAbusedTLDs.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\DNS_DomainAnomalousLookupIncrease.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\DNS_FullNameAnomalousLookupIncrease.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\DNS_HighPercentNXDomainCount.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\DNS_HighReverseDNSCount.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\DNS_LongURILookup.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\DNS_WannaCry.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\Solorigate-DNS-Pattern.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\DnsEvents\Solorigate-Encoded-Domain-URL.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\First Time User Invite and Add Member to Org.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\Inactive or New Account Usage.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\Mass Deletion of Repositories .yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\Oauth App Restrictions Disabled.yaml
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\Org Repositories Default Permissions Change.yaml
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\Repository Permission Switched to Public.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\Suspicious Fork Activity.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\Unusual Number of Repository Clones.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\User First Time Repository Delete Activity.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\GitHub\User Grant Access and Grants Other Access.yaml
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\CrossServiceADXQueries.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\CrossWorkspaceQueryAnomolies.yaml
Copiado correctamente
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\MultipleLargeQueriesByUser.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\NewClientRunningQueries.yaml
Copiado correctamente
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\NewServicePrincipalRunningQueries.yaml
Copiado correctamente
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\NewUserCallingSensitiveWatchlist.yaml
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\NewUserRunningQueries.yaml
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\QueryDataVolumeAnomolies.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\QueryLookingForSecrets.yaml
Copiado correctamente
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\UserReturningMoreDataThanDailyAverage.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\LAQueryLogs\UserRunningMultipleQueriesThatFail.yaml
Copiado correctamente
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\ASR rules\ASR-rules-categorized-detection-graph.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\Abuse.ch Recent Threat Feed (1).yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\Abuse.ch Recent Threat Feed.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\Abusing settingcontent-ms.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\APT Baby Shark.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\apt sofacy zebrocy.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\apt sofacy.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\apt ta17 293a ps.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\apt tropictrooper.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\apt unidentified nov 18 (1).yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\apt unidentified nov 18.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\APT29 thinktanks.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\Bazacall\Bazacall Emails.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\Bazacall\Cobalt Strike Lateral Movement.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\Bazacall\Dropping payload via certutil.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\Bazacall\Excel file download domain pattern.yaml
C:\Users\jelopez\AppData\Local\Temp\Azure-Sentinel-master\Hunting Queries\Microsoft 365 Defender\Campaigns\Bazacall\Excel Macro Execution.yaml

##### TTP's BlueTeamLabs/sentinel-attack

In [87]:
zip_sentinel_attack = 'https://github.com/netevert/sentinel-attack/archive/refs/heads/master.zip'

save_path_sentinel_attack = os.path.join(save_path, 'netevert_sentinel-attack')

In [88]:
create_output_folder(save_path_sentinel_attack)

'c:\\Users\\jelopez\\Documents\\CyberProof\\python\\download_ttps\\saved\\netevert_sentinel-attack'

In [74]:
download_unzip(zip_sentinel_attack, temp_path)

In [75]:
files = getListOfFilesSub(temp_path+r'\sentinel-attack-master')

['C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\.gitignore',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\azuredeploy.json',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\CODE_OF_CONDUCT.md',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\CONTRIBUTING.md',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\deployment\\gallery.azuredeploy.json',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\sentinel_attack_rules.json',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T0000_Console_History.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T0000_Named_Pipes.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T0000_Named_Pipes_CobaltStrike.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T0000_Remotely_Query_Login_Sessions_Network.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T0000_Remotely_Query_Login_Sessions_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T0000_Suspicious_Filename_Used.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1002_Data_Compressed.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1003_Credential_Dumping_ImageLoad.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1003_Credential_Dumping_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1003_Credential_Dumping_Process_Access.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1003_Credential_Dumping_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1003_Credential_Dumping_Registry_Save.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1004_Win_Logon_Helper_DLL.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1007_System_Service_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1012_Query_Registry_Network.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1012_Query_Registry_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1013_Local_Port_Monitor.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1015_Accessibility_Features.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1015_Accessibility_Features_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1016_System_Network_Configuration_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1018_Remote_System_Discovery_Network.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1018_Remote_System_Discovery_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1027_Obfuscated_Files_Or_Information.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1028_Windows_Remote_Management.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1031_Modify_Existing_Service.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1033_System_Owner_User_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1036_Masquerading_Extension.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1036_Masquerading_Location.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1037_Logon_Scripts.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1040_Network_Sniffing.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1042_Change_Default_File_Association.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1044_File_System_Permissions_Weakness.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1047_Windows_Management_Instrumentation_Active_Script_Event_Consumer_FileAccess.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1047_Windows_Management_Instrumentation_Active_Script_Event_Consumer_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1047_Windows_Management_Instrumentation_Network.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1047_Windows_Management_Instrumentation_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1047_WMI_Command_Execution.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1049_System_Network_Connections_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1050_New_Service_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1053_Scheduled_Task_FileAccess.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1053_Scheduled_Task_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1054_Indicator_Blocking_Driver_Unloaded.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1054_Indicator_Blocking_Sysmon_Registry_Edited_From_Other_Source.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1055_Process_Injection_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1057_Process_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1059_Command_Line_Interface.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1060_Registry_Run_Keys_Or_Start_Folder.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1063_Security_Software_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1069_Permission_Groups_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1069_Permission_Groups_Discovery_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1070_Indicator_Removal_On_Host.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1074_Datal_Staged_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1076_Remote_Desktop_Protocol_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1076_Remote_Desktop_Protocol_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1077_Windows_Admin_Shares.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1077_Windows_Admin_Shares_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1077_Windows_Admin_Shares_Process_Created.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1081_Credentials_In_Files.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1082_System_Information_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1085_Rundll32.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1086_PowerShell.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1086_PowerShell_Downloads_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1087_Account_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1088_Bypass_User_Account_Control_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1088_Bypass_User_Account_Control_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1089_Disabling_Security_Tools_Service_Stopped.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1093_Process_Hollowing.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1096_NTFS_File_Attributes.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1103_AppInit_DLLs.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1107_File_Deletion.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1112_Modify_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1115_Clipboard_Data.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1117_Bypassing_Application_Whitelisting_With_Regsvr32.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1117_Regsvr32_Network.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1118_InstallUtil.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1121_Regsvcs_Regasm.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1122_Component_Object_Model_Hijacking.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1123_Audio_Capture.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1124_System_Time_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1126_Network_Share_Connection_Removal.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1127_Trusted_Developer_Utilities.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1128_Narsh_Helper_DLL_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1128_Netsh_Helper_DLL_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1130_Install_Root_Certificates.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1131_Authentication_Package.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1135_Network_Share_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1135_Network_Share_Discovery_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1136_Create_Account.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1138_Application_Shimming_FileAccess.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1138_Application_Shimming_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1138_Application_Shimming_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1140_Deobfuscate_Decode_Files_Or_Information.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1146_Clear_Command_History.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1158_Hidden_Files_And_Directories.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1158_Hidden_Files_And_Directories_VSS.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1170_MSHTA_FileAccess.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1170_MSHTA_Network.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1170_MSHTA_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1179_Hooking.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1180_Screensaver.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1182_AppCert_DLLs.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1183_Image_File_Execution_Options_Injection.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1187_Forced_Authentication.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1191_CMSTP.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1196_Control_Panel_Items_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1196_Control_Panel_Items_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1197_BITS_Jobs_Network.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1197_BITS_Jobs_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1201_Password_Policy_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1202_Indirect_Command_Execution.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1209_Time_Providers.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1214_Credentials_In_Registry.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1216_Signed_Script_Proxy_Execution.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1217_Browser_Bookmark_Discovery.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1218_Signed_Binary_Proxy_Execution_Network.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1218_Signed_Binary_Proxy_Execution_Process.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\detections\\T1223_Compiled_HTML_File.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\attack_drilldown.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\computer_drilldown.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\connect-vm.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\data-test.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\DEFCON_attacking_the_sentinel.pdf',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\demo.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\deploy-analytics.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\deploy-sentinel.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\drilldown_highlights.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\enable-event-logs.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\enable-security-events.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\execute-hunts.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\file_create_drilldown.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\install-parser.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\killchain-overview.png',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\logo.png',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\network_drilldown.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\pipe_name_drilldown.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\process-overview.png',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\process_guid_drilldown.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\sentinel_attack_coverage.JPG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\sentinel_attack_coverage.json',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\sentinel_attack_coverage.svg',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\sentinel_attack_coverage.xlsx',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\technique-overview.png',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\trigger_overview.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\upload-dashboard.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\upload-detection-rules.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\upload-notebook.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\upload-workbooks.gif',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\docs\\user_drilldown.PNG',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\hunting\\sysmon_threat_hunting.json',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\create-ad.ps1',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\dns_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\file_access_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\file_create_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\image_load_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\install-utilities.ps1',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\network_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\pipe_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\process_access_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\process_create_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\registry_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\files\\remote_thread_whitelist.csv',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\main.tf',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\variables.tf',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\lab\\variables.tfvars.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\LICENSE.md',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\parser\\Sysmon-OSSEM.txt',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\README.md',
 'C:\\Users\\jelopez\\AppData\\Local\\Temp\\sentinel-attack-master\\sysmonconfig.xml']

In [96]:
for item in files:
    root,extension = os.path.splitext(item)
    if extension == '.txt':
        basename = os.path.basename(item)
        print(basename[0:5])
        if basename[0] == 'T' and basename[1:5].isdigit():
            if not os.path.exists(os.path.join(save_path_sentinel_attack, basename[0:5])):
                os.makedirs(os.path.join(save_path_sentinel_attack, basename[0:5]))
                print('Carpeta creada correctamente')
            #print(os.path.join(save_path_sentinel_attack, basename[0:5]))
            shutil.copy(item,os.path.join(save_path_sentinel_attack, basename[0:5]))

T0000
Carpeta creada correctamente
T0000
T0000
T0000
T0000
T0000
T1002
Carpeta creada correctamente
T1003
Carpeta creada correctamente
T1003
T1003
T1003
T1003
T1004
Carpeta creada correctamente
T1007
Carpeta creada correctamente
T1012
Carpeta creada correctamente
T1012
T1013
Carpeta creada correctamente
T1015
Carpeta creada correctamente
T1015
T1016
Carpeta creada correctamente
T1018
Carpeta creada correctamente
T1018
T1027
Carpeta creada correctamente
T1028
Carpeta creada correctamente
T1031
Carpeta creada correctamente
T1033
Carpeta creada correctamente
T1036
Carpeta creada correctamente
T1036
T1037
Carpeta creada correctamente
T1040
Carpeta creada correctamente
T1042
Carpeta creada correctamente
T1044
Carpeta creada correctamente
T1047
Carpeta creada correctamente
T1047
T1047
T1047
T1047
T1049
Carpeta creada correctamente
T1050
Carpeta creada correctamente
T1053
Carpeta creada correctamente
T1053
T1054
Carpeta creada correctamente
T1054
T1055
Carpeta creada correctamente
T1057
Carpeta creada correctamente
T1059
Carpeta creada correctamente
T1060
Carpeta creada correctamente
T1063
Carpeta creada correctamente
T1069
Carpeta creada correctamente
T1069

T1070
Carpeta creada correctamente
T1074
Carpeta creada correctamente
T1076
Carpeta creada correctamente
T1076
T1077
Carpeta creada correctamente
T1077
T1077
T1081
Carpeta creada correctamente
T1082
Carpeta creada correctamente
T1085
Carpeta creada correctamente
T1086
Carpeta creada correctamente
T1086
T1087
Carpeta creada correctamente
T1088
Carpeta creada correctamente
T1088
T1089
Carpeta creada correctamente
T1093
Carpeta creada correctamente
T1096
Carpeta creada correctamente
T1103
Carpeta creada correctamente
T1107
Carpeta creada correctamente
T1112
Carpeta creada correctamente
T1115
Carpeta creada correctamente
T1117
Carpeta creada correctamente
T1117
T1118
Carpeta creada correctamente
T1121
Carpeta creada correctamente
T1122
Carpeta creada correctamente
T1123
Carpeta creada correctamente
T1124
Carpeta creada correctamente
T1126
Carpeta creada correctamente
T1127
Carpeta creada correctamente
T1128
Carpeta creada correctamente
T1128
T1130
Carpeta creada correctamente
T1131
Carpeta creada correctamente
T1135
Carpeta creada correctamente
T1135
T1136
Carpeta creada correctamente
T1138
Carpeta creada correctamente
T1138
T1138
T1140
Carpeta creada correctamente
T1146
Carpeta creada correctamente
T1158
Carpeta creada correctamente
T1158
T1170
Carpeta creada correctamente
T1170
T1170
T1179
Carpeta creada correctamente
T1180
Carpeta creada correctamente
T1182
Carpeta creada correctamente
T1183
Carpeta creada correctamente
T1187
Carpeta creada correctamente
T1191
Carpeta creada correctamente
T1196
Carpeta creada correctamente
T1196
T1197
Carpeta creada correctamente
T1197
T1201
Carpeta creada correctamente
T1202
Carpeta creada correctamente
T1209
Carpeta creada correctamente
T1214
Carpeta creada correctamente
T1216
Carpeta creada correctamente
T1217
Carpeta creada correctamente
T1218
Carpeta creada correctamente
T1218
T1223
Carpeta creada correctamente
varia
Sysmo

##### TTP's Elastic - 1

In [115]:

zip_elastic_1 = 'https://github.com/elastic/detection-rules/archive/refs/heads/main.zip'

save_path_elastic_1 = os.path.join(save_path, 'elastic_1')

In [ ]:
create_output_folder(save_path_elastic_1)

In [120]:
download_folder_unzip(zip_elastic_1, 'detection-rules-main/rules', temp_path)

Descarga y descompresión completadas correctamente.

In [121]:
files = getListOfFilesSub(temp_path+r'\detection-rules-main/rules')
files[:3]

['C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\apm\\apm_403_response_to_a_post.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\apm\\apm_405_response_method_not_allowed.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\apm\\apm_sqlmap_user_agent.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\command_and_control_google_drive_malicious_file_download.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\command_and_control_non_standard_ssh_port.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\credential_access_cookies_chromium_browsers_debugging.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\defense_evasion_agent_spoofing_mismatched_id.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\defense_evasion_agent_spoofing_multiple_hosts.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\defense_evasion_deleting_websvr_access_logs.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\defense_evasion_deletion_of_bash_command_line_history.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\defense_evasion_elastic_agent_service_terminated.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\defense_evasion_masquerading_space_after_filename.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\defense_evasion_timestomp_touch.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\discovery_security_software_grep.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\discovery_virtual_machine_fingerprinting_grep.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\execution_pentest_eggshell_remote_admin_tool.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\execution_potential_widespread_malware_infection.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\execution_python_script_in_cmdline.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\execution_revershell_via_shell_cmd.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\execution_suspicious_jar_child_process.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\execution_suspicious_java_netcon_childproc.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\guided_onboarding_sample_rule.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\impact_hosts_file_modified.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\initial_access_zoom_meeting_with_no_passcode.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\multiple_alerts_different_tactics_host.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\multiple_alerts_involving_user.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\persistence_credential_access_modify_auth_module_or_config.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\persistence_shell_profile_modification.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\persistence_ssh_authorized_keys_modification.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\privilege_escalation_echo_nopasswd_sudoers.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\privilege_escalation_setuid_setgid_bit_set_via_chmod.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\privilege_escalation_sudoers_file_mod.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\privilege_escalation_sudo_buffer_overflow.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\threat_intel_indicator_match_address.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\threat_intel_indicator_match_hash.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\threat_intel_indicator_match_registry.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\cross-platform\\threat_intel_indicator_match_url.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\collection_cloudtrail_logging_created.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\credential_access_aws_getpassword_for_ec2_instance.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\credential_access_aws_iam_assume_role_brute_force.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\credential_access_iam_user_addition_to_group.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\credential_access_new_terms_secretsmanager_getsecretvalue.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\credential_access_root_console_failure_brute_force.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_cloudtrail_logging_deleted.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_cloudtrail_logging_suspended.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_cloudwatch_alarm_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_configuration_recorder_stopped.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_config_service_rule_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_ec2_flow_log_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_ec2_network_acl_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_elasticache_security_group_creation.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_elasticache_security_group_modified_or_deleted.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_escalation_aws_suspicious_saml_activity.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_guardduty_detector_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_route53_dns_query_resolver_config_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_s3_bucket_configuration_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_waf_acl_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\defense_evasion_waf_rule_or_rule_group_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\exfiltration_ec2_ami_shared_with_separate_account.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\exfiltration_ec2_full_network_packet_capture_detected.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\exfiltration_ec2_snapshot_change_activity.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\exfiltration_ec2_vm_export_failure.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\exfiltration_rds_snapshot_export.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\exfiltration_rds_snapshot_restored.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_aws_eventbridge_rule_disabled_or_deleted.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_aws_s3_bucket_enumeration_or_brute_force.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_cloudtrail_logging_updated.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_cloudwatch_log_group_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_cloudwatch_log_stream_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_ec2_disable_ebs_encryption.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_efs_filesystem_or_mount_deleted.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_iam_deactivate_mfa_device.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_iam_group_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_kms_cmk_disabled_or_scheduled_for_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_rds_group_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_rds_instance_cluster_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\impact_rds_instance_cluster_stoppage.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\initial_access_console_login_root.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\initial_access_password_recovery.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\initial_access_via_system_manager.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\ml_cloudtrail_error_message_spike.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\ml_cloudtrail_rare_error_code.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\ml_cloudtrail_rare_method_by_city.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\ml_cloudtrail_rare_method_by_country.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\ml_cloudtrail_rare_method_by_user.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\NOTICE.txt',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_ec2_network_acl_creation.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_ec2_security_group_configuration_change_detection.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_iam_group_creation.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_rds_cluster_creation.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_rds_group_creation.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_rds_instance_creation.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_redshift_instance_creation.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_route_53_domain_transferred_to_another_account.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_route_53_domain_transfer_lock_disabled.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_route_53_hosted_zone_associated_with_a_vpc.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_route_table_created.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\persistence_route_table_modified_or_deleted.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\privilege_escalation_root_login_without_mfa.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\privilege_escalation_sts_assumerole_usage.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\privilege_escalation_sts_getsessiontoken_abuse.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws\\privilege_escalation_updateassumerolepolicy.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws_bedrock\\aws_bedrock_guardrails_multiple_violations_by_single_user.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws_bedrock\\aws_bedrock_guardrails_multiple_violations_in_single_request.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws_bedrock\\aws_bedrock_high_confidence_misconduct_blocks_detected.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws_bedrock\\aws_bedrock_high_resource_consumption_detection.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\aws_bedrock\\aws_bedrock_multiple_attempts_to_use_denied_models_by_user.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\collection_update_event_hub_auth_rule.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\credential_access_azure_full_network_packet_capture_detected.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\credential_access_key_vault_modified.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\credential_access_storage_account_key_regenerated.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_azure_application_credential_modification.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_azure_automation_runbook_deleted.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_azure_blob_permissions_modified.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_azure_diagnostic_settings_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_azure_service_principal_addition.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_event_hub_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_firewall_policy_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_frontdoor_firewall_policy_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_kubernetes_events_deleted.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_network_watcher_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\defense_evasion_suppression_rule_created.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\discovery_blob_container_access_mod.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\execution_command_virtual_machine.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\impact_azure_service_principal_credentials_added.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\impact_kubernetes_pod_deleted.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\impact_resource_group_deletion.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\impact_virtual_network_device_modified.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\initial_access_azure_active_directory_high_risk_signin.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\initial_access_azure_active_directory_high_risk_signin_atrisk_or_confirmed.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\initial_access_azure_active_directory_powershell_signin.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\initial_access_consent_grant_attack_via_azure_registered_application.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\initial_access_external_guest_user_invite.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_azure_automation_account_created.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_azure_automation_runbook_created_or_modified.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_azure_automation_webhook_created.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_azure_conditional_access_policy_modified.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_azure_global_administrator_role_assigned.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_azure_pim_user_added_global_admin.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_azure_privileged_identity_management_role_modified.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_mfa_disabled_for_azure_user.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_user_added_as_owner_for_azure_application.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\persistence_user_added_as_owner_for_azure_service_principal.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\azure\\privilege_escalation_azure_kubernetes_rolebinding_created.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\beaconing\\command_and_control_beaconing.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\beaconing\\command_and_control_beaconing_high_confidence.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\cloud_defend\\container_workload_protection.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\cloud_defend\\credential_access_aws_creds_search_inside_a_container.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\cloud_defend\\credential_access_collection_sensitive_files_compression_inside_a_container.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\cloud_defend\\credential_access_sensitive_keys_or_passwords_search_inside_a_container.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\cloud_defend\\defense_evasion_ld_preload_shared_object_modified_inside_a_container.toml',
 'C:\\Users\\jelopez\\Downloads\\detection-rules-main/rules\\integrations\\cloud_defend\\discovery_suspicious_network_tool_launched_inside_a_container.toml',

In [152]:
for item in files:
    root,extension = os.path.splitext(item)
    if extension == '.toml':
        with open(item, 'r') as file:
            rules = []
            try:
                data_toml = toml.load(file)
            except (IndexError, TomlDecodeError) as e:
                if isinstance(e, IndexError):
                    print("Se produjo un IndexError:", e)
                    print('No se ha podido asignar ninguna carpeta al archivo:  '+str(item))
                elif "Unterminated string found. Reached end of file." in str(e):
                    print('No se ha podido asignar ninguna carpeta al archivo:  '+str(item))
            except Exception as e:
                print("Se produjo un error:", e)
                print('No se ha podido asignar ninguna carpeta al archivo:  '+str(item))
            if len(data_toml.get('rule',[]).get('threat',[]))>0:
                for i in range(len(data_toml['rule']['threat'])):
                    #print(i)
                    if data_toml.get('rule', []).get('threat', [])[i].get('technique'):
                        data_rules = data_toml['rule']['threat'][i]['technique']
                        for i in range(len(data_rules)):
                            rules.append(data_rules[i]['id'])
                            subtechniques = data_rules[i].get('subtechnique', [])
                            if len(subtechniques)>0:
                                for z in range(len(subtechniques)):
                                    rules.append(subtechniques[z]['id'])
        for rule in rules:
            if not os.path.exists(os.path.join(save_path_elastic_1, rule)):
                os.makedirs(os.path.join(save_path_elastic_1, rule))
            shutil.copy(item,os.path.join(save_path_elastic_1, rule))

            #Guardar en algun sitio como no indexadas

Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\collection_cloudtrail_logging_created.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\defense_evasion_cloudtrail_logging_deleted.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\defense_evasion_elasticache_security_group_creation.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\defense_evasion_s3_bucket_configuration_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\defense_evasion_waf_acl_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\exfiltration_ec2_full_network_packet_capture_detected.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\exfiltration_rds_snapshot_export.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\exfiltration_rds_snapshot_restored.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\impact_ec2_disable_ebs_encryption.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\impact_efs_filesystem_or_mount_deleted.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\impact_iam_deactivate_mfa_device.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\impact_rds_group_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\impact_rds_instance_cluster_stoppage.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\persistence_ec2_security_group_configuration_change_detection.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\persistence_rds_cluster_creation.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\persistence_redshift_instance_creation.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\persistence_route_table_created.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\persistence_route_table_modified_or_deleted.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\aws\privilege_escalation_sts_getsessiontoken_abuse.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\credential_access_key_vault_modified.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\defense_evasion_azure_application_credential_modification.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\defense_evasion_azure_diagnostic_settings_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\defense_evasion_azure_service_principal_addition.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\defense_evasion_firewall_policy_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\defense_evasion_network_watcher_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\discovery_blob_container_access_mod.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\impact_resource_group_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\initial_access_azure_active_directory_powershell_signin.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\initial_access_external_guest_user_invite.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\azure\persistence_azure_pim_user_added_global_admin.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\gcp\collection_gcp_pub_sub_topic_creation.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\gcp\defense_evasion_gcp_pub_sub_topic_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\gcp\impact_gcp_iam_role_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\gcp\impact_gcp_storage_bucket_deleted.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\gcp\persistence_gcp_iam_service_account_key_deletion.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\integrations\kubernetes\initial_access_anonymous_request_authorized.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\linux\lateral_movement_telnet_network_activity_external.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\linux\lateral_movement_telnet_network_activity_internal.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\ml\ml_high_count_network_events.toml
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\windows\credential_access_disable_kerberos_preauth.toml
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\windows\defense_evasion_amsi_bypass_powershell.toml
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\windows\persistence_dontexpirepasswd_account.toml
Se produjo un IndexError: string index out of range
No se ha podido asignar ninguna carpeta al archivo:  C:\Users\jelopez\Downloads\detection-rules-main/rules\_deprecated\exfiltration_rds_snapshot_export.toml

#### TTP's UCM Catalog 2024 Sentinel *from excel

In [381]:
# Esto es temporal ya que parece ser que he excedido el número de peticiones
#lift = attack_client()

path_techniques = 'C:/Users/jelopez/Documents/CyberProof/python/recursos/id_tecnicas_16052024.csv'
techniques_enterprise = pd.read_csv(path_techniques)
techniques_enterprise = techniques_enterprise['ID Tecnica'].to_list()
techniques_enterprise

['T1059.010',
 'T1564.012',
 'T1027.013',
 'T1574.014',
 'T1584.008',
 'T1548.006',
 'T1588.007',
 'T1218.015',
 'T1543.005',
 'T1665',
 'T1216.002',
 'T1556.009',
 'T1027.012',
 'T1036.009',
 'T1555.006',
 'T1016.002',
 'T1566.004',
 'T1598.004',
 'T1578.005',
 'T1659',
 'T1564.011',
 'T1657',
 'T1656',
 'T1567.004',
 'T1098.006',
 'T1654',
 'T1548.005',
 'T1653',
 'T1021.008',
 'T1562.012',
 'T1556.008',
 'T1652',
 'T1027.011',
 'T1027.010',
 'T1562.011',
 'T1552.008',
 'T1651',
 'T1650',
 'T1036.008',
 'T1567.003',
 'T1583.008',
 'T1021.007',
 'T1205.002',
 'T1608.006',
 'T1027.009',
 'T1027.008',
 'T1556.007',
 'T1546.016',
 'T1027.007',
 'T1593.003',
 'T1649',
 'T1070.009',
 'T1070.008',
 'T1584.007',
 'T1583.007',
 'T1070.007',
 'T1556.006',
 'T1586.003',
 'T1585.003',
 'T1648',
 'T1647',
 'T1622',
 'T1621',
 'T1505.005',
 'T1557.003',
 'T1059.009',
 'T1595.003',
 'T1098.005',
 'T1574.013',
 'T1556.005',
 'T1055.015',
 'T1564.010',
 'T1564.009',
 'T1559.003',
 'T1562.010',
 'T1547.015',
 'T1620',
 'T1619',
 'T1218.014',
 'T1218.013',
 'T1614.001',
 'T1615',
 'T1036.007',
 'T1562.009',
 'T1564.008',
 'T1505.004',
 'T1027.006',
 'T1213.003',
 'T1553.006',
 'T1614',
 'T1613',
 'T1552.007',
 'T1612',
 'T1611',
 'T1204.003',
 'T1053.007',
 'T1610',
 'T1609',
 'T1608.005',
 'T1608.004',
 'T1608.003',
 'T1608.002',
 'T1608.001',
 'T1608',
 'T1016.001',
 'T1553.005',
 'T1555.005',
 'T1484.002',
 'T1484.001',
 'T1547.014',
 'T1606.002',
 'T1606.001',
 'T1606',
 'T1555.004',
 'T1059.008',
 'T1602.002',
 'T1542.005',
 'T1542.004',
 'T1602.001',
 'T1602',
 'T1601.002',
 'T1601.001',
 'T1601',
 'T1600.002',
 'T1600.001',
 'T1600',
 'T1556.004',
 'T1599.001',
 'T1599',
 'T1020.001',
 'T1557.002',
 'T1588.006',
 'T1053.006',
 'T1562.008',
 'T1547.012',
 'T1598.003',
 'T1598.002',
 'T1598.001',
 'T1598',
 'T1597.002',
 'T1597.001',
 'T1597',
 'T1596.005',
 'T1596.004',
 'T1596.003',
 'T1596.001',
 'T1596.002',
 'T1596',
 'T1595.002',
 'T1595.001',
 'T1595',
 'T1594',
 'T1593.002',
 'T1593.001',
 'T1593',
 'T1592.004',
 'T1592.003',
 'T1592.002',
 'T1592.001',
 'T1592',
 'T1591.004',
 'T1591.003',
 'T1591.001',
 'T1591.002',
 'T1591',
 'T1590.006',
 'T1590.005',
 'T1590.004',
 'T1590.003',
 'T1590.002',
 'T1590.001',
 'T1590',
 'T1589.003',
 'T1589.002',
 'T1589.001',
 'T1589',
 'T1588.005',
 'T1588.004',
 'T1588.003',
 'T1588.002',
 'T1588.001',
 'T1588',
 'T1587.004',
 'T1587.003',
 'T1587.002',
 'T1587.001',
 'T1587',
 'T1586.002',
 'T1586.001',
 'T1586',
 'T1585.002',
 'T1585.001',
 'T1585',
 'T1584.006',
 'T1584.005',
 'T1584.004',
 'T1584.003',
 'T1584.002',
 'T1584.001',
 'T1583.006',
 'T1583.005',
 'T1583.004',
 'T1583.003',
 'T1583.002',
 'T1584',
 'T1583.001',
 'T1583',
 'T1564.007',
 'T1558.004',
 'T1580',
 'T1218.012',
 'T1205.001',
 'T1564.006',
 'T1564.005',
 'T1556.003',
 'T1574.012',
 'T1562.007',
 'T1098.004',
 'T1480.001',
 'T1059.007',
 'T1578.004',
 'T1578.003',
 'T1578.001',
 'T1578.002',
 'T1127.001',
 'T1027.005',
 'T1562.006',
 'T1573.002',
 'T1573.001',
 'T1573',
 'T1027.004',
 'T1574.004',
 'T1546.015',
 'T1071.004',
 'T1071.003',
 'T1071.002',
 'T1071.001',
 'T1572',
 'T1048.003',
 'T1048.002',
 'T1048.001',
 'T1001.003',
 'T1001.002',
 'T1001.001',
 'T1132.002',
 'T1132.001',
 'T1090.004',
 'T1090.003',
 'T1090.002',
 'T1090.001',
 'T1102.003',
 'T1102.002',
 'T1102.001',
 'T1571',
 'T1074.002',
 'T1074.001',
 'T1078.004',
 'T1564.004',
 'T1564.003',
 'T1078.003',
 'T1078.002',
 'T1078.001',
 'T1564.002',
 'T1574.006',
 'T1574.002',
 'T1574.001',
 'T1574.008',
 'T1574.007',
 'T1574.009',
 'T1574.011',
 'T1574.005',
 'T1574.010',
 'T1574',
 'T1069.001',
 'T1570',
 'T1568.003',
 'T1204.002',
 'T1204.001',
 'T1195.003',
 'T1195.002',
 'T1195.001',
 'T1568.001',
 'T1052.001',
 'T1569.002',
 'T1569.001',
 'T1569',
 'T1568.002',
 'T1568',
 'T1011.001',
 'T1567.002',
 'T1567.001',
 'T1059.006',
 'T1059.005',
 'T1059.004',
 'T1059.003',
 'T1059.002',
 'T1059.001',
 'T1567',
 'T1497.003',
 'T1497.002',
 'T1497.001',
 'T1498.002',
 'T1498.001',
 'T1566.003',
 'T1566.002',
 'T1566.001',
 'T1566',
 'T1565.003',
 'T1565.002',
 'T1565.001',
 'T1565',
 'T1564.001',
 'T1564',
 'T1563.002',
 'T1563.001',
 'T1563',
 'T1518.001',
 'T1069.003',
 'T1069.002',
 'T1087.004',
 'T1087.003',
 'T1087.002',
 'T1087.001',
 'T1553.004',
 'T1562.004',
 'T1562.003',
 'T1562.002',
 'T1562.001',
 'T1562',
 'T1003.004',
 'T1003.005',
 'T1561.002',
 'T1561.001',
 'T1561',
 'T1560.003',
 'T1560.002',
 'T1560.001',
 'T1560',
 'T1499.004',
 'T1499.003',
 'T1499.002',
 'T1499.001',
 'T1491.002',
 'T1491.001',
 'T1114.003',
 'T1114.002',
 'T1114.001',
 'T1134.005',
 'T1134.004',
 'T1134.003',
 'T1134.002',
 'T1134.001',
 'T1213.002',
 'T1213.001',
 'T1555.003',
 'T1555.002',
 'T1555.001',
 'T1559.002',
 'T1559.001',
 'T1559',
 'T1558.002',
 'T1558.001',
 'T1558',
 'T1557.001',
 'T1557',
 'T1556.002',
 'T1556.001',
 'T1556',
 'T1056.004',
 'T1056.003',
 'T1056.002',
 'T1056.001',
 'T1555',
 'T1552.005',
 'T1003.008',
 'T1003.007',
 'T1003.006',
 'T1558.003',
 'T1552.006',
 'T1003.003',
 'T1003.002',
 'T1003.001',
 'T1110.004',
 'T1110.003',
 'T1110.002',
 'T1110.001',
 'T1021.006',
 'T1021.005',
 'T1021.004',
 'T1021.003',
 'T1021.002',
 'T1021.001',
 'T1554',
 'T1036.006',
 'T1036.005',
 'T1036.004',
 'T1036.003',
 'T1036.002',
 'T1036.001',
 'T1553.003',
 'T1553.002',
 'T1553.001',
 'T1553',
 'T1027.003',
 'T1027.002',
 'T1027.001',
 'T1222.002',
 'T1222.001',
 'T1552.004',
 'T1552.003',
 'T1552.002',
 'T1552.001',
 'T1552',
 'T1216.001',
 'T1070.006',
 'T1070.005',
 'T1070.004',
 'T1070.003',
 'T1550.004',
 'T1550.001',
 'T1550.003',
 'T1550.002',
 'T1550',
 'T1548.004',
 'T1548.003',
 'T1548.002',
 'T1548.001',
 'T1548',
 'T1136.003',
 'T1070.002',
 'T1070.001',
 'T1136.002',
 'T1136.001',
 'T1547.010',
 'T1547.009',
 'T1547.008',
 'T1547.007',
 'T1547.006',
 'T1547.005',
 'T1547.004',
 'T1547.003',
 'T1546.014',
 'T1546.013',
 'T1546.012',
 'T1218.008',
 'T1546.011',
 'T1547.002',
 'T1546.010',
 'T1546.009',
 'T1218.007',
 'T1546.008',
 'T1546.007',
 'T1546.006',
 'T1546.005',
 'T1546.004',
 'T1546.003',
 'T1546.002',
 'T1546.001',
 'T1547.001',
 'T1218.002',
 'T1218.010',
 'T1218.009',
 'T1218.005',
 'T1218.004',
 'T1218.001',
 'T1218.003',
 'T1218.011',
 'T1547',
 'T1546',
 'T1098.003',
 'T1098.002',
 'T1098.001',
 'T1543.004',
 'T1543.003',
 'T1543.002',
 'T1543.001',
 'T1037.005',
 'T1037.004',
 'T1055.012',
 'T1055.013',
 'T1055.011',
 'T1055.014',
 'T1055.009',
 'T1055.008',
 'T1055.005',
 'T1055.004',
 'T1055.003',
 'T1055.002',
 'T1055.001',
 'T1037.003',
 'T1543',
 'T1037.002',
 'T1037.001',
 'T1542.003',
 'T1542.002',
 'T1542.001',
 'T1505.003',
 'T1505.002',
 'T1505.001',
 'T1053.003',
 'T1053.005',
 'T1053.002',
 'T1542',
 'T1137.001',
 'T1137.004',
 'T1137.003',
 'T1137.005',
 'T1137.006',
 'T1137.002',
 'T1531',
 'T1539',
 'T1529',
 'T1518',
 'T1547.013',
 'T1534',
 'T1528',
 'T1535',
 'T1525',
 'T1538',
 'T1530',
 'T1578',
 'T1537',
 'T1526',
 'T1505',
 'T1499',
 'T1497',
 'T1498',
 'T1496',
 'T1495',
 'T1491',
 'T1490',
 'T1489',
 'T1486',
 'T1485',
 'T1484',
 'T1482',
 'T1480',
 'T1222',
 'T1221',
 'T1220',
 'T1190',
 'T1213',
 'T1218',
 'T1202',
 'T1207',
 'T1212',
 'T1201',
 'T1197',
 'T1189',
 'T1211',
 'T1195',
 'T1219',
 'T1205',
 'T1204',
 'T1199',
 'T1217',
 'T1200',
 'T1210',
 'T1203',
 'T1216',
 'T1176',
 'T1185',
 'T1187',
 'T1137',
 'T1140',
 'T1135',
 'T1134',
 'T1136',
 'T1133',
 'T1132',
 'T1129',
 'T1127',
 'T1125',
 'T1124',
 'T1123',
 'T1120',
 'T1119',
 'T1115',
 'T1114',
 'T1113',
 'T1112',
 'T1111',
 'T1110',
 'T1106',
 'T1105',
 'T1104',
 'T1102',
 'T1098',
 'T1095',
 'T1092',
 'T1091',
 'T1090',
 'T1087',
 'T1083',
 'T1082',
 'T1080',
 'T1078',
 'T1074',
 'T1072',
 'T1071',
 'T1070',
 'T1069',
 'T1068',
 'T1059',
 'T1057',
 'T1056',
 'T1055',
 'T1053',
 'T1052',
 'T1049',
 'T1048',
 'T1047',
 'T1046',
 'T1041',
 'T1040',
 'T1039',
 'T1037',
 'T1036',
 'T1033',
 'T1030',
 'T1029',
 'T1027',
 'T1025',
 'T1021',
 'T1020',
 'T1018',
 'T1016',
 'T1014',
 'T1012',
 'T1011',
 'T1010',
 'T1008',
 'T1007',
 'T1006',
 'T1005',
 'T1003',
 'T1001']

In [285]:
path_UCMCatalog2024 = r'C:\Users\jelopez\Documents\CyberProof\python\check_0905\UCM Catalog 2024'

path_UCMCatalog2024_Sentinel = path_UCMCatalog2024 + '/UCM Catalog 2024 [Sentinel].xlsx'

save_path_sentinel = os.path.join(save_path, 'UCM Catalog 2024 Sentinel')

In [ ]:
create_output_folder(save_path_sentinel)

In [297]:
# Formateo del fichero
UCMCatalog2024_Sentinel = pd.read_excel(path_UCMCatalog2024_Sentinel)
UCMCatalog2024_Sentinel['techniques'] = UCMCatalog2024_Sentinel['techniques'].str.replace('[','')
UCMCatalog2024_Sentinel['techniques'] = UCMCatalog2024_Sentinel['techniques'].str.replace(']','')
UCMCatalog2024_Sentinel['techniques'] = UCMCatalog2024_Sentinel['techniques'].str.replace('"','')
UCMCatalog2024_Sentinel['techniques'] = UCMCatalog2024_Sentinel['techniques'].str.split(',')
UCMCatalog2024_Sentinel = UCMCatalog2024_Sentinel.explode('techniques').reset_index()
UCMCatalog2024_Sentinel['query'] = UCMCatalog2024_Sentinel['query'].str.replace('\n', '', regex=False)
UCMCatalog2024_Sentinel['QUERY'] = UCMCatalog2024_Sentinel['query'].str.upper()
UCMCatalog2024_Sentinel['QUERY'] = UCMCatalog2024_Sentinel['QUERY'].fillna('N/A')
UCMCatalog2024_Sentinel.head(2)

,index,displayName,tactics,techniques,query,QUERY
0,0,Azure Redis Cache - Config modification attempt,"[""Execution""]",T0863,AzureActivity| where OperationNameValue contai...,AZUREACTIVITY| WHERE OPERATIONNAMEVALUE CONTAI...
1,1,Azure Redis Cache - Access keys regeneration a...,"[""ResourceDevelopment""]",T1587,AzureActivity| where OperationName == 'Regener...,AZUREACTIVITY| WHERE OPERATIONNAME == 'REGENER...

In [298]:
# Limpiamos el df para poder unir
UCMCatalog2024_Sentinel_raw = UCMCatalog2024_Sentinel.assign(type_source='item raw')[['displayName','tactics','techniques','query','type_source']]
UCMCatalog2024_Sentinel_raw = UCMCatalog2024_Sentinel_raw[UCMCatalog2024_Sentinel_raw['techniques']!='']
UCMCatalog2024_Sentinel_raw = UCMCatalog2024_Sentinel_raw.dropna(subset=['techniques'])
UCMCatalog2024_Sentinel_raw = UCMCatalog2024_Sentinel_raw.drop_duplicates()
UCMCatalog2024_Sentinel_raw.rename(columns={'techniques': 'Technique','displayName':'Display name','tactics':'Tactics','query':'Query','type_source':'Type source'}, inplace=True)
UCMCatalog2024_Sentinel_raw.head(2)

,Display name,Tactics,Technique,Query,Type source
0,Azure Redis Cache - Config modification attempt,"[""Execution""]",T0863,AzureActivity| where OperationNameValue contai...,item raw
1,Azure Redis Cache - Access keys regeneration a...,"[""ResourceDevelopment""]",T1587,AzureActivity| where OperationName == 'Regener...,item raw

In [299]:
# Limpiamos y formateamos para la union
UCMCatalog2024_Sentinel_query = UCMCatalog2024_Sentinel
UCMCatalog2024_Sentinel_query['techniques_from_query'] = UCMCatalog2024_Sentinel_query['query'].apply(lambda x: find_techniques(x))
UCMCatalog2024_Sentinel_query = UCMCatalog2024_Sentinel_query[UCMCatalog2024_Sentinel_query['techniques_from_query']!='']
UCMCatalog2024_Sentinel_query = UCMCatalog2024_Sentinel_query.dropna(subset=['techniques_from_query'])
UCMCatalog2024_Sentinel_query['techniques_from_query_explode'] = UCMCatalog2024_Sentinel_query['techniques_from_query'].str.split(',')
UCMCatalog2024_Sentinel_query = UCMCatalog2024_Sentinel_query.explode('techniques_from_query_explode')
UCMCatalog2024_Sentinel_query = UCMCatalog2024_Sentinel_query.drop_duplicates()
UCMCatalog2024_Sentinel_query = UCMCatalog2024_Sentinel_query.assign(type_source='item description')[['displayName','tactics','techniques_from_query_explode','query','type_source']].reset_index(drop=True)
UCMCatalog2024_Sentinel_query.rename(columns={'techniques_from_query_explode': 'Technique','displayName':'Display name','tactics':'Tactics','query':'Query','type_source':'Type source'}, inplace=True)
UCMCatalog2024_Sentinel_query.head(2)

,Display name,Tactics,Technique,Query,Type source
0,SOC - FW - Threat Intelligence - Malicious IP,"[""InitialAccess""]",T1597.001,// Threat Intelligence - Malicious IP// Mitre ...,item description
1,SOC - FW - Threat Intelligence - Malicious IP,"[""InitialAccess""]",T1597,// Threat Intelligence - Malicious IP// Mitre ...,item description

In [300]:
UCMCatalog2024_Sentinel_union = pd.concat([UCMCatalog2024_Sentinel_raw, UCMCatalog2024_Sentinel_query])
UCMCatalog2024_Sentinel_union.head(2)

,Display name,Tactics,Technique,Query,Type source
0,Azure Redis Cache - Config modification attempt,"[""Execution""]",T0863,AzureActivity| where OperationNameValue contai...,item raw
1,Azure Redis Cache - Access keys regeneration a...,"[""ResourceDevelopment""]",T1587,AzureActivity| where OperationName == 'Regener...,item raw

In [302]:

for indice, row in UCMCatalog2024_Sentinel_union.iterrows():
    folder_name = row['Technique'].replace(' ', '')
    file_name = row['Display name'] + ".csv"
    file_name = clean_names(file_name)
    folder_path = os.path.join(save_path_sentinel, folder_name)
    csv_file = os.path.join(save_path_sentinel, folder_name, file_name)
    os.makedirs(folder_path, exist_ok=True)
    #row.to_csv(csv_file, index=False, header=True, sep=';', quoting=csv.QUOTE_ALL)
    temp_df = pd.DataFrame(row).T
    temp_df.columns = UCMCatalog2024_Sentinel_union.columns
    temp_df.to_csv(csv_file, index=False, header=True, sep=';', quoting=csv.QUOTE_ALL)

#### TTP's UCM Catalog 2024 Qradar *from excel

In [303]:
# Esto es temporal ya que parece ser que he excedido el número de peticiones
#lift = attack_client()

path_techniques = 'C:/Users/jelopez/Documents/CyberProof/python/recursos/id_tecnicas_16052024.csv'
techniques_enterprise = pd.read_csv(path_techniques)
techniques_enterprise = techniques_enterprise['ID Tecnica'].to_list()

In [304]:
path_UCMCatalog2024 = r'C:\Users\jelopez\Documents\CyberProof\python\check_0905\UCM Catalog 2024'

path_UCMCatalog2024_Qradar = path_UCMCatalog2024 + '/UCM Catalog 2024 [Qradar].xlsx'

save_path_qradar = os.path.join(save_path, 'UCM Catalog 2024 Qradar')

In [ ]:
create_output_folder(save_path_qradar)

*baseline*

In [305]:
UCMCatalog2024_Qradar_baseline = pd.read_excel(path_UCMCatalog2024_Qradar,'Baseline')

UCMCatalog2024_Qradar_baseline['Mitre Technique'] = UCMCatalog2024_Qradar_baseline['Mitre Technique'].str.replace('\n', '', regex=False)

UCMCatalog2024_Qradar_baseline['MITRE_TECHNIQUE'] = UCMCatalog2024_Qradar_baseline['Mitre Technique'].str.upper()
UCMCatalog2024_Qradar_baseline['techniques_from_raw'] = UCMCatalog2024_Qradar_baseline['MITRE_TECHNIQUE'].apply(lambda x: find_techniques(x))
UCMCatalog2024_Qradar_baseline = UCMCatalog2024_Qradar_baseline.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_baseline['Required Telemetry'] = UCMCatalog2024_Qradar_baseline['Required Telemetry'].fillna('N/A')
UCMCatalog2024_Qradar_baseline['Name Mitre Technique'] = UCMCatalog2024_Qradar_baseline['Mitre Technique'].str.split('-').str[1]
UCMCatalog2024_Qradar_baseline['techniques_from_raw_explode'] = UCMCatalog2024_Qradar_baseline['techniques_from_raw'].str.split(',')
UCMCatalog2024_Qradar_baseline = UCMCatalog2024_Qradar_baseline.explode('techniques_from_raw_explode')
UCMCatalog2024_Qradar_baseline = UCMCatalog2024_Qradar_baseline[UCMCatalog2024_Qradar_baseline['techniques_from_raw']!='']
UCMCatalog2024_Qradar_baseline = UCMCatalog2024_Qradar_baseline.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_baseline.rename(columns={'techniques_from_raw_explode': 'Technique'}, inplace=True)

UCMCatalog2024_Qradar_baseline.shape

(124, 10)

In [306]:
UCMCatalog2024_Qradar_baseline.tail(2)

,Rule,Priority,Mitre Tactic,Mitre Technique,Log Source Type,Required Telemetry,MITRE_TECHNIQUE,techniques_from_raw,Name Mitre Technique,Technique
92,[CyberProof] - [Windows] - Suspicious MS Offic...,MED,Initial Access\nExecution\nDefense Evasion,T1059.003 - Command and Scripting Interpreter:...,Windows,N/A,T1059.003 - COMMAND AND SCRIPTING INTERPRETER:...,"T1059.003, T1566.001, T1566, T1218, T1059",Command and Scripting Interpreter: Windows Co...,T1059
100,[CyberProof] - [QRadar] - Multiple Failed Logins,LOW,Credential Access,T1110 - Brute Force,QRadar Audit,N/A,T1110 - BRUTE FORCE,T1110,Brute Force,T1110

In [307]:
colums_sel = ['Rule','Priority','Mitre Technique','Technique','Name Mitre Technique','Mitre Tactic','Required Telemetry']
UCMCatalog2024_Qradar_baseline = UCMCatalog2024_Qradar_baseline[colums_sel]
UCMCatalog2024_Qradar_baseline.tail(2)

,Rule,Priority,Mitre Technique,Technique,Name Mitre Technique,Mitre Tactic,Required Telemetry
92,[CyberProof] - [Windows] - Suspicious MS Offic...,MED,T1059.003 - Command and Scripting Interpreter:...,T1059,Command and Scripting Interpreter: Windows Co...,Initial Access\nExecution\nDefense Evasion,N/A
100,[CyberProof] - [QRadar] - Multiple Failed Logins,LOW,T1110 - Brute Force,T1110,Brute Force,Credential Access,N/A

In [308]:
for indice, row in UCMCatalog2024_Qradar_baseline.iterrows():
    folder_name = row['Technique'].replace(' ', '')
    file_name = 'Baseline - '+row['Rule'] + ".csv"
    file_name = clean_names(file_name)
    folder_path = os.path.join(save_path_qradar, folder_name)
    csv_file = os.path.join(save_path_qradar, folder_name, file_name)
    os.makedirs(folder_path, exist_ok=True)
    temp_df = pd.DataFrame(row).T
    temp_df.columns = UCMCatalog2024_Qradar_baseline.columns
    temp_df.to_csv(csv_file, index=False, header=True, sep=';', quoting=csv.QUOTE_ALL)

*Windows|Sysmon*

In [309]:
UCMCatalog2024_Qradar_winsysmon = pd.read_excel(path_UCMCatalog2024_Qradar,'Windows|Sysmon')
UCMCatalog2024_Qradar_winsysmon.shape

(223, 5)

In [310]:
UCMCatalog2024_Qradar_winsysmon = pd.read_excel(path_UCMCatalog2024_Qradar,'Windows|Sysmon')

UCMCatalog2024_Qradar_winsysmon['Mitre Technique'] = UCMCatalog2024_Qradar_winsysmon['Mitre Technique'].str.replace('\n', '', regex=False)

UCMCatalog2024_Qradar_winsysmon['MITRE_TECHNIQUE'] = UCMCatalog2024_Qradar_winsysmon['Mitre Technique'].str.upper()
UCMCatalog2024_Qradar_winsysmon['techniques_from_raw'] = UCMCatalog2024_Qradar_winsysmon['MITRE_TECHNIQUE'].apply(lambda x: find_techniques(x))
UCMCatalog2024_Qradar_winsysmon = UCMCatalog2024_Qradar_winsysmon.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_winsysmon['Mitre Tactic'] = UCMCatalog2024_Qradar_winsysmon['Mitre Tactic'].fillna('N/A')
UCMCatalog2024_Qradar_winsysmon['Name Mitre Technique'] = UCMCatalog2024_Qradar_winsysmon['Mitre Technique'].str.split('-').str[1]
UCMCatalog2024_Qradar_winsysmon['techniques_from_raw_explode'] = UCMCatalog2024_Qradar_winsysmon['techniques_from_raw'].str.split(',')
UCMCatalog2024_Qradar_winsysmon = UCMCatalog2024_Qradar_winsysmon.explode('techniques_from_raw_explode')
UCMCatalog2024_Qradar_winsysmon = UCMCatalog2024_Qradar_winsysmon[UCMCatalog2024_Qradar_winsysmon['techniques_from_raw']!='']
UCMCatalog2024_Qradar_winsysmon = UCMCatalog2024_Qradar_winsysmon.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_winsysmon.rename(columns={'techniques_from_raw_explode': 'Technique'}, inplace=True)
UCMCatalog2024_Qradar_winsysmon['Name Mitre Technique'] = UCMCatalog2024_Qradar_winsysmon['Name Mitre Technique'].fillna('N/A')
UCMCatalog2024_Qradar_winsysmon.head(2)

,Rule,Priority,Mitre Tactic,Mitre Technique,Log Source Type,MITRE_TECHNIQUE,techniques_from_raw,Name Mitre Technique,Technique
81,PingCastle Binary Execution,HIGH,"Execution, Defense Evasion","T1059, T1202",Windows/Sysmon,"T1059, T1202","T1202, T1059",N/A,T1202
81,PingCastle Binary Execution,HIGH,"Execution, Defense Evasion","T1059, T1202",Windows/Sysmon,"T1059, T1202","T1202, T1059",N/A,T1059

In [311]:
colums_sel = ['Rule','Priority','Technique','Mitre Technique','Name Mitre Technique','Mitre Tactic','Log Source Type']
UCMCatalog2024_Qradar_winsysmon = UCMCatalog2024_Qradar_winsysmon[colums_sel]
UCMCatalog2024_Qradar_winsysmon.tail(2)

,Rule,Priority,Technique,Mitre Technique,Name Mitre Technique,Mitre Tactic,Log Source Type
81,PingCastle Binary Execution,HIGH,T1202,"T1059, T1202",N/A,"Execution, Defense Evasion",Windows/Sysmon
81,PingCastle Binary Execution,HIGH,T1059,"T1059, T1202",N/A,"Execution, Defense Evasion",Windows/Sysmon

In [312]:
for indice, row in UCMCatalog2024_Qradar_winsysmon.iterrows():
    folder_name = row['Technique'].replace(' ', '')
    file_name = 'WindowsSysmon - '+row['Rule'] + ".csv"
    file_name = clean_names(file_name)
    folder_path = os.path.join(save_path_qradar, folder_name)
    csv_file = os.path.join(save_path_qradar, folder_name, file_name)
    os.makedirs(folder_path, exist_ok=True)
    temp_df = pd.DataFrame(row).T
    temp_df.columns = UCMCatalog2024_Qradar_winsysmon.columns
    temp_df.to_csv(csv_file, index=False, header=True, sep=';', quoting=csv.QUOTE_ALL)

*Atomics*

In [313]:
UCMCatalog2024_Qradar_atomics = pd.read_excel(path_UCMCatalog2024_Qradar,'Atomics')

UCMCatalog2024_Qradar_atomics['Mitre Technique'] = UCMCatalog2024_Qradar_atomics['Mitre Technique'].str.replace('\n', '', regex=False)

UCMCatalog2024_Qradar_atomics['MITRE_TECHNIQUE'] = UCMCatalog2024_Qradar_atomics['Mitre Technique'].str.upper()
UCMCatalog2024_Qradar_atomics['techniques_from_raw'] = UCMCatalog2024_Qradar_atomics['MITRE_TECHNIQUE'].apply(lambda x: find_techniques(x))
UCMCatalog2024_Qradar_atomics = UCMCatalog2024_Qradar_atomics.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_atomics['Mitre Tactic'] = UCMCatalog2024_Qradar_atomics['Mitre Tactic'].fillna('N/A')
UCMCatalog2024_Qradar_atomics['Name Mitre Technique'] = UCMCatalog2024_Qradar_atomics['Mitre Technique'].str.split('-').str[1]
UCMCatalog2024_Qradar_atomics['techniques_from_raw_explode'] = UCMCatalog2024_Qradar_atomics['techniques_from_raw'].str.split(',')
UCMCatalog2024_Qradar_atomics = UCMCatalog2024_Qradar_atomics.explode('techniques_from_raw_explode')
UCMCatalog2024_Qradar_atomics = UCMCatalog2024_Qradar_atomics[UCMCatalog2024_Qradar_atomics['techniques_from_raw']!='']
UCMCatalog2024_Qradar_atomics = UCMCatalog2024_Qradar_atomics.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_atomics.rename(columns={'techniques_from_raw_explode': 'Technique','TREND': 'Trend'}, inplace=True)
UCMCatalog2024_Qradar_atomics.head(2)

,Trend,Rule,Priority,Mitre Tactic,Mitre Technique,Log Source Type,MITRE_TECHNIQUE,techniques_from_raw,Name Mitre Technique,Technique
0,2024 - Ransomware,[AtomicRedTeam] - [InhibitSystemRecovery #1] ...,HIGH,Impact,T1490 - Inhibit System Recovery,Windows/Sysmon/Powershell,T1490 - INHIBIT SYSTEM RECOVERY,T1490,Inhibit System Recovery,T1490
1,2024 - Ransomware,[AtomicRedTeam] - [InhibitSystemRecovery #2] ...,HIGH,Impact,T1490 - Inhibit System Recovery,Windows/Sysmon/Powershell,T1490 - INHIBIT SYSTEM RECOVERY,T1490,Inhibit System Recovery,T1490

In [314]:
colums_sel = ['Trend','Rule','Priority','Technique','Mitre Technique','Name Mitre Technique','Mitre Tactic','Log Source Type']
UCMCatalog2024_Qradar_atomics = UCMCatalog2024_Qradar_atomics[colums_sel]
UCMCatalog2024_Qradar_atomics.tail(2)

,Trend,Rule,Priority,Technique,Mitre Technique,Name Mitre Technique,Mitre Tactic,Log Source Type
54,2024 - Threats,[AtomicRedTeam] - [Smashjacker #1] - AppInit D...,MED,T1546,T1546.010 - Event Triggered Execution:AppInit ...,Event Triggered Execution:AppInit DLLs,Privilege Escalation\nPersistence,Windows/Sysmon/Powershell
55,2024 - Threats,[AtomicRedTeam] - [Smashjacker #2] - Web Brows...,MED,T1176,T1176 - Browser Extensions,Browser Extensions,Persistence,Windows/Sysmon/Powershell

In [315]:
for indice, row in UCMCatalog2024_Qradar_atomics.iterrows():
    folder_name = row['Technique'].replace(' ', '')
    file_name = 'Atomics - '+row['Rule'] + ".csv"
    file_name = clean_names(file_name)
    folder_path = os.path.join(save_path_qradar, folder_name)
    csv_file = os.path.join(save_path_qradar, folder_name, file_name)
    os.makedirs(folder_path, exist_ok=True)
    temp_df = pd.DataFrame(row).T
    temp_df.columns = UCMCatalog2024_Qradar_atomics.columns
    temp_df.to_csv(csv_file, index=False, header=True, sep=';', quoting=csv.QUOTE_ALL)

*FW*

In [316]:
UCMCatalog2024_Qradar_fw = pd.read_excel(path_UCMCatalog2024_Qradar,'FW')

UCMCatalog2024_Qradar_fw['Mitre Technique'] = UCMCatalog2024_Qradar_fw['Mitre Technique'].str.replace('\n', '', regex=False)

UCMCatalog2024_Qradar_fw['MITRE_TECHNIQUE'] = UCMCatalog2024_Qradar_fw['Mitre Technique'].str.upper()
UCMCatalog2024_Qradar_fw['techniques_from_raw'] = UCMCatalog2024_Qradar_fw['MITRE_TECHNIQUE'].apply(lambda x: find_techniques(x))
UCMCatalog2024_Qradar_fw = UCMCatalog2024_Qradar_fw.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_fw['Mitre Tactic'] = UCMCatalog2024_Qradar_fw['Mitre Tactic'].fillna('N/A')
UCMCatalog2024_Qradar_fw['Name Mitre Technique'] = UCMCatalog2024_Qradar_fw['Mitre Technique'].str.split('-').str[1]
UCMCatalog2024_Qradar_fw['techniques_from_raw_explode'] = UCMCatalog2024_Qradar_fw['techniques_from_raw'].str.split(',')
UCMCatalog2024_Qradar_fw = UCMCatalog2024_Qradar_fw.explode('techniques_from_raw_explode')
UCMCatalog2024_Qradar_fw = UCMCatalog2024_Qradar_fw[UCMCatalog2024_Qradar_fw['techniques_from_raw']!='']
UCMCatalog2024_Qradar_fw = UCMCatalog2024_Qradar_fw.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_fw.rename(columns={'techniques_from_raw_explode': 'Technique'}, inplace=True)
UCMCatalog2024_Qradar_fw.head(2)

,Rule,Priority,Mitre Tactic,Mitre Technique,MITRE_TECHNIQUE,techniques_from_raw,Name Mitre Technique,Technique
10,[CyberProof] - [Cisco ASA] - Login to SSH Inte...,Low,Initial Access,T1078 - Valid Accounts,T1078 - VALID ACCOUNTS,T1078,Valid Accounts,T1078
11,[CyberProof] - [Cisco ASA] - User Deleted,Medium,Defense Evasion,T1070 - Indicator Removal,T1070 - INDICATOR REMOVAL,T1070,Indicator Removal,T1070

In [317]:
colums_sel = ['Rule','Priority','Technique','Mitre Technique','Name Mitre Technique','Mitre Tactic']
UCMCatalog2024_Qradar_fw = UCMCatalog2024_Qradar_fw[colums_sel]
UCMCatalog2024_Qradar_fw.tail(2)

,Rule,Priority,Technique,Mitre Technique,Name Mitre Technique,Mitre Tactic
15,[CyberProof] - [Cisco ASA] - Group Policy Deleted,Medium,T1484,T1484.001 - Group Policy Modification,Group Policy Modification,Defense Evasion
16,[CyberProof] - [Cisco ASA] - User Locked,Medium,T1531,T1531 - Account Access Removal,Account Access Removal,Impact

In [318]:
for indice, row in UCMCatalog2024_Qradar_fw.iterrows():
    folder_name = row['Technique'].replace(' ', '')
    file_name = 'FW - '+row['Rule'] + ".csv"
    file_name = clean_names(file_name)
    folder_path = os.path.join(save_path_qradar, folder_name)
    csv_file = os.path.join(save_path_qradar, folder_name, file_name)
    os.makedirs(folder_path, exist_ok=True)
    temp_df = pd.DataFrame(row).T
    temp_df.columns = UCMCatalog2024_Qradar_fw.columns
    temp_df.to_csv(csv_file, index=False, header=True, sep=';', quoting=csv.QUOTE_ALL)

*AWS*

In [319]:
UCMCatalog2024_Qradar_aws = pd.read_excel(path_UCMCatalog2024_Qradar,'AWS')

UCMCatalog2024_Qradar_aws['Mitre Technique'] = UCMCatalog2024_Qradar_aws['Mitre Technique'].str.replace('\n', '', regex=False)

UCMCatalog2024_Qradar_aws['MITRE_TECHNIQUE'] = UCMCatalog2024_Qradar_aws['Mitre Technique'].str.upper()
UCMCatalog2024_Qradar_aws['techniques_from_raw'] = UCMCatalog2024_Qradar_aws['MITRE_TECHNIQUE'].apply(lambda x: find_techniques(x))
UCMCatalog2024_Qradar_aws = UCMCatalog2024_Qradar_aws.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_aws['Mitre Tactic'] = UCMCatalog2024_Qradar_aws['Mitre Tactic'].fillna('N/A')
UCMCatalog2024_Qradar_aws['Name Mitre Technique'] = UCMCatalog2024_Qradar_aws['Mitre Technique'].str.split('-').str[1]
UCMCatalog2024_Qradar_aws['techniques_from_raw_explode'] = UCMCatalog2024_Qradar_aws['techniques_from_raw'].str.split(',')
UCMCatalog2024_Qradar_aws = UCMCatalog2024_Qradar_aws.explode('techniques_from_raw_explode')
UCMCatalog2024_Qradar_aws = UCMCatalog2024_Qradar_aws[UCMCatalog2024_Qradar_aws['techniques_from_raw']!='']
UCMCatalog2024_Qradar_aws = UCMCatalog2024_Qradar_aws.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_Qradar_aws.rename(columns={'techniques_from_raw_explode': 'Technique'}, inplace=True)
UCMCatalog2024_Qradar_aws.head(2)

,Rule,Priority,Mitre Tactic,Mitre Technique,Log Source Type,MITRE_TECHNIQUE,techniques_from_raw,Name Mitre Technique,Technique
1,[CyberProof] - [AWS] - Config Disabling Channe...,HIGH,Defense Evasion,T1562.001 - Impair Defenses: Disable or Modify...,AWS,T1562.001 - IMPAIR DEFENSES: DISABLE OR MODIFY...,"T1562.001, T1562",Impair Defenses: Disable or Modify Tools,T1562.001
1,[CyberProof] - [AWS] - Config Disabling Channe...,HIGH,Defense Evasion,T1562.001 - Impair Defenses: Disable or Modify...,AWS,T1562.001 - IMPAIR DEFENSES: DISABLE OR MODIFY...,"T1562.001, T1562",Impair Defenses: Disable or Modify Tools,T1562

In [320]:
colums_sel = ['Rule','Priority','Technique','Mitre Technique','Name Mitre Technique','Mitre Tactic','Log Source Type']
UCMCatalog2024_Qradar_aws = UCMCatalog2024_Qradar_aws[colums_sel]
UCMCatalog2024_Qradar_aws.tail(2)

,Rule,Priority,Technique,Mitre Technique,Name Mitre Technique,Mitre Tactic,Log Source Type
8,[CyberProof] - [AWS] - AWS GuardDuty Trusted I...,HIGH,T1562,T1562.001 - Impair Defenses: Disable or Modify...,Impair Defenses: Disable or Modify Tools,Defense Evasion,AWS
9,[CyberProof] - [AWS] - Identity Center Identit...,HIGH,T1556,T1556 - Modify Authentication Process,Modify Authentication Process,Persistence,AWS

In [321]:
for indice, row in UCMCatalog2024_Qradar_aws.iterrows():
    folder_name = row['Technique'].replace(' ', '')
    file_name = 'AWS - '+row['Rule'] + ".csv"
    file_name = clean_names(file_name)
    folder_path = os.path.join(save_path_qradar, folder_name)
    csv_file = os.path.join(save_path_qradar, folder_name, file_name)
    os.makedirs(folder_path, exist_ok=True)
    temp_df = pd.DataFrame(row).T
    temp_df.columns = UCMCatalog2024_Qradar_aws.columns
    temp_df.to_csv(csv_file, index=False, header=True, sep=';', quoting=csv.QUOTE_ALL)

#### TTP's UCM Catalog 2024 Splunk *from excel

In [322]:
path_UCMCatalog2024 = r'C:\Users\jelopez\Documents\CyberProof\python\check_0905\UCM Catalog 2024'

path_UCMCatalog2024_Splunk = path_UCMCatalog2024 + '/UCM Catalog 2024 [Splunk].xlsx'

save_path_splunk = os.path.join(save_path, 'UCM Catalog 2024 Splunk')

In [ ]:
create_output_folder(save_path_splunk)

In [323]:
UCMCatalog2024_splunk = pd.read_excel(path_UCMCatalog2024_Splunk)

UCMCatalog2024_splunk['search'] = UCMCatalog2024_splunk['search'].str.replace('\n', '', regex=False)

UCMCatalog2024_splunk['MITRE_TECHNIQUE'] = UCMCatalog2024_splunk['Mitre Technique'].str.upper()
UCMCatalog2024_splunk['DESCRIPTION'] = UCMCatalog2024_splunk['description'].str.upper()
UCMCatalog2024_splunk['SEARCH'] = UCMCatalog2024_splunk['search'].str.upper()
UCMCatalog2024_splunk['techniques_from_raw'] = UCMCatalog2024_splunk['MITRE_TECHNIQUE'].apply(lambda x: find_techniques(x))
UCMCatalog2024_splunk['techniques_from_description'] = UCMCatalog2024_splunk['DESCRIPTION'].apply(lambda x: find_techniques(x))
UCMCatalog2024_splunk['techniques_from_search'] = UCMCatalog2024_splunk['SEARCH'].apply(lambda x: find_techniques(x))
UCMCatalog2024_splunk = UCMCatalog2024_splunk.fillna('N/A')
UCMCatalog2024_splunk.head(2)

,title,description,search,severity,security_domain,MITRE Tactic,Mitre Technique,MITRE_TECHNIQUE,DESCRIPTION,SEARCH,techniques_from_raw,techniques_from_description,techniques_from_search
0,Access - Abstraction Non-Us Login - Rule,Abstractors are not allowed to work within Pat...,index=duo sourcetype!=okta:im p- user=p-* fact...,high,access,N/A,N/A,N/A,ABSTRACTORS ARE NOT ALLOWED TO WORK WITHIN PAT...,INDEX=DUO SOURCETYPE!=OKTA:IM P- USER=P-* FACT...,,,
1,Access - Credential Stuffing - Rule,Detects automated injection of stolen username...,| tstats summariesonly=t count as actioncount ...,low,access,N/A,N/A,N/A,DETECTS AUTOMATED INJECTION OF STOLEN USERNAME...,| TSTATS SUMMARIESONLY=T COUNT AS ACTIONCOUNT ...,,,

*raw*

In [324]:
UCMCatalog2024_splunk_raw = UCMCatalog2024_splunk
UCMCatalog2024_splunk_raw['Name Mitre Technique'] = UCMCatalog2024_splunk_raw['Mitre Technique'].str.split('-').str[1]
UCMCatalog2024_splunk_raw['techniques_from_raw_explode'] = UCMCatalog2024_splunk_raw['techniques_from_raw'].str.split(',')
UCMCatalog2024_splunk_raw = UCMCatalog2024_splunk_raw.explode('techniques_from_raw_explode')
UCMCatalog2024_splunk_raw = UCMCatalog2024_splunk_raw[UCMCatalog2024_splunk_raw['techniques_from_raw']!='']
UCMCatalog2024_splunk_raw = UCMCatalog2024_splunk_raw.dropna(subset=['techniques_from_raw'])
UCMCatalog2024_splunk_raw.rename(columns={'title': 'Rule','description': 'Description','search': 'Search','severity': 'Severity','techniques_from_raw_explode': 'Technique','security_domain': 'Security domain','MITRE Tactic': 'Mitre Tactic'}, inplace=True)
UCMCatalog2024_splunk_raw['Search'] = UCMCatalog2024_splunk_raw['Search'].str.replace('\n', '', regex=False)
colums_sel = ['Rule','Description','Severity','Technique','Mitre Technique','Name Mitre Technique','Mitre Tactic','Security domain','Search']
UCMCatalog2024_splunk_raw = UCMCatalog2024_splunk_raw[colums_sel]
UCMCatalog2024_splunk_raw.tail(2)

,Rule,Description,Severity,Technique,Mitre Technique,Name Mitre Technique,Mitre Tactic,Security domain,Search
2363,CyberProof - Ransomware - Clop Ransomware Know...,This detection is to identify the common servi...,N/A,T1543,"{""analytic_story"":[""Clop Ransomware""],""cis20"":...",NaN,N/A,N/A,index=windows sourcetype=WinEventLog eventtype...
2364,CyberProof - Ransomware - Known Services Kille...,This search detects a suspicioous termination ...,N/A,T1490,"{""analytic_story"":[""Ransomware"",""BlackMatter R...",NaN,N/A,N/A,index=windows sourcetype=WinEventLog eventtype...

In [325]:
UCMCatalog2024_splunk_description = UCMCatalog2024_splunk
UCMCatalog2024_splunk_description['Name Mitre Technique'] = UCMCatalog2024_splunk_description['Mitre Technique'].str.split('-').str[1]
UCMCatalog2024_splunk_description['techniques_from_description_explode'] = UCMCatalog2024_splunk_description['techniques_from_description'].str.split(',')
UCMCatalog2024_splunk_description = UCMCatalog2024_splunk_description.explode('techniques_from_description_explode')
UCMCatalog2024_splunk_description = UCMCatalog2024_splunk_description[UCMCatalog2024_splunk_description['techniques_from_description']!='']
UCMCatalog2024_splunk_description = UCMCatalog2024_splunk_description.dropna(subset=['techniques_from_description'])
UCMCatalog2024_splunk_description.rename(columns={'title': 'Rule','description': 'Description','search': 'Search','severity': 'Severity','techniques_from_description_explode': 'Technique','security_domain': 'Security domain','MITRE Tactic': 'Mitre Tactic'}, inplace=True)
UCMCatalog2024_splunk_description['Search'] = UCMCatalog2024_splunk_description['Search'].str.replace('\n', '', regex=False)
colums_sel = ['Rule','Description','Severity','Technique','Mitre Technique','Name Mitre Technique','Mitre Tactic','Security domain','Search']
UCMCatalog2024_splunk_description = UCMCatalog2024_splunk_description[colums_sel]
UCMCatalog2024_splunk_description.tail(2)

Empty DataFrame
Columns: [Rule, Description, Severity, Technique, Mitre Technique, Name Mitre Technique, Mitre Tactic, Security domain, Search]
Index: []

In [326]:
UCMCatalog2024_splunk_search = UCMCatalog2024_splunk
UCMCatalog2024_splunk_search['Name Mitre Technique'] = UCMCatalog2024_splunk_search['Mitre Technique'].str.split('-').str[1]
UCMCatalog2024_splunk_search['techniques_from_search_explode'] = UCMCatalog2024_splunk_search['techniques_from_search'].str.split(',')
UCMCatalog2024_splunk_search = UCMCatalog2024_splunk_search.explode('techniques_from_search_explode')
UCMCatalog2024_splunk_search = UCMCatalog2024_splunk_search[UCMCatalog2024_splunk_search['techniques_from_search']!='']
UCMCatalog2024_splunk_search = UCMCatalog2024_splunk_search.dropna(subset=['techniques_from_search'])
UCMCatalog2024_splunk_search.rename(columns={'title': 'Rule','description': 'Description','search': 'Search','severity': 'Severity','techniques_from_search_explode': 'Technique','security_domain': 'Security domain','MITRE Tactic': 'Mitre Tactic'}, inplace=True)
UCMCatalog2024_splunk_search['Search'] = UCMCatalog2024_splunk_search['Search'].str.replace('\n', '', regex=False)
colums_sel = ['Rule','Description','Severity','Technique','Mitre Technique','Name Mitre Technique','Mitre Tactic','Security domain','Search']
UCMCatalog2024_splunk_search = UCMCatalog2024_splunk_search[colums_sel]
UCMCatalog2024_splunk_search.tail(2)

Empty DataFrame
Columns: [Rule, Description, Severity, Technique, Mitre Technique, Name Mitre Technique, Mitre Tactic, Security domain, Search]
Index: []

In [327]:
UCMCatalog2024_Splunk_union = pd.concat([UCMCatalog2024_splunk_raw, UCMCatalog2024_splunk_description, UCMCatalog2024_splunk_search])
UCMCatalog2024_Splunk_union.shape

(105, 9)

In [328]:
for indice, row in UCMCatalog2024_Splunk_union.iterrows():
    folder_name = row['Technique'].replace(' ', '')
    file_name = row['Rule'] + ".csv"
    file_name = clean_names(file_name)
    folder_path = os.path.join(save_path_splunk, folder_name)
    csv_file = os.path.join(save_path_splunk, folder_name, file_name)
    os.makedirs(folder_path, exist_ok=True)
    temp_df = pd.DataFrame(row).T
    temp_df.columns = UCMCatalog2024_Splunk_union.columns
    temp_df.to_csv(csv_file, index=False, header=True, sep=';', quoting=csv.QUOTE_ALL)

#### TTP's Sigma HQ 1

<h5 style="background-color: #E11717; color: black;">
    Importante: No ejecutar por solicitud de Seguridad
</h5>

In [16]:
# zip_sigma_hq1 = 'https://github.com/SigmaHQ/sigma/archive/refs/heads/master.zip'
save_path_sigma_hq1 = os.path.join(save_path, 'sigmaHQ1')

In [17]:
create_output_folder(save_path_sigma_hq1)

In [18]:
download_folder_unzip(zip_sigma_hq1, 'sigma-master/rules', temp_path)
download_folder_unzip(zip_sigma_hq1, 'sigma-master/rules-compliance', temp_path)
download_folder_unzip(zip_sigma_hq1, 'sigma-master/rules-dfir', temp_path)
download_folder_unzip(zip_sigma_hq1, 'sigma-master/rules-emerging-threats', temp_path)
download_folder_unzip(zip_sigma_hq1, 'sigma-master/rules-placeholder', temp_path)
download_folder_unzip(zip_sigma_hq1, 'sigma-master/rules-threat-hunting', temp_path)
download_folder_unzip(zip_sigma_hq1, 'sigma-master/rules-placeholder', temp_path)

Descarga y descompresión completadas correctamente.
Descarga y descompresión completadas correctamente.
Descarga y descompresión completadas correctamente.
Descarga y descompresión completadas correctamente.
Descarga y descompresión completadas correctamente.
Descarga y descompresión completadas correctamente.
Descarga y descompresión completadas correctamente.

In [19]:
files = getListOfFilesSub(temp_path+r'\sigma-master')
files[:3]

['C:\\Users\\jelopez\\Downloads\\sigma-master\\rules\\application\\django\\appframework_django_exceptions.yml',
 'C:\\Users\\jelopez\\Downloads\\sigma-master\\rules\\application\\jvm\\java_jndi_injection_exploitation_attempt.yml',
 'C:\\Users\\jelopez\\Downloads\\sigma-master\\rules\\application\\jvm\\java_local_file_read.yml']

In [20]:
# Recorrer la lista de archivos
num_yamls = []
has_label_tags = []
has_label_with_content_tags = []
has_label_without_content_tags = []
no_label_tags = []
notTTPinTags = []
notTTPinTags_with_TTP_in_description = []
notTTPinTags_without_description = []
error_load = []

for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yaml' or extension == '.yml':
        with open(item) as file:
            num_yamls.append(item)
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y copiamos el fichero a la carpeta T0000
                document = yaml.full_load(file)
                if 'tags' in document:
                    # Si encontramos la etiqueta 'tags' en el yaml lo guardamos como una variable 
                    tags = document.get('tags', [])
                    has_label_tags.append(item)
                    # Si el resultado de esa variable no está vacío y contiene información lo convertimos en una lista
                    if not isinstance(tags, type(None)):
                        has_label_with_content_tags.append(item)
                        # Convertimos en lista el contenido de la etiqueta
                        #tags = [tags]
                        tags = [tag.upper() for tag in tags if isinstance(tag, str)]
                        # Recorremos la lista de items contenidos en tags y contamos las ttp encontradas ya que si no encontramos ninguna, pese haber texto en la etiqueta
                        # deberemos mover el fichero a la carpeta T0000
                        ttp_counter = 0
                        for tag in range(len(tags)):
                            # Matcheamos el item de la lista tags con nuestra lista de ttps 
                            ttp = find_techniques_in_list(tags[tag],techniques_enterprise)
                            # Y si es un string lo que tenemos, entonces guardamos en la carpeta de la la ttp correspondiente
                            # Ojo,¿que pasa si la lista tiene un string pero no una ttp?
                            if isinstance(ttp, str):
                                ttp_counter += 1
                                copy_file_to_path(item, save_path_sigma_hq1, ttp)
                        if ttp_counter == 0:
                            raise NotTTPatTags('.yaml sin TTP encontrada en los tags')
                
                    else:
                        # En el caso de que la etiquete exista pero su contenido sea vacio (NoneType), accedemos a la etiqueta 'description' para buscar las TTP´s
                        has_label_without_content_tags.append(item)
                        if 'description' in document:
                            description = [document.get('description', [])]
                            # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                            for tag in range(len(description)):
                                ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                                if not isinstance(ttp, type(None)):
                                    if not os.path.exists(os.path.join(save_path_sigma_hq1, ttp)):
                                        os.makedirs(os.path.join(save_path_sigma_hq1, ttp))
                                else:
                                    ttp='T0000'
                                copy_file_to_path(item, save_path_sigma_hq1, ttp)
                else:
                    no_label_tags.append(item)
                    # Repetimos la busqueda de TTP en la etiqueta description en los casos en los que 'tags' no exista.
                    if 'description' in document:
                        description = [document.get('description', [])]
                        # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                        for tag in range(len(description)):
                            ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                            if not isinstance(ttp, type(None)):
                                if not os.path.exists(os.path.join(save_path_sigma_hq1, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq1, ttp))
                            else:
                                ttp='T0000'
                            copy_file_to_path(item, save_path_sigma_hq1, ttp)
                    else:
                        copy_file_to_path(item, save_path_sigma_hq1, 'T0000')
            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except yaml.YAMLError as e:
                print(f"Error al cargar el archivo YAML: {e}")
                error_load.append(item)
                copy_file_to_path(item, save_path_sigma_hq1, 'T0000')
            
            # Con esta excepción llegamos si hemos recorrido la lista de tags y no hemos encontrado ninguna TTP, por lo que revisamos la etiqueta dando lugar a 3 casuísticas,
            # la primera que encuentre dicha etiqueta, en cuyo caso se revisa el contenido, si dentro de este se encuentra alguna TTP se mandara a la carpeta correspondiente. En caso de no haber coincidencia, al igual que ocurrirá si no hay etiqueta 'description' el fichero será copiado a T000.
            except NotTTPatTags as e:
                print(f"{e}")
                notTTPinTags.append(item)
                if 'description' in document:
                    description = [document.get('description', [])]
                    # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                    for tag in range(len(description)):
                        ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                        if not isinstance(ttp, type(None)):
                            notTTPinTags_with_TTP_in_description.append(item)
                            pass
                        else:
                            ttp='T0000'
                        copy_file_to_path(item, save_path_sigma_hq1, ttp)
                else:
                    notTTPinTags_without_description.append(item)
                    copy_file_to_path(item, save_path_sigma_hq1, 'T0000')

Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1498
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T1609
Copiado correctamente a la carpeta de la TTP: T1611
Copiado correctamente a la carpeta de la TTP: T1036.005
Copiado correctamente a la carpeta de la TTP: T1611
Copiado correctamente a la carpeta de la TTP: T1069.003
Copiado correctamente a la carpeta de la TTP: T1087.004
Copiado correctamente a la carpeta de la TTP: T1552.007
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1609
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1498
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1123
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1005
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1041
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T1053.002
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1033
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T1053.002
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T1112
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1569.002
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T1053.002
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1033
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1203
Copiado correctamente a la carpeta de la TTP: T1219
Copiado correctamente a la carpeta de la TTP: T1204
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.002
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1588
Copiado correctamente a la carpeta de la TTP: T1505.003
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1505.001
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1021.007
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1565
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1059.003
Copiado correctamente a la carpeta de la TTP: T1059.004
Copiado correctamente a la carpeta de la TTP: T1005
Copiado correctamente a la carpeta de la TTP: T1537
Copiado correctamente a la carpeta de la TTP: T1525
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1136.003
Copiado correctamente a la carpeta de la TTP: T1531
Copiado correctamente a la carpeta de la TTP: T1580
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1059.009
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1059.009
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1059.009
Copiado correctamente a la carpeta de la TTP: T1078.004
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1020
Copiado correctamente a la carpeta de la TTP: T1020
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1537
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1537
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1550
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1550
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1550
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1578
Copiado correctamente a la carpeta de la TTP: T1578.003
Copiado correctamente a la carpeta de la TTP: T1098.003
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1489
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1565.001
Copiado correctamente a la carpeta de la TTP: T1565.001
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1098.003
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.007
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053.003
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1562.001
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1531
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1562.007
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1059
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078.004
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1484
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1098.001
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1098.003
Copiado correctamente a la carpeta de la TTP: T1098.003
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1589
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1606
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1087.004
Copiado correctamente a la carpeta de la TTP: T1526
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1556.006
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1621
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1621
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1213.003
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1586
Copiado correctamente a la carpeta de la TTP: T1213.003
Copiado correctamente a la carpeta de la TTP: T1586
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1082
Copiado correctamente a la carpeta de la TTP: T1591.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1082
Copiado correctamente a la carpeta de la TTP: T1591.004
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1548
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1565
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1074
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.007
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1531
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098.003
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1213.003
Copiado correctamente a la carpeta de la TTP: T1195.001
Copiado correctamente a la carpeta de la TTP: T1556

In [30]:
print('Reglas totales para asignar: '+str(len(num_yamls)))
rules_unique = get_unique_items(num_yamls)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 3320
Reglas únicas para asignar: 3320

In [26]:
print('Tienen informada la etiqueta "tags": '+str(len(has_label_tags)))
print('Tienen información en la etiqueta "tags": '+str(len(has_label_with_content_tags)))
print('NO tienen información en la etiqueta "tags": '+str(len(has_label_without_content_tags)))

Tienen informada la etiqueta "tags": 3318
Tienen información en la etiqueta "tags": 3318
NO tienen información en la etiqueta "tags": 0

In [27]:
print('NO tienen la etiqueta "tags": '+str(len(no_label_tags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags": '+str(len(notTTPinTags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": '+str(len(notTTPinTags_without_description)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": '+str(len(notTTPinTags_with_TTP_in_description)))

NO tienen la etiqueta "tags": 2
NO se ha encontrado TTP alguna en la etiqueta "tags": 448
NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": 0
NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": 1

In [28]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_sigma_hq1))))
print('Reglas sin TTP asignada (T0000): '+str(len(getListOfFilesSub(os.path.join(save_path_sigma_hq1, 'T0000')))))
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_sigma_hq1)) - len(getListOfFilesSub(os.path.join(save_path_sigma_hq1, 'T0000')))))
print('Reglas asignadas a 2 o más TTPs: '+str((len(getListOfFilesSub(save_path_sigma_hq1)) - len(getListOfFilesSub(os.path.join(save_path_sigma_hq1, 'T0000'))))-len(rules_unique)))

Número de TTPs únicas identificadas (puede incluir T0000): 376
Reglas sin TTP asignada (T0000): 449
Reglas asignadas a TTP: 3808
Reglas asignadas a 2 o más TTPs: 488

#### TTP's Sigma HQ 2

<h5 style="background-color: #E11717; color: black;">
    Importante: No ejecutar por solicitud de Seguridad
</h5>

In [17]:
# zip_sigma_hq2 = 'https://github.com/mdecrevoisier/SIGMA-detection-rules/archive/refs/heads/main.zip'
save_path_sigma_hq2 = os.path.join(save_path, 'sigmaHQ2')
unzip_folder = r'\SIGMA-detection-rules-main'
techniques_enterprise[:3]

['T1059.010', 'T1564.012', 'T1027.013']

In [18]:
create_output_folder(save_path_sigma_hq2)

In [19]:
download_unzip(zip_sigma_hq2, temp_path)

In [20]:
files = getListOfFilesSub(temp_path+unzip_folder)
files[:3]

['C:\\Users\\jelopez\\Downloads\\SIGMA-detection-rules-main\\.gitignore',
 'C:\\Users\\jelopez\\Downloads\\SIGMA-detection-rules-main\\cloud-azure\\azure-active-directory-new federated trust added.yaml',
 'C:\\Users\\jelopez\\Downloads\\SIGMA-detection-rules-main\\cloud-azure\\azure-exchange-email forwarding to external domain.yaml']

In [21]:
# Recorrer la lista de archivos
num_yamls = []
has_label_tags = []
has_label_with_content_tags = []
has_label_without_content_tags = []
no_label_tags = []
notTTPinTags = []
notTTPinTags_with_TTP_in_description = []
notTTPinTags_without_description = []
error_load = []

for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yaml' or extension == '.yml':
        with open(item) as file:
            num_yamls.append(item)
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y copiamos el fichero a la carpeta T0000
                document = yaml.full_load(file)
                if 'tags' in document:
                    # Si encontramos la etiqueta 'tags' en el yaml lo guardamos como una variable 
                    tags = document.get('tags', [])
                    has_label_tags.append(item)
                    # Si el resultado de esa variable no está vacío y contiene información lo convertimos en una lista
                    if not isinstance(tags, type(None)):
                        has_label_with_content_tags.append(item)
                        # Convertimos en lista el contenido de la etiqueta
                        #tags = [tags]
                        tags = [tag.upper() for tag in tags if isinstance(tag, str)]
                        # Recorremos la lista de items contenidos en tags y contamos las ttp encontradas ya que si no encontramos ninguna, pese haber texto en la etiqueta
                        # deberemos mover el fichero a la carpeta T0000
                        ttp_counter = 0
                        for tag in range(len(tags)):
                            # Matcheamos el item de la lista tags con nuestra lista de ttps 
                            ttp = find_techniques_in_list(tags[tag],techniques_enterprise)
                            # Y si es un string lo que tenemos, entonces guardamos en la carpeta de la la ttp correspondiente
                            # Ojo,¿que pasa si la lista tiene un string pero no una ttp?
                            if isinstance(ttp, str):
                                ttp_counter += 1
                                copy_file_to_path(item, save_path_sigma_hq2, ttp)
                        if ttp_counter == 0:
                            raise NotTTPatTags('.yaml sin TTP encontrada en los tags')
                
                    else:
                        # En el caso de que la etiquete exista pero su contenido sea vacio (NoneType), accedemos a la etiqueta 'description' para buscar las TTP´s
                        has_label_without_content_tags.append(item)
                        if 'description' in document:
                            description = [document.get('description', [])]
                            # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                            for tag in range(len(description)):
                                ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                                if not isinstance(ttp, type(None)):
                                    if not os.path.exists(os.path.join(save_path_sigma_hq2, ttp)):
                                        os.makedirs(os.path.join(save_path_sigma_hq2, ttp))
                                else:
                                    ttp='T0000'
                                copy_file_to_path(item, save_path_sigma_hq2, ttp)
                else:
                    no_label_tags.append(item)
                    # Repetimos la busqueda de TTP en la etiqueta description en los casos en los que 'tags' no exista.
                    if 'description' in document:
                        description = [document.get('description', [])]
                        # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                        for tag in range(len(description)):
                            ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                            if not isinstance(ttp, type(None)):
                                if not os.path.exists(os.path.join(save_path_sigma_hq2, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq2, ttp))
                            else:
                                ttp='T0000'
                            copy_file_to_path(item, save_path_sigma_hq2, ttp)
                    else:
                        copy_file_to_path(item, save_path_sigma_hq2, 'T0000')
            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except yaml.YAMLError as e:
                print(f"Error al cargar el archivo YAML: {e}")
                error_load.append(item)
                copy_file_to_path(item, save_path_sigma_hq2, 'T0000')
            
            # Con esta excepción llegamos si hemos recorrido la lista de tags y no hemos encontrado ninguna TTP, por lo que revisamos la etiqueta dando lugar a 3 casuísticas,
            # la primera que encuentre dicha etiqueta, en cuyo caso se revisa el contenido, si dentro de este se encuentra alguna TTP se mandara a la carpeta correspondiente. En caso de no haber coincidencia, al igual que ocurrirá si no hay etiqueta 'description' el fichero será copiado a T000.
            except NotTTPatTags as e:
                print(f"{e}")
                notTTPinTags.append(item)
                if 'description' in document:
                    description = [document.get('description', [])]
                    # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                    for tag in range(len(description)):
                        ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                        if not isinstance(ttp, type(None)):
                            notTTPinTags_with_TTP_in_description.append(item)
                            pass
                        else:
                            ttp='T0000'
                        copy_file_to_path(item, save_path_sigma_hq2, ttp)
                else:
                    notTTPinTags_without_description.append(item)
                    copy_file_to_path(item, save_path_sigma_hq2, 'T0000')

Copiado correctamente a la carpeta de la TTP: T1484.002
Copiado correctamente a la carpeta de la TTP: T1114.003
Copiado correctamente a la carpeta de la TTP: T1114
Copiado correctamente a la carpeta de la TTP: T1566
Copiado correctamente a la carpeta de la TTP: T1114
Copiado correctamente a la carpeta de la TTP: T1566
Copiado correctamente a la carpeta de la TTP: T1562.006
Copiado correctamente a la carpeta de la TTP: T1546
Copiado correctamente a la carpeta de la TTP: T1110.001
Copiado correctamente a la carpeta de la TTP: T1110.003
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1222.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1555.004
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1564
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1484.001
Copiado correctamente a la carpeta de la TTP: T1484.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1003.003
Copiado correctamente a la carpeta de la TTP: T1003.003
Copiado correctamente a la carpeta de la TTP: T1558.003
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1558.004
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1558.001
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1558.001
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1087.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1558.001
Copiado correctamente a la carpeta de la TTP: T1003.006
Copiado correctamente a la carpeta de la TTP: T1201
Copiado correctamente a la carpeta de la TTP: T1210
Copiado correctamente a la carpeta de la TTP: T1482
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1003.006
Copiado correctamente a la carpeta de la TTP: T1222.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1207
Copiado correctamente a la carpeta de la TTP: T1558.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1558.003
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078.002
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1555
Copiado correctamente a la carpeta de la TTP: T1059.003
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1570
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1197
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1570
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1197
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1570
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1197
Copiado correctamente a la carpeta de la TTP: T1555.003
Copiado correctamente a la carpeta de la TTP: T1204
Copiado correctamente a la carpeta de la TTP: T1204
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1222.001
Copiado correctamente a la carpeta de la TTP: T1003.006
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1557.001
Copiado correctamente a la carpeta de la TTP: T1505.002
Copiado correctamente a la carpeta de la TTP: T1505.002
Copiado correctamente a la carpeta de la TTP: T1505.002
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1547.009
Copiado correctamente a la carpeta de la TTP: T1547.009
Copiado correctamente a la carpeta de la TTP: T1547.009
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1562.002
Copiado correctamente a la carpeta de la TTP: T1562.002
Copiado correctamente a la carpeta de la TTP: T1082
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1553.004
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1546.003
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1071.004
Copiado correctamente a la carpeta de la TTP: T1071.004
Copiado correctamente a la carpeta de la TTP: T1555.004
Error al cargar el archivo YAML: while scanning for the next token
found character '\t' that cannot start any token
  in "C:\Users\jelopez\Downloads\SIGMA-detection-rules-main\windows-os\win-os-dump file transfered over SMB share.yaml", line 20, column 3
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1562.002
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1041
Copiado correctamente a la carpeta de la TTP: T1555.004
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1018
Copiado correctamente a la carpeta de la TTP: T1565
Copiado correctamente a la carpeta de la TTP: T1003.002
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1134.001
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1564.006
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1135
Copiado correctamente a la carpeta de la TTP: T1546.007
Copiado correctamente a la carpeta de la TTP: T1546.007
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1134
Copiado correctamente a la carpeta de la TTP: T1562.010
Copiado correctamente a la carpeta de la TTP: T1550.002
Copiado correctamente a la carpeta de la TTP: T1201
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1059.003
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1557.001
Copiado correctamente a la carpeta de la TTP: T1547.010
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1134.002
Copiado correctamente a la carpeta de la TTP: T1134.002
Copiado correctamente a la carpeta de la TTP: T1569.002
Copiado correctamente a la carpeta de la TTP: T1489
Copiado correctamente a la carpeta de la TTP: T1569.002
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1112
Copiado correctamente a la carpeta de la TTP: T1003.002
Copiado correctamente a la carpeta de la TTP: T1003.004
Copiado correctamente a la carpeta de la TTP: T1003.005
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1547.008
Copiado correctamente a la carpeta de la TTP: T1547.008
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1135
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1222.001
Copiado correctamente a la carpeta de la TTP: T1021.002
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1553.003
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1562.010
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1040
Copiado correctamente a la carpeta de la TTP: T1040
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1547.010
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1547.010
Copiado correctamente a la carpeta de la TTP: T1070.006
Copiado correctamente a la carpeta de la TTP: T1070.006
Copiado correctamente a la carpeta de la TTP: T1555
Copiado correctamente a la carpeta de la TTP: T1136.001
Copiado correctamente a la carpeta de la TTP: T1136.002
Copiado correctamente a la carpeta de la TTP: T1136.001
Copiado correctamente a la carpeta de la TTP: T1087.001
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1555
Copiado correctamente a la carpeta de la TTP: T1555.004
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1546.003
Copiado correctamente a la carpeta de la TTP: T1546.003
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1222
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1563.002
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1563.002
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1113
Copiado correctamente a la carpeta de la TTP: T1125
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1113
Copiado correctamente a la carpeta de la TTP: T1125
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1113
Copiado correctamente a la carpeta de la TTP: T1125
Copiado correctamente a la carpeta de la TTP: T1572
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1572
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1572
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1053.005
Copiado correctamente a la carpeta de la TTP: T1053.005
Copiado correctamente a la carpeta de la TTP: T1053.005
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1053.005
Copiado correctamente a la carpeta de la TTP: T1053.005

In [47]:
print('Reglas totales para asignar: '+str(len(yamls)))
rules_unique = get_unique_items(yamls)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 348
Reglas únicas para asignar: 348

In [48]:
print('Tienen informada la etiqueta "tags": '+str(len(has_label_tags)))
print('Tienen información en la etiqueta "tags": '+str(len(has_label_with_content_tags)))
print('NO tienen información en la etiqueta "tags": '+str(len(has_label_without_content_tags)))

Tienen informada la etiqueta "tags": 347
Tienen información en la etiqueta "tags": 347
NO tienen información en la etiqueta "tags": 0

In [52]:
print('NO tienen la etiqueta "tags": '+str(len(no_label_tags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags": '+str(len(notTTPinTags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": '+str(len(notTTPinTags_without_description)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": '+str(len(notTTPinTags_with_TTP_in_description)))

NO tienen la etiqueta "tags": 0
NO se ha encontrado TTP alguna en la etiqueta "tags": 4
NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": 0
NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": 0

In [84]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_sigma_hq2))))
print('Reglas sin TTP asignada (T0000): '+str(len(getListOfFilesSub(os.path.join(save_path_sigma_hq2, 'T0000')))))
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_sigma_hq2)) - len(getListOfFilesSub(os.path.join(save_path_sigma_hq2, 'T0000')))))
print('Reglas asignadas a 2 o más TTPs: '+str((len(getListOfFilesSub(save_path_sigma_hq2)) - len(getListOfFilesSub(os.path.join(save_path_sigma_hq2, 'T0000'))))-len(rules_unique)))

Número de TTPs únicas identificadas (puede incluir T0000): 111
Reglas sin TTP asignada (T0000): 5
Reglas asignadas a TTP: 410
Reglas asignadas a 2 o más TTPs: 62

#### TTP's Sigma HQ 3

In [11]:
zip_sigma_hq3 = 'https://github.com/joesecurity/sigma-rules/archive/refs/heads/master.zip'
save_path_sigma_hq3 = os.path.join(save_path, 'sigmaHQ3')
techniques_enterprise = techniques()
techniques_enterprise = sorted(techniques_enterprise, key=len, reverse=True)

[taxii2client.v20] [WARNING ] [2024-05-23 11:38:42,264] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2024-05-23 11:38:42,296] TAXII Server Response with different amount of objects! Setting per_request=780

In [568]:
create_output_folder(save_path_sigma_hq3)

In [569]:
download_unzip(zip_sigma_hq3, temp_path)

In [12]:
files = getListOfFilesSub(temp_path+r'\sigma-rules-master')
files[0:3]

['C:\\Users\\jelopez\\Downloads\\sigma-rules-master\\images\\sigma.png',
 'C:\\Users\\jelopez\\Downloads\\sigma-rules-master\\LICENSE',
 'C:\\Users\\jelopez\\Downloads\\sigma-rules-master\\README.md']

In [41]:
# Recorrer la lista de archivos
num_yamls = []
has_label_mitreattack = []
has_label_with_content_mitreattack = []
has_label_without_content_mitreattack = []
no_label_mitreattack = []
error_load = []

for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yaml' or extension == '.yml':
        with open(item) as file:
            TTP_list = [] #?
            num_yamls.append(item)
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y copiamos el fichero a la carpeta T0000
                document = yaml.full_load(file)
                if 'mitreattack' in document:
                    # Si encontramos el tag 'mitreattack' en el yaml lo guardamos como una variable 
                    mitreattacks = document.get('mitreattack', [])
                    has_label_mitreattack.append(item)
                    # Si el resultado de esa variable no está vacío y contiene información lo convertimos en una lista
                    if not isinstance(mitreattacks, type(None)):
                        has_label_with_content_mitreattack.append(item)
                        # Convertimos en lista el contenido de la etiqueta
                        mitreattacks = [mitreattacks]
                        if isinstance(mitreattacks, list):
                            # Chequeamos que se haya podido generar correctamente la lista y la vamos recorriendo añadiendo las ttps encontradas en el listado de Mitre
                            # Guardamos el fichero en la carpeta correspondiente.
                            for tag in range(len(mitreattacks)):
                                ttp = find_techniques_in_list(mitreattacks[tag],techniques_enterprise)
                                if not os.path.exists(os.path.join(save_path_sigma_hq3, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq3, ttp))
                                shutil.copy(item,os.path.join(save_path_sigma_hq3, ttp))
                                print('Copiado correctamente a la carpeta de la TTP: '+ ttp)   
                    else:
                        # En el caso de que la etiquete exista pero su contenido sea vacio (NoneType), accedemos a la etiqueta 'description' para buscar las TTP´s
                        has_label_without_content_mitreattack.append(item)
                        if 'description' in document:
                            description = [document.get('description', [])]
                            # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                            for tag in range(len(description)):
                                ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                                if not isinstance(ttp, type(None)):
                                    if not os.path.exists(os.path.join(save_path_sigma_hq3, ttp)):
                                        os.makedirs(os.path.join(save_path_sigma_hq3, ttp))
                                else:
                                    ttp='T0000'
                                if not os.path.exists(os.path.join(save_path_sigma_hq3, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq3, 'T0000'))
                                shutil.copy(item,os.path.join(save_path_sigma_hq3, ttp))
                                print('Copiado correctamente a la carpeta de la TTP: '+ ttp)
                else:
                    no_label_mitreattack.append(item)
                    # Repetimos la busqueda de TTP en la etiqueta description en los casos en los que 'mitreattack' no exista
                    if 'description' in document:
                        description = [document.get('description', [])]
                        # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                        for tag in range(len(description)):
                            ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                            if not isinstance(ttp, type(None)):
                                if not os.path.exists(os.path.join(save_path_sigma_hq3, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq3, ttp))
                            else:
                                ttp='T0000'
                            if not os.path.exists(os.path.join(save_path_sigma_hq3, ttp)):
                                os.makedirs(os.path.join(save_path_sigma_hq3, 'T0000'))
                            shutil.copy(item,os.path.join(save_path_sigma_hq3, ttp))
                            print('Copiado correctamente a la carpeta de la TTP: '+ ttp)
            except yaml.YAMLError as e:
                print(f"Error al cargar el archivo YAML: {e}")
                error_load.append(item)
                if not os.path.exists(os.path.join(save_path_sigma_hq3, 'T0000')):
                    os.makedirs(os.path.join(save_path_sigma_hq3, 'T0000'))
                shutil.copy(item,os.path.join(save_path_sigma_hq3, 'T0000'))
                print('Copiado correctamente correctamente a la carpeta T0000')

Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1497
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1218.010
Copiado correctamente a la carpeta de la TTP: T1218.010
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1497
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: found undefined alias 'chcp'
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\koadicpostexploitationrootkit.yml", line 18, column 15
Copiado correctamente correctamente a la carpeta T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1127
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: while scanning an alias
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\powershelldownloadingfilefromurlshortenersite.yml", line 33, column 16
expected alphabetic or numeric character, but found '*'
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\powershelldownloadingfilefromurlshortenersite.yml", line 33, column 27
Copiado correctamente correctamente a la carpeta T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Error al cargar el archivo YAML: while scanning an alias
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\powershelllaunchregsvr32.yml", line 18, column 15
expected alphabetic or numeric character, but found '*'
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\powershelllaunchregsvr32.yml", line 18, column 26
Copiado correctamente correctamente a la carpeta T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: found undefined alias 'powershell'
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\powershellsleepandlaunchexecutable.yml", line 18, column 15
Copiado correctamente correctamente a la carpeta T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: while scanning an alias
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\registerdllwithspoofedextension.yml", line 20, column 16
expected alphabetic or numeric character, but found '*'
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\registerdllwithspoofedextension.yml", line 20, column 25
Copiado correctamente correctamente a la carpeta T0000
Copiado correctamente a la carpeta de la TTP: T1547.001
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: while scanning an alias
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\shedulehiddenpowershellscript.yml", line 18, column 15
expected alphabetic or numeric character, but found '.'
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\shedulehiddenpowershellscript.yml", line 18, column 24
Copiado correctamente correctamente a la carpeta T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1218
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: found undefined alias 'cmd'
  in "C:\Users\jelopez\Downloads\sigma-rules-master\rules\wscriptdownloadfileintotemplocationfromwordpresssite.yml", line 18, column 15
Copiado correctamente correctamente a la carpeta T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000

In [32]:
type(mitreattacks[0])

NoneType

In [24]:
num_yamls = []
has_label_mitreattack = []
has_label_with_content_mitreattack = []
has_label_without_content_mitreattack = []
no_label_mitreattack = []
error_load = []

7

In [31]:
len(no_label_mitreattack)

14

In [42]:
len(getListOfFilesSub(save_path_sigma_hq3))

118

In [43]:
len(getListOfFilesSub(os.path.join(save_path_sigma_hq3, 'T0000')))

105

#### TTP's Sigma HQ 4

<h5 style="background-color: #E11717; color: black;">
    Importante: No ejecutar por solicitud de Seguridad
</h5>

In [32]:
# zip_sigma_hq4 = 'https://github.com/SigmaHQ/sigma/archive/refs/heads/master.zip'
save_path_sigma_hq4 = os.path.join(save_path, 'sigmaHQ4')
unzip_folder = r'sigma-master/rules/'

In [36]:
download_folder_unzip(zip_sigma_hq4, unzip_folder, temp_path)

Descarga y descompresión completadas correctamente.

In [37]:
files = getListOfFilesSub(os.path.join(temp_path, unzip_folder))
len(files)

2889

In [58]:
create_output_folder(save_path_sigma_hq4)

In [38]:
# Recorrer la lista de archivos
num_yamls = []
has_label_tags = []
has_label_with_content_tags = []
has_label_without_content_tags = []
no_label_tags = []
notTTPinTags = []
notTTPinTags_with_TTP_in_description = []
notTTPinTags_without_description = []
error_load = []

for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yaml' or extension == '.yml':
        with open(item) as file:
            num_yamls.append(item)
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y copiamos el fichero a la carpeta T0000
                document = yaml.full_load(file)
                if 'tags' in document:
                    # Si encontramos la etiqueta 'tags' en el yaml lo guardamos como una variable 
                    tags = document.get('tags', [])
                    has_label_tags.append(item)
                    # Si el resultado de esa variable no está vacío y contiene información lo convertimos en una lista
                    if not isinstance(tags, type(None)):
                        has_label_with_content_tags.append(item)
                        # Convertimos en lista el contenido de la etiqueta
                        #tags = [tags]
                        tags = [tag.upper() for tag in tags if isinstance(tag, str)]
                        # Recorremos la lista de items contenidos en tags y contamos las ttp encontradas ya que si no encontramos ninguna, pese haber texto en la etiqueta
                        # deberemos mover el fichero a la carpeta T0000
                        ttp_counter = 0
                        for tag in range(len(tags)):
                            # Matcheamos el item de la lista tags con nuestra lista de ttps 
                            ttp = find_techniques_in_list(tags[tag],techniques_enterprise)
                            # Y si es un string lo que tenemos, entonces guardamos en la carpeta de la la ttp correspondiente
                            # Ojo,¿que pasa si la lista tiene un string pero no una ttp?
                            if isinstance(ttp, str):
                                ttp_counter += 1
                                copy_file_to_path(item, save_path_sigma_hq4, ttp)
                        if ttp_counter == 0:
                            raise NotTTPatTags('.yaml sin TTP encontrada en los tags')
                
                    else:
                        # En el caso de que la etiquete exista pero su contenido sea vacio (NoneType), accedemos a la etiqueta 'description' para buscar las TTP´s
                        has_label_without_content_tags.append(item)
                        if 'description' in document:
                            description = [document.get('description', [])]
                            # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                            for tag in range(len(description)):
                                ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                                if not isinstance(ttp, type(None)):
                                    if not os.path.exists(os.path.join(save_path_sigma_hq4, ttp)):
                                        os.makedirs(os.path.join(save_path_sigma_hq4, ttp))
                                else:
                                    ttp='T0000'
                                copy_file_to_path(item, save_path_sigma_hq4, ttp)
                else:
                    no_label_tags.append(item)
                    # Repetimos la busqueda de TTP en la etiqueta description en los casos en los que 'tags' no exista.
                    if 'description' in document:
                        description = [document.get('description', [])]
                        # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                        for tag in range(len(description)):
                            ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                            if not isinstance(ttp, type(None)):
                                if not os.path.exists(os.path.join(save_path_sigma_hq4, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq4, ttp))
                            else:
                                ttp='T0000'
                            copy_file_to_path(item, save_path_sigma_hq4, ttp)
                    else:
                        copy_file_to_path(item, save_path_sigma_hq4, 'T0000')
            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except yaml.YAMLError as e:
                print(f"Error al cargar el archivo YAML: {e}")
                error_load.append(item)
                copy_file_to_path(item, save_path_sigma_hq4, 'T0000')
            
            # Con esta excepción llegamos si hemos recorrido la lista de tags y no hemos encontrado ninguna TTP, por lo que revisamos la etiqueta dando lugar a 3 casuísticas,
            # la primera que encuentre dicha etiqueta, en cuyo caso se revisa el contenido, si dentro de este se encuentra alguna TTP se mandara a la carpeta correspondiente. En caso de no haber coincidencia, al igual que ocurrirá si no hay etiqueta 'description' el fichero será copiado a T000.
            except NotTTPatTags as e:
                print(f"{e}")
                notTTPinTags.append(item)
                if 'description' in document:
                    description = [document.get('description', [])]
                    # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                    for tag in range(len(description)):
                        ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                        if not isinstance(ttp, type(None)):
                            notTTPinTags_with_TTP_in_description.append(item)
                            pass
                        else:
                            ttp='T0000'
                        copy_file_to_path(item, save_path_sigma_hq4, ttp)
                else:
                    notTTPinTags_without_description.append(item)
                    copy_file_to_path(item, save_path_sigma_hq4, 'T0000')

Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1498
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T1609
Copiado correctamente a la carpeta de la TTP: T1611
Copiado correctamente a la carpeta de la TTP: T1036.005
Copiado correctamente a la carpeta de la TTP: T1611
Copiado correctamente a la carpeta de la TTP: T1069.003
Copiado correctamente a la carpeta de la TTP: T1087.004
Copiado correctamente a la carpeta de la TTP: T1552.007
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1609
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1498
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1123
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1005
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1133
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1041
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T1053.002
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1033
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T1053.002
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T1112
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1569.002
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T1053.002
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1033
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1203
Copiado correctamente a la carpeta de la TTP: T1219
Copiado correctamente a la carpeta de la TTP: T1204
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.002
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1588
Copiado correctamente a la carpeta de la TTP: T1505.003
Copiado correctamente a la carpeta de la TTP: T1190
Copiado correctamente a la carpeta de la TTP: T1505.001
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1021.007
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1565
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1059.003
Copiado correctamente a la carpeta de la TTP: T1059.004
Copiado correctamente a la carpeta de la TTP: T1005
Copiado correctamente a la carpeta de la TTP: T1537
Copiado correctamente a la carpeta de la TTP: T1525
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1136.003
Copiado correctamente a la carpeta de la TTP: T1531
Copiado correctamente a la carpeta de la TTP: T1580
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1059.009
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1059.009
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1059.009
Copiado correctamente a la carpeta de la TTP: T1078.004
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1020
Copiado correctamente a la carpeta de la TTP: T1020
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1537
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1537
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1550
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1550
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1550
Copiado correctamente a la carpeta de la TTP: T1550.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1578
Copiado correctamente a la carpeta de la TTP: T1578.003
Copiado correctamente a la carpeta de la TTP: T1098.003
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1489
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1485
Copiado correctamente a la carpeta de la TTP: T1565.001
Copiado correctamente a la carpeta de la TTP: T1565.001
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1098.003
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.001
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.007
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053.003
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1562.001
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1531
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1562.007
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1059
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078.004
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1484
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1098.001
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1098.003
Copiado correctamente a la carpeta de la TTP: T1098.003
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1548
Copiado correctamente a la carpeta de la TTP: T1556
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1589
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1528
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1606
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1087.004
Copiado correctamente a la carpeta de la TTP: T1526
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1556.006
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1621
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1621
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1213.003
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1586
Copiado correctamente a la carpeta de la TTP: T1213.003
Copiado correctamente a la carpeta de la TTP: T1586
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1082
Copiado correctamente a la carpeta de la TTP: T1591.004
Copiado correctamente a la carpeta de la TTP: T1078.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1213
Copiado correctamente a la carpeta de la TTP: T1082
Copiado correctamente a la carpeta de la TTP: T1591.004
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1548
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1565
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1074
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1552
Copiado correctamente a la carpeta de la TTP: T1552.007
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1531
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098.003
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1213.003
Copiado correctamente a la carpeta de la TTP: T1195.001
Copiado correctamente a la carpeta de la TTP: T1556

In [39]:
print('Reglas totales para asignar: '+str(len(num_yamls)))
rules_unique = get_unique_items(num_yamls)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 2888
Reglas únicas para asignar: 2888

In [40]:
print('Tienen informada la etiqueta "tags": '+str(len(has_label_tags)))
print('Tienen información en la etiqueta "tags": '+str(len(has_label_with_content_tags)))
print('NO tienen información en la etiqueta "tags": '+str(len(has_label_without_content_tags)))

Tienen informada la etiqueta "tags": 2887
Tienen información en la etiqueta "tags": 2887
NO tienen información en la etiqueta "tags": 0

In [41]:
print('NO tienen la etiqueta "tags": '+str(len(no_label_tags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags": '+str(len(notTTPinTags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": '+str(len(notTTPinTags_without_description)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": '+str(len(notTTPinTags_with_TTP_in_description)))

NO tienen la etiqueta "tags": 1
NO se ha encontrado TTP alguna en la etiqueta "tags": 338
NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": 0
NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": 1

In [42]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_sigma_hq4))))
print('Reglas sin TTP asignada (T0000): '+str(len(getListOfFilesSub(os.path.join(save_path_sigma_hq4, 'T0000')))))
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_sigma_hq4)) - len(getListOfFilesSub(os.path.join(save_path_sigma_hq4, 'T0000')))))
print('Reglas asignadas a 2 o más TTPs: '+str((len(getListOfFilesSub(save_path_sigma_hq4)) - len(getListOfFilesSub(os.path.join(save_path_sigma_hq4, 'T0000'))))-len(rules_unique)))

Número de TTPs únicas identificadas (puede incluir T0000): 372
Reglas sin TTP asignada (T0000): 338
Reglas asignadas a TTP: 3377
Reglas asignadas a 2 o más TTPs: 489

#### TTP's Sigma HQ 5

In [46]:
zip_sigma_hq5 = 'https://github.com/socprime/socprime_sigma/archive/refs/heads/master.zip'
save_path_sigma_hq5 = os.path.join(save_path, 'sigmaHQ5')
unzip_folder = r'socprime_sigma-master'

In [44]:
download_unzip(zip_sigma_hq5, temp_path)

In [47]:
files = getListOfFilesSub(os.path.join(temp_path, unzip_folder))
len(files)

37

In [48]:
create_output_folder(save_path_sigma_hq5)

In [59]:
num_yamls = []
has_label_tags = []
has_label_with_content_tags = []
has_label_without_content_tags = []
no_label_tags = []
notTTPinTags = []
notTTPinTags_with_TTP_in_description = []
notTTPinTags_without_description = []
error_load = []

ttps_in_tags_not_in_techniques_enterprise = []
ttps_in_tags_not_in_techniques_enterprise_items = []

for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yaml' or extension == '.yml':
        with open(item) as file:
            num_yamls.append(item)
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y copiamos el fichero a la carpeta T0000
                document = yaml.full_load(file)
                if 'tags' in document:
                    # Si encontramos la etiqueta 'tags' en el yaml lo guardamos como una variable 
                    tags = document.get('tags', [])
                    has_label_tags.append(item)
                    # Si el resultado de esa variable no está vacío y contiene información lo convertimos en una lista
                    if not isinstance(tags, type(None)):
                        has_label_with_content_tags.append(item)
                        # Convertimos en lista el contenido de la etiqueta
                        #tags = [tags]
                        tags = [tag.upper() for tag in tags if isinstance(tag, str)]
                        # Recorremos la lista de items contenidos en tags y contamos las ttp encontradas ya que si no encontramos ninguna, pese haber texto en la etiqueta
                        # deberemos mover el fichero a la carpeta T0000
                        ttp_counter = 0
                        for tag in range(len(tags)):
                            # Matcheamos el item de la lista tags con nuestra lista de ttps 
                            ttp = find_techniques_in_list(tags[tag],techniques_enterprise)
                            # He encontrado en sigma HQ 5 tags que contienen técnicas que no están en el listado de techniques_enterprise, vamos a almacenarlas para reportarlas.
                            if '.T0' in tags[tag] or '.T1' in tags[tag]:
                                ttps_in_tags_not_in_techniques_enterprise.append(tags[tag])
                                ttps_in_tags_not_in_techniques_enterprise_items.append(item)
                            # Y si es un string lo que tenemos, entonces guardamos en la carpeta de la la ttp correspondiente
                            if isinstance(ttp, str):
                                ttp_counter += 1
                                copy_file_to_path(item, save_path_sigma_hq5, ttp)
                        if ttp_counter == 0:
                            raise NotTTPatTags('.yaml sin TTP encontrada en los tags')
                
                    else:
                        # En el caso de que la etiquete exista pero su contenido sea vacio (NoneType), accedemos a la etiqueta 'description' para buscar las TTP´s
                        has_label_without_content_tags.append(item)
                        if 'description' in document:
                            description = [document.get('description', [])]
                            # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                            for tag in range(len(description)):
                                ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                                if not isinstance(ttp, type(None)):
                                    if not os.path.exists(os.path.join(save_path_sigma_hq5, ttp)):
                                        os.makedirs(os.path.join(save_path_sigma_hq5, ttp))
                                else:
                                    ttp='T0000'
                                copy_file_to_path(item, save_path_sigma_hq5, ttp)
                else:
                    no_label_tags.append(item)
                    # Repetimos la busqueda de TTP en la etiqueta description en los casos en los que 'tags' no exista.
                    if 'description' in document:
                        description = [document.get('description', [])]
                        # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                        for tag in range(len(description)):
                            ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                            if not isinstance(ttp, type(None)):
                                if not os.path.exists(os.path.join(save_path_sigma_hq5, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq5, ttp))
                            else:
                                ttp='T0000'
                            copy_file_to_path(item, save_path_sigma_hq5, ttp)
                    else:
                        copy_file_to_path(item, save_path_sigma_hq5, 'T0000')
            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except yaml.YAMLError as e:
                print(f"Error al cargar el archivo YAML: {e}")
                error_load.append(item)
                copy_file_to_path(item, save_path_sigma_hq5, 'T0000')
            
            # Con esta excepción llegamos si hemos recorrido la lista de tags y no hemos encontrado ninguna TTP, por lo que revisamos la etiqueta dando lugar a 3 casuísticas,
            # la primera que encuentre dicha etiqueta, en cuyo caso se revisa el contenido, si dentro de este se encuentra alguna TTP se mandara a la carpeta correspondiente. En caso de no haber coincidencia, al igual que ocurrirá si no hay etiqueta 'description' el fichero será copiado a T000.
            except NotTTPatTags as e:
                print(f"{e}")
                notTTPinTags.append(item)
                if 'description' in document:
                    description = [document.get('description', [])]
                    # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                    for tag in range(len(description)):
                        ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                        if not isinstance(ttp, type(None)):
                            notTTPinTags_with_TTP_in_description.append(item)
                            pass
                        else:
                            ttp='T0000'
                        copy_file_to_path(item, save_path_sigma_hq5, ttp)
                else:
                    notTTPinTags_without_description.append(item)
                    copy_file_to_path(item, save_path_sigma_hq5, 'T0000')

Error al cargar el archivo YAML: expected '<document start>', but found '<scalar>'
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Fancy_Bear\Rule\Fancy_Bear.yml", line 58, column 1
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: expected a single document in the stream
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\FlawedAmmyy\Rule\FlawedAmmyy_RAT.yml", line 1, column 1
but found another document
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\FlawedAmmyy\Rule\FlawedAmmyy_RAT.yml", line 21, column 1
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: while scanning for the next token
found character '\t' that cannot start any token
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\InvisiMole\Rule\InvisiMole.yml", line 35, column 1
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: while scanning for the next token
found character '\t' that cannot start any token
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\LokiBot_Trojan\Rule\LokiBot_Trojan_Detector.yml", line 15, column 1
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: expected a single document in the stream
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\PowerShell_Obfuscation\Rule\PowerShell_Obfuscation.yml", line 1, column 1
but found another document
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\PowerShell_Obfuscation\Rule\PowerShell_Obfuscation.yml", line 17, column 1
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: expected a single document in the stream
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Quasar\Rule\Quasar.yml", line 1, column 1
but found another document
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Quasar\Rule\Quasar.yml", line 29, column 1
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: expected a single document in the stream
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Rig-Exploit-for-CVE-2018-8174\Rule\Rig-Exploit-for-CVE-2018-8174.yml", line 1, column 1
but found another document
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Rig-Exploit-for-CVE-2018-8174\Rule\Rig-Exploit-for-CVE-2018-8174.yml", line 20, column 1
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: expected a single document in the stream
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Sobaken\Rule\Sobaken.yml", line 1, column 1
but found another document
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Sobaken\Rule\Sobaken.yml", line 57, column 1
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: expected a single document in the stream
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Vermin\Rule\Vermin.yml", line 1, column 1
but found another document
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\Vermin\Rule\Vermin.yml", line 59, column 1
Copiado correctamente a la carpeta de la TTP: T0000
Error al cargar el archivo YAML: expected a single document in the stream
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\VPNFilter_Malware\Rule\VPNFilter_Malware_Detector.yml", line 1, column 1
but found another document
  in "C:\Users\jelopez\Downloads\socprime_sigma-master\VPNFilter_Malware\Rule\VPNFilter_Malware_Detector.yml", line 29, column 1
Copiado correctamente a la carpeta de la TTP: T0000

In [69]:
ttps_in_tags_not_in_techniques_enterprise

['ATTACK.T1035', 'ATTACK.T1177']

In [63]:
print('Reglas totales para asignar: '+str(len(num_yamls)))
rules_unique = get_unique_items(num_yamls)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 12
Reglas únicas para asignar: 12

In [67]:
print('Reglas que retornan error de apertura: '+str(len(error_load)))

Reglas que retornan error de apertura: 10

In [64]:
print('Tienen informada la etiqueta "tags": '+str(len(has_label_tags)))
print('Tienen información en la etiqueta "tags": '+str(len(has_label_with_content_tags)))
print('NO tienen información en la etiqueta "tags": '+str(len(has_label_without_content_tags)))

Tienen informada la etiqueta "tags": 1
Tienen información en la etiqueta "tags": 1
NO tienen información en la etiqueta "tags": 0

In [65]:
print('NO tienen la etiqueta "tags": '+str(len(no_label_tags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags": '+str(len(notTTPinTags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": '+str(len(notTTPinTags_without_description)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": '+str(len(notTTPinTags_with_TTP_in_description)))

NO tienen la etiqueta "tags": 1
NO se ha encontrado TTP alguna en la etiqueta "tags": 1
NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": 0
NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": 0

In [66]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_sigma_hq5))))
print('Reglas sin TTP asignada (T0000): '+str(len(getListOfFilesSub(os.path.join(save_path_sigma_hq5, 'T0000')))))
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_sigma_hq5)) - len(getListOfFilesSub(os.path.join(save_path_sigma_hq5, 'T0000')))))
print('Reglas asignadas a 2 o más TTPs: '+str((len(getListOfFilesSub(save_path_sigma_hq5)) - len(getListOfFilesSub(os.path.join(save_path_sigma_hq5, 'T0000'))))-len(rules_unique)))

Número de TTPs únicas identificadas (puede incluir T0000): 1
Reglas sin TTP asignada (T0000): 12
Reglas asignadas a TTP: 0
Reglas asignadas a 2 o más TTPs: -12

#### TTP's Sigma HQ 6

**URL caída**

#### TTP's Sigma HQ 7

En este caso el repositorio almacena las reglas por técnica por lo que simplemente descargamos los ficheros y los movemos a la carpeta final

In [68]:
zip_sigma_hq7 = 'https://github.com/P4T12ICK/Sigma-Rule-Repository/archive/refs/heads/master.zip'
save_path_sigma_hq7 = os.path.join(save_path, 'sigmaHQ7')
unzip_folder = r'Sigma-Rule-Repository-master/detection-rules/'

In [69]:
download_folder_unzip(zip_sigma_hq7, unzip_folder, temp_path)

Descarga y descompresión completadas correctamente.

In [70]:
copy_files_between_paths(os.path.join(temp_path, unzip_folder),save_path_sigma_hq7)

#### TTP's Sigma HQ 8

In [43]:
zip_sigma_hq8 = 'https://github.com/blacklanternsecurity/sigma-rules/archive/refs/heads/main.zip'
save_path_sigma_hq8 = os.path.join(save_path, 'sigmaHQ8')
unzip_folder = r'sigma-rules-main/'

In [51]:
download_unzip(zip_sigma_hq8, temp_path)

In [44]:
os.path.join(temp_path, unzip_folder)

'C:\\Users\\jelopez\\Downloads\\sigma-rules-main/'

In [45]:
files = getListOfFilesSub(os.path.join(temp_path, unzip_folder))
len(files)

11

In [47]:
create_output_folder(save_path_sigma_hq8)

In [57]:
num_yamls = []
has_label_tags = []
has_label_with_content_tags = []
has_label_without_content_tags = []
no_label_tags = []
notTTPinTags = []
notTTPinTags_with_TTP_in_description = []
notTTPinTags_without_description = []
error_load = []
error_load_ttp_in_path_name = []

ttps_in_tags_not_in_techniques_enterprise = []
ttps_in_tags_not_in_techniques_enterprise_items = []

for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yaml' or extension == '.yml':
        with open(item) as file:
            num_yamls.append(item)
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y copiamos el fichero a la carpeta T0000
                document = yaml.full_load(file)
                if 'tags' in document:
                    # Si encontramos la etiqueta 'tags' en el yaml lo guardamos como una variable 
                    tags = document.get('tags', [])
                    has_label_tags.append(item)
                    # Si el resultado de esa variable no está vacío y contiene información lo convertimos en una lista
                    if not isinstance(tags, type(None)):
                        has_label_with_content_tags.append(item)
                        # Convertimos en lista el contenido de la etiqueta
                        #tags = [tags]
                        tags = [tag.upper() for tag in tags if isinstance(tag, str)]
                        # Recorremos la lista de items contenidos en tags y contamos las ttp encontradas ya que si no encontramos ninguna, pese haber texto en la etiqueta
                        # deberemos mover el fichero a la carpeta T0000
                        ttp_counter = 0
                        for tag in range(len(tags)):
                            # Matcheamos el item de la lista tags con nuestra lista de ttps 
                            ttp = find_techniques_in_list(tags[tag],techniques_enterprise)
                            # He encontrado en sigma HQ 5 tags que contienen técnicas que no están en el listado de techniques_enterprise, vamos a almacenarlas para reportarlas.
                            if '.T0' in tags[tag] or '.T1' in tags[tag]:
                                ttps_in_tags_not_in_techniques_enterprise.append(tags[tag])
                                ttps_in_tags_not_in_techniques_enterprise_items.append(item)
                            # Y si es un string lo que tenemos, entonces guardamos en la carpeta de la la ttp correspondiente
                            if isinstance(ttp, str):
                                ttp_counter += 1
                                copy_file_to_path(item, save_path_sigma_hq8, ttp)
                        if ttp_counter == 0:
                            raise NotTTPatTags('.yaml sin TTP encontrada en los tags')
                
                    else:
                        # En el caso de que la etiquete exista pero su contenido sea vacio (NoneType), accedemos a la etiqueta 'description' para buscar las TTP´s
                        has_label_without_content_tags.append(item)
                        if 'description' in document:
                            description = [document.get('description', [])]
                            # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                            for tag in range(len(description)):
                                ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                                if not isinstance(ttp, type(None)):
                                    if not os.path.exists(os.path.join(save_path_sigma_hq9, ttp)):
                                        os.makedirs(os.path.join(save_path_sigma_hq8, ttp))
                                else:
                                    ttp='T0000'
                                copy_file_to_path(item, save_path_sigma_hq8, ttp)
                else:
                    no_label_tags.append(item)
                    # Repetimos la busqueda de TTP en la etiqueta description en los casos en los que 'tags' no exista.
                    if 'description' in document:
                        description = [document.get('description', [])]
                        # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                        for tag in range(len(description)):
                            ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                            if not isinstance(ttp, type(None)):
                                if not os.path.exists(os.path.join(save_path_sigma_hq8, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq8, ttp))
                            else:
                                ttp='T0000'
                            copy_file_to_path(item, save_path_sigma_hq8, ttp)
                    else:
                        copy_file_to_path(item, save_path_sigma_hq8, 'T0000')
            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except yaml.YAMLError as e:
                error_load.append(item)
                ttp = find_techniques_in_list(item,techniques_enterprise)
                if not isinstance(ttp, type(None)):
                    print(f'Error al cargar el archivo YAML: {e}\nEncontrada TTP en la path del fichero')
                    error_load_ttp_in_path_name.append(item)
                    copy_file_to_path(item, save_path_sigma_hq8, ttp)
                else:
                    print(f"Error al cargar el archivo YAML: {e}")
                    copy_file_to_path(item, save_path_sigma_hq8, 'T0000')
            # Con esta excepción llegamos si hemos recorrido la lista de tags y no hemos encontrado ninguna TTP, por lo que revisamos la etiqueta dando lugar a 3 casuísticas,
            # la primera que encuentre dicha etiqueta, en cuyo caso se revisa el contenido, si dentro de este se encuentra alguna TTP se mandara a la carpeta correspondiente. En caso de no haber coincidencia, al igual que ocurrirá si no hay etiqueta 'description' el fichero será copiado a T000.
            except NotTTPatTags as e:
                print(f"{e}")
                notTTPinTags.append(item)
                if 'description' in document:
                    description = [document.get('description', [])]
                    # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                    for tag in range(len(description)):
                        ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                        if not isinstance(ttp, type(None)):
                            notTTPinTags_with_TTP_in_description.append(item)
                            pass
                        else:
                            ttp='T0000'
                        copy_file_to_path(item, save_path_sigma_hq8, ttp)
                else:
                    notTTPinTags_without_description.append(item)
                    copy_file_to_path(item, save_path_sigma_hq8, 'T0000')

Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1207
Copiado correctamente a la carpeta de la TTP: T1003.006
Copiado correctamente a la carpeta de la TTP: T1558.003
Copiado correctamente a la carpeta de la TTP: T1018
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1482
Error al cargar el archivo YAML: while scanning an alias
  in "C:\Users\jelopez\Downloads\sigma-rules-main/TA0008 - Lateral Movement\T1550 - Use Alternate Authentication Material\002 - Pass the Hash\ad_cs_relay.yml", line 18, column 25
expected alphabetic or numeric character, but found '\n'
  in "C:\Users\jelopez\Downloads\sigma-rules-main/TA0008 - Lateral Movement\T1550 - Use Alternate Authentication Material\002 - Pass the Hash\ad_cs_relay.yml", line 18, column 26
Encontrada TTP en la path del fichero
Copiado correctamente a la carpeta de la TTP: T1550

In [54]:
print('Reglas totales para asignar: '+str(len(num_yamls)))
rules_unique = get_unique_items(num_yamls)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 10
Reglas únicas para asignar: 10

In [58]:
print('Reglas que retornan error de apertura: '+str(len(error_load)))
print('Reglas que en las que se ha identificado TTP en la path del archivo: '+str(len(error_load_ttp_in_path_name)))

Reglas que retornan error de apertura: 1
Reglas que en las que se ha identificado TTP en la path del archivo: 1

In [55]:
print('Tienen informada la etiqueta "tags": '+str(len(has_label_tags)))
print('Tienen información en la etiqueta "tags": '+str(len(has_label_with_content_tags)))
print('NO tienen información en la etiqueta "tags": '+str(len(has_label_without_content_tags)))

Tienen informada la etiqueta "tags": 9
Tienen información en la etiqueta "tags": 9
NO tienen información en la etiqueta "tags": 0

In [59]:
print('NO tienen la etiqueta "tags": '+str(len(no_label_tags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags": '+str(len(notTTPinTags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": '+str(len(notTTPinTags_without_description)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": '+str(len(notTTPinTags_with_TTP_in_description)))

NO tienen la etiqueta "tags": 0
NO se ha encontrado TTP alguna en la etiqueta "tags": 0
NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": 0
NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": 0

In [63]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_sigma_hq8))))
# print('Reglas sin TTP asignada (T0000): '+str(len(getListOfFilesSub(os.path.join(save_path_sigma_hq8, 'T0000')))))
try:
    t0000_count = len(os.listdir(getListOfFilesSub(os.path.join(save_path_sigma_hq8, 'T0000'))))
    print('Reglas sin TTP asignada (T0000):', t0000_count)
except FileNotFoundError:
    t0000_count = 0
    print('Reglas sin TTP asignada (T0000): 0')
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_sigma_hq8)) - t0000_count))
print('Reglas asignadas a 2 o más TTPs: '+str((len(getListOfFilesSub(save_path_sigma_hq8)) - t0000_count)-len(rules_unique)))

Número de TTPs únicas identificadas (puede incluir T0000): 9
Reglas sin TTP asignada (T0000): 0
Reglas asignadas a TTP: 10
Reglas asignadas a 2 o más TTPs: 0

#### TTP's Sigma HQ 9

<h5 style="background-color: #E11717; color: black;">
    Importante: No ejecutar por solicitud de Seguridad
</h5>

In [19]:
zip_sigma_hq9 = 'https://github.com/mdecrevoisier/SIGMA-detection-rules/archive/refs/heads/main.zip'
save_path_sigma_hq9 = os.path.join(save_path, 'sigmaHQ9')
unzip_folder = r'SIGMA-detection-rules-main/'

In [18]:
download_unzip(zip_sigma_hq9, temp_path)

In [ ]:
create_output_folder(save_path_sigma_hq9)

In [21]:
files = getListOfFilesSub(os.path.join(temp_path, unzip_folder))
len(files)

351

In [23]:
num_yamls = []
has_label_tags = []
has_label_with_content_tags = []
has_label_without_content_tags = []
no_label_tags = []
notTTPinTags = []
notTTPinTags_with_TTP_in_description = []
notTTPinTags_without_description = []
error_load = []
error_load_ttp_in_path_name = []

ttps_in_tags_not_in_techniques_enterprise = []
ttps_in_tags_not_in_techniques_enterprise_items = []

for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yaml' or extension == '.yml':
        with open(item) as file:
            num_yamls.append(item)
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y copiamos el fichero a la carpeta T0000
                document = yaml.full_load(file)
                if 'tags' in document:
                    # Si encontramos la etiqueta 'tags' en el yaml lo guardamos como una variable 
                    tags = document.get('tags', [])
                    has_label_tags.append(item)
                    # Si el resultado de esa variable no está vacío y contiene información lo convertimos en una lista
                    if not isinstance(tags, type(None)):
                        has_label_with_content_tags.append(item)
                        # Convertimos en lista el contenido de la etiqueta
                        #tags = [tags]
                        tags = [tag.upper() for tag in tags if isinstance(tag, str)]
                        # Recorremos la lista de items contenidos en tags y contamos las ttp encontradas ya que si no encontramos ninguna, pese haber texto en la etiqueta
                        # deberemos mover el fichero a la carpeta T0000
                        ttp_counter = 0
                        for tag in range(len(tags)):
                            # Matcheamos el item de la lista tags con nuestra lista de ttps 
                            ttp = find_techniques_in_list(tags[tag],techniques_enterprise)
                            # He encontrado en sigma HQ 5 tags que contienen técnicas que no están en el listado de techniques_enterprise, vamos a almacenarlas para reportarlas.
                            if '.T0' in tags[tag] or '.T1' in tags[tag]:
                                ttps_in_tags_not_in_techniques_enterprise.append(tags[tag])
                                ttps_in_tags_not_in_techniques_enterprise_items.append(item)
                            # Y si es un string lo que tenemos, entonces guardamos en la carpeta de la la ttp correspondiente
                            if isinstance(ttp, str):
                                ttp_counter += 1
                                copy_file_to_path(item, save_path_sigma_hq9, ttp)
                        if ttp_counter == 0:
                            raise NotTTPatTags('.yaml sin TTP encontrada en los tags')
                
                    else:
                        # En el caso de que la etiquete exista pero su contenido sea vacio (NoneType), accedemos a la etiqueta 'description' para buscar las TTP´s
                        has_label_without_content_tags.append(item)
                        if 'description' in document:
                            description = [document.get('description', [])]
                            # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                            for tag in range(len(description)):
                                ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                                if not isinstance(ttp, type(None)):
                                    if not os.path.exists(os.path.join(save_path_sigma_hq9, ttp)):
                                        os.makedirs(os.path.join(save_path_sigma_hq9, ttp))
                                else:
                                    ttp='T0000'
                                copy_file_to_path(item, save_path_sigma_hq9, ttp)
                else:
                    no_label_tags.append(item)
                    # Repetimos la busqueda de TTP en la etiqueta description en los casos en los que 'tags' no exista.
                    if 'description' in document:
                        description = [document.get('description', [])]
                        # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                        for tag in range(len(description)):
                            ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                            if not isinstance(ttp, type(None)):
                                if not os.path.exists(os.path.join(save_path_sigma_hq9, ttp)):
                                    os.makedirs(os.path.join(save_path_sigma_hq9, ttp))
                            else:
                                ttp='T0000'
                            copy_file_to_path(item, save_path_sigma_hq9, ttp)
                    else:
                        copy_file_to_path(item, save_path_sigma_hq9, 'T0000')
            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except yaml.YAMLError as e:
                error_load.append(item)
                ttp = find_techniques_in_list(item,techniques_enterprise)
                if not isinstance(ttp, type(None)):
                    print(f'Error al cargar el archivo YAML: {e}\nEncontrada TTP en la path del fichero')
                    error_load_ttp_in_path_name.append(item)
                    copy_file_to_path(item, save_path_sigma_hq9, ttp)
                else:
                    print(f"Error al cargar el archivo YAML: {e}")
                    copy_file_to_path(item, save_path_sigma_hq9, 'T0000')
            # Con esta excepción llegamos si hemos recorrido la lista de tags y no hemos encontrado ninguna TTP, por lo que revisamos la etiqueta dando lugar a 3 casuísticas,
            # la primera que encuentre dicha etiqueta, en cuyo caso se revisa el contenido, si dentro de este se encuentra alguna TTP se mandara a la carpeta correspondiente. En caso de no haber coincidencia, al igual que ocurrirá si no hay etiqueta 'description' el fichero será copiado a T000.
            except NotTTPatTags as e:
                print(f"{e}")
                notTTPinTags.append(item)
                if 'description' in document:
                    description = [document.get('description', [])]
                    # Si no se encuentra ninguna, directamente guardamos en la carpeta T0000 y en caso contrario en la correspondiente a la TTP encontrada
                    for tag in range(len(description)):
                        ttp = find_techniques_in_list(description[tag],techniques_enterprise)
                        if not isinstance(ttp, type(None)):
                            notTTPinTags_with_TTP_in_description.append(item)
                            pass
                        else:
                            ttp='T0000'
                        copy_file_to_path(item, save_path_sigma_hq9, ttp)
                else:
                    notTTPinTags_without_description.append(item)
                    copy_file_to_path(item, save_path_sigma_hq9, 'T0000')

Copiado correctamente a la carpeta de la TTP: T1484.002
Copiado correctamente a la carpeta de la TTP: T1114.003
Copiado correctamente a la carpeta de la TTP: T1114
Copiado correctamente a la carpeta de la TTP: T1566
Copiado correctamente a la carpeta de la TTP: T1114
Copiado correctamente a la carpeta de la TTP: T1566
Copiado correctamente a la carpeta de la TTP: T1562.006
Copiado correctamente a la carpeta de la TTP: T1546
Copiado correctamente a la carpeta de la TTP: T1110.001
Copiado correctamente a la carpeta de la TTP: T1110.003
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1222.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1555.004
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1564
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1484.001
Copiado correctamente a la carpeta de la TTP: T1484.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T1003.003
Copiado correctamente a la carpeta de la TTP: T1003.003
Copiado correctamente a la carpeta de la TTP: T1558.003
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1558.004
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1558.001
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1558.001
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1558
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1087.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1558.001
Copiado correctamente a la carpeta de la TTP: T1003.006
Copiado correctamente a la carpeta de la TTP: T1201
Copiado correctamente a la carpeta de la TTP: T1210
Copiado correctamente a la carpeta de la TTP: T1482
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1003.006
Copiado correctamente a la carpeta de la TTP: T1222.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1207
Copiado correctamente a la carpeta de la TTP: T1558.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1558.003
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1078.002
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1555
Copiado correctamente a la carpeta de la TTP: T1059.003
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1486
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1570
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1197
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1570
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1197
Copiado correctamente a la carpeta de la TTP: T1048
Copiado correctamente a la carpeta de la TTP: T1570
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1197
Copiado correctamente a la carpeta de la TTP: T1555.003
Copiado correctamente a la carpeta de la TTP: T1204
Copiado correctamente a la carpeta de la TTP: T1204
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1562.001
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1222.001
Copiado correctamente a la carpeta de la TTP: T1003.006
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1557.001
Copiado correctamente a la carpeta de la TTP: T1505.002
Copiado correctamente a la carpeta de la TTP: T1505.002
Copiado correctamente a la carpeta de la TTP: T1505.002
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1505.004
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1003.001
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1547.009
Copiado correctamente a la carpeta de la TTP: T1547.009
Copiado correctamente a la carpeta de la TTP: T1547.009
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1562.004
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1021.004
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1562.002
Copiado correctamente a la carpeta de la TTP: T1562.002
Copiado correctamente a la carpeta de la TTP: T1082
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1490
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1553.004
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1546.003
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1021.003
Copiado correctamente a la carpeta de la TTP: T1071.004
Copiado correctamente a la carpeta de la TTP: T1071.004
Copiado correctamente a la carpeta de la TTP: T1555.004
Error al cargar el archivo YAML: while scanning for the next token
found character '\t' that cannot start any token
  in "C:\Users\jelopez\Downloads\SIGMA-detection-rules-main/windows-os\win-os-dump file transfered over SMB share.yaml", line 20, column 3
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1070.001
Copiado correctamente a la carpeta de la TTP: T1562.002
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1041
Copiado correctamente a la carpeta de la TTP: T1555.004
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1069.001
Copiado correctamente a la carpeta de la TTP: T1069.002
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T1136
Copiado correctamente a la carpeta de la TTP: T1018
Copiado correctamente a la carpeta de la TTP: T1565
Copiado correctamente a la carpeta de la TTP: T1003.002
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1134.001
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1564.006
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1135
Copiado correctamente a la carpeta de la TTP: T1546.007
Copiado correctamente a la carpeta de la TTP: T1546.007
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T1134
Copiado correctamente a la carpeta de la TTP: T1562.010
Copiado correctamente a la carpeta de la TTP: T1550.002
Copiado correctamente a la carpeta de la TTP: T1201
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T1059.003
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T1059.001
Copiado correctamente a la carpeta de la TTP: T1557.001
Copiado correctamente a la carpeta de la TTP: T1547.010
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1134.002
Copiado correctamente a la carpeta de la TTP: T1134.002
Copiado correctamente a la carpeta de la TTP: T1569.002
Copiado correctamente a la carpeta de la TTP: T1489
Copiado correctamente a la carpeta de la TTP: T1569.002
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1112
Copiado correctamente a la carpeta de la TTP: T1003.002
Copiado correctamente a la carpeta de la TTP: T1003.004
Copiado correctamente a la carpeta de la TTP: T1003.005
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1547.008
Copiado correctamente a la carpeta de la TTP: T1547.008
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1135
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1222.001
Copiado correctamente a la carpeta de la TTP: T1021.002
.yaml sin TTP encontrada en los tags
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1553.003
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1562.010
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1040
Copiado correctamente a la carpeta de la TTP: T1040
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1546.008
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1547.010
Copiado correctamente a la carpeta de la TTP: T1574.002
Copiado correctamente a la carpeta de la TTP: T1547.010
Copiado correctamente a la carpeta de la TTP: T1070.006
Copiado correctamente a la carpeta de la TTP: T1070.006
Copiado correctamente a la carpeta de la TTP: T1555
Copiado correctamente a la carpeta de la TTP: T1136.001
Copiado correctamente a la carpeta de la TTP: T1136.002
Copiado correctamente a la carpeta de la TTP: T1136.001
Copiado correctamente a la carpeta de la TTP: T1087.001
Copiado correctamente a la carpeta de la TTP: T1087.002
Copiado correctamente a la carpeta de la TTP: T1555
Copiado correctamente a la carpeta de la TTP: T1555.004
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T1562
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1546.003
Copiado correctamente a la carpeta de la TTP: T1546.003
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T1021.002
Copiado correctamente a la carpeta de la TTP: T1222
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1046
Copiado correctamente a la carpeta de la TTP: T1110
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1563.002
Copiado correctamente a la carpeta de la TTP: T1543.003
Copiado correctamente a la carpeta de la TTP: T1563.002
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1113
Copiado correctamente a la carpeta de la TTP: T1125
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1113
Copiado correctamente a la carpeta de la TTP: T1125
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1113
Copiado correctamente a la carpeta de la TTP: T1125
Copiado correctamente a la carpeta de la TTP: T1572
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1572
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1572
Copiado correctamente a la carpeta de la TTP: T1021.001
Copiado correctamente a la carpeta de la TTP: T1053.005
Copiado correctamente a la carpeta de la TTP: T1053.005
Copiado correctamente a la carpeta de la TTP: T1053.005
Copiado correctamente a la carpeta de la TTP: T1016
Copiado correctamente a la carpeta de la TTP: T1053.005
Copiado correctamente a la carpeta de la TTP: T1053.005

In [27]:
print('Reglas totales para asignar: '+str(len(num_yamls)))
rules_unique = get_unique_items(num_yamls)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 348
Reglas únicas para asignar: 348

In [28]:
print('Reglas que retornan error de apertura: '+str(len(error_load)))
print('Reglas que en las que se ha identificado TTP en la path del archivo: '+str(len(error_load_ttp_in_path_name)))

Reglas que retornan error de apertura: 1
Reglas que en las que se ha identificado TTP en la path del archivo: 0

In [29]:
print('Tienen informada la etiqueta "tags": '+str(len(has_label_tags)))
print('Tienen información en la etiqueta "tags": '+str(len(has_label_with_content_tags)))
print('NO tienen información en la etiqueta "tags": '+str(len(has_label_without_content_tags)))

Tienen informada la etiqueta "tags": 347
Tienen información en la etiqueta "tags": 347
NO tienen información en la etiqueta "tags": 0

In [30]:
print('NO tienen la etiqueta "tags": '+str(len(no_label_tags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags": '+str(len(notTTPinTags)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": '+str(len(notTTPinTags_without_description)))
print('NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": '+str(len(notTTPinTags_with_TTP_in_description)))

NO tienen la etiqueta "tags": 0
NO se ha encontrado TTP alguna en la etiqueta "tags": 4
NO se ha encontrado TTP alguna en la etiqueta "tags" y NO disponen de la etiqueta "description": 0
NO se ha encontrado TTP alguna en la etiqueta "tags" y disponen de la etiqueta "description": 0

In [38]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_sigma_hq9))))
# print('Reglas sin TTP asignada (T0000): '+str(len(getListOfFilesSub(os.path.join(save_path_sigma_hq8, 'T0000')))))
try:
    t0000_count = len(getListOfFilesSub(os.path.join(save_path_sigma_hq9, 'T0000')))
    print('Reglas sin TTP asignada (T0000):', t0000_count)
except FileNotFoundError:
    t0000_count = 0
    print('Reglas sin TTP asignada (T0000): 0')
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_sigma_hq9)) - t0000_count))
print('Reglas asignadas a 2 o más TTPs: '+str((len(getListOfFilesSub(save_path_sigma_hq9)) - t0000_count)-len(rules_unique)))

Número de TTPs únicas identificadas (puede incluir T0000): 111
Reglas sin TTP asignada (T0000): 5
Reglas asignadas a TTP: 410
Reglas asignadas a 2 o más TTPs: 62

#### TTP's Yara 1

In [18]:
zip_yara_1 = 'https://github.com/Yara-Rules/rules/archive/refs/heads/master.zip'
save_path_yara_1 = os.path.join(save_path, 'yara_1')
unzip_folder = r'rules-master/'

In [19]:
download_unzip(zip_yara_1, temp_path)

In [20]:
create_output_folder(save_path_yara_1)

In [21]:
files = getListOfFilesSub(os.path.join(temp_path, unzip_folder))
len(files)

582

In [22]:
num_yaras = []
ttp_in_filename = []
content_in_yara = []
no_content_in_yara = []
ttp_in_yara = []
error_load = []
no_ttp_in_content_or_filename = []


for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yar' or extension == '.yara':
        with open(item, 'r', encoding='utf-8') as file:
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y se revisa el nombre del fichero antes de copiar el fichero a la carpeta T0000
                md_content = file.read()
                md_content = md_content.upper()
                num_yaras.append(item)
                # Revisamos que se haya podido obtener texto del contenido del .yar 
                if isinstance(md_content, str):
                    ttps = find_techniques(md_content)
                    ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                    content_in_yara.append(item)
                else:
                    #Si el contenido no dispone de texto, buscamos ttps en el propio nombre del fichero
                    ttps = find_techniques(item.upper())
                    ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                    no_content_in_yara.append(item)
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_yara.append(item)
                            copy_file_to_path(item, save_path_yara_1, ttp)
                
                #En cualquier caso, siempre buscamos ttp en el nombre del fichero
                ttps = find_techniques(item.upper())
                ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_filename.append(item)
                            copy_file_to_path(item, save_path_yara_1, ttp)
                else:
                    copy_file_to_path(item, save_path_yara_1, 'T0000')

            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except Exception as e:
                print(f"Error al intentar leer el archivo markdown: {e}")
                error_load.append(item)
                ttps = find_techniques(item.upper())
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_filename.append(item)
                            copy_file_to_path(item, save_path_yara_1, ttp)
                else:
                    copy_file_to_path(item, save_path_yara_1, 'T0000')

Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000

In [23]:
print('Reglas totales para asignar: '+str(len(num_yaras)))
rules_unique = get_unique_items(num_yaras)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 566
Reglas únicas para asignar: 566

In [24]:
print('Reglas que retornan error de lectura: '+str(len(error_load)))

Reglas que retornan error de lectura: 0

In [25]:
print('El archivo ha sido abierto y dispone de contenido: '+str(len(content_in_yara)))
print('El archivo ha sido abierto y NO dispone de contenido: '+str(len(no_content_in_yara)))
print('Se ha podido identificar al menos una TTP en el contenido del archivo: '+str(len(ttp_in_yara)))
print('Se ha podido identificar al menos una TTP en el nombre del archivo: '+str(len(ttp_in_filename)))

El archivo ha sido abierto y dispone de contenido: 566
El archivo ha sido abierto y NO dispone de contenido: 0
Se ha podido identificar al menos una TTP en el contenido del archivo: 0
Se ha podido identificar al menos una TTP en el nombre del archivo: 0

In [26]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_yara_1))))
try:
    t0000_count = len(getListOfFilesSub(os.path.join(save_path_yara_1, 'T0000')))
    print('Reglas sin TTP asignada (T0000):', t0000_count)
except FileNotFoundError:
    t0000_count = 0
    print('Reglas sin TTP asignada (T0000): 0')
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_yara_1)) - t0000_count))
print('Reglas asignadas a 2 o más TTP: '+str(len(count_duplicate_rules(getListOfFilesSub(save_path_yara_1)))))

Número de TTPs únicas identificadas (puede incluir T0000): 1
Reglas sin TTP asignada (T0000): 566
Reglas asignadas a TTP: 0
Reglas asignadas a 2 o más TTP: 0

#### TTP's Yara 2

In [19]:
zip_yara_2 = 'https://github.com/bartblaze/Yara-rules/archive/refs/heads/master.zip'
save_path_yara_2 = os.path.join(save_path, 'yara_2')
unzip_folder = r'Yara-rules-master/'

In [20]:
download_unzip(zip_yara_2, temp_path)

In [21]:
create_output_folder(save_path_yara_2)

In [22]:
files = getListOfFilesSub(os.path.join(temp_path, unzip_folder))
len(files)

93

In [23]:
num_yaras = []
ttp_in_filename = []
content_in_yara = []
no_content_in_yara = []
ttp_in_yara = []
error_load = []
no_ttp_in_content_or_filename = []


for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.yar' or extension == '.yara':
        with open(item, 'r', encoding='utf-8') as file:
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y se revisa el nombre del fichero antes de copiar el fichero a la carpeta T0000
                md_content = file.read()
                md_content = md_content.upper()
                num_yaras.append(item)
                # Revisamos que se haya podido obtener texto del contenido del .yar 
                if isinstance(md_content, str):
                    ttps = find_techniques(md_content)
                    ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                    content_in_yara.append(item)
                else:
                    #Si el contenido no dispone de texto, buscamos ttps en el propio nombre del fichero
                    ttps = find_techniques(item.upper())
                    ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                    no_content_in_yara.append(item)
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_yara.append(item)
                            copy_file_to_path(item, save_path_yara_2, ttp)
                
                #En cualquier caso, siempre buscamos ttp en el nombre del fichero
                ttps = find_techniques(item.upper())
                ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_filename.append(item)
                            copy_file_to_path(item, save_path_yara_2, ttp)
                else:
                    copy_file_to_path(item, save_path_yara_2, 'T0000')

            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except Exception as e:
                print(f"Error al intentar leer el archivo markdown: {e}")
                error_load.append(item)
                ttps = find_techniques(item.upper())
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_filename.append(item)
                            copy_file_to_path(item, save_path_yara_2, ttp)
                else:
                    copy_file_to_path(item, save_path_yara_2, 'T0000')

Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1021.005
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000

In [24]:
print('Reglas totales para asignar: '+str(len(num_yaras)))
rules_unique = get_unique_items(num_yaras)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 88
Reglas únicas para asignar: 88

In [25]:
print('Reglas que retornan error de lectura: '+str(len(error_load)))

Reglas que retornan error de lectura: 0

In [26]:
print('El archivo ha sido abierto y dispone de contenido: '+str(len(content_in_yara)))
print('El archivo ha sido abierto y NO dispone de contenido: '+str(len(no_content_in_yara)))
print('Se ha podido identificar al menos una TTP en el contenido del archivo: '+str(len(ttp_in_yara)))
print('Se ha podido identificar al menos una TTP en el nombre del archivo: '+str(len(ttp_in_filename)))

El archivo ha sido abierto y dispone de contenido: 88
El archivo ha sido abierto y NO dispone de contenido: 0
Se ha podido identificar al menos una TTP en el contenido del archivo: 2
Se ha podido identificar al menos una TTP en el nombre del archivo: 0

In [29]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_yara_2))))
try:
    t0000_count = len(getListOfFilesSub(os.path.join(save_path_yara_2, 'T0000')))
    print('Reglas sin TTP asignada (T0000):', t0000_count)
except FileNotFoundError:
    t0000_count = 0
    print('Reglas sin TTP asignada (T0000): 0')
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_yara_2)) - t0000_count))
print('Reglas asignadas a 2 o más TTP: '+str(len(count_duplicate_rules(getListOfFilesSub(save_path_yara_2)))))

Número de TTPs únicas identificadas (puede incluir T0000): 3
Reglas sin TTP asignada (T0000): 88
Reglas asignadas a TTP: 2
Reglas asignadas a 2 o más TTP: 1

#### TTP's Atomic threat 

<h5 style="background-color: #F80000; color: black;">
    Importante: No ejecutar por solicitud de Seguridad
</h5>

In [37]:
# zip_atomic = 'https://github.com/krakow2600/atomic-threat-coverage/archive/refs/heads/master.zip'
save_path_atomic = os.path.join(save_path, 'atomic')
unzip_folder = r'atomic-threat-coverage-master/Atomic_Threat_Coverage/'

In [38]:
download_folder_unzip(zip_atomic, unzip_folder, temp_path)

Descarga y descompresión completadas correctamente.

In [39]:
create_output_folder(save_path_atomic)

In [65]:
files = getListOfFilesSub(os.path.join(temp_path, unzip_folder))
len(files)

534

In [75]:
num_mds = []
ttp_in_filename = []
content_in_md = []
no_content_in_md = []
ttp_in_md = []
error_load = []
no_ttp_in_content_or_filename = []

for item in files:
    root, extension = os.path.splitext(item)
    if extension == '.md' or extension == '.markdown':
        with open(item, 'r', encoding='utf-8') as file:
            try:
                # Comenzamos intentando abrir el fichero, en caso de que no se pueda generamos excepción y se revisa el nombre del fichero antes de copiar el fichero a la carpeta T0000
                md_content = file.read()
                md_content = md_content.upper()
                num_mds.append(item)
                # Revisamos que se haya podido obtener texto del contenido del .md 
                if isinstance(md_content, str):
                    ttps = find_techniques(md_content)
                    ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                    content_in_md.append(item)
                else:
                    #Si el contenido no dispone de texto, buscamos ttps en el propio nombre del fichero
                    ttps = find_techniques(item.upper())
                    ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                    no_content_in_md.append(item)
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_md.append(item)
                            copy_file_to_path(item, save_path_atomic, ttp)
                
                #En cualquier caso, siempre buscamos ttp en el nombre del fichero
                ttps = find_techniques(item.upper())
                ttps = [item.strip() for item in ttps.split(',') if item.strip()]
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_filename.append(item)
                            copy_file_to_path(item, save_path_atomic, ttp)
                else:
                    copy_file_to_path(item, save_path_atomic, 'T0000')

            # Excepción que controla errores de carga del fichero, moviendolo a T0000. 
            except Exception as e:
                print(f"Error al intentar leer el archivo markdown: {e}")
                error_load.append(item)
                ttps = find_techniques(item.upper())
                if len(ttps)>0:
                    # Copiamos cada una de las ttps encontradas en su carpeta correspondiente
                    for ttp in ttps:
                        if ttp != '':
                            ttp_in_md.append(item)
                            copy_file_to_path(item, save_path_atomic, ttp)
                else:
                    copy_file_to_path(item, save_path_atomic, 'T0000')

Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1219
Copiado correctamente a la carpeta de la TTP: T1203
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1112
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1037
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1011
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1210
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1114
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1059
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1114
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1059
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1047
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1211
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1203
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1068
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1112
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1218
Copiado correctamente a la carpeta de la TTP: T1055
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1090
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1021
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1212
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1202
Copiado correctamente a la carpeta de la TTP: T1059
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1202
Copiado correctamente a la carpeta de la TTP: T1059
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1127
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1197
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1053
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1210
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1105
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1059
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1082
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1098
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1070
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1078
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1212
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1211
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1087
Copiado correctamente a la carpeta de la TTP: T1069
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1202
Copiado correctamente a la carpeta de la TTP: T1059
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1140
Copiado correctamente a la carpeta de la TTP: T1027
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T1003
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1036
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T0000
Copiado correctamente a la carpeta de la TTP: T1087

In [76]:
print('Reglas totales para asignar: '+str(len(num_mds)))
rules_unique = get_unique_items(num_mds)
print('Reglas únicas para asignar: '+str(len(rules_unique)))

Reglas totales para asignar: 534
Reglas únicas para asignar: 534

In [77]:
print('Reglas que retornan error de lectura: '+str(len(error_load)))

Reglas que retornan error de lectura: 0

In [86]:
print('El archivo ha sido abierto y dispone de contenido: '+str(len(content_in_md)))
print('El archivo ha sido abierto y NO dispone de contenido: '+str(len(no_content_in_md)))
print('Se ha podido identificar al menos una TTP en el contenido del archivo: '+str(len(ttp_in_md)))
print('Se ha podido identificar al menos una TTP en el nombre del archivo: '+str(len(ttp_in_filename)))

El archivo ha sido abierto y dispone de contenido: 534
El archivo ha sido abierto y NO dispone de contenido: 0
Se ha podido identificar al menos una TTP en el contenido del archivo: 247
Se ha podido identificar al menos una TTP en el nombre del archivo: 63

In [114]:
print('Número de TTPs únicas identificadas (puede incluir T0000): '+str(len(get_folders(save_path_atomic))))
# print('Reglas sin TTP asignada (T0000): '+str(len(getListOfFilesSub(os.path.join(save_path_sigma_hq8, 'T0000')))))
try:
    t0000_count = len(getListOfFilesSub(os.path.join(save_path_atomic, 'T0000')))
    print('Reglas sin TTP asignada (T0000):', t0000_count)
except FileNotFoundError:
    t0000_count = 0
    print('Reglas sin TTP asignada (T0000): 0')
print('Reglas asignadas a TTP: '+str(len(getListOfFilesSub(save_path_atomic)) - t0000_count))
print('Reglas asignadas a 2 o más TTP: '+str(len(count_duplicate_rules(getListOfFilesSub(save_path_atomic)))))

Número de TTPs únicas identificadas (puede incluir T0000): 78
Reglas sin TTP asignada (T0000): 471
Reglas asignadas a TTP: 247
Reglas asignadas a 2 o más TTP: 150